SPELL_CSPELL_PRE_COMMANDS:
  - command: npm install @cspell/dict-pl_pl
    cwd: "root"
  - command: cspell link ls
    cwd: "root"
  - command: cspell link add @cspell/dict-pl_pl
    cwd: "root"
ACTION_ZIZMOR_UNSECURED_ENV_VARIABLES:
  - GITHUB_TOKEN
# 1. Przekazujemy pełną konfigurację jako zmienną środowiskową.
# Zizmor (jako narzędzie w Rust) potrafi ją odczytać bezpośrednio z pamięci.
ZIZMOR_CONFIG: '{"rules": {"unpinned-uses": {"ignored": true}}}'

# 2. Resetujemy problematyczne mapowania plików MegaLintera
ACTION_ZIZMOR_CONFIG_FILE: "LINTER_DEFAULT"
ACTION_ZIZMOR_ARGUMENTS: ""
ACTION_ZIZMOR_COMMAND_REMOVE_ARGUMENTS: "--config /github/workspace/zizmor.yml"
