SPELL_CSPELL_PRE_COMMANDS:
  - command: npm install @cspell/dict-pl_pl
    cwd: "root"
  - command: cspell link ls
    cwd: "root"
  - command: cspell link add @cspell/dict-pl_pl
    cwd: "root"
ACTION_ZIZMOR_UNSECURED_ENV_VARIABLES:
  - GITHUB_TOKEN
# 1. Informujemy MegaLintera, aby nie wstrzykiwał swojej domyślnej flagi --config
ACTION_ZIZMOR_CONFIG_FILE: "LINTER_DEFAULT"

# 2. Tworzymy plik w formacie słownika, którego oczekuje MegaLinter
ACTION_ZIZMOR_PRE_COMMANDS:
  - command: |
      echo -e "rules:\n  unpinned-uses:\n    ignored: true" > .zizmor.yml

# 3. Czyścimy argumenty CLI
ACTION_ZIZMOR_ARGUMENTS: ""
ACTION_ZIZMOR_COMMAND_REMOVE_ARGUMENTS: ""
