= Lista przepisów

++++
include::filters.html[]
++++

== Przepisy


== Dania glowne

++++
<div class="cards-wrapper">
<div class="cards-grid">
<article class="card"><a href="Przepisy/Dania_glowne/biała_ryba_na_parze.html"><div class="card-emoji">🐟</div><div class="card-title">Biała ryba na parze</div><div class="card-tag">ryby</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/bigos.html"><div class="card-emoji">🐖 🥩</div><div class="card-title">Bigos</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/bułeczki_baozi.html"><div class="card-emoji">🌱</div><div class="card-title">Bułeczki baozi</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/buraki_po_burgundzku.html"><div class="card-emoji">🌱</div><div class="card-title">Buraki po burgundzku</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/burgerki.html"><div class="card-emoji">🥩</div><div class="card-title">Burgerki</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/burrito_z_chili_con_carne.html"><div class="card-emoji">🥩</div><div class="card-title">Burrito z chili con carne</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/butter_chicken.html"><div class="card-emoji">🐔</div><div class="card-title">Butter chicken</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/chakalaka.html"><div class="card-emoji">🌱</div><div class="card-title">Chakalaka</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/chili_con_carne.html"><div class="card-emoji">🥩 🔥</div><div class="card-title">Chili con carne</div><div class="card-tag">mięsne, ostre</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/ciecierzyca_po_bretońsku.html"><div class="card-emoji">🌱</div><div class="card-title">Ciecierzyca po bretońsku</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/cukinia_faszerowana.html"><div class="card-emoji">🐖</div><div class="card-title">Cukinia faszerowana</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/cukinie_z_chili_con_carne.html"><div class="card-emoji">🥩</div><div class="card-title">Cukinie z chili con carne</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/curry_z_kalafiora.html"><div class="card-emoji">🌱</div><div class="card-title">Curry z kalafiora</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/ćwiartki_pieczone.html"><div class="card-emoji">🐔</div><div class="card-title">Ćwiartki pieczone</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/dal_z_soczewicy_z_sri_lanki.html"><div class="card-emoji">🌱</div><div class="card-title">Dal z soczewicy z sri lanki</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/dewolaje.html"><div class="card-emoji">🐔</div><div class="card-title">Dewolaje</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/domowa_pizza.html"><div class="card-emoji">🐖</div><div class="card-title">Domowa pizza</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/domowa_pizza_2.html"><div class="card-emoji"></div><div class="card-title">Domowa pizza 2</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/domowy_kebab.html"><div class="card-emoji">🐔</div><div class="card-title">Domowy kebab</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/domowy_kebab_2.html"><div class="card-emoji">🐔</div><div class="card-title">Domowy kebab 2</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/dorada_pieczona.html"><div class="card-emoji">🐟</div><div class="card-title">Dorada pieczona</div><div class="card-tag">ryby</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/dorsz_pod_śródziemnomorską_kruszonką.html"><div class="card-emoji">🐟</div><div class="card-title">Dorsz pod śródziemnomorską kruszonką</div><div class="card-tag">ryby</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/dorsz_w_sosie_curry.html"><div class="card-emoji">🐟</div><div class="card-title">Dorsz w sosie curry</div><div class="card-tag">ryby</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/dorsz_z_porami.html"><div class="card-emoji">🐟</div><div class="card-title">Dorsz z porami</div><div class="card-tag">ryby</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/dziwne_łukaszkowe_danie.html"><div class="card-emoji">🐔</div><div class="card-title">Dziwne łukaszkowe danie</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/enchilada_z_kurczakiem.html"><div class="card-emoji">🐔</div><div class="card-title">Enchilada z kurczakiem</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/falafel_humus_i_świeże_warzywa.html"><div class="card-emoji">🌱</div><div class="card-title">Falafel humus i świeże warzywa</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/fasolka_po_bretońsku.html"><div class="card-emoji">🐖</div><div class="card-title">Fasolka po bretońsku</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/fish_&_chips_z_sosem_tatarskim.html"><div class="card-emoji">🐟</div><div class="card-title">Fish & chips z sosem tatarskim</div><div class="card-tag">ryby</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/flaki.html"><div class="card-emoji">🥩</div><div class="card-title">Flaki</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/gołąbki.html"><div class="card-emoji">🐖</div><div class="card-title">Gołąbki</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/gołąbki_bez_zawijania.html"><div class="card-emoji">🐖</div><div class="card-title">Gołąbki bez zawijania</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/gołąbki_wegetariańskie_bez_zawijania.html"><div class="card-emoji">🌱</div><div class="card-title">Gołąbki wegetariańskie bez zawijania</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/greckie_klopsiki_w_sosie_pomidorowym.html"><div class="card-emoji">🐖 🥩</div><div class="card-title">Greckie klopsiki w sosie pomidorowym</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/gulasz_wołowy.html"><div class="card-emoji">🥩</div><div class="card-title">Gulasz wołowy</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/gulasz_z_szynki.html"><div class="card-emoji">🐖</div><div class="card-title">Gulasz z szynki</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/hotdogi_z_warzywkami.html"><div class="card-emoji">🐖</div><div class="card-title">Hotdogi z warzywkami</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/kaczka_po_wietnamsku.html"><div class="card-emoji">🦆</div><div class="card-title">Kaczka po wietnamsku</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/kaczka_z_jabłkami_żurawiną_i_rozmarynem.html"><div class="card-emoji">🦆</div><div class="card-title">Kaczka z jabłkami żurawiną i rozmarynem</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/kalamaki_z_pitą.html"><div class="card-emoji">🐖</div><div class="card-title">Kalamaki z pitą</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/kanapka_z_pieczonym_indykiem.html"><div class="card-emoji">🐔</div><div class="card-title">Kanapka z pieczonym indykiem</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/karkówka_smażona_z_przyprawami.html"><div class="card-emoji">🐖</div><div class="card-title">Karkówka smażona z przyprawami</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/kartacze.html"><div class="card-emoji">🐖</div><div class="card-title">Kartacze</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/kaszotto_z_grzybami_leśnymi.html"><div class="card-emoji">🌱</div><div class="card-title">Kaszotto z grzybami leśnymi</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/kaszotto_z_indykiem_fasolką_i_cukinią.html"><div class="card-emoji">🐔</div><div class="card-title">Kaszotto z indykiem fasolką i cukinią</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/kaszotto_z_kurkami.html"><div class="card-emoji">🌱</div><div class="card-title">Kaszotto z kurkami</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/klopsiki_z_pieczarkami_w_sosie_pomidorowym.html"><div class="card-emoji">🐖</div><div class="card-title">Klopsiki z pieczarkami w sosie pomidorowym</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/klopsy.html"><div class="card-emoji">🐖</div><div class="card-title">Klopsy</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/kopytka.html"><div class="card-emoji">🌱</div><div class="card-title">Kopytka</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/krewetki_po_luizjańsku.html"><div class="card-emoji">🦐 🔥</div><div class="card-title">Krewetki po luizjańsku</div><div class="card-tag">ostre, ryby</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/krokiety_z_kapustą_i_grzybami.html"><div class="card-emoji">🌱</div><div class="card-title">Krokiety z kapustą i grzybami</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/krokiety_z_pieczarkami.html"><div class="card-emoji">🐖</div><div class="card-title">Krokiety z pieczarkami</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/kukurydziane_placuszki_z_ryb_i_krewetek.html"><div class="card-emoji">🐟 🦐</div><div class="card-title">Kukurydziane placuszki z ryb i krewetek</div><div class="card-tag">ryby</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/kurczak_hoisin.html"><div class="card-emoji">🐔</div><div class="card-title">Kurczak hoisin</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/kurczak_w_sosie_śmietanowo_serowym.html"><div class="card-emoji">🐔</div><div class="card-title">Kurczak w sosie śmietanowo serowym</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/kurczak_w_sosie_śmietanowym.html"><div class="card-emoji">🐔</div><div class="card-title">Kurczak w sosie śmietanowym</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/kurczak_z_mozzarellą.html"><div class="card-emoji">🐔</div><div class="card-title">Kurczak z mozzarellą</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/kurczak_z_porami.html"><div class="card-emoji">🐔</div><div class="card-title">Kurczak z porami</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/lasagne_bolognese.html"><div class="card-emoji">🐖 🥩</div><div class="card-title">Lasagne bolognese</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/leczo.html"><div class="card-emoji">🐖</div><div class="card-title">Leczo</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/leczo_wegetariańskie.html"><div class="card-emoji">🌱</div><div class="card-title">Leczo wegetariańskie</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/łatwe_kimchi.html"><div class="card-emoji">🌱 🔥</div><div class="card-title">Łatwe kimchi</div><div class="card-tag">ostre, vege</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/łosoś_teriyaki.html"><div class="card-emoji">🐟</div><div class="card-title">Łosoś teriyaki</div><div class="card-tag">ryby</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/łosoś_z_koperkiem_i_porem.html"><div class="card-emoji">🐟</div><div class="card-title">Łosoś z koperkiem i porem</div><div class="card-tag">ryby</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/łosoś_z_sosem_koperkowym.html"><div class="card-emoji">🐟</div><div class="card-title">Łosoś z sosem koperkowym</div><div class="card-tag">ryby</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/mielone_kalafiorowe.html"><div class="card-emoji">🌱</div><div class="card-title">Mielone kalafiorowe</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/naleśniki_z_kurczakiem.html"><div class="card-emoji">🐔</div><div class="card-title">Naleśniki z kurczakiem</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/nugetsy_z_kurczaka.html"><div class="card-emoji">🐔</div><div class="card-title">Nugetsy z kurczaka</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/pad_gra_prow_z_wołowiną.html"><div class="card-emoji">🥩</div><div class="card-title">Pad gra prow z wołowiną</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/paella.html"><div class="card-emoji">🐟 🐔</div><div class="card-title">Paella</div><div class="card-tag">mięsne, ryby</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/paella_z_kurczakiem.html"><div class="card-emoji">🐔</div><div class="card-title">Paella z kurczakiem</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/paluszki_rybne.html"><div class="card-emoji">🐟</div><div class="card-title">Paluszki rybne</div><div class="card-tag">ryby</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/pałki_z_kurczaka_pieczone.html"><div class="card-emoji">🐔</div><div class="card-title">Pałki z kurczaka pieczone</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/papryka_faszerowana.html"><div class="card-emoji">🐖</div><div class="card-title">Papryka faszerowana</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/pasztet.html"><div class="card-emoji">🐖 🥩</div><div class="card-title">Pasztet</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/pasztet_z_białej_fasoli.html"><div class="card-emoji">🌱</div><div class="card-title">Pasztet z białej fasoli</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/pęczotto_z_burakami_i_kozim_serem.html"><div class="card-emoji">🌱</div><div class="card-title">Pęczotto z burakami i kozim serem</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/pieczone_udko_gęsi.html"><div class="card-emoji">🐔</div><div class="card-title">Pieczone udko gęsi</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/pieczony_filet_z_indyka.html"><div class="card-emoji">🐔</div><div class="card-title">Pieczony filet z indyka</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/pieczony_kalafior_z_ciecierzycą.html"><div class="card-emoji">🌱</div><div class="card-title">Pieczony kalafior z ciecierzycą</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/pierogi_gyoza.html"><div class="card-emoji">🐖</div><div class="card-title">Pierogi gyoza</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/pierogi_leniwe.html"><div class="card-emoji">🌱</div><div class="card-title">Pierogi leniwe</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/pierogi_z_jagodami.html"><div class="card-emoji">🌱</div><div class="card-title">Pierogi z jagodami</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/pierogi_z_kapustą_i_grzybami.html"><div class="card-emoji">🌱</div><div class="card-title">Pierogi z kapustą i grzybami</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/pierogi_z_mięsem.html"><div class="card-emoji">🐔</div><div class="card-title">Pierogi z mięsem</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/pierś_z_kaczki.html"><div class="card-emoji">🦆</div><div class="card-title">Pierś z kaczki</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/pierś_z_kaczki_z_sosem_pomarańczowym.html"><div class="card-emoji">🦆</div><div class="card-title">Pierś z kaczki z sosem pomarańczowym</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/placek_po_węgiersku.html"><div class="card-emoji">🐖</div><div class="card-title">Placek po węgiersku</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/placki_ziemniaczane.html"><div class="card-emoji">🌱</div><div class="card-title">Placki ziemniaczane</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/placki_z_cukinii.html"><div class="card-emoji">🌱</div><div class="card-title">Placki z cukinii</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/potrawka_z_udka_kurczaka_z_warzywami.html"><div class="card-emoji">🐔</div><div class="card-title">Potrawka z udka kurczaka z warzywami</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/pstrąg_pieczony_w_całości.html"><div class="card-emoji">🐟</div><div class="card-title">Pstrąg pieczony w całości</div><div class="card-tag">ryby</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/pulpety_w_sosie_koperkowym.html"><div class="card-emoji">🐖</div><div class="card-title">Pulpety w sosie koperkowym</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/quesadilla.html"><div class="card-emoji">🐔</div><div class="card-title">Quesadilla</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/quesadilla_2.html"><div class="card-emoji">🐔</div><div class="card-title">Quesadilla 2</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/quesadilla_3.html"><div class="card-emoji">🐔</div><div class="card-title">Quesadilla 3</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/quesadilla_4.html"><div class="card-emoji">🌱</div><div class="card-title">Quesadilla 4</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/quinotto_z_czerwoną_fasolą_i_papryką.html"><div class="card-emoji">🌱</div><div class="card-title">Quinotto z czerwoną fasolą i papryką</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/ratatuj.html"><div class="card-emoji">🌱</div><div class="card-title">Ratatuj</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/risotto_primavera.html"><div class="card-emoji">🌱</div><div class="card-title">Risotto primavera</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/risotto_z_szpinakiem_i_krewetkami.html"><div class="card-emoji">🦐</div><div class="card-title">Risotto z szpinakiem i krewetkami</div><div class="card-tag">ryby</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/roladki_z_kurczaka_z_serem_i_papryką_pieczone_w_boczku.html"><div class="card-emoji">🐔</div><div class="card-title">Roladki z kurczaka z serem i papryką pieczone w boczku</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/roladki_z_kurczaka_z_serem_pieczarkami_pieczone_w_boczku.html"><div class="card-emoji">🐔</div><div class="card-title">Roladki z kurczaka z serem pieczarkami pieczone w boczku</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/ryba_z_porami.html"><div class="card-emoji">🐟</div><div class="card-title">Ryba z porami</div><div class="card-tag">ryby</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/ryż_z_krewetkami_na_ostro.html"><div class="card-emoji">🦐 🔥</div><div class="card-title">Ryż z krewetkami na ostro</div><div class="card-tag">ostre, ryby</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/ryż_z_warzywami_chińskimi_i_kurczakiem.html"><div class="card-emoji">🐔</div><div class="card-title">Ryż z warzywami chińskimi i kurczakiem</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/sajgonki.html"><div class="card-emoji">🐖</div><div class="card-title">Sajgonki</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/schabowy_własnym_w_sosie_z_cebulą.html"><div class="card-emoji">🐖</div><div class="card-title">Schabowy własnym w sosie z cebulą</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/schabowy_ze_schabu.html"><div class="card-emoji">🐖</div><div class="card-title">Schabowy ze schabu</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/schabowy_z_kurczaka.html"><div class="card-emoji">🐔</div><div class="card-title">Schabowy z kurczaka</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/schab_nadziewany_mozzarellą_i_pieczarkami.html"><div class="card-emoji">🐖</div><div class="card-title">Schab nadziewany mozzarellą i pieczarkami</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/seleryba.html"><div class="card-emoji">🌱</div><div class="card-title">Seleryba</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/skrzydełka_w_miodzie.html"><div class="card-emoji">🐔</div><div class="card-title">Skrzydełka w miodzie</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/stek_z_sosem_bearnaise_i_szparagami.html"><div class="card-emoji">🥩</div><div class="card-title">Stek z sosem bearnaise i szparagami</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/szare_kluski_ze_skwarkami.html"><div class="card-emoji">🐖</div><div class="card-title">Szare kluski ze skwarkami</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/szaszłyki_z_kurczakiem.html"><div class="card-emoji">🐔</div><div class="card-title">Szaszłyki z kurczakiem</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/sztuka_mięsa_łee.html"><div class="card-emoji">🐖</div><div class="card-title">Sztuka mięsa łee</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/szwedzkie_klopsiki.html"><div class="card-emoji">🐖 🥩</div><div class="card-title">Szwedzkie klopsiki</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/tortilki_ser_bekon_ala_kfc.html"><div class="card-emoji">🐔</div><div class="card-title">Tortilki ser bekon ala kfc</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/tortille.html"><div class="card-emoji">🐔</div><div class="card-title">Tortille</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/warzywka_z_piekarnika.html"><div class="card-emoji">🌱</div><div class="card-title">Warzywka z piekarnika</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/wątróbka.html"><div class="card-emoji">🐖</div><div class="card-title">Wątróbka</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/wegeburgerki.html"><div class="card-emoji">🌱</div><div class="card-title">Wegeburgerki</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/wieprzowina_char_siu.html"><div class="card-emoji">🐖</div><div class="card-title">Wieprzowina char siu</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/wieprzowina_po_chińsku.html"><div class="card-emoji">🐖</div><div class="card-title">Wieprzowina po chińsku</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/wieprzowina_po_chińsku_z_mango.html"><div class="card-emoji">🐖</div><div class="card-title">Wieprzowina po chińsku z mango</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/wołowina_po_burgundzku.html"><div class="card-emoji">🥩</div><div class="card-title">Wołowina po burgundzku</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/zapiekanka_łukaszkowa.html"><div class="card-emoji">🐖 🥩</div><div class="card-title">Zapiekanka łukaszkowa</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/zapiekanka_makaronowa.html"><div class="card-emoji">🐖</div><div class="card-title">Zapiekanka makaronowa</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/zapiekanka_makaronowa_ze_szparagami.html"><div class="card-emoji">🐟</div><div class="card-title">Zapiekanka makaronowa ze szparagami</div><div class="card-tag">ryby</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/zapiekanka_makaronowa_2.html"><div class="card-emoji">🐔</div><div class="card-title">Zapiekanka makaronowa 2</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/zapiekanka_pasterska.html"><div class="card-emoji">🥩</div><div class="card-title">Zapiekanka pasterska</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/zapiekanka_ziemniaczana.html"><div class="card-emoji">🐖</div><div class="card-title">Zapiekanka ziemniaczana</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/zapiekanki.html"><div class="card-emoji">🐖</div><div class="card-title">Zapiekanki</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/zielone_curry_z_groszkiem_cukrowym.html"><div class="card-emoji">🐔</div><div class="card-title">Zielone curry z groszkiem cukrowym</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/ziemniaki_faszerowane.html"><div class="card-emoji">🐖</div><div class="card-title">Ziemniaki faszerowane</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/zrazy_wołowe.html"><div class="card-emoji">🥩</div><div class="card-title">Zrazy wołowe</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Dania_glowne/żeberka_w_miodzie.html"><div class="card-emoji">🐖</div><div class="card-title">Żeberka w miodzie</div><div class="card-tag">mięsne</div></a></article>
</div>
</div>
++++

== Desery

++++
<div class="cards-wrapper">
<div class="cards-grid">
<article class="card"><a href="Przepisy/Desery/baklava.html"><div class="card-emoji">🌱</div><div class="card-title">Baklava</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Desery/brownie.html"><div class="card-emoji">🌱</div><div class="card-title">Brownie</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Desery/bułki_cynamonowe.html"><div class="card-emoji">🌱</div><div class="card-title">Bułki cynamonowe</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Desery/chlebek_bananowy.html"><div class="card-emoji">🌱</div><div class="card-title">Chlebek bananowy</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Desery/ciastka_z_maszynki.html"><div class="card-emoji">🌱</div><div class="card-title">Ciastka z maszynki</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Desery/ciasto_drożdżowe_ze_śliwkami.html"><div class="card-emoji">🌱</div><div class="card-title">Ciasto drożdżowe ze śliwkami</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Desery/ciasto_marchewkowe.html"><div class="card-emoji">🌱</div><div class="card-title">Ciasto marchewkowe</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Desery/ciasto_porzeczkowiec.html"><div class="card-emoji">🌱</div><div class="card-title">Ciasto porzeczkowiec</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Desery/fluffy_pancakes.html"><div class="card-emoji">🌱</div><div class="card-title">Fluffy pancakes</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Desery/jogurt_grecki_z_miodem_i_orzechami.html"><div class="card-emoji">🌱</div><div class="card-title">Jogurt grecki z miodem i orzechami</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Desery/kokosanka.html"><div class="card-emoji">🌱</div><div class="card-title">Kokosanka</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Desery/kokosowy_jabłecznik.html"><div class="card-emoji">🌱</div><div class="card-title">Kokosowy jabłecznik</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Desery/muffinki_z_malinami.html"><div class="card-emoji">🌱</div><div class="card-title">Muffinki z malinami</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Desery/murzynek_z_wiśniami.html"><div class="card-emoji">🌱</div><div class="card-title">Murzynek z wiśniami</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Desery/pierniczki.html"><div class="card-emoji">🌱</div><div class="card-title">Pierniczki</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Desery/racuchy_z_jabłkami.html"><div class="card-emoji">🌱</div><div class="card-title">Racuchy z jabłkami</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Desery/sernik.html"><div class="card-emoji">🌱</div><div class="card-title">Sernik</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Desery/sernik_tradycyjny.html"><div class="card-emoji">🌱</div><div class="card-title">Sernik tradycyjny</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Desery/skyrnik.html"><div class="card-emoji">🌱</div><div class="card-title">Skyrnik</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Desery/sos_waniliowy.html"><div class="card-emoji">🌱</div><div class="card-title">Sos waniliowy</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Desery/szybki_piernik.html"><div class="card-emoji">🌱</div><div class="card-title">Szybki piernik</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Desery/tarta_bananowa.html"><div class="card-emoji">🌱</div><div class="card-title">Tarta bananowa</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Desery/tort_czekoladowy.html"><div class="card-emoji">🌱</div><div class="card-title">Tort czekoladowy</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Desery/tort_raffaello.html"><div class="card-emoji">🌱</div><div class="card-title">Tort raffaello</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Desery/tort_truskawkowy.html"><div class="card-emoji">🌱</div><div class="card-title">Tort truskawkowy</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Desery/wiśniowy_paj.html"><div class="card-emoji">🌱</div><div class="card-title">Wiśniowy paj</div><div class="card-tag">vege</div></a></article>
</div>
</div>
++++

== Makarony

++++
<div class="cards-wrapper">
<div class="cards-grid">
<article class="card"><a href="Przepisy/Makarony/bucatini_alla_amatriciana.html"><div class="card-emoji">🐖</div><div class="card-title">Bucatini alla amatriciana</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Makarony/cannelloni.html"><div class="card-emoji">🥩</div><div class="card-title">Cannelloni</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Makarony/makaron_aglio_olio_z_pomidorkami.html"><div class="card-emoji">🌱</div><div class="card-title">Makaron aglio olio z pomidorkami</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Makarony/makaron_azjatycki_z_pikantną_wołowiną.html"><div class="card-emoji">🥩</div><div class="card-title">Makaron azjatycki z pikantną wołowiną</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Makarony/makaron_carbonara.html"><div class="card-emoji">🐖</div><div class="card-title">Makaron carbonara</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Makarony/makaron_chiński_z_krewetkami.html"><div class="card-emoji">🦐</div><div class="card-title">Makaron chiński z krewetkami</div><div class="card-tag">ryby</div></a></article>
<article class="card"><a href="Przepisy/Makarony/makaron_w_sosie_słodko_kwaśnym.html"><div class="card-emoji">🐔</div><div class="card-title">Makaron w sosie słodko kwaśnym</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Makarony/makaron_zapiekany_z_boczkiem_i_cukinią.html"><div class="card-emoji">🐖</div><div class="card-title">Makaron zapiekany z boczkiem i cukinią</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Makarony/makaron_ze_szpinakiem.html"><div class="card-emoji">🌱</div><div class="card-title">Makaron ze szpinakiem</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Makarony/makaron_z_brokułami.html"><div class="card-emoji">🌱</div><div class="card-title">Makaron z brokułami</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Makarony/makaron_z_krewetkami.html"><div class="card-emoji">🦐</div><div class="card-title">Makaron z krewetkami</div><div class="card-tag">ryby</div></a></article>
<article class="card"><a href="Przepisy/Makarony/makaron_z_pesto.html"><div class="card-emoji">🌱</div><div class="card-title">Makaron z pesto</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Makarony/makaron_z_pieczonymi_pomidorami.html"><div class="card-emoji">🌱</div><div class="card-title">Makaron z pieczonymi pomidorami</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Makarony/makaron_z_pulpecikami.html"><div class="card-emoji">🐖 🥩</div><div class="card-title">Makaron z pulpecikami</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Makarony/noodle_z_krewetkami_po_koreańsku.html"><div class="card-emoji">🦐</div><div class="card-title">Noodle z krewetkami po koreańsku</div><div class="card-tag">ryby</div></a></article>
<article class="card"><a href="Przepisy/Makarony/noodle_z_mielonym_mięsem_drobiowym.html"><div class="card-emoji">🐔</div><div class="card-title">Noodle z mielonym mięsem drobiowym</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Makarony/pasta_alla_norma.html"><div class="card-emoji">🌱</div><div class="card-title">Pasta alla norma</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Makarony/pesto_alla_trapanese.html"><div class="card-emoji">🌱</div><div class="card-title">Pesto alla trapanese</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Makarony/ragu_alla_bolognese.html"><div class="card-emoji">🥩</div><div class="card-title">Ragu alla bolognese</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Makarony/spaghetti_bolognese.html"><div class="card-emoji">🐖</div><div class="card-title">Spaghetti bolognese</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Makarony/spaghetti_napoli.html"><div class="card-emoji">🌱</div><div class="card-title">Spaghetti napoli</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Makarony/spaghetti_pomodoro.html"><div class="card-emoji">🌱</div><div class="card-title">Spaghetti pomodoro</div><div class="card-tag">vege</div></a></article>
</div>
</div>
++++

== Przetwory

++++
<div class="cards-wrapper">
<div class="cards-grid">
<article class="card"><a href="Przepisy/Przetwory/kompot_czeresniowy.html"><div class="card-emoji">🌱</div><div class="card-title">Kompot czeresniowy</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Przetwory/nalewka_cytrynowa.html"><div class="card-emoji">🌱</div><div class="card-title">Nalewka cytrynowa</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Przetwory/nalewka_gruszkowa.html"><div class="card-emoji">🌱</div><div class="card-title">Nalewka gruszkowa</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Przetwory/nalewka_jabłkowa.html"><div class="card-emoji">🌱</div><div class="card-title">Nalewka jabłkowa</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Przetwory/nalewka_malinowa.html"><div class="card-emoji">🌱</div><div class="card-title">Nalewka malinowa</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Przetwory/nalewka_mango.html"><div class="card-emoji">🌱</div><div class="card-title">Nalewka mango</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Przetwory/nalewka_z_kwiatów_bzu.html"><div class="card-emoji">🌱</div><div class="card-title">Nalewka z kwiatów bzu</div><div class="card-tag">vege</div></a></article>
</div>
</div>
++++

== Przystawki

++++
<div class="cards-wrapper">
<div class="cards-grid">
<article class="card"><a href="Przepisy/Przystawki/bułeczki_czosnkowe.html"><div class="card-emoji">🌱</div><div class="card-title">Bułeczki czosnkowe</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Przystawki/feta_zapiekana_w_cieście_filo_na_słodko.html"><div class="card-emoji">🌱</div><div class="card-title">Feta zapiekana w cieście filo na słodko</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Przystawki/granola_z_owocami_i_jogurtem.html"><div class="card-emoji">🌱</div><div class="card-title">Granola z owocami i jogurtem</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Przystawki/guacamole.html"><div class="card-emoji">🌱</div><div class="card-title">Guacamole</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Przystawki/jajecznica.html"><div class="card-emoji">🌱</div><div class="card-title">Jajecznica</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Przystawki/nocna_owsianka.html"><div class="card-emoji">🌱</div><div class="card-title">Nocna owsianka</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Przystawki/pasta_z_makreli.html"><div class="card-emoji">🐟</div><div class="card-title">Pasta z makreli</div><div class="card-tag">ryby</div></a></article>
<article class="card"><a href="Przepisy/Przystawki/pita.html"><div class="card-emoji">🌱</div><div class="card-title">Pita</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Przystawki/roladki_tortilowe.html"><div class="card-emoji">🐖</div><div class="card-title">Roladki tortilowe</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Przystawki/rozczyn.html"><div class="card-emoji">🌱</div><div class="card-title">Rozczyn</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Przystawki/salsa_pomidorowa.html"><div class="card-emoji">🌱</div><div class="card-title">Salsa pomidorowa</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Przystawki/sos_grzybowy.html"><div class="card-emoji">🌱</div><div class="card-title">Sos grzybowy</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Przystawki/tatar_ze_śledzia.html"><div class="card-emoji">🐟</div><div class="card-title">Tatar ze śledzia</div><div class="card-tag">ryby</div></a></article>
<article class="card"><a href="Przepisy/Przystawki/tortille_placki.html"><div class="card-emoji">🌱</div><div class="card-title">Tortille placki</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Przystawki/tzatziki.html"><div class="card-emoji">🌱</div><div class="card-title">Tzatziki</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Przystawki/wegański_tatar.html"><div class="card-emoji">🌱</div><div class="card-title">Wegański tatar</div><div class="card-tag">vege</div></a></article>
</div>
</div>
++++

== Salatki

++++
<div class="cards-wrapper">
<div class="cards-grid">
<article class="card"><a href="Przepisy/Salatki/makaronowa_sałatka_warstwowa.html"><div class="card-emoji">🌱</div><div class="card-title">Makaronowa sałatka warstwowa</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Salatki/sałatka_cezar.html"><div class="card-emoji">🐔</div><div class="card-title">Sałatka cezar</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Salatki/sałatka_grecka.html"><div class="card-emoji">🌱</div><div class="card-title">Sałatka grecka</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Salatki/sałatka_gyros.html"><div class="card-emoji">🐔</div><div class="card-title">Sałatka gyros</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Salatki/sałatka_japońska_z_krewetkami.html"><div class="card-emoji">🦐</div><div class="card-title">Sałatka japońska z krewetkami</div><div class="card-tag">ryby</div></a></article>
<article class="card"><a href="Przepisy/Salatki/sałatka_warstwowa_z_szynką_jajkiem_i_serem_żółtym.html"><div class="card-emoji">🐖</div><div class="card-title">Sałatka warstwowa z szynką jajkiem i serem żółtym</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Salatki/sałatka_z_krewetkami.html"><div class="card-emoji">🦐</div><div class="card-title">Sałatka z krewetkami</div><div class="card-tag">ryby</div></a></article>
<article class="card"><a href="Przepisy/Salatki/sałatka_z_kurczakiem.html"><div class="card-emoji">🐔</div><div class="card-title">Sałatka z kurczakiem</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Salatki/sałatka_z_kurczakiem_i_pomarańczą.html"><div class="card-emoji">🐔</div><div class="card-title">Sałatka z kurczakiem i pomarańczą</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Salatki/sałatka_z_łososiem_i_mozzarellą.html"><div class="card-emoji">🐟</div><div class="card-title">Sałatka z łososiem i mozzarellą</div><div class="card-tag">ryby</div></a></article>
<article class="card"><a href="Przepisy/Salatki/sałatka_z_mango_i_awokado.html"><div class="card-emoji">🌱</div><div class="card-title">Sałatka z mango i awokado</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Salatki/sałatka_z_rukolą_granatem_i_pomarańczą.html"><div class="card-emoji">🌱</div><div class="card-title">Sałatka z rukolą granatem i pomarańczą</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Salatki/sałatka_z_sałatą_lodową_suszonymi_pomidorami_i_fetą.html"><div class="card-emoji">🌱</div><div class="card-title">Sałatka z sałatą lodową suszonymi pomidorami i fetą</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Salatki/sałatka_z_suszonymi_pomidorami_serem_pleśniowym_i_pestkami_dyni.html"><div class="card-emoji">🌱</div><div class="card-title">Sałatka z suszonymi pomidorami serem pleśniowym i pestkami dyni</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Salatki/tabbouleh_sałatka_z_bulgurem.html"><div class="card-emoji">🌱</div><div class="card-title">Tabbouleh sałatka z bulgurem</div><div class="card-tag">vege</div></a></article>
</div>
</div>
++++

== Zupy

++++
<div class="cards-wrapper">
<div class="cards-grid">
<article class="card"><a href="Przepisy/Zupy/francuska_zupa_cebulowa.html"><div class="card-emoji">🌱</div><div class="card-title">Francuska zupa cebulowa</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Zupy/hiszpańska_zupa_z_ciecierzycy.html"><div class="card-emoji">🌱</div><div class="card-title">Hiszpańska zupa z ciecierzycy</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Zupy/ramen_shoyu.html"><div class="card-emoji">🐔 🐖</div><div class="card-title">Ramen shoyu</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Zupy/tantanmen_ramen.html"><div class="card-emoji">🐖</div><div class="card-title">Tantanmen ramen</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Zupy/zapiekany_rosół.html"><div class="card-emoji">🐔</div><div class="card-title">Zapiekany rosół</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Zupy/zupa_barszcz_z_uszkami.html"><div class="card-emoji">🌱</div><div class="card-title">Zupa barszcz z uszkami</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Zupy/zupa_brokułowa_z_ryżem_i_koperkiem.html"><div class="card-emoji">🌱</div><div class="card-title">Zupa brokułowa z ryżem i koperkiem</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Zupy/zupa_buraczkowa.html"><div class="card-emoji">🌱</div><div class="card-title">Zupa buraczkowa</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Zupy/zupa_fasolkowa.html"><div class="card-emoji">🌱</div><div class="card-title">Zupa fasolkowa</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Zupy/zupa_fasolowa.html"><div class="card-emoji">🌱</div><div class="card-title">Zupa fasolowa</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Zupy/zupa_grochowa_2.html"><div class="card-emoji">🌱</div><div class="card-title">Zupa grochowa 2</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Zupy/zupa_grochówka.html"><div class="card-emoji">🐖</div><div class="card-title">Zupa grochówka</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Zupy/zupa_grzybowa_2.html"><div class="card-emoji">🌱</div><div class="card-title">Zupa grzybowa 2</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Zupy/zupa_grzybowa_50_złotych_grzybów.html"><div class="card-emoji">🌱</div><div class="card-title">Zupa grzybowa 50 złotych grzybów</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Zupy/zupa_kalafiorowa.html"><div class="card-emoji">🌱</div><div class="card-title">Zupa kalafiorowa</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Zupy/zupa_klopsowa.html"><div class="card-emoji">🐖</div><div class="card-title">Zupa klopsowa</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Zupy/zupa_krem_z_groszku_z_grzankami.html"><div class="card-emoji">🌱</div><div class="card-title">Zupa krem z groszku z grzankami</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Zupy/zupa_krem_z_marchewki_z_grzankami.html"><div class="card-emoji">🌱</div><div class="card-title">Zupa krem z marchewki z grzankami</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Zupy/zupa_krem_z_szparagów.html"><div class="card-emoji">🌱</div><div class="card-title">Zupa krem z szparagów</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Zupy/zupa_krupnik.html"><div class="card-emoji">🐔</div><div class="card-title">Zupa krupnik</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Zupy/zupa_kurkowa_z_makaronem.html"><div class="card-emoji">🌱</div><div class="card-title">Zupa kurkowa z makaronem</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Zupy/zupa_ogórkowa.html"><div class="card-emoji">🌱</div><div class="card-title">Zupa ogórkowa</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Zupy/zupa_pieczarkowa.html"><div class="card-emoji">🌱</div><div class="card-title">Zupa pieczarkowa</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Zupy/zupa_pomidorowa.html"><div class="card-emoji">🐔</div><div class="card-title">Zupa pomidorowa</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Zupy/zupa_rosół.html"><div class="card-emoji">🐔</div><div class="card-title">Zupa rosół</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Zupy/zupa_serkowa_z_klopsami.html"><div class="card-emoji">🐖</div><div class="card-title">Zupa serkowa z klopsami</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Zupy/zupa_tajska.html"><div class="card-emoji">🐔</div><div class="card-title">Zupa tajska</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Zupy/zupa_tajska_z_owocami_morza.html"><div class="card-emoji">🐟 🦐</div><div class="card-title">Zupa tajska z owocami morza</div><div class="card-tag">ryby</div></a></article>
<article class="card"><a href="Przepisy/Zupy/zupa_warzywna.html"><div class="card-emoji">🌱</div><div class="card-title">Zupa warzywna</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Zupy/zupa_z_cukinii.html"><div class="card-emoji">🌱</div><div class="card-title">Zupa z cukinii</div><div class="card-tag">vege</div></a></article>
<article class="card"><a href="Przepisy/Zupy/zupa_żurek_z_białą_kiełbasą.html"><div class="card-emoji">🐖</div><div class="card-title">Zupa żurek z białą kiełbasą</div><div class="card-tag">mięsne</div></a></article>
<article class="card"><a href="Przepisy/Zupy/zuppa_di_pesce.html"><div class="card-emoji">🐟 🦐</div><div class="card-title">Zuppa di pesce</div><div class="card-tag">ryby</div></a></article>
</div>
</div>
++++
