= Bigos z kapustą zwykłą i kiszoną

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* 8 porcji
* https://www.kwestiasmaku.com/przepis/bigos[link do źródła przepisu]

== Składniki
* 40 g suszonych grzybów
* 200 g boczku
* 400 g mięsa gulaszowego wieprzowego
* 400 g mięsa gulaszowego wołowego
* 3 łyżki oleju
* 1 litr bulionu wołowego
* 1 kg świeżej białej kapusty
* 500 g kiszonej kapusty (waga po odciśnięciu)
* 100 g suszonych śliwek
* 2 cebule
* 250 g dobrej kiełbasy np. wiejskiej
* 1 łyżka koncentratu pomidorowego
* przyprawy: po 3 liście laurowe, kulki ziela angielskiego i jałowca oraz 1/2 łyżeczki kminku i szczypta ostrej papryki lub płatków chili

|
== Przygotowanie
Suszone grzyby połamać, zalać szklanką ciepłej wody i odstawić do namoczenia.

Przygotować duży garnek z grubym dnem oraz dużą patelnię. Boczek pokroić w kosteczkę. Całe mięso pokroić w niedużą kostkę.

Na gorącą patelnię wlać 1 łyżkę oleju, włożyć boczek i co chwilę mieszając smażyć przez ok. 5 minut, przełożyć do garnka.

Na patelnię wlać drugą łyżkę oleju i partiami obsmażać mięso, następnie przekładać je do garnka z boczkiem.

Garnek z obsmażonym mięsem postawić na ogniu, wlać bulion (najlepiej gorący) i zagotować. Gotować pod przykryciem przez około 45 minut.

Świeżą kapustę drobno poszatkować, pomijając głąba ze środka kapusty. Włożyć do garnka z mięsem i wymieszać. Przykryć i gotować przez około 1/2 godziny.

Ciągle gotując bigos dodać grzyby wraz z wodą z moczenia, odciśnię kapustę kiszoną, posiekane śliwki oraz przyprawy. Dokładnie wymieszać i gotować przez około 1/2 godziny.

Cebulę pokroić w kostkę, następnie zeszklić ją na patelni na 1 łyżce oleju. Przełożyć do garnka z mięsem.

Kiełbasę obrać, pokroić w kostkę lub plasterki i podsmażyć na patelni, dodać do bigosu.

Dodać koncentrat, dokładnie wymieszać, przykryć i gotować przez ok. 1 godzinę. Czasem zamieszać i sprawdzić czy bigos nie przywiera do dna. Doprawić pieprzem oraz w razie potrzeby solą.

== Zdjęcia
|===
