= Buraki po burgundzku

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* Czas przygotowania: powyżej godziny									180M
* https://www.jadlonomia.com/przepisy/burak-z-burgundii[link do źródła przepisu]

== Składniki


|
== Przygotowanie
Szalotki obrać, ale nie kroić. Po kolei nadziewać każdą z nich na widelec i opalać nad palnikiem gazowym przez kilka minut, dopóki nie będzie mocno przypalona. Opalone szalotki odłożyć na bok.

Pieczarki pokroić na ćwiartki, te najmniejsze wystarczy przekroić na pół. Na dnie dużego garnka z bardzo grubym dnem rozgrzać kilka łyżek oliwy i dodać pokrojone pieczarki, poddusić przez chwilę i dodać opalone szalotki pokrojone w bardzo grube plastry.

Dodać pokrojone w pół-talarki marchewki, pokrojoną w drobną kostkę pietruszkę, buraczki, pokrojone w grube paski, orzechy laskowe i drobno posiekany czosnek. Warzywa kilka razy delikatnie wymieszać, następnie dodać soczewicę, bulion, wino, przecier pomidorowy i zioła. Wsypać sporą szczyptę soli i gotować na minimalnym ogniu przez przynajmniej godzinę.

Po upływie godziny spróbować i dodać sól oraz pieprz do smaku. W razie potrzeby dodać jeszcze pół szklanki bulionu i gotować kolejne pół godziny.

Gotowy gulasz jeść z bagietką lub chlebem, koniecznie wycierając spód talerza kawałkiem pieczywa. Gulasz jest lepszy z każdym kolejnym dniem, szczególnie warto poczekać do trzeciego dnia.

== Zdjęcia
|===
