= Butter chicken

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* https://www.kwestiasmaku.com/przepis/butter-chicken[link do źródła przepisu]

== Składniki
* 500 g filetu z piersi kurczaka
* 1 łyżka tartego imbiru
* 2 ząbki czosnku
* sól i pieprz
* 1 łyżka garam masala
* 2 łyżki soku z cytryny
* 1 łyżka oliwy
* 1/2 szklanki jogurtu
|
== Przygotowanie
Filety z piersi kurczaka oczyścić z błonek i kostek i pokroić na ok. 2 - 3 cm kawałki. Natrzeć startym imbirem i czosnkiem, doprawić solą, pieprzem i garam masalą. Skropić sokiem z cytryny, polać oliwą i włożyć do miski. Dodać jogurt i dokładnie wymieszać. Przykryć i odstawić do lodówki na minimum 2 godziny a najlepiej na całą noc. Orzechy nerkowca zalać wodą i również zostawić do namoczenia na całą noc.

Wyjąć kurczaka z lodówki i ocieplić w temperaturze pokojowej. W garnku rozgrzać łyżkę masła klarowanego i zeszklić pokrojoną cebulę. Dodać przyprawy oraz orzechy nerkowca i chwilę podsmażyć mieszając, następnie dodać pomidory oraz bulion. Wymieszać, zagotować i zostawić na małym gazie pod przykryciem na ok. 10 minut. Zmiksować na gładki sos w blenderze stojącym.

W międzyczasie na patelni rozgrzać drugą łyżkę masła klarowanego i obsmażyć zamarynowane kawałki kurczaka. Obsmażonego kurczaka przenieść do zmiksowanego sosu i całość zagotować. Śmietankę zahartować (dodać najpierw kilka łyżek gorącego sosu i wymieszać), następnie wlać wszystko do garnka z sosem i kurczakiem i wymieszać. Gotować jeszcze ok. 3 minuty na małym ogniu. Podawać z ryżem i kolendrą.
== Zdjęcia
|===
