= Ciecierzyca po bretońsku

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* Czas przygotowania: 15 minut									15M
* https://www.jadlonomia.com/przepisy/ciecierzyca-po-bretonsku[link do źródła przepisu]

== Składniki
* 1 cebula czerwona
* 4 liście laurowe
* 2 ziarna ziela angielskiego
* 2 ziarna pieprzu
* olej roślinny do smażenia
* 4 puszki ciecierzycy, odcedzone
* 1 łyżeczka wędzonej papryki
* 1 łyżeczka słodkiej papryki
* 1/2 łyżeczki ostrej papryki
* 1/2 łyżeczka mielonego kminku, opcjonalnie
* 1/2 łyżeczki mielonego kuminu, opcjonalnie
* 1 łyżeczka majeranku, suszonego
* ½ łyżeczki pietruszki, suszonego
* 500 g przecieru pomidorowego
* 4 łyżki koncentratu pomidorowego
* ½ - ¾ szklanki wody
* 1 łyżka sosu sojowego
* sól i czarny pieprz


|
== Przygotowanie
Cebulę pokroić w kostkę. Na dnie garnka rozgrzać olej, dodać cebulę oraz liście laurowe, ziele angielskie i ziarna pieprzu. Smażyć przez 2 - 3 minuty do czasu, aż cebula będzie złota.

Wtedy dodać ciecierzycę, dokładnie wymieszać i dodać wszystkie pozostałe przyprawy. Smażyć minutę po czym dodać pozostałe składniki.

Garnek przykryć i gotować przez 7 - 15 minut. Na koniec doprawić do smaku solą oraz pieprzem, podawać z chlebem lub z ulubioną kaszą.

Ten przepis jest prosty jak drut i nic tu nie można zepsuć. Ale warto wcześniej naszykować wszystkie przyprawy, żeby mieć je pod ręką w odpowiednim momencie 🙂



== Zdjęcia
|===
