= Curry z kalafiora

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* Czas przygotowania: do 45 minut									45M
* https://www.jadlonomia.com/przepisy/na-przednowku-czyli-ulubione-curry-z[link do źródła przepisu]

== Składniki


|
== Przygotowanie
Na dnie dużego garnka z grubym dnem rozgrzać kilka łyżek oleju, dodać cebulę i zeszklić. Dodać wszystkie przyprawy, smażyć przez 2-3 minuty.

Następnie dodać kalafiora i ziemniaka, wszystko delikatnie, ale bardzo dokładnie wymieszać i wlać wodę oraz pomidory. Gotować na małym ogniu przez około 20 minut albo do miękkości warzyw, powinny być miękkie, ale nie rozgotowane.

W międzyczasie przygotować ryż. Do niedużego garnka dodać wszystkie składniki, garnek przykryć i gotować na małym ogniu przez 5 minut. Potem wyłączyć ogień i pozostawić ryż w garnku kolejne 15 minut – w tym czasie wchłonie wodę i będzie puszysty.

Gotowe curry spróbować, dosolić do smaku i ewentualnie dodać kilka kropel soku z cytryny. Podawać bardzo gorące, z cynamonowym ryżem.

Nie podnosić pokrywki z garnka z ryżem! Dzięki temu ryż będzie sypki, puchaty, miękki i w końcu nic się nie przypali 🙂

== Zdjęcia
|===
