= Dorsz w sosie curry

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* 4 porcje
* https://www.kwestiasmaku.com/przepis/dorsz-w-sosie-curry[link do źródła przepisu]

== Składniki
* 400 g filetów dorsza
* 1 łyżka czerwonej pasty curry
* 1 łyżka oleju kokosowego
* 200 ml mleka kokosowego
* 2 łyżeczki koncentratu pomidorowego
* 1 łyżka sosu rybnego
* opcjonalnie: 2 liście limonki kafir*
* 150 g groszku cukrowego lub fasolki szparagowej (mrożonej)
* limonka
* 200 g ryżu


|
== Przygotowanie
Rybę pokroić na porcje, doprawić solą, pieprzem oraz natrzeć połową pasty curry.

Rozgrzać wok lub dużą patelnię i na oleju kokosowym obsmażyć z dwóch stron rybę, odłożyć na talerz.

Wytrzeć naczynie ręcznikiem papierowym, wlać mleko kokosowe, dodać pozostałą pastę curry, koncentrat pomidorowy oraz sos rybny i kafir. Gotować przez ok. 6 minut.

Dodać groszek lub pokrojoną fasolkę a także podsmażonego dorsza. Gotować przez ok. 5 minut.

Skropić sokiem z limonki i podawać z ryżem.



== Zdjęcia
|===
