= Falafel, humus i świeże warzywa (marchewki, sałata)

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* Czas przygotowania: noc namaczania + 30 minut									0M
* https://www.jadlonomia.com/przepisy/falafel-idealny[link do źródła przepisu]

== Składniki


|
== Przygotowanie
Ciecierzycę odcedzić, opłukać i zmielić w maszynce do mielenia razem z cebulą. Do zmielonej masy dać natki, sodę, sól i resztę przypraw, jeśli nie macie mielonych przypraw, możecie też zmielić je razem z ciecierzycą. Wszystko dokładnie wymieszać i dodać 1 - 2 łyżki wody - masa jest dobra, kiedy ściśnięta w ręce łatwo przyjmuje kształt. Przykryć szczelnie folią i odstawić do lodówki na pół godziny lub dłużej.

W dużej patelni z grubym dnem rozgrzać olej, warstwa powinna mieć 2 - 3 cm. Nabierać po łyżce masy i formować małe, lekko spłaszczone kulki. Ważne jest, by dokładnie je ścisnąć, w przeciwnym wypadku będą się rozpadać.

Uformowane falafle od razu wrzucać na gorący olej na patelni i smażyć 2 - 3 minuty z każdej strony. Następnie odkładać na talerz wyłożony papierowym ręcznikiem, żeby odsączyć je z tłuszczu i od razu podawać ze świeżymi warzywami, sałatkami lub hummusem.

== Zdjęcia
|===
