= Francuska zupa cebulowa

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* 6 porcji
* https://www.kwestiasmaku.com/kuchnia_francuska/zupa_cebulowa/przepis.html[link do źródła przepisu]

== Składniki
* 900 g cebuli
* 2 łyżki masła
* 2 łyżki oliwy
* 250 ml białego wytrawnego wina
* 1 litr bulionu wołowego np. z tego przepisu
* 60 ml koniaku, brandy lub sherry (można pominąć)
* sól i świeżo zmielony czarny pieprz

|
== Przygotowanie
Cebulę obrać, przekroić wzdłuż na pół i posiekać w poprzek na półplasterki grubości ok. 1,5 - 2 mm. W dużym i szerokim garnku roztopić masło z oliwą.

Ustawić ogień na średni, dodać cebulę i mieszając smażyć na średnim ogniu przez ok. 25 minut, aż cebula będzie skarmelizowana (miękka i lekko brązowa).

Zwiększyć ogień, wlać wino i wymieszać cebulę drewnianą łyżką, zeskrobać z dna garnka drobne przyrumienienia. Gotować przez 3 minuty następnie dodać wrzący bulion i gotować na małym ogniu pod przykryciem przez ok. 25 minut. Zupę doprawić solą i świeżo zmielonym czarnym pieprzem. Dodać brandy i jeszcze chwilę pogotować.

Piekarnik nagrzać do 220 stopni, ustawić kratkę na nieco wyższej półce niż połowa piekarnika. Bagietkę pokroić na kromki i opiec na złoty kolor z dwóch stron na tosterze lub w piekarniku, następnie grzanki delikatnie natrzeć przekrojonym ząbkiem czosnku.

Do 4 małych żaroodpornych misek (lub do jednego większego garnka żaroodpornego lub naczynia) nalać gorącą zupę i przykryć grzankami, posypać tartym serem i ewentualnie posypać świeżym tymiankiem. Zapiekać przez około 5 minut aż ser się roztopi.

== Zdjęcia
|===
