= Krewetki po luizjańsku

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* ok. 2 - 3 porcje
* https://www.kwestiasmaku.com/przepis/krewetki-w-sosie-po-luizjansku[link do źródła przepisu]

== Składniki
* ok. 375 g krewetek
* 1 łyżka oleju roślinnego
* 1 mała cebulka
* 2 ząbki czosnku
* 2 łyżki masła
* 2 łyżki słodkiego sosu chilli
* 2 łyżki sosu worcestershire
* 1/4 szklanki bulionu
* 2 łyżki soku z cytryny
* 1/2 łyżeczki cukru
* przyprawy: po 1 łyżeczce suszonego oregano i tymianku, 2 łyżeczki papryki w proszku
* do podania: bagietka, natka pietruszki

|
== Przygotowanie
Krewetki rozmrozić jeśli były zamrożone i oczyścić jeśli jest potrzeba.

Na większej patelni na łyżce oleju zeszklić pokrojoną w kosteczkę cebulę. Dodać przeciśnięty przez praskę czosnek i podsmażać przez ok. pół minuty.

Dodać 1 łyżkę masła, słodki sos chilli, sos worcestershire, bulion, sok z cytryny i cukier. Zagotować, następnie dodać przyprawy i gotować przez 2 minuty co chwilę mieszając drewnianą łyżką.

Do sosu dodać krewetki i gotować przez ok. 1 minutę, doprawić szczyptą soli i pieprzem (przed posoleniem sprawdzić czy sos nie jest już wystarczająco słony). Przewrócić na drugą stronę i powtórzyć gotowanie przez 1 minutę.

Dodać pozostałą łyżkę masła, roztopić i wymieszać. Posypać posiekaną natką pietruszki i podawać z pokrojoną bagietką.

== Zdjęcia
|===
