= Krokiety z kapustą i grzybami

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* https://www.kwestiasmaku.com/przepis/krokiety-z-kapusta-i-grzybami[link do źródła przepisu]

== Składniki
* 40 g suszonych grzybów
* 500 g kapusty kiszonej
* 1 mała marchewka
* 1 duża cebula
* 4 łyżki oleju roślinnego
* 400 g pieczarek
* sól, zmielony pieprz, 1 listek laurowy, 2 ziela angielskie
* 1 szklanka mąki pszennej
* 2 jajka
* 1 szklanka mleka
* 3/4 szklanki wody (najlepiej gazowanej)
* szczypta soli
* 3 łyżki masła lub oleju roślinnego
* 2 jajka
* sól
* bułka tarta
* masło klarowane do smażenia
* barszcz wigilijny lub barszcz czerwony


|
== Przygotowanie
Grzyby wypłukać w chłodnej wodzie, włożyć do rondelka, zalać 2 szklankami wody i odstawić do namoczenia na całą noc lub na kilka godzin.

Wylać wodę z moczenia grzybów, wlać świeżą w ilości 1 szklanki, posolić i gotować przez ok. 20 minut. Odcedzić zachowując oddzielnie wywar i grzyby. Grzyby drobno posiekać na desce.

Kapustę odcisnąć z soku i posiekać, włożyć do garnka i zalać przecedzonym wywarem z grzybów. Wlać dodatkowa 1 szklankę wody lub bulionu, dodać listek laurowy i ziela angielskie i gotować pod przykryciem, aż do miękkości przez ok. 40 minut.

Marchewkę obrać, umyć i zetrzeć na tarce o dużych oczkach. Dodać do gotującej się kapusty na 10 minut przed końcem jej gotowania.

Obrać i posiekać cebulę w drobną kosteczkę. Zeszklić na patelni na 2 łyżkach oleju.

Cebulę i grzyby dodać do ugotowanej kapusty.

Pieczarki umyć, pokroić na plasterki i odparować na patelni co chwilę mieszając. Dodać 2 łyżki oleju i smażyć przez kilka minut w międzyczasie doprawić solą i pieprzem. Zdjąć z patelni i posiekać, dodać do kapusty.

Kapustę doprawić solą, pieprzem i ewentualnie szczyptą cukru. Zagotować.

== Zdjęcia
|===
