= Leczo wegetariańskie

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* 4 porcje
* https://www.kwestiasmaku.com/zielony_srodek/papryka/leczo_wegetarianskie/przepis.html[link do źródła przepisu]

== Składniki
* 1 ząbek czosnku
* 1 cebula
* 1/3 papryczki chili
* 1 łyżka oliwy i 1 łyżka masła lub 2 łyżki oliwy
* 2 papryki
* 1 cukinia
* 150 g pieczarek
* 1 bakłażan
* 2 pomidory (lub 1 puszka)
* 250 g domowego przecieru pomidorowego lub gotowej passaty w butelce
* 1/2 łyżeczki papryki w proszku
* 1 łyżeczka suszonego oregano
* około 1/2 łyżeczki soli morskiej i świeżo zmielony pieprz


|
== Przygotowanie
Czosnek obrać i pokroić w drobną kosteczkę. Cebulę pokroić w kostkę.

Na dużą wysoką patelnię lub do dużego garnka wlać 1 łyżkę oliwy, włożyć czosnek i podgrzewać przez kilkanaście sekund, dodać cebulę oraz papryczkę chili w całości. Smażyć przez około 5 minut na umiarkowanym ogniu co chwilę mieszając aż cebula się zeszkli.

Dodać paprykę oczyszczoną z nasion i pokrojoną w kosteczkę. Zwiększyć ogień, dodać pokrojoną cukinię i smażyć przez 2 minuty.

Dodać łyżkę oliwy, pokrojone na plasterki pieczarki oraz pokrojonego w kosteczkę bakłażana. Smażyć przez około 10 - 12 minut, od czasu do czasu warzywa przemieszać, w międzyczasie doprawić solą i pieprzem.

Pomidory sparzyć, obrać ze skórki, wyciąć szypułki, usunąć pestki. Pokroić w kostkę i razem z sokiem wrzucić do warzyw (pomidory z puszki posiekać).

Dodać passatę pomidorową, czerwoną paprykę w proszku oraz suszone oregano i gotować przez około 5 minut, od czasu do czasu zamieszać.



== Zdjęcia
|===
