= Noodle z mielonym mięsem drobiowym

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* 2 porcje
* https://www.kwestiasmaku.com/przepis/noodle-z-mielonym-miesem-drobiowym[link do źródła przepisu]

== Składniki
* 2 łyżki oleju roślinnego
* 200 g mielonego mięsa drobiowego
* 2 ząbki czosnku
* 2 cm świeżego imbiru
* szczypta mielonego białego pieprzu
* 4 liście kapusty pak choi (można zastąpić pekińską)
* 1/2 czerwonej papryki
* 200 g makaronu świeżego Udon lub Ramen
* 2 łyżki posiekanego szczypiorku
* sezam lub orzeszki ziemne
|
== Przygotowanie
Rozgrzać wok z olejem, włożyć mięso oraz przeciśnięty przez praskę czosnek, obrany i drobno starty imbir, sól i pieprz. Smażać na dużym ogniu co chwilę mieszając, mniej więcej przez ok. 8 minut.

Dodać pokrojone liście pak choi i pokrojoną na kawałeczki paprykę. Smażyć mieszając przez ok. 2 - 3 minuty.

Przygotować sos mieszając wszystkie składniki: gorący bulion, pastę tahini, sos sojowy, sos chili.

Do woka z mięsem i warzywami dodać ugotowany makaron i wymieszać.

Wlać sos, wymieszać i podgrzać. Posypać szczypiorkiem i sezamem lub orzeszkami.
== Zdjęcia
|===
