= Noodle z krewetkami po koreańsku

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* https://www.kwestiasmaku.com/przepis/noodle-z-krewetkami-po-koreansku[link do źródła przepisu]

== Składniki
* 125 g makaronu chow mein
* 125 g oczyszczonych krewetek
* 2 ząbki czosnku
* 1/2 czerwonej papryki
* 2 łyżki sezamu
* 2 łyżki oleju
* 1 łyżka szczypiorku
|
== Przygotowanie
Makaron ugotować zgodnie z instrukcją na opakowaniu (ok. 4,5 minuty). Odcedzić i przelać chłodną wodą na durszlaku.

Krewetki rozmrozić jeśli były mrożone, oderwać ogonki, osuszyć. Doprawić solą, pieprzem oraz wymieszać z przeciśniętym przez praskę czosnkiem.

Paprykę pokroić w paseczki. Wymieszać składniki sosu w oddzielnym naczyniu. Sezam delikatnie podprażyć na suche patelni.

Rozgrzać wok lub szeroką dużą patelnię, wlać olej i gdy będzie gorący włożyć krewetki. Obsmażać po minicie z każdej strony, następnie zdjąć na talerz.

Włożyć paprykę i smażyć co chwilę mieszając łopatką przez ok. 2 minuty, następnie dodać krewetki i chwilę razem podsmażać.

Dodać makaron i wymieszać, podsmażać razem przez ok. 1 minutę.

Przesunąć składniki na bok patelni i zrobić miejsce na dnie. Wlać w nie sos i zagotować. Wymieszać ze składnikami i smażyć przez około 2 minuty, co chwilę mieszając łopatką. Na koniec wymieszać ze szczypiorkiem i posypać sezamem.
== Zdjęcia
|===
