= Papryka faszerowana

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* 4 porcje
* https://www.kwestiasmaku.com/przepis/papryka-faszerowana-mielonym-miesem-i-ryzem[link do źródła przepisu]

== Składniki
* 4 papryki
* 350 g mielonego mięsa
* 2 łyżki oliwy
* 1 cebula
* 2 ząbki czosnku
* 2 łyżki posiekanej natki
* 100 g (1 woreczek) ryżu
* 1 jajko
* 2 łyżki koncentratu pomidorowego
* 100 g żółtego sera
* 1 pomidor
* 1/2 łyżeczki tymianku
* po 1 łyżeczce słodkiej papryki i kurkumy
* 2 łyżeczki oregano


|
== Przygotowanie
Ryż ugotować do miękkości w osolonej wodzie, ok. 10 - 15 minut lub zgodnie z instrukcją na opakowaniu.

Na patelni na oliwie zeszklić pokrojoną cebulę, dodać starty czosnek, po chwili włożyć zmielone mięso i dokładnie obsmażyć. Jeśli mielimy sami mięso najlepiej zmielić je od razu z surową cebulą, natką i czosnkiem, całość wyłożyć na patelnię i dokładnie obsmażyć.

Mięso doprawić solą (ok. 2/3 łyżeczki), pieprzem, dodać przyprawy: tymianek, czerwoną paprykę i kurkumę oraz połowę suszonego oregano. Dodać koncentrat pomidorowy oraz natkę, smażyć przez ok. 2 minuty.

Dodać odcedzony ryż, wymieszać i podgrzewać przez ok. minutę. Odstawić z ognia. Po lekkim przestudzeniu dodać jajko i wymieszać.

Piekarnik nagrzać do 200 stopni C. Papryki przekroić na połówki (postawić pionowo na desce i przekroić pionowo). Usunąć nasiona. Wnętrze doprawić solą, pieprzem, skropić oliwą i ułożyć w naczyniu żaroodpornym.

Wypełnić farszem, na wierzchu położyć plasterek pomidora, doprawić solą i resztą suszonego oregano. Wstawić do piekarnika, do naczynia wlać ok. 1/2 szklanki wody i piec przez 35 minut.

Na każdej papryce położyć plasterek sera lub starty ser i zapiekać jeszcze przez ok. 5 - 10 minut, aż ser będzie roztopiony lub również zrumieniony.

== Zdjęcia
|===
