= Pierogi z kapustą i grzybami

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* ok. 80 sztuk
* https://www.kwestiasmaku.com/kuchnia_polska/pierogi/pierogi_z_kapusta/przepis.html[link do źródła przepisu]

== Składniki
* 1 słoik litrowy suszonych grzybów (ok. 100 g)
* 1 kg kiszonej kapusty
* 1 marchewka
* 1 pietruszka
* 3 łyżki oleju
* 3 cebule

|
== Przygotowanie
Grzyby opłukać, zalać zimną wodą i odstawić na 6 godzin lub na całą noc. Następnego dnia zagotować, dodać obraną marchewkę, pietruszkę i gotować aż będą miękkie. Pod koniec gotowania doprawić solą i pieprzem.

Kapustę odcisnąć i ugotować w 300 ml wody do miękkości z dodatkiem soli do smaku (ok. 45 minut), dokładnie odcisnąć.

Grzyby, marchewkę i pietruszkę odcedzić, zachowując wywar (wykorzystać do np. do zupy grzybowej). Bardzo dobrze odcisnąć z wody i razem z kapustą zmielić w maszynce do mięsa o bardzo dużych oczkach, ok 1 cm średnicy (lub drobno posiekać na desce).

Na patelni na oleju zeszklić cebule, dodać do farszu. Składniki farszu dobrze wyrobić, łącząc wszystko razem, doprawić solą i pieprzem.

== Zdjęcia
|===
