= Placek po węgiersku

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* 1 porcja
* https://www.kwestiasmaku.com/przepis/placek-po-wegiersku[link do źródła przepisu]

== Składniki
* gulasz węgierski
* 1/2 kg ziemniaków
* 1/2 łyżki mąki pszennej
* 1/4 cebuli
* 1 jajko
* sól
* 5 łyżek oleju roślinnego do smażenia
* do podania: śmietana i natka pietruszki
|
== Przygotowanie
Przygotować i podgrzać porcję gulaszu węgierskiego.

Ziemniaki obrać i zetrzeć na tarce o małych oczkach. Zostawić je na ok. 5 minut bez mieszania po czym w dłoniach dokładnie odcisnąć z soku. Do odciśniętych ziemniaków dodać mąkę, drobno startą cebulę, jajko oraz dwie szczypty soli, wymieszać.

Rozgrzać patelnię (śr. 20-22 cm), wlać 3 łyżki oleju. Wyłożyć całą masę ziemniaczaną na rozgrzany olej i rozprowadzić ją na równy placek. Smażyć na średnim ogniu przez ok. 4 minuty na złoty kolor, przewrócić na drugą stronę, dodać pozostałe 2 łyżki oleju i powtórzyć smażenie (ok. 3 minuty).

Przełożyć na talerz, nałożyć gorący gulasz i złożyć na pół. Po wierzchu polać gęstą śmietaną i posypać natką.
== Zdjęcia
|===
