= Quesadilla z chili con carne

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* https://www.kwestiasmaku.com/przepis/quesadilla-z-chili-con-carne[link do źródła przepisu]

== Składniki
* 500 g mielonej wołowiny
* 3 łyżki oleju roślinnego
* 1 cebula
* 2 ząbki czosnku
* przyprawy: po 1 łyżeczce papryki w proszku, kminu rzymskiego, oregano oraz 1/2 łyżeczki chili
* 250 ml bulionu wołowego
* 1/2 czerwonej papryki
* 1 mała puszka ok. 200 ml czerwonej fasoli
* 1 mała puszka ok. 200 ml kukurydzy
* 2 łyżki koncentratu pomidorowego
|
== Przygotowanie
Na dużej patelni na oleju zeszklić pokrojoną w kosteczkę cebulę oraz drobno posiekany czosnek.

Dodać przyprawy i mieszając smażyć przez kilkanaście sekund. Stopniowo dodawać mieloną wołowinę obsmażając mięso na dużym ogniu, jednocześnie mieszając drewnianą łyżką.

Gdy mięso będzie już dobrze obsmażone wlać bulion i zagotować. Przykryć i gotować przez ok. 20 minut (do miękkości).

Dodać pokrojoną w kosteczkę paprykę, odcedzoną fasolę oraz kukurydzę. Doprawić solą i pieprzem, dokładnie wymieszać i gotować już bez przykrycia co chwilę mieszając przez ok. 10 minut.

Dodać koncentrat pomidorowy i gotować jeszcze przez ok. 5 minut, aż sos będzie gęsty.

Na dużej patelni rozgrzać i rozprowadzić łyżeczkę masła. Położyć placek tortilli, posypać 3 łyżkami tartego sera, następnie wyłożyć ok. 5 łyżek sosu mięsnego i znów posypać serem. Przykryć drugim plackiem tortilli i podsmażać na małym ogniu ok. 2 minuty, aż tortilla na spodzie się zrumieni.

Placki przewrócić na drugą stronę* i ponownie podsmażyć na maśle do zrumienienia. Powtórzyć z resztą placków i nadzieniem.

Podgrzane quesadille kroić nożem na kawałki jak pizzę, podawać ze śmietaną i kolendrą.
== Zdjęcia
|===
