= Ramen shoyu

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* 6 porcji
* https://www.kwestiasmaku.com/przepis/ramen-shoyu-z-wieprzowina[link do źródła przepisu]

== Składniki
* 1 kg kości wieprzowych
* 1 kg kości drobiowych (np. korpus kurczaka, indyka)
* 4 cebulki szalotki
* 10 cm korzenia imbiru
* pół główki czosnku
* 2 marchewki
* wodorosty/algi konbu - płat o wymiarach ok. 7 x 20 cm
* ok. 80 - 100 ml japońskiego sosu sojowego (shoyu)
* 80 ml sake (wino ryżowe)
* wolno gotowana wieprzowina
* 30 g suszonych grzybów shitake
* 500 g świeżego makaronu ramen lub 220 g suszonego
* dymka lub szczypiorek
* 6 jajek
* przyprawa shichimi togarashi
* prasowane glony (sushi nori)
* kiełki fasoli
* 200 g bok choy (pak choy)
* sezamowy olej chili


|
== Przygotowanie
Do dużego garnka włożyć kości wieprzowe i drobiowe. Całkowicie zalać je zimną wodą. Doprowadzić do wrzenia na dużym ogniu, następnie odcedzić, przepłukać zimną wodą i ponownie włożyć je do pustego garnka.

Cebulki obrać z zewnętrznych łusek, umyć. Cebulki i czosnek rozgnieść dla uwolnienia soku, dodać do garnka z mięsem. Dodać pokrojony na plastry imbir oraz obraną i pokrojoną na kilka części marchewkę. Dodać zgrubnie opłukany glon konbu i zalać całość zimną wodą (około 2 litry, do przykrycia składników).

Zagotować na dużym ogniu, wyjąć konbu (nie będzie potrzebne), usunąć z wierzchu szumowinę jeśli się pojawi. Ustawić garnek na minimalnym palniku, zmniejszyć ogień do minimum. Gotować pod uchyloną pokrywą przez około 6 godzin.

Po przestudzeniu wyjąć kości i przecedzić bulion przez sito. Ostudzić i odstawić do lodówki.

== Zdjęcia
|===
