= Risotto primavera

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* 2 - 3 porcje
* https://www.kwestiasmaku.com/przepis/risotto-primavera[link do źródła przepisu]

== Składniki
* 150 g ryżu do risotto np. Arborio
* 60 ml białego wina (można pominąć)
* ok. 700 ml bulionu (może być np. z kostki eko)
* 250 g szparagów lub 150 g fasolki szparagowej
* 1 marchewka
* 1 mała cukinia
* 1 nieduża cebula
* 3 ząbki czosnku
* 1 pomidor
* 2 łyżki oliwy extra
* 2 łyżki masła lub masła roślinnego
* 1 łyżeczka suszonego oregano
* 1 łyżka posiekanego szczypiorku
* 2 łyżki posiekanej bazylii
* 3 łyżki tartego parmezanu lub grana padano lub wegańskiego*

|
== Przygotowanie
Jeśli używamy szparagów, należy je opłukać, odłamać (same złamią się we właściwym miejscu), wyrzucić twarde, zdrewniałe końce (są włókniste i nie nadają się do jedzenia). Pozostałą zieloną część szparagów pokroić ukośnie na kawałeczki, zachowując zielone główki w całości.

Jeśli używamy fasolki szparagowej, należy ją pokroić na kawałeczki.

Marchewkę obrać, następnie obieraczką do warzyw "obierać ją" robiąc paseczki - tasiemki. Tak samo postąpić z nieobraną cukinią (pomijając środek z pestkami ze środka).

Cebulę pokroić w drobną kosteczkę, czosnek przecisnąć przez praskę, pomidora sparzyć, obrać ze skórki a miąższ pokroić w kosteczkę.

W wysokim garnku roztopić łyżkę masła, dodać połowę cebuli i zeszklić ją mieszając od czasu do czasu nie rumieniąc.

Dodać ryż i smażyć na małym ogniu przez około 1 minutę ciągle mieszając aż cały ryż się podgrzeje. Wlać wino i całkowicie odparować.

Następnie stopniowo (po około 1/2 szklanki) dodawać gorący bulion, mieszając ryż. Dodawać kolejną porcję bulionu dopiero wówczas gdy poprzednia zostanie wchłonięta przez ryż. Gotować w ten sposób risotto przez ok. 17 minut. Na ostatnie 7 minut dodać fasolkę.

W czasie gdy gotuje się ryż, na oddzielnej patelni podsmażyć warzywa: na dużej pateli na 2 łyżkach oliwy zeszklić pokrojoną w kosteczkę cebulę. Następnie dodać marchewkę i dalej smażyć co chwilę mieszając przez ok. 2 minuty. Dodać szparagi i smażyć przez kolejne 2 minuty. Pod koniec dodać czosnek.

Dodać pomidora, doprawić całość solą, pieprzem oraz oregano. Gotować przez około 3 minuty co chwilę mieszając.

Dodać cukinię i gotować przez ok. 2 minuty aż zmięknie.

Gotowe warzywa przełożyć do garnka z ugotowanym, gorącym ryżem. Odstawić z ognia, dodać pozostałą łyżkę masła, 2 łyżki tartego sera, posiekany szczypiorek i bazylię. Całość wymieszać.

Sprawdzić doprawienie solą i pieprzem. Podawać z dodatkowym serem i oliwą wedle uznania.

== Zdjęcia
|===
