= Ryba z porami, ziemniaczki, i

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* https://www.kwestiasmaku.com/przepis/ryba-z-porami[link do źródła przepisu]

== Składniki
* 600 g filetów ryby (np. mintaj, dorsz, halibut)
* 1 por
* 1/3 łyżeczki nasion kopru włoskiego
* 1 łyżka oliwy
* 2 łyżki masła
* 1 łyżka posiekanego koperku
* 5 łyżek śmietanki 30%
|
== Przygotowanie
Rybę pokroić na porcje i umieścić w naczyniu żaroodpornym. Doprawić solą, pieprzem, posypać nasionami kopru włoskiego i wysmarować oliwą.

Piekarnik nagrzać do 200 stopni C.

Odciąć zielone końce pora, resztę przekroić wzdłuż na pół i dokładnie opłukać. Cienko posiekać na desce.

Włożyć na patelnię, doprawić solą i pieprzem i co chwilę mieszając dusić przez ok. 8 minut. Pod koniec dodać masło.

Wlać pół szklanki wody lub bulionu, zagotować i przykryć. Dusić przez ok. 5 minut do miękkości.

Zdjąć pokrywę, dodać śmietankę oraz koperek, wymieszać i zagotować. Wyłożyć na rybę i wstawić do piekarnika. Piec przez 20 minut (bez przykrycia).
== Zdjęcia
|===
