= Ryż z warzywami chińskimi i kurczakiem

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* 2 porcje
* https://www.kwestiasmaku.com/przepis/smazony-ryz-po-chinsku-z-kurczakiem-i-warzywami[link do źródła przepisu]

== Składniki
* 100 g ryżu (np. jaśminowego, długoziarnistego)
* 3 łyżki oleju roślinnego
* 250 g filetu kurczaka
* 1 łyżeczka mąki ziemniaczanej (skrobi)
* 3 łyżki sosu sojowego
* 1 mała cebula
* 2 ząbki czosnku
* 2 jajka
* 1/2 marchewki
* 1/4 główki kapusty pekińskiej
* 1/2 papryki
* sól, pieprz, 1 łyżeczka cukru
* 1 łyżka octu ryżowego lub 2 łyżki soku z cytryny lub limonki
* 4 łyżki posiekanego szczypiorku
|
== Przygotowanie
Z wyprzedzeniem ugotować ryż, odcedzić, wysypać na duży talerz i rozłożyć po całej powierzchni, całkowicie go ostudzić i osuszyć, od czasu do czasu przemieszać.

Filet z kurczaka pokroić w kostkę, doprawić solą i pieprzem, następnie dodać 2 łyżeczki sosu sojowego oraz 2 łyżeczki oleju roślinnego a także mąkę ziemniaczaną i wszystko wymieszać.

W woku lub dużej patelni z nieprzywierającą (śliską) powłoką podgrzać olej, dodać pokrojoną w kosteczkę lub piórka cebulę. Zeszklić ją co chwilę mieszając, pod koniec dodając czosnek. Odłożyć na talerz.

Do woka lub na patelnię wlać drugą łyżkę oleju, gdy będzie gorący wlać roztrzepane jajka i smażyć omlet przez ok. pół minuty aż od spodu się zetnie i zacznie lekko rumienić. Wówczas przewrócić na drugą stronę i łopatką podzielić go na mniejsze kawałeczki. Doprawić solą i po ponownym obsmażeniu wyłożyć na talerz z cebulą.

Na patelnię wlać trzecią łyżkę oleju i włożyć kurczaka. Dokładnie obsmażyć z każdej strony.

Zsunąć mięso na bok, w wolne miejsce włożyć obraną i pokrojoną w małą kosteczkę marchewkę (można ją też zetrzeć na tarce). Smażyć mieszając co chwilę przez ok. 3 minuty.

Dodać pokrojoną paprykę i znów co chwilę mieszając smażyć przez ok. 3 minuty. Dodać posiekaną kapustę pekińską, ryż oraz odłożoną cebulę. Smażyć co chwilę mieszając przez ok. 4 minuty. Pod koniec dodać usmażone jajka.

W miseczce wymieszać 2 łyżki sosu sojowego z cukrem oraz octem lub sokiem z cytryny/limonki. Wlać na patelnię, wymieszać i smażyć jeszcze przez ok. 1 minutę. Wymieszać z połową posiekanego szczypiorku, nałożyć porcje i posypać resztą szczypiorku.
== Zdjęcia
|===
