= Sajgonki

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* ok. 25 - 30 sztuk
* https://www.kwestiasmaku.com/kuchnia_orientu/sajgonki_przepis/przepis.html[link do źródła przepisu]

== Składniki
* 1/2 cebuli
* 1 średnia marchewka starta na tarce o małych oczkach
* 1/2 - 1 łyżeczki startego imbiru
* 1 ząbek czosnku
* 200 g drobno zmielonego mięsa (pół na pół mielonej wołowiny np. udźca i wieprzowej łopatki)
* 50 g drobno zmielonej piersi kurczaka (opcjonalnie)
* 3 łyżki sosu sojowego
* 2 łyżki sosu rybnego
* po 1/2 łyżki posiekanej natki pietruszki, mięty, szczypiorku
* 150 g ugotowanego makaronu sojowego lub ryżowego (zważone po ugotowaniu)
* kilka dużych liści szpinaku (opcjonalnie)
* 6 - 8 suszonych grzybów mun
* 1 - 2 jajka (w zależności od wielkości)

|
== Przygotowanie
Na patelni rozgrzać łyżkę oleju, zeszklić drobniutko posiekaną cebulę, dodać marchewkę, imbir i starty czosnek, smażyć przez minutę. Dodać mięso i mieszając smażyć przez około 2 minuty aż całe będzie obsmażone (zmieni kolor na szary).

Wlać sos sojowy i sos rybny, mieszając smażyć przez pół minuty. Odstawić z ognia i przełożyć do dużej miski, dodać natkę, miętę, szczypiorek.

Dodać drobniutko posiekany wcześniej ugotowany i osuszony makaron ryżowy, drobniutko posiekany szpinak i wcześniej ugotowane i posiekane (około 5  minut w gorącej wodzie) grzyby mun. Do ostudzonej masy dodać jajko (jajka) i wymieszać.

Naleśniki wkładać na kilkanaście sekund do ciepłej wody, układać na desce, nakładać po łyżce nadzienia, zawinąć naleśnik na nadzienie, docisnąć nadzienie, złożyć boki naleśnika do środka, następnie zwinąć dość ciasno nadzienie z naleśnikiem w rulonik (zwijanie jak przy krokietach).

Smażyć partiami, w woku lub na patelni, na około 3 mm warstwie oleju (sajgonki mają mieć złoty kolor i być zrumienione nieco bardziej niż na zdjęciach).

== Zdjęcia
|===
