= Sałatka gyros

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* 4 porcje
* https://www.kwestiasmaku.com/przepis/salatka-gyros[link do źródła przepisu]

== Składniki
* 3 pojedyncze filety kurczaka
* 2 łyżki stołowe przyprawy gyros/kebab
* 1 średnia czerwona cebula
* 1 duży por
* 1 średni słoik ogórków konserwowych (np. korniszonów)
* 1 puszka kukurydzy
* 1 czerwona papryka
* 1/2 kapusty pekińskiej lub 1/3 lodowej
* 4 łyżki ketchupu pikantnego
* 2 łyżki oleju roślinnego
* 2/3 szklanki majonezu
* 1/3 szklanki gęstej śmietany lub jogurtu greckiego (opcjonalnie)
|
== Przygotowanie
Filety opłukać, osuszyć, oczyścić z błonek i kostek. Pokroić na małe paseczki lub w kostkę. Wymieszać z przyprawą gyros/kebab i odłożyć na ok. 1/2 godziny lub dłużej jeśli mamy czas.

W międzyczasie przygotować warzywa. Czerwoną cebulę obrać, przekroić na 4 części, następnie na plasterki, oprószyć solą.

Odciąć korzonki pora, zielone liście oraz zewnętrzną 1 - 2 warstwy. Przekroić wzdłuż na 4 części i opłukać. Posiekać na desce, włożyć na sitko i przelać wrzątkiem z czajnika, odsączyć.

Ogórki konserwowe pokroić w kosteczkę, kukurydzę odcedzić na sitku z zalewy, paprykę pokroić w kosteczkę, kapustę pekińską opłukać, osuszyć i drobno poszatkować.

Na większej patelni podgrzać olej, włożyć kurczaka i obsmażać na złoty kolor z każdej strony (w sumie ok. 10 minut). W trakcie smażenia doprawić mięso solą oraz pieprzem. Przełożyć na dno salaterki o średnicy 20 cm.

Polać ketchupem, przykryć plasterkami czerwonej cebuli, następnie układać kolejne warstwy składników: ogórki, kukurydzę, pora, paprykę, majonez wymieszany ze śmietaną lub jogurtem, a na koniec przykryć posiekaną kapustą pekińską.
== Zdjęcia
|===
