= Sałatka z krewetkami

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* 2 porcje
* https://www.kwestiasmaku.com/przepis/salatka-z-krewetkami-smazonymi-z-czosnkiem-i-papryczka-chili[link do źródła przepisu]

== Składniki
* 200 g oczyszczonych krewetek
* 1/2 opakowania miksu sałat
* 1/2 opakowania rukoli
* 250 g pomidorków koktajlowych
* 2 ząbki czosnku
* 1 papryczka chili
* 3 łyżki masła
* 1 łyżka oliwy extra vergine
* 2 łyżki białego wina (opcjonalnie)
* 3 łyżki soku z cytryny

|
== Przygotowanie
Mrożone krewetki rozmrozić (w temp. pokojowej lub pod strumieniem bieżącej, chłodnej wody). Opłukać i oderwać ogonki, osuszyć.

Jeden ząbek czosnku zetrzeć lub przecisnąć przez praskę, drugi pokroić na cienkie plasterki. Papryczkę chili pokroić ukośnie na cienkie plasterki.

Na talerze wyłożyć sałatę, posypać rukolą, na wierzch wyłożyć pokrojone na połówki lub ćwiartki pomidorki koktajlowe.

Na patelni roztopić masło z oliwą i gdy zacznie skwierczeć dodać plasterki czosnku, krewetki i papryczkę chili. Smażyć na nieco większym ogniu po około jednej minucie z każdej strony, w międzyczasie doprawić solą.

Następnie dodać starty czosnek, wymieszać i smażyć przez pół minuty co chwilę mieszając. Wlać wino, sok z cytryny, wymieszać i odstawić z ognia. Wyłożyć na sałatę. Można skropić dodatkową oliwą.

== Zdjęcia
|===
