= Sałatka z sałatą lodową, suszonymi pomidorami i fetą

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* 2 porcje
* https://www.kwestiasmaku.com/dania_dla_dwojga/party/salatka_z_feta/przepis.html[link do źródła przepisu]

== Składniki
* 1/4 lub 1/3 główki sałaty lodowej
* garstka roszponki
* 5 kawałków suszonych pomidorów w zalewie
* 4 łyżki pestek dyni
* 100 g sera feta
* 1 zielona papryczka chili
* 3 dymki (białe części) lub 2 młode cebulki
* 5 łyżek oleju ze słoika z suszonymi pomidorami
* 1,5 łyżki soku z limonki
* 1 łyżka syropu z agawy lub klonowego lub płynnego miodu
* sól i pieprz


|
== Przygotowanie
Sałatę opłukać i osuszyć, pokroić w kostkę, włożyć do salaterek razem z opłukaną roszponką. Doprawić solą i pieprzem.

Pomidory suszone wyjąć z zalewy i pokroić na cienkie paseczki, fetę pokroić w kosteczkę, chili oraz białe i jasnozielone części dymki na cienkie plasterki, wszystko dodać do sałatki.

Posypać pestkami dyni i polać winegretem: olej z suszonych pomidorów (można zebrać z dna słoika suszone zioła) wymieszać w miseczce z sokiem z limonki, syropem lub miodem i doprawić solą oraz pieprzem. Polać po sałatce.

== Zdjęcia
|===
