= Sałatka warstwowa z szynką, jajkiem i serem żółtym bez selera

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* https://www.kwestiasmaku.com/przepis/salatka-warstwowa-z-szynka-jajkiem-i-serem-zoltym[link do źródła przepisu]

== Składniki
* 5 jajek
* 1 puszka kukurydzy
* 1 puszka krojonego ananasa
* opcjonalnie: 1 słoik selera sałatkowego (siekany, konserwowy)
* 150 g sera żółtego
* 150 g szynki konserwowej
* 2/3 szklanki majonezu + 1/3 szklanki gęstej śmietany lub jogurtu greckiego
* na wierzch: kapusta pekińska + kawałek czerwonej papryki
|
== Przygotowanie
Jajka ugotować na twardo, obrać i posiekać na desce. Na sitku odcedzić kolejno kukurydzę, potem ananasa i selera jeśli go używamy.

Na dnie salaterki o średnicy ok. 20 cm ułożyć selera, potem kukurydzę, startą na tarce o dużych oczkach lub pokrojoną w kosteczkę lub paseczki szynkę.

Wyłożyć majonez wymieszany ze śmietaną lub jogurtem, kawałki ananasa, starty na tarce ser żółty oraz jajka. Doprawić solą i pieprzem.

Uzupełnić posiekaną kapustą pekińską oraz udekorować papryką pokrojoną w kosteczkę.
== Zdjęcia
|===
