= Spaghetti bolognese

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* ok. 8 porcji
* https://www.kwestiasmaku.com/przepis/spaghetti-bolognese[link do źródła przepisu]

== Składniki
* 150 g boczku*
* 1 cebula
* 2 łodygi selera naciowego
* 1 marchewka
* 2 łyżki oliwy
* 500 g mielonego mięsa**
* 1 szklanka czerwonego wina
* 1 szklanka gorącego bulionu
* 4 łyżki koncentratu pomidorowego
* 1 puszka obranych pomidorów
* 1/2 szklanki mleka
* makaron spaghetti (75 g / porcję)
* tarty parmezan


|
== Przygotowanie
Boczek pokroić w drobną kostkę i włożyć na dużą patelnię, wytopić na małym ogniu aż się zrumieni. Przesunąć na bok, w wytopiony tłuszcz włożyć drobno posiekaną cebulę i zeszklić. Dodać drobno posiekany seler naciowy i startą marchewkę. Obsmażyć, następnie wszystko przełożyć do garnka.

Na patelnię wlać oliwę i obsmażyć mięso. Obsmażone mięso przełożyć do garnka z boczkiem i warzywami. Wlać wino i gotować mieszając ok. 5 minut. Dodać gorący bulion i koncentrat pomidorowy, wymieszać. Dodać pomidory z puszki, doprawić solą i pieprzem. Drewnianą łyżką rozdrobnić pomidory i wymieszać.

Przykryć i gotować na małym ogniu przez minimum 2 godziny, od czasu do czasu mieszając. W połowie gotowania dodać mleko. Podawać z ugotowanym makaronem spaghetti posypując tartym parmezanem.

== Zdjęcia
|===
