= Stek z sosem béarnaise i szparagami

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* https://www.kwestiasmaku.com/kuchnia_angielska/steki/stek_z_sosem_bearnaise/przepis.html[link do źródła przepisu]

== Składniki
* 500 g polędwicy wołowej
* sól, świeżo mielony pieprz
* 8 zielonych szparagów
|
== Przygotowanie
Sos béarnaise: wino, ocet, pokrojoną w drobną kostkę szalotkę, ziarna pieprzu, łodygi estragonu (bez liści, liście zachować) i suszony estragon włożyć do garnka i podgrzewać ok. 8 minut aż płyn zredukuje się do około 4 łyżek wywaru. Wywar odcedzić na sitku. Masło roztopić i podgrzać (ma być gorące), usunąć powstałą pianę z powierzchni. Ogrzane w temp. pokojowej żółtka ubić na pianę z dodatkiem soku z cytryny i soli. Wciąż ubijając, stopniowo dodawać gorące masło i na koniec odcedzony wywar. Wymieszać z listkami świeżego estragonu.

Steki: mięso wcześniej pokroić, ocieplić, pokroić na 3 cm plastry. Piekarnik rozgrzać do maksymalnej temperatury i włączyć funkcję grilla*. Steki wyłożyć na kratkę i umieścić na górnej półce piekarnika (pod samym grillem, uwaga - poniżej warto włożyć blachę, na którą będzie ściekać tłuszcz). Piec po ok. 4 minuty z każdej strony. Po wyjęciu z pieca steki luźno przykryć folią aluminiową na około 5 minut.

Szparagi opłukać w zlewie pod bieżącą wodą, odłamać grube jasne końce łodyg (nie będą potrzebne). Ładne zielone łodygi ugotować w koszyczku na parze (jeśli nie mamy koszyczka lub naczynia do gotowania na parze możemy użyć sitka - włożyć szparagi do sitka główkami do góry, zawiesić sitko na brzegu garnka z wodą (wystarczy wypełnić go wodą do 1/3), przykryć pokrywką i gotować przez około 5 minut licząc od czasu zagotowania wody.
== Zdjęcia
|===
