= Szare kluski ze skwarkami

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* https://aniagotuje.pl/przepis/szare-kluski[link do źródła przepisu]

== Składniki
* 1 kg ziemniaków - waga przed obraniem
* 1 szklanka mąki pszennej uniwersalnej lub mąki żytniej typ. 720 - około 160 g
* 1-2 łyżki skrobi ziemniaczanej
* 1 średnie lub większe jajko
* pół płaskiej łyżeczki soli
* 300 g boczku surowego wędzonego
* 2 średnie cebule - do 300 g
* 5 łyżek oleju do smażenia


|
== Przygotowanie
Zapraszam po przepis na super pyszne i wyjątkowo proste do zrobienia szare kluski. Można je podać na kilka sprawdzonych sposobów i w każdej wersji smakują rewelacyjnie.

- tylko kilka tanich składników

- bez potrzeby formowania klusek

- do podania z wersji z mięsem lub z serem

Czas przygotowania: 30 minut

Czas gotowania 1 partii: 7 minut

Liczba porcji: 1 kg szarych klusek





Kaloryczność kcal: 140 w 100 g



Składniki na szare kluski

Propozycja podania

Szklanka ma u mnie pojemność 250 ml.

Z podanej ilości składników powinno wyjść około jednego kilograma szarych klusek.

Potrzebujesz również: tarka do ziemniaków lub maszynka do mielenia ze specjalną nakładką do ścierania na bardzo drobno; szeroki, spory garnek; cedzak do łowienia kluseczek.

Kalorie policzone zostały na podstawie użytych przeze mnie składników. Jest to więc orientacyjna liczba kalorii, ponieważ Twoje składniki mogą mieć inną liczbę kalorii niż te, których użyłam ja. Kalorie policzone zostały wyłącznie do szarych klusek, czyli bez okrasy. Zanim zaczniesz szykować kluski szare, polecam najpierw przeczytać cały przepis, by przygotować się odpowiednio wcześniej do kolejnych etapów wykonania.

Szare kluski polecam szykować z ziemniaków z kategorii C, czyli z ziemniaków sypkich, mączystych. Takie ziemniaki zawierają dużo skrobi a mniej wody. Do tej kategorii ziemniaków należą odmiany: augusta, agnes, omega, jurata, bryza, finezja, gracja, hinga.. i wiele innych. Ziemniaki ogólnoużytkowe, czyli z kategorii B oraz C/B też nadają się do zrobienia tych klusek.

Jeden kilogram sypkich ziemniaków obierz cienko i zetrzyj na tarce, na bardzo drobnych oczkach. (Po obraniu otrzymałam 880 gramów ziemniaków gotowych do tarcia). Do starcia ziemniaków używam wyłącznie tarki o bardzo drobnych oczkach, co widać też na zdjęciu poniżej. Ziemniaki można też zetrzeć przy użyciu malaksera/maszynki do mielenia z odpowiednią nakładką.

Szare kluseczki, czy też kluski szare, to pyszne i wyjątkowo proste do zrobienia kluski. Ziemniaki są w naszym kraju jednym z najpopularniejszych warzyw, więc szykujemy z nich całe mnóstwo pysznych posiłków. Są głównymi składnikami wielu dań. Stanowią świetny dodatek do zup i sosów. Pieczone ziemniaczki uwielbia chyba każdy. Można je szykować przez cały rok i zawsze super smakują. Babka ziemniaczana to danie, które uwielbiam i pamiętam jeszcze jak wspaniale przyrządzała je moja Babcia. Wracając jednak do tematu, szare kluski ziemniaczane są warte spróbowania. Szare kluchy szykujemy bowiem głównie z surowych, tartych na bardzo drobnych oczkach ziemniaków. Szare kluski najlepiej jest robić z ziemniaków sypkich, czyli tych bardziej mączystych. Nie znaczy to jednak, że z innych nie wyjdą. Wyjdą również smaczne, tylko odejdzie więcej wody i otrzymasz mniej klusek na obiad. Szare kluski to ziemniaki tarte, symboliczne jajko surowe oraz trochę soli. Pieprzu do masy nie daję, ale można to zrobić. Do tego jeszcze dosypujemy sporo mąki pszennej lub też mąki żytniej. Ja bardzo często łączę ze sobą obie te mąki w proporcji pół na pół. Na jeden kilogram ziemniaków daję zazwyczaj jedną szklankę mąki. Mój przepis na szare kluski jest więc bardzo prosty i można go śmiało zapamiętać na stałe. Warto wiedzieć, że szare kluski szykowane z tych mniej mączystych ziemniaków można śmiało wspomóc przez dodanie dodatkowej porcji mąki/skrobi ziemniaczanej. Zazwyczaj wystarczy jedna lub dwie dodatkowe łyżki. To jak dokładnie szykuje się szare kluski, opisałam już w przepisie na kluski szare. Jest bowiem kilka dość istotnych informacji oraz sposobów na to, by kluski nie rozpadały się w trakcie gotowania. Zapomniałam dodać jeszcze, że szare kluski należą do tych wygodniejszych i prostszych przepisów również dlatego, że nie trzeba formować kształtu klusek. Gęste ciasto nakłada się na łyżkę i od razu porcja ląduje w garnku z wrzątkiem. Otrzymujemy wówczas niekształtne szare kluseczki. W bardzo podobnym stylu szykuję też moje ulubione kluski kładzione, które polecam bardzo gorąco.

Na szare kluski przepisy są do siebie raczej podobne. Jedni dają więcej mąki, inni zaś mniej. Czasem w masie ziemniaczanej pojawiają się dodatkowe przyprawy. Na szare kluski przepis nie jest jeden, ale nie ma między nimi dużych różnic. Szare kluski w całej Polsce szykujmy raczej bardzo podobnie. Szare kluski poznańskie bardzo często oprócz okrasy z cebuli i boczku wzbogacone są jeszcze o podsmażoną dodatkowo kiełbasę. Niektórzy znają też przepis na szare kluski śląskie, które tak samo jak szare kluski tradycyjne, szykuje się ze startych, surowych ziemniaków. Jednak w przypadku szarych klusek śląskich, bardziej odciskana jest woda i daje się więcej skrobi i czasem też mąki pszennej. Oczywiście szare kluski śląskie mają też kształt wszystkim znanych klusek śląskich. Jeśli masz ochotę poznać przepis na kluski śląskie białe, to zapraszam do szykowania ich razem ze mną. Szare kluski bardzo przypominają tez pyzy, które robimy okrągłe. Do pyz daje się już dość dużo dodatkowej porcji skrobi, by zachowały swój kształt. Warto jeszcze napisać o tym, z czym można podawać szare kluski. Kluski szare możesz oczywiście podać całkowicie dowolnie, i tak jak Ci będą tylko smakowały. Najczęściej jednak szare kluski podajemy z okrasą z podsmażonego boczku z cebulką. Jeśli będą podane wyłącznie z taką okrasą, to robimy jej więcej. Jeśli jednak taka okrasa to nie wszystko, to szykujemy tylko symboliczną jej ilość. Można też pominąć mięso i podać szare kluski tylko z cebulką podsmażoną na oleju. Do tego pasuje jeszcze pokruszony twaróg lub ser ricotta. Takie szare kluski z serem są rewelacyjne i lubię je tak samo jak makaron z serem. Szare kluski świetnie smakują też w towarzystwie kapusty zasmażanej lub też bigosu. Wszelkie kapustne dodatki będą rewelacyjne. A mój bigos pasuje do szarych klusek, jak żaden inny. Zapraszam zatem na przepis na szare kluski i życzę smacznego.



== Zdjęcia
|===
