= Wieprzowina po chińsku z mango

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* https://www.kwestiasmaku.com/przepis/wieprzowina-po-chinsku-z-mango[link do źródła przepisu]

== Składniki
* 1 mała polędwiczka wieprzowa
* 1 łyżka mąki ziemniaczanej
* 1 mango
* 1 czerwona papryka
* 1 czerwona cebula
* 2 ząbki czosnku
* 1 mała papryczka chili
* 3 cm kawałek imbiru
* 2 łyżki oleju roślinnego
|
== Przygotowanie
Odciąć białą błonę na zewnętrznej stronie polędwiczki. Mięso przekroić wzdłuż na pół, następnie w poprzek włókien na jak najcieńsze plasterki. Doprawić solą i pieprzem, obtoczyć w mące ziemniaczanej.

Nastawić ryż na gotowanie. Mango obrać i pokroić w słupki. Paprykę pokroić w paski, cebulę obrać i pokroić w piórka.

Papryczkę chili przekroić wzdłuż, usunąć pestki, następnie drobno posiekać. Czosnek i imbir obrać i zetrzeć na drobnej tarce.

Przygotować sos: wymieszać wszystkie składniki w miseczce.

W woku lub w wysokiej, dużej patelni rozgrzać 1 łyżkę oleju, włożyć przygotowane warzywa (paprykę, cebulę, papryczkę chili, czosnek i imbir) i mieszając smażyć na większym ogniu przez około 3 minuty. Dodać mango i wymieszać. Smażyć razem przez ok. 2 minuty, następnie wszystko wyjąć na talerz.

Dodać drugą łyżkę oleju do woka i włożyć polędwiczkę, zwiększyć ogień do dużego i smażyć przez około 3 minuty co chwilę mieszając aby równomiernie się obsmażała.

Włożyć z powrotem warzywa z mango i wszystko wymieszać, następnie wlać sos. Gotować na dużym ogniu przez około 2 minuty aż sos zgęstnieje, w międzyczasie co chwilę zamieszać.

Wyłożyć danie na talerze, obok położyć ryż, posypać szczypiorkiem i podawać.
== Zdjęcia
|===
