= Zapiekanka ziemniaczana

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* https://aniagotuje.pl/przepis/zapiekanka-ziemniaczana-z-kielbasa[link do źródła przepisu]

== Składniki
* 1 kg ziemniaków - waga przed obraniem
* opakowanie kiełbasy morlińskiej z szynki - 540 g [zobacz]
* 2 średnie cebule - około 400 g
* 150 g sera żółtego - w kostce lub w plasterkach
* około 1/3 szklanki śmietanki 30 % - 90 g
* 2 średnie jajka
* 3 łyżki oleju do smażenia
* przyprawy: po płaskiej łyżeczce soli i słodkiej papryki; pół płaskiej łyżeczki pieprzu; szczypta gałki muszkatołowej
* dodatki: garść pomidorków koktajlowych oraz natka pietruszki lub szczypiorek


|
== Przygotowanie
Zapiekanka ziemniaczana z kiełbasą to jeden z ciekawszych pomysłów na pyszny i szybki obiad. Przepis jest super prosty a zapiekanka smaczna, piękna i łatwa w przygotowaniu.

- tylko niezbędne składniki

- świetny obiad dla całej rodziny

- dokładny opis wykonania ze zdjęciami

Czas przygotowania: 1 godzina

Czas pieczenia zapiekanki: 40 minut

Liczba porcji: do 1900 g zapiekanki





Kaloryczność kcal: 170 w 100 g dania

Dieta: bezglutenowa

Składniki

Szklanka ma u mnie pojemność 250 ml.

Warzywa ważone były przed ewentualnym obraniem/przygotowaniem.

Do zrobienia zapiekanki użyłam naczynia żaroodpornego o średnicy 28 cm. Możesz też użyć innego naczynia żaroodpornego o pojemności około dwóch litrów.

Kalorie policzone zostały na podstawie użytych przeze mnie składników. Jest to więc orientacyjna liczba kalorii, ponieważ Twoje składniki mogą mieć inną liczbę kalorii niż te, których użyłam ja. Z podanej ilości składników otrzymasz do 1900 gramów pysznej zapiekanki ziemniaczanej z kiełbasą. Zanim zaczniesz szykować zapiekankę, polecam najpierw przeczytać cały przepis, by przygotować się odpowiednio wcześniej do kolejnych etapów wykonania.

Potrzebujesz jeden kilogram ładnych ziemniaków typ A lub typ B. Ponieważ w Polsce jest około sto odmian ziemniaków, nie będę więc pisała o tym jaką konkretnie wybrać. Najlepsze będą ziemniaki przeznaczone do gotowania i do pieczenia. Latem świetne są młode, ale już duże ziemniaki, które wystarczy wyszorować przed pokrojeniem i ugotowaniem. Zimą ziemniaki należy obrać i pokroić w plasterki nie grubsze niż 1 cm.

Przepłukane plasterki ziemniaków zalej w garnku zimną wodą. Wsyp płaską łyżkę soli. Garnek przykryj przykrywką i ustaw wysoką moc palnika. Gdy ziemniaki zaczną się gotować zmniejsz moc palnika i gotuj je około 5-8 minut licząc od zagotowania wody. Plasterki ziemniaków powinny być na wpół ugotowane. Odlej wodę a plasterki ziemniaków odstaw do lekkiego przestudzenia.

Na zdjęciu poniżej ziemniaki przed podgotowaniem.

Kiełbasę pokrój w plasterki o grubości o około 5 mm i umieść je na patelni po cebuli. Plasterki kiełbasy podsmażaj na lekko rumiano z obu stron. Zajęło mi to około 20 minut. Do podsmażania kiełbasy nie używałam już dodatkowego tłuszczu na patelnię.

Polecam sprawdź też mój przepis na ziemniaczki gratin. Czyli cienkie plasterki ziemniaków zapiekane w śmietance i przyprawach

Smacznego.Wpis zawiera lokowanie produktu.

Bardzo często szykuję najróżniejsze zapiekanki. Zazwyczaj sezon na nie zaczyna się po wakacjach, kiedy temperatury spadają i chętniej włączam piekarnik. Taka zapiekanka z ziemniaków i kiełbasy to świetny pomysł na pyszny obiad dla całej rodziny. Według mnie jest to jeden z najprostszych przepisów na ziemniaczaną zapiekankę. Zapiekanka ziemniaczana z boczkiem też jest pyszna, ale ta z kiełbasą ostatnio najbardziej nam smakuje. Ta wersja to zapiekanka ziemniaczana z kiełbasą i cebulą. Starałam się nie dodawać do niej niepotrzebnych składników. Czasem wystarczy mniej, by otrzymać ciekawszy i bardziej wyrazisty smak zapiekanki. Już same ziemniaczki z kiełbasą smakują rewelacyjnie. Moja zapiekanka ziemniaczana z kiełbasą i cebulką to propozycja na bardzo prosty i sycący obiad. Czasem zdarza mi się przygotować całą zapiekankę rano i odstawić ją na parę godzin, by w odpowiednim momencie wstawić ją do piekarnika i zapiekać na obiad. Bardzo dobry i z dodatkiem kiełbasy jest też mój chłopski garnek z ziemniakami. Rewelacyjne danie jednogarnkowe z dodatkiem kiełbasy to np. mój ulubiony forszmak o lekko kwaśnej nucie uzyskanej dzięki ogórkom kiszonym. Bardzo dobre i szybkie do zrobienia są też pyszne kuleczki ziemniaczane.

Obowiązkowo zapiekanka z kiełbasy i ziemniaków oraz serem, który doskonale się komponuje. Tym razem zdecydowałam się na bardzo oczywiste i popularne produkty i użyłam najzwyklejszego sera żółtego. Zapiekanka ziemniaczana z kielbasa będzie pyszna z każdym dobrej jakości żółtym serem. Możesz zatem wybrać swój ulubiony. Zapiekanka z ziemniakow i kielbasy może być szykowana z dodatkiem sera w plasterkach lub też sera w kostce, który trzeba zetrzeć na zapiekankę. Masz całkowitą dowolność. Zapiekanka z ziemniakami i kiełbasa jest pyszna i zawsze tak pięknie pachnie, że wszyscy schodzą się do kuchni pod koniec pieczenia. Zapiekanka z ziemniakami i kiełbasą przepis, który każdy polubi. Bardzo często pod koniec pieczenia wykładam też na wierch odrobinę sera mozzarella, by lekko tylko się podpiekł i rozpłyną po zapiekance. W przepisie sięgam po śmietankę kremówkę 30 %, ale można też śmiało użyć zwykłego mleka lub połączyć mleko z kremówką. Zapiekanka ziemniaczana z kiełbasą może za każdym razem smakować trochę inaczej jeśli sięgniesz po różne rodzaje kiełbasy. W tym przepisie użyłam kiełbasy z szynki, ale możesz też śmiało sięgnąć np. po kiełbasę śląską lub też nawet z piersi kurczaka. Zapraszam przepis na zapiekankę ziemniaczaną z kiełbasą i życzę smacznego. A przy okazji polecam też mój ulubiony przepis na pyszny boeuf strogonow, który podaję na wiele sposobów.



== Zdjęcia
|===
