= Zupa ogórkowa

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* 4 porcje
* https://www.kwestiasmaku.com/przepis/zupa-ogorkowa[link do źródła przepisu]

== Składniki
* 1 łyżka masła
* 1 łyżka oliwy
* 1 mała cebula
* 1 marchewka
* 1,5 litra bulionu (np. drobiowy, warzywny, rosół)
* 300 g ziemniaków (3 sztuki)
* 4 średnie kiszone ogórki
* 150 g śmietany 18%
* 4 łyżki posiekanego szczypiorku


|
== Przygotowanie
W garnku na maśle i oliwie zeszklić pokrojoną w kosteczkę cebulę. Dodać obraną i pokrojoną w kosteczkę marchewkę i mieszając smażyć przez ok. 3 minuty.

Wlać gorący bulion i zagotować. Przykryć, zmniejszyć ogień i gotować przez ok. 5 minut.

Dodać obrane i pokrojone w kosteczkę ziemniaki i gotować przez ok. 10 minut.

Dodać starte na tarce obrane ogórki oraz 1/2 szklanki soku z kiszonych ogórków (zalewy) jeśli mamy. Gotować przez ok. 10 minut. Odstawić z ognia.

Dodać szczypiorek oraz zaprawioną śmietanę (najpierw wymieszaną z 2 łyżkami wody, potem z kilkoma łyżkami wywaru).

== Zdjęcia
|===
