= Zupa grochówka

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* 4 porcje
* https://www.kwestiasmaku.com/przepis/zupa-grochowa-z-ziemniakami-i-kielbasa[link do źródła przepisu]

== Składniki
* 150 g grochu łuskanego połówki żółtego
* 1 łyżka masła
* 1 cebula
* 1 listek laurowy, 1 ziele angielskie, 1 łyżeczka kminku, 2 łyżeczki majeranku
* 1 marchewka
* 3 ziemniaki
* 15 cm kawałek kiełbasy
* 1 litr bulionu np. wieprzowego, drobiowego
* 1 łyżka posiekanej natki
|
== Przygotowanie
Dzień wcześniej zalać groch 1 litrem zimnej wody i odstawić do namoczenia na całą noc. Następnego dnia odcedzić, zalać świeżą wodą (kilka centymetrów ponad poziom grochu), dodać pół łyżeczki soli i zagotować. Zmniejszyć ogień i gotować pod lekko uchyloną pokrywą przez około 45 minut lub do miękkości (groch może się częściowo rozpaść i rozgotować).

W dużym garnku na maśle zeszklić pokrojoną w kosteczkę cebulę. Dodać listek laurowy, ziele angielskie, kminek, majeranek oraz obraną i pokrojoną w kosteczkę marchewkę. Mieszając smażyć przez ok. 5 minut.

Dodać obrane i pokrojone w kosteczkę ziemniaki oraz obraną i pokrojoną w kosteczkę kiełbasę i chwilę razem podsmażać.

Zalać gorącym bulionem i zagotować. Dodać ugotowany groch (wraz z pozostałą wodą z gotowania), doprawić pieprzem, wymieszać i w razie potrzeby doprawić solą.

Przykryć i gotować przez ok. 15 minut do miękkości warzyw, pod koniec dodać posiekaną natkę pietruszki. Podawać z pieczywem.
== Zdjęcia
|===
