= Zupa tajska z owocami morza

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* https://www.kwestiasmaku.com/kuchnia_orientu/curry/zupa_curry_z_owocami_morza/przepis.html[link do źródła przepisu]

== Składniki
* 2 łyżeczki oleju roślinnego
* 2 łyżeczki czerwonej pasty curry
* 1 łyżeczka tartego imbiru
* 250 ml bulionu
* 200 ml mleka kokosowego
* 200 g filetu z dorsza
* opcjonalnie - 150 g mieszanki owoców morza (może być mrożona) lub wybranych np. krewetek, małży lub pierścieni kalmarów
* 1 łyżeczka soku z limonki
* 1 łyżeczka cukru trzcinowego
* 1 łyżka sosu rybnego
* 1 czerwona papryczka chili świeża lub suszona + mielona papryka ostra do smaku
|
== Przygotowanie
Rybę i owoce morza rozmrozić jeśli były zamrożone.

W garnku podgrzać olej, dodać pastę curry i smażyć ją przez około 1 - 2 minuty (garnek można przykryć aby nie pryskało).

Dodać imbir, wlać bulion, mleko kokosowe i zagotować. W międzyczasie dodać sok z limonki, cukier, sos rybny. Gotować przez 3 minuty.

Do lekko gotującego się wywaru włożyć pokrojone filety i owoce morza. Gotować bez przykrycia na małym ogniu przez około 5 minut dodając sól do smaku.

Doprawić papryczką chili. Podawać z ugotowanym ryżem i świeżą kolendrą.
== Zdjęcia
|===
