= Zupa krem z szparagów

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* 2 - 4 porcje
* https://www.kwestiasmaku.com/zielony_srodek/szparagi/zupa_krem_z_bialych_szparagow/przepis.html[link do źródła przepisu]

== Składniki
* 2 pęczki białych szparagów
* 1 duża cebula
* 4 łyżki masła
* 2 ziemniaki
* 1/2 łyżeczki tartej gałki muszkatołowej
* 1,25 litra bulionu jarzynowego lub drobiowego
* drobno zmielony pieprz
* 100 ml śmietanki kremówki 30%
|
== Przygotowanie
Szparagi opłukać, odłamać twarde i grube końcówki (ok. 3 cm), łodyżki obrać, pokroić na 2 cm kawałki. Twarde końcówki można wykorzystać do ugotowania bulionu jarzynowego, są łykowate i nie nadają się na zmiksowanie w zupie.

W garnku roztopić 2 łyżki masła i zeszklić pokrojoną w kosteczkę cebulę. Następnie dodać obrane i pokrojone w drobną kosteczkę ziemniaki i mieszając co chwilę smażyć przez ok. 5 minut.

Dodać szparagi (oprócz główek) oraz 2 łyżki masła i smażyć co chwilę mieszając przez 1 - 2 minuty. Doprawić solą, gałką muszkatołową i wymieszać.

Wlać gorący bulion i zagotować. Gotować przez ok. 5 minut, następnie dodać główki szparagów i gotować jeszcze 2 minuty. Zmiksować w stojącym blenderze z dodatkiem śmietanki kremówki na idealnie gładki krem (około 1 minuta miksowania), pozostawiając kilka główek szparagów do dekoracji.

Zupę można dodatkowo przelać przez sito i przetrzeć łyżką zgromadzony na sicie miąższ, w ten sposób pozbędziemy się resztek łykowatych cząstek szparagów. Do zupy dodać pół łyżeczki drobno zmielonego pieprzu i podgrzać przed podaniem na małym ogniu. Podawać z chipsami z bekonu i tartą gałką muszkatołową oraz opcjonalnie z rukwią wodną lub rukolą.
== Zdjęcia
|===
