= Zupa grzybowa 50 złotych grzybów

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* 4 - 5 porcji
* https://www.kwestiasmaku.com/przepis/zupa-krem-grzybowa-z-suszonych-grzybow[link do źródła przepisu]

== Składniki
* 70 g grzybów suszonych (borowików i/lub podgrzybków)
* 1,5 litra bulionu (np. grzybowy, warzywny, mięsny)
* 1 łyżka oleju roślinnego
* 1 cebula
* 1 marchewka
* 2 ziemniaki
* zioła: po 1 łyżeczce tymianku, cząbru i majeranku
* pęczek natki pietruszki
* 250 ml śmietanki 30%
* do podania: grzaneczki z chleba


|
== Przygotowanie
Suszone grzyby opłukać pod bieżącą chłodną wodą, włożyć do miski, zalać bulionem i odstawić na noc do namoczenia.

Do większego garnka wlać oliwę i zeszklić pokrojoną w kosteczkę cebulę.

Następnie dodać obraną i startą na tarce marchewkę i podsmażać przez ok. 2 minuty.

Dodać obrane i pokrojone w kostkę ziemniaki oraz zioła. Mieszając co chwilę podsmażać przez minutę.

Wlać namoczone grzyby wraz z bulionem. Zagotować na dużym ogniu. Doprawić solą i pieprzem (ok. pół łyżeczki).

Po zagotowaniu zmniejszyć ogień i gotować pod przykryciem przez ok. 20 minut (do miękkości składników).

Odstawić z ognia i zmiksować z dodatkiem oderwanych listków natki pietruszki oraz śmietanki.

Zupę można zawekować (wlać gorącą do słoików) i po ostudzeniu przechować przez kilka dni w lodówce. Lub też od razu podawać z grzankami (chleb pokroić w małą kosteczkę, rozłożyć na blaszce i suszyć w piekarniku nagrzanym do 160 stopni C, aż będzie chrupiący).



== Zdjęcia
|===
