= Zupa pomidorowa

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* https://www.kwestiasmaku.com/kuchnia_polska/zupy/zupa_pomidorowa/przepis.html[link do źródła przepisu]

== Składniki
* ćwiartka kurczaka
* 2 litry wody
* 1/2 łyżeczki soli
* włoszczyzna (marchewka, pietruszka, kawałeczek pora, plasterek selera)
* 200 g koncentratu pomidorowego w słoiczku*
* 250 ml śmietany 18% z kartonika (do zup i sosów)
* szczypta zmielonego pieprzu

|
== Przygotowanie
Mięso opłukać pod bieżącą chłodną wodą, włożyć do garnka, dodać szczyptę soli, zalać zimną wodą i moczyć przez około 15 minut. Następnie wylać wodę z moczenia kurczaka, dodać czystą zimną wodę (2 litry), posolić i zagotować na większym ogniu.

W międzyczasie zdejmować łyżką cedzakową wytrącone na powierzchni "szumowiny". Zmniejszyć ogień do minimum i gotować na małym ogniu przez około 1/2 godziny. Dodać obraną i opłukaną włoszczyznę i gotować przez następne 20 minut.

Wyjąć mięso z wywaru, dodać pomidory, dokładnie wymieszać i zagotować. Najlepiej dodać na początek mniej przecieru, zawsze można go później dodać po spróbowaniu zupy, chodzi o to aby zupa nie była za kwaśna.

Zmniejszyć ogień i stopniowo dodawać śmietanę - aby uniknąć zwarzenia najlepiej wcześniej wymieszać ją w oddzielnym naczyniu (np. kubku) z kilkoma łyżkami zimnej wody a następnie ze stopniowo dodawanym gorącym wywarem (około 1/3 szklanki). Całość delikatnie podgrzać. Doprawić do smaku pieprzem.

== Zdjęcia
|===
