= Zupa z cukinii

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* https://aniagotuje.pl/przepis/zupa-z-cukinii[link do źródła przepisu]

== Składniki
* 500 ml bulionu warzywnego lub drobiowego
* 2 cukinie - 800 g
* mała cebula cukrowa
* 2 łyżki masła
* 4 ząbki czosnku
* 5 łyżek śmietanki 30 %
* przyprawy: po pół płaskiej łyżeczki soli i pieprzu, łyżeczka ziół prowansalskich
* zioła: garść siekanego szczypiorku, oraz natki pietruszki
* 2 kromki jasnego pieczywa pszennego
* 4 łyżki delikatnej oliwy
* łyżeczka ziół prowansalskich


|
== Przygotowanie
Cukinia jest fantastycznym warzywem, z którego można wyczarować wiele dań. Jednym z najlepszych pomysłów na jej wykorzystanie jest zupa z cukinii. Mój przepis na zupę cukiniową jest prosty. Serdecznie zapraszam

- gotowa do jedzenia w niecałą godzinę

- opis wykonania krok po kroku ze zdjęciami

- pyszna, prosta i sprawdzona zupa krem

Jeśli masz więcej dorodnych kabaczków, to bardzo proszę.. mam świetny przepis na leczo warzywne lub pasztet z cukinii - rewelacja!

Czas przygotowania: 25 minut

Czas gotowania: 20 minut

Liczba porcji: 1 litr zupy





Kaloryczność kcal: 90 w 100 ml zupy

Dieta: wegetariańska

Składniki na zupę z cukinii

Składniki na grzanki do zupy

Czas liczony jest bez gotowania bulionu.

Kaloryczność zupy liczona jest bez dodatku grzanek.

Szklanka ma u mnie pojemność 250 ml.

Zupa z cukinii to zwiastun jesieni, chociaż zajadamy się nią również przez połowę lata. Już sam kolor zupy z cukinii sprawia, że planuje się dokładkę. Słoneczna zieleń. Piękny zapach. Super kremowa konsystencja oraz chrupiące grzanki. Coś wspaniałego.

Do zrobienia zupy cukiniowej potrzebujesz na start 500 ml dobrego, esencjonalnego bulionu. Może to być bulion warzywny albo rosół drobiowy.

Ja zazwyczaj gotuję rosół na szyi i skrzydle z indyka. Do garnka wlewam dwa litry wody. Dodaję opaloną cebulę, 3 marchewki, korzeń pietruszki, kawałek korzenia selera; kilka liści laurowych, kilka ziaren ziela angielskiego i czarnego pieprzu oraz płaską łyżkę soli. Czasem dodaję też czosnek i lubczyk. Rosół gotuję przez 1,5 godziny bez zdejmowania przykrywki.

Do zupy z cukinii odlewam 500 ml bulionu. Z reszty zaś robię inną zupę. Świetna jest zupa szparagowa. Z warzyw i mięsa szykuję pasztet drobiowy z mięsa i warzyw z rosołu.

Moja pyszna i super prosta do zrobienia zupa krem z cukinii. Szykuję ją latem oraz jesienią. Zawsze gotuję dużo bulionu warzywnego lub rosołu drobiowego. Taki wywar jest najlepszą bazą pod wszelkie zupy. Mrożenie torebek z gotowym bulionem niesamowicie przyspiesza szykowanie każdej zupy lub sosu pod dania mięsne i warzywne z makaronem czy ryżem. Zupa z cukinii krem przepis wyśmienity i wart polecania. Zapewnia, że Ci się spodoba. Polecam Ci też coś równie pysznego, czyli zupa porowa krem.

Prosta zupa z cukinii z warzywami a raczej z samą cebulą, ponieważ cukinia sama w sobie jest tak pyszna, że nie potrzeba wiele dodatków. by zrobić świetną zupę na obiad. Zupa z cukinii fit będzie wtedy, gdy nie dodasz do niej śmietanki. Koniecznie zobacz też moje inne przepisy na domowe zupy. Zupa pomidorowa ze świeżych pomidorów - najlepsza latem, gdy mamy cudowne pomidory malinowe.



== Zdjęcia
|===
