= Zupa barszcz z uszkami

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* 6 porcji
* https://www.kwestiasmaku.com/kuchnia_polska/wigilia/barszcz_wigilijny_z_uszkami/przepis.html[link do źródła przepisu]

== Składniki
* 40 g suszonych borowików
* 1 cebula
* 2 ząbki czosnku
* 3 listki laurowe, 4 ziela angielskie, 10 ziaren pieprzu
* 2 kg czerwonych buraków
* 1/2 korzenia selera
* 1 jabłko (np. szara reneta)
* 3 łyżki octu spirytusowego 10%
* sól morska (około 1/2 łyżki) i świeżo zmielony czarny pieprz (około 1 łyżeczki)
* 3 łyżki cukru
* opcjonalnie: 3 goździki, kawałek kory cynamonu, kawałek gwiazdki anyżu
* warto dodać: 250 - 500 ml zakwasu (kwasu) burakowego


|
== Przygotowanie
Do garnka wlać 500 ml wody, wsypać suszone borowiki. Na palniku kuchenki opalić nieobraną cebulę oraz 1 ząbek czosnku.

Cebulę i czosnek przekroić na pół i dodać do grzybów. Zagotować na umiarkowanym ogniu, następnie zmniejszyć ogień do minimum, przykryć i na minimalnym ogniu gotować przez około 25 minut (wywar ma tylko lekko mrugać a nie mocno się gotować).

W międzyczasie dodać do wywaru liście laurowe, ziele angielskie i pieprz ziarnisty.

Buraki i selera umyć, obrać ze skórki, następnie zetrzeć na tarce (na dużych oczkach, jak do surówki) lub posiekać w melakserze. Jabłko razem ze skórką zetrzeć na tarce.

Starte buraki, selera i jabłko włożyć do dużego garnka (warzyw będzie dość sporo), dodać 2,5 litry wody oraz wywar z grzybami. Przykryć garnek i zagotować na minimalnym ogniu (zagotowanie ma trwać około 20 minut). W międzyczasie dodać goździki, cynamon i anyż jeśli ich używamy.

Po zagotowaniu trzymać wywar jeszcze na minimalnym ogniu przez około 10 minut. Na koniec dodać ocet i wymieszać. Odstawić z ognia.

Do barszczu warto dodać wywar grzybowy pozostały po uszkach (niekoniecznie cały) oraz 250 ml kwasu burakowego.

Barszcz odstawić na około godzinę. W międzyczasie można zacząć przygotowywać uszka.

Do barszczu dodać sól (do smaku), pieprz mielony, cukier oraz świeży posiekany ząbek czosnku, znów zostawić na minimum godzinę ale najlepiej do czasu całkowitego ostudzenia.

Barszcz przecedzić i schować do lodówki. Następnego dnia lub przed podaniem podgrzać, spróbować i w razie potrzeby doprawić solą i pieprzem.

== Zdjęcia
|===
