= Zuppa di pesce

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* 2 porcje
* https://www.kwestiasmaku.com/przepis/zuppa-di-pesce[link do źródła przepisu]

== Składniki
* 2 łyżki oliwy extra vergine
* 1 ząbek czosnku
* pół pęczka natki pietruszki
* 1/2 papryczki chili
* 2 pomidory + 1 łyżka koncentratu pomidorowego
* 100 ml białego wytrawnego wina
* 350 ml wrzącej wody
* 300 filetów ryby morskiej (np. dorsz, halibut, sola, żabnica)
* 200 g świeżych małży
* 100 g krewetek + opcjonalnie 2 krewetki nieobrane, z głowami
* bagietka
|
== Przygotowanie
Do szerokiego większego garnka wlać oliwę, dodać obrany i pokrojony na cienkie plasterki czosnek, posiekaną w kosteczkę papryczkę chili i smażyć na małym ogniu przez około 3 minuty co chwilę mieszając.

Pomidory sparzyć, obrać ze skórki i pokroić w kosteczkę. Dodać do garnka i na większym ogniu gotować przez ok. 5 minut co chwilę mieszając.

Dodać koncentrat, połowę posiekanej natki pietruszki, wlać wino i gotować przez kolejne 5 minut. Wlać wrzątek, doprawić solą, świeżo zmielonym pieprzem i gotować na większym ogniu przez ok. 5 minut aż sos odparuje i zgęstnieje.

Filety ryby bez skóry i ości pokroić na kilka mniejszych kawałków. Małże opłukać pod bieżącą zimną wodą i oczyścić. Krewetki obrać z pancerzy, naciąć grzbiet i usunąć ciemne jelito. Jeśli mamy 2 krewetki z głowami, pozostawiamy je w całości.

Do garnka z sosem dodać małże, krewetki oraz filety ryby. Gotować przez ok. 3 minuty na średnim ogniu, w połowie delikatnie przemieszać składniki.

Wszystkie nieotwarte małże wyrzucić. Dodać resztę natki pietruszki, jeszcze raz doprawić w razie potrzeby. Przygotować grzanki z bagietki.

Zupę nałożyć do talerzy, dodać grzanki. Obok każdej porcji postawić talerz na muszle po małżach oraz miseczkę z zimną wodą i kawałkiem cytryny (do umycia palców po posiłku).
== Zdjęcia
|===
