= Łatwe kimchi

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* Czas przygotowania: powyżej godziny									180M
* https://www.jadlonomia.com/przepisy/kimchi-czyli-koreanska-kiszona-kapusta[link do źródła przepisu]

== Składniki


|
== Przygotowanie
Kapustę przekroić wzdłuż na cztery części, następnie każdą ćwiartkę pokroić na małe kawałki. Tak przygotowaną kapustę przełożyć do dużej miski, zalać wodą z solą, docisnąć talerzykiem obciążonym słoikiem i odstawić na 60 minut.

W międzyczasie zagotować wodę z mąką ryżową oraz cukrem i gotować przez 1 -2 minuty do czasu, aż zmieni się w gęsty, ryżowy kleik. Wtedy zdjąć z ognia i odstawić do przestudzenia.

Cebulę i czosnek bardzo drobno posiekać lub rozetrzeć na pastę w blenderze. Następnie do przestudzonego kleiku dodać posiekaną cebulę, czosnek, sos sojowy, paprykę oraz sól i bardzo dokładnie wymieszać.

Kiedy pasta będzie wymieszana dodać posiekany szczypior oraz marchew i jeszcze raz krótko wymieszać.

Namoczoną kapustę odcedzić, bardzo dokładnie odcisnąć i przełożyć do dużej miski. Dodać pastę kimchi i przy pomocy dłoni w rękawiczkach dokładnie natrzeć kapustę pastą. Kiedy całość będzie wymieszana przełożyć do pojemnika, pojemnik zamknąć i zostawić na blacie na 2 – 5 dni, czyli do momentu, aż zrobi się lekko kwaśne. Potem przełożyć do lodówki i wykorzystywać wtedy, kiedy najdzie was ochota.

Powyższy przepis to najprostszy, podstawowy przepis na domowe kimchi – w smaku jest łagodne, możecie też dorzucić do niego kilka pasków kalarepy, rzepy lub innych warzyw korzeniowych.

Tradycyjne kimchi zawiera paprykę gochuagru, w którą możecie się zaopatrzyć kiedy rozkręcicie się z robieniem domowego kimchi.

Nie pomijajcie przygotowania kleiku ryżowego, ponieważ dzięki niemu kimchi jest gęste i ma odpowiednio zbilansowany smak.

Nie próbujcie nacierać kapusty pastą kimchi bez rękawiczek, będzie piec!

Kiszonki przechowywane przez cały rok najlepiej jest kisić w kamionkowych naczyniach, ponieważ nie reagują z kiszonką i dodatkowo są higroskopijne, czyli wchłaniają nadmiar wilgoci i pomagają uniknąć pleśni. Tak też było kiszone kimchi w dawnych czasach, jednak obecnie w domach przez dużą częstotliwość i małe ilości przygotowywanego kimchi, koreańska kapusta jest wkładana w niedużych porcjach do małych plastikowych pojemników. Dzięki temu, że kimchi jest kiszone krótko i przechowywane w lodówce przechowywanie go w pojemniku absolutnie w niczym mu nie szkodzi. Oczywiście jeśli macie kamionkowy słoik i chcecie go użyć to śmiało, kimchi będzie jeszcze bliższe dawnym koreańskim tradycjom!

== Zdjęcia
|===
