= Kompot czereśniowy 🌱 +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++
:imagesdir: /Recipes/static/images

[.recipe-hero]

[.recipe-category-label]
Dania główne

[.card-image-placeholder]
Brak zdjęcia przepisu 🍲


[.recipe-details]

[.recipe-details-item]
📝 4 słoiki po 900 ml

[.recipe-details-item]
🕒 czas przygotowania: 20 minut

[.recipe-details-item]
🕒 czas pasteryzacji: 20 minut

[.recipe-details-item]
🔗 https://aniagotuje.pl/przepis/kompot-z-czeresni[link do źródła przepisu]



[.recipe-columns]

[.recipe-column-box]
== Składniki
* 2 kg czereśni
* 3 łyżki cukru
* 2 litry przegotowanej wody



[.recipe-column-box]
== Przygotowanie
Przejrzyj swoje czereśnie i wybierz te dojrzałe oraz nieuszkodzone i nie zepsute. Czereśnie umyj pod zimną i bieżącą wodą.

Przygotuj też cztery czyste słoiki o pojemności 900 ml każdy. Słoiki powinny być idealnie czyste, a najlepiej odparzone wrzątkiem. Tak samo zakrętki. Używaj tylko nieuszkodzonych słoików i zakrętek. 

Do każdego słoika daj tyle samo czereśni. Swoje słoiki wypełniam czereśniami do około 3/4 wysokości. Do każdego słoika z owocami wsyp też cukier - po jednej łyżce.

Do każdego słoika wlej przegotowaną wodę. Może być to wrzątek lub woda letnia. Na słoiki o pojemności 900 ml wyszło mi idealnie po 500 ml wody. Zostaw minimum 1 cm wolnej przestrzeni przy rantach i mocno zakręć słoiki. Słoiki z kompotem należy teraz poddać pasteryzacji. (20 minut w piekarniku)

