= Nalewka mango  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 30 minut + 1 miesic
* liczba porcji: okoo 1,5 l nalewki
* https://all-exclusive.pl/nalewka-z-mango-mangowka/[link do 藕r贸da przepisu]

== Skadniki

* 2 du偶e mango (dojrzae, ale nadal lekko twarde)
* 700 ml w贸dki 40%;
* 1 limonka;
* 350 ml wody;
* 150 g cukru.

|
== Przygotowanie

Owoce obieramy i kroimy na du偶 kosteczk albo w co nam tam wygodnie. Mango wrzucamy do soja, a nastpnie dodajemy sok wycinity z jednej limonki. Mieszamy ze sob 500 ml w贸dki oraz 200 ml spirytusu i przelewamy alkohol do soja. W idealnym wiecie alkohol powinien zakry nam w caoci owoce. 

Cao odstawiamy w bezpieczne miejsce na 3 tygodnie, od czasu do czasu potrzsajc. Po tym czasie mango zaczyna wytraca sw贸j kolor i og贸lnie wyglda coraz mniej apetycznie. Nie ma co ryzykowa pogbienia tego procesu, dlatego odcedzamy owoce na durszlaku i zlewamy alkohol do osobnego naczynia. Podczas gdy mango spokojnie sobie ocieka, my przystpujemy do robienia syropu.

Gotujemy wod w garnku, a nastpnie rozpuszczamy w niej cukier. Mango ponownie wrzucamy do soja i wlewamy do niego ostudzony syrop. Zakrcamy pojemnik i trzsiemy nim kilka minut jak podczas gry na meksykaskich marakasach. Dla zachowania odpowiedniej intensywnoci i wyczucia czasu mo偶na puci sobie w tle ten utw贸r. Proces ten ma na celu wycinicie z mango resztek pochonitego alkoholu oraz zapewnienie organizmowi odpowiedniej dawki kardio. 

Po zakoczeniu kcika muzycznego po raz kolejny cedzimy mango. Syrop wlewamy do wczeniej pozyskanego nalewu i mieszamy, a mango wykorzystujemy wedle wasnej inwencji tw贸rczej. W dalszej kolejnoci bierzemy si do filtrowania nalewki. Ja w pierwszej kolejnoci odcedziem nalewk przez worek do nalewek, a dopiero za drugim razem przelaem j do butelek przez filtr do kawy. W efekcie uzyskaem niecay 1 litr przejrzystej nalewki z mango. 

|===

[.text-center]
== Zdjcia
