= Nalewka cytrynowa  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 30 minut + 1 miesic
* liczba porcji: okoo 1,5 l nalewki
* https://fajnyogrod.pl/kuchnia/nalewki-domowe/nalewka-cytrynowa-najlepsze-przepisy-na-cytrynowke-na-spirytusie-i-na-wodce/[link do 藕r贸da przepisu]

== Skadniki

* 6 do 8 cytryn (w zale偶noci od wielkoci)
* 0,5 l w贸dki
* 1 szklanka wody
* 1 szklanka cukru

|
== Przygotowanie

Wod nale偶y zagotowa w garnku, a nastpnie doda cukier i gotowa, od czas do czasu mieszajc - tak, by cukier si rozpuci. Ze wszystkich cytryn wyciskamy sok, najlepiej przy u偶yciu wyciskarki, a uprzednio z poowy cytryn cieramy sk贸rk. Przygotowan wczeniej wod mieszkamy z alkoholem, sokiem, otart sk贸rk i odstawiamy na co najmniej kilkanacie godzin, a najlepiej na dob, by skadniki mogy dobrze si ze sob wymiesza. Po tym czasie mieszanin przecedzamy przez sito i rozlewamy do butelek. Taka domowej roboty szybka nalewka na cytrynie powinna dojrzewa w zacienionym miejscu przez minimum trzy tygodnie. Po tym czasie nadaje si do spo偶ycia.

|===

[.text-center]
== Zdjcia
