= Nalewka gruszkowa  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: 30 minut + 1 miesic
* liczba porcji: okoo 1,5 l nalewki
* https://fajnyogrod.pl/kuchnia/nalewki-domowe/nalewka-z-gruszek-na-wodce-i-spirytusie-przepisy-krok-po-kroku/[link do 藕r贸da przepisu]

== Skadniki

* 1 kg dojrzaych i sodkich gruszek,
* 陆 szklanki cukru lub cukru trzcinowego,
* 陆 litra w贸dki.
* opcjonalnie: go藕dziki, kawaek laski wanilii, kawaek kory cynamonu, rodzynki, sk贸rka cytryny lub pomaraczy. 

|
== Przygotowanie

Gruszki nale偶y dokadnie umy, obra i wykroi z nich gniazda nasienne. Tak przygotowane owoce kroimy w 贸semki lub grubsze plastry i umieszczamy w du偶ym soju. Zwarto naczynia zasypujemy cukrem, zakrywamy szczelnie ciereczk obwizan sznurkiem i odstawiamy na jeden dzie, by gruszki puciy sok. Po upywie wyznaczonego czasu, dla uzyskania bardziej wyrazistego smaku owoce mo偶na dodatkowo rozdrobni, na przykad przy u偶yciu blendera.

Kolejny krok to dolanie alkoholu i ewentualnie tak偶e wybranych przypraw. Ze smakiem gruszek doskonale komponuj si go藕dziki, jednak nie ka偶dy lubi ich specyficzny smak, dlatego z powodzeniem mo偶na sign po inne dodatki. S贸j ponownie zamykamy, tym razem szczelnie i odstawiamy a zacienione miejsce na minimum tydzie, od czasu do czasu mieszajc. Po upywie wyznaczonego czasu nalewka gruszkowa na w贸dce wymaga ju偶 tylko przefiltrowania przez gaz (drobne sitko mo偶e nie zatrzyma charakterystycznych na owoc贸w gruszki drobinek) i przelanie do butelki. Ostawienie jej na minimum miesic da gwarancj wybornego smaku, ale jak to w przypadku nalewek jest - im du偶sze le偶akowanie, tym dla trunku lepiej.

|===

[.text-center]
== Zdjcia
