= Nalewka mango +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 30 minut + 1 miesiąc
* liczba porcji: około 1,5 l nalewki
* https://all-exclusive.pl/nalewka-z-mango-mangowka/[link do źródła przepisu]

== Składniki
* 2 duże mango (dojrzałe, ale nadal lekko twarde)
* 700 ml wódki 40%;
* 1 limonka;
* 350 ml wody;
* 150 g cukru.

|
== Przygotowanie

Owoce obieramy i kroimy na dużą kosteczkę albo w co nam tam wygodnie. Mango wrzucamy do słoja, a następnie dodajemy sok wyciśnięty z jednej limonki. Mieszamy ze sobą 500 ml wódki oraz 200 ml spirytusu i przelewamy alkohol do słoja. W idealnym świecie alkohol powinien zakryć nam w całości owoce. 

Całość odstawiamy w bezpieczne miejsce na 3 tygodnie, od czasu do czasu potrząsając. Po tym czasie mango zaczyna wytracać swój kolor i ogólnie wyglądać coraz mniej apetycznie. Nie ma co ryzykować pogłębienia tego procesu, dlatego odcedzamy owoce na durszlaku i zlewamy alkohol do osobnego naczynia. Podczas gdy mango spokojnie sobie ocieka, my przystępujemy do robienia syropu.

Gotujemy wodę w garnku, a następnie rozpuszczamy w niej cukier. Mango ponownie wrzucamy do słoja i wlewamy do niego ostudzony syrop. Zakręcamy pojemnik i trzęsiemy nim kilka minut jak podczas gry na meksykańskich marakasach. Dla zachowania odpowiedniej intensywności i wyczucia czasu można puścić sobie w tle ten utwór. Proces ten ma na celu wyciśnięcie z mango resztek pochłoniętego alkoholu oraz zapewnienie organizmowi odpowiedniej dawki kardio. 

Po zakończeniu kącika muzycznego po raz kolejny cedzimy mango. Syrop wlewamy do wcześniej pozyskanego nalewu i mieszamy, a mango wykorzystujemy wedle własnej inwencji twórczej. W dalszej kolejności bierzemy się do filtrowania nalewki. Ja w pierwszej kolejności odcedziłem nalewkę przez worek do nalewek, a dopiero za drugim razem przelałem ją do butelek przez filtr do kawy. W efekcie uzyskałem niecały 1 litr przejrzystej nalewki z mango. 

|===

[.text-center]
== Zdjęcia
