= Nalewka jabkowa  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: 30 minut + 1 miesic
* liczba porcji: okoo 2,5 l nalewki
* https://fajnyogrod.pl/kuchnia/nalewki-domowe/nalewka-z-jablek-najlepsze-przepisy-na-nalewke-jablkowa-na-spirytusie/[link do 藕r贸da przepisu]

== Skadniki

* 1 kg jabek,
* 2 szklanki cukru (lub po 1 szklance biaego i brzowego),
* 1 szklanka wody,
* 3 szklanki w贸dki (lub 2 szklanki w贸dki i 1 szklanka innego alkoholu, np. brandy),
* dodatki do wyboru i czenia: cynamon, go藕dziki, p贸 laski wanilii, otarta sk贸rka cytryny.

|
== Przygotowanie

Z jabek usuwamy gniazda nasienne i dzielimy je na kawaki, na przykad wiartki lun plastry. Tak przygotowane owoce umieszczamy w du偶ym soju, wsypujemy wybrane przyprawy i zalewamy wszystko ostudzonym syropem z wody i cukru oraz alkoholem. Tak przygotowan mieszkank nale偶y odstawi w zacienione miejsce na kilka tygodni. Po upywie wyznaczonego czasu nalewka z jabek wymaga zlania, przefiltrowania przez drobne sito lub gaz i rozlania do butelek, by moga dalej le偶akowa przez kilka kolejnych tygodni i nabiera smaku.

|===

[.text-center]
== Zdjcia
