= Nalewka malinowa  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: 30 minut + 1 miesic
* liczba porcji: okoo 1,5 l nalewki
* https://aniagotuje.pl/przepis/nalewka-z-malin[link do 藕r贸da przepisu]

== Skadniki
* 1 kg wie偶ych malin
* 1000 ml w贸dki 40 lub 45 %
* 400 g zwykego cukru

|
== Przygotowanie
Zbierz lub kup kilogram adnych i dojrzaym malin. W razie potrzeby zdejmij je z szypuek, oczy i przebierz z zepsutych, czy uszkodzonych sztuk. Maliny delikatnie przepucz pod prysznicem z zimnej, bie偶cej wody. 

Cay kilogram gotowych malin prze贸偶 do du偶ego i czystego soja. Ja u偶ywam uniwersalnego soja, w kt贸rym szykuj wikszo nalewek. To s贸j o pojemnoci 3,8 l.

Do soika z malinami wlej prawie ca w贸dk. W przepisie podaam litr czystej w贸dki, ale do samych malin wlej p贸ki co 800 ml w贸dki. 200 ml w贸dki (niecaa szklanka) zostaw w butelce "na potem". Bdziesz jej potrzebowa za tydzie, gdy zlejesz nalewk do osobnego naczynia i dodasz do malin cukier. 

Po zalaniu malin w贸dk zakoysz kilak razy sojem, by pcherzyki powietrza poszy do g贸ry a w贸dka spenetrowaa ka偶dy zaktek w malinach. Soik mo偶esz zakrci lub zamkn wieczko, jeli to wek. Swoje nalewki malinowe trzymam w kuchni na blacie przy oknie. Jest to soneczne miejsce. S贸j z przysz nalewk malinow zostaw tak na cae siedem dni. Ka偶dego dnia lekko zakoysz sojem. Zawsze ulec do g贸ry zabkane pcherzyki powietrza. 

Po tygodniu czyst nalewk przelej do mniejszego soja. Soik zakr i odstaw obok soja z samymi malinami. Do du偶ego soja z malinami wlej zostawione wczeniej 200 ml w贸dki i wsyp 400 gram贸w cukru. 


Maliny z cukrem i pozosta w贸dk zamieszaj dokadnie i zamknij soik. S贸j trzymaj w tym samym miejscu co wczeniej. Warto kilka razy dziennie zamiesza cao, by cukier szybciej si rozpuci. Zawsze trzymam taki s贸j dwa dni. W tym czasie cukier cakowicie powinien si ju偶 rozpuci. 

Sok oraz owoce przecedzam przez sitko do soika z dwa dni temu zlan nalewk. Dokadnie odciskam cay sodki sok z owoc贸w. Ostatecznie otrzymaam cznie 1500 ml nalewki malinowej.

To jeszcze nie koniec. Po przecedzeniu resztek soku nalewka nie bdzie klarowna. Aby mo偶na j byo spokojnie odo偶y do le偶akowania, trzeba j dokadnie przefiltrowa z fragment贸w owoc贸w oraz innych zanieczyszcze. 

Po prawidowym i dokadnym przefiltrowaniu Twoja nalewka malinowa bdzie idealnie klarowna. Mo偶esz j przela do kilku mniejszych butelek lub soik贸w. Nalewka z malin powinna le偶akowa np. w kuchennym schowku lub piwniczce minimum sze miesicy. 

|===

[.text-center]
== Zdjcia
