= Nalewka malinowa +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 30 minut + 1 miesiąc
* liczba porcji: około 1,5 l nalewki
* https://aniagotuje.pl/przepis/nalewka-z-malin[link do źródła przepisu]

== Składniki
* 1 kg świeżych malin
* 1000 ml wódki 40 lub 45 %
* 400 g zwykłego cukru

|
== Przygotowanie
Zbierz lub kup kilogram ładnych i dojrzałym malin. W razie potrzeby zdejmij je z szypułek, oczyść i przebierz z zepsutych, czy uszkodzonych sztuk. Maliny delikatnie przepłucz pod prysznicem z zimnej, bieżącej wody. 

Cały kilogram gotowych malin przełóż do dużego i czystego słoja. Ja używam uniwersalnego słoja, w którym szykuję większość nalewek. To słój o pojemności 3,8 l.

Do słoika z malinami wlej prawie całą wódkę. W przepisie podałam litr czystej wódki, ale do samych malin wlej póki co 800 ml wódki. 200 ml wódki (niecała szklanka) zostaw w butelce "na potem". Będziesz jej potrzebować za tydzień, gdy zlejesz nalewkę do osobnego naczynia i dodasz do malin cukier. 

Po zalaniu malin wódką zakołysz kilak razy słojem, by pęcherzyki powietrza poszły do góry a wódka spenetrowała każdy zakątek w malinach. Słoik możesz zakręcić lub zamknąć wieczko, jeśli to wek. Swoje nalewki malinowe trzymam w kuchni na blacie przy oknie. Jest to słoneczne miejsce. Słój z przyszłą nalewką malinową zostaw tak na całe siedem dni. Każdego dnia lekko zakołysz słojem. Zawsze ulecą do góry zabłąkane pęcherzyki powietrza. 

Po tygodniu czystą nalewkę przelej do mniejszego słoja. Słoik zakręć i odstaw obok słoja z samymi malinami. Do dużego słoja z malinami wlej zostawione wcześniej 200 ml wódki i wsyp 400 gramów cukru. 


Maliny z cukrem i pozostałą wódką zamieszaj dokładnie i zamknij słoik. Słój trzymaj w tym samym miejscu co wcześniej. Warto kilka razy dziennie zamieszać całość, by cukier szybciej się rozpuścił. Zawsze trzymam taki słój dwa dni. W tym czasie cukier całkowicie powinien się już rozpuścić. 

Sok oraz owoce przecedzam przez sitko do słoika z dwa dni temu zlaną nalewką. Dokładnie odciskam cały słodki sok z owoców. Ostatecznie otrzymałam łącznie 1500 ml nalewki malinowej.

To jeszcze nie koniec. Po przecedzeniu resztek soku nalewka nie będzie klarowna. Aby można ją było spokojnie odłożyć do leżakowania, trzeba ją dokładnie przefiltrować z fragmentów owoców oraz innych zanieczyszczeń. 

Po prawidłowym i dokładnym przefiltrowaniu Twoja nalewka malinowa będzie idealnie klarowna. Możesz ją przelać do kilku mniejszych butelek lub słoików. Nalewka z malin powinna leżakować np. w kuchennym schowku lub piwniczce minimum sześć miesięcy. 

|===

[.text-center]
== Zdjęcia
