= Przecier z warzyw na zupę (Jarzynka domowa) 🌱 +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++
:imagesdir: /Recipes/static/images

[.recipe-hero]
[.card-image-placeholder]
Brak zdjęcia przepisu 🍲

[.recipe-details]
* 🕒 czas przygotowania: 1 godzina
* 👥 4 porcje
* 🔗 Przepis z zeszytu mamy

[.recipe-columns]
== Składniki

== Przygotowanie
1 kg marchwi

0,5 kg pietruszki (korzeń)

0,5 kg selera (korzeń)

0,5 kg pora

1 duży pęczek natki pietruszki

1 pęczek koperku

0,5 kg soli kamiennej (niejodowanej)

Marchew, pietruszkę i seler zetrzeć na tarce o drobnych lub grubych oczkach (według uznania). Por, natkę i koperek drobno posiekać. Wszystkie warzywa wrzucić do bardzo dużej miski, zasypać całą ilością soli i dokładnie wymieszać dłońmi. Odstawić na 2-3 godziny, aż warzywa puszczą sok i zmiękną. Przekładać ciasno do słoików, mocno ugniatając, by na wierzchu zebrał się sok. Zakręcić. Dzięki dużej ilości soli nie trzeba pasteryzować — przechowywać w chłodzie. Doskonały dodatek do zup i sosów zamiast kupnych kostek.

[.recipe-gallery]
== Zdjęcia

[.gallery-grid]
// Tutaj pojawią się zdjęcia
