= Sok z czarnego bzu z miodem 🌱 +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++
:imagesdir: /Recipes/static/images

[.recipe-hero]
[.card-image-placeholder]
Brak zdjęcia przepisu 🍲

[.recipe-details]
* 🕒 czas przygotowania: 1 godzina
* 👥 4 porcje
* 🔗 Przepis z zeszytu mamy

[.recipe-columns]
== Składniki

== Przygotowanie
3 kg dojrzałych owoców czarnego bzu (oczyszczonych z szypułek)

1 szklanka wody

0,5 kg miodu naturalnego (np. lipowego lub wielokwiatowego)

sok z 1 cytryny

Owoce zalać wodą i gotować ok. 25 min, aż całkowicie puszczą sok i zmiękną. Przecedzić płyn przez bardzo gęste sito lub gazę, mocno odciskając owoce. Sok lekko przestudzić (tak do temperatury letniej, by miód nie stracił właściwości), dodać miód oraz sok z cytryny. Mieszać dokładnie, aż miód całkowicie się rozpuści. Przelać do czystych butelek. Pasteryzować bardzo krótko — ok. 5-7 min (lub przechowywać wyłącznie w lodówce).

[.recipe-gallery]
== Zdjęcia

[.gallery-grid]
// Tutaj pojawią się zdjęcia
