= Babka 🌱 +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++
:imagesdir: /Recipes/static/images

[.recipe-hero]
[.card-image-placeholder]
Brak zdjęcia przepisu 🍲

[.back-to-home-wrapper]
link:../../index.html[← Wróć do przepisów, role="back-to-home-btn"]

[.recipe-details]
* 🕒 czas przygotowania: 1 godzina
* 👥 4 porcje
* 🔗 Przepis z zeszytu mamy

[.recipe-columns]
== Składniki
* 3 jaja
* 1 szklanka cukru
* 1 cukier waniliowy
* 1 1/2 szklanki mąki
* 1 szklanka oleju
* 2 łyżki proszku
* 1 łyżka octu

== Przygotowanie

Całe jaja wbijamy do miski, dodajemy cukier oraz cukier waniliowy i miksujemy na najwyższych obrotach, aż powstanie puszysta, jasna i gęsta masa. Następnie, nie przerywając miksowania na wolniejszych obrotach, stopniowo wlewamy olej cienkim strumieniem. Do puszystej masy przesiewamy mąkę wymieszaną z proszkiem do pieczenia i delikatnie łączymy całość łyżką lub łopatką. Na samym końcu do ciasta dolewamy łyżkę octu i szybko, ale ostrożnie mieszamy, co sprawi, że babka po upieczeniu będzie wyjątkowo puszysta i wilgotna. Gotowe ciasto przelewamy do natłuszczonej i oprószonej mąką lub bułką tartą formy, po czym wstawiamy do piekarnika nagrzanego do 180°C i pieczemy przez około 40-45 minut, do momentu uzyskania suchego patyczka.

[.recipe-gallery]
== Zdjęcia

[.gallery-grid]
// Tutaj pojawią się zdjęcia
