= Brownie +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 45 min
* 20 porcji
* https://www.kwestiasmaku.com/desery/ciasta/czekoladowe_brownie/przepis.html[link do źródła przepisu]

== Składniki
* 200 g masła
* 200 g gorzkiej czekolady
* 3 jajka (temp. pokojowa)
* 250 g cukru
* 135 g mąki
* mała szczypta soli
* dodatkowo: ok. 50 - 100 g gorzkiej czekolady na wierzch

|
== Przygotowanie

Piekarnik nagrzać do 160 stopni C. Przygotować małą prostokątną foremkę o wymiarach ok. 21 cm x 28 cm (lub o podobnej powierzchni). Posmarować ją masłem i wyłożyć papierem do pieczenia.

Masło pokroić w kostkę i włożyć do rondelka, dodać połamaną na kosteczki czekoladę i cały czas mieszając roztopić na małym ogniu, odstawić z palnika.

W oddzielnej misce rozmiksować lub wymieszać rózgą jajka z cukrem. Dodać do nich roztopioną czekoladę z masłem zmiksować lub wymieszać rózgą na gładką masę.

Dodać mąkę oraz sól i zmiksować na jednolite ciasto. Wyłożyć do przygotowanej blaszki, wyrównać powierzchnię.

Dodatkową czekoladę pokroić na kawałki i posypać po wierzchu ciasta.

Wstawić do piekarnika i piec przez ok. 30 minut aż ciasto lekko urośnie. Jeśli używamy większej blaszki, ciasto będzie gotowe szybciej, jeśli mniejszej - czas pieczenia należy wydłużyć.

Po upieczeniu i ostudzeniu pokroić na małe kawałeczki.

|===

[.text-center]
== Zdjęcia
