= Brownie  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 45 min
* 20 porcji
* https://www.kwestiasmaku.com/desery/ciasta/czekoladowe_brownie/przepis.html[link do 藕r贸da przepisu]

== Skadniki

* 200 g masa
* 200 g gorzkiej czekolady
* 3 jajka (temp. pokojowa)
* 250 g cukru
* 135 g mki
* maa szczypta soli
* dodatkowo: ok. 50 - 100 g gorzkiej czekolady na wierzch

|
== Przygotowanie

Piekarnik nagrza do 160 stopni C. Przygotowa ma prostoktn foremk o wymiarach ok. 21 cm x 28 cm (lub o podobnej powierzchni). Posmarowa j masem i wyo偶y papierem do pieczenia.

Maso pokroi w kostk i wo偶y do rondelka, doda poaman na kosteczki czekolad i cay czas mieszajc roztopi na maym ogniu, odstawi z palnika.

W oddzielnej misce rozmiksowa lub wymiesza r贸zg jajka z cukrem. Doda do nich roztopion czekolad z masem zmiksowa lub wymiesza r贸zg na gadk mas.

Doda mk oraz s贸l i zmiksowa na jednolite ciasto. Wyo偶y do przygotowanej blaszki, wyr贸wna powierzchni.

Dodatkow czekolad pokroi na kawaki i posypa po wierzchu ciasta.

Wstawi do piekarnika i piec przez ok. 30 minut a偶 ciasto lekko uronie. Jeli u偶ywamy wikszej blaszki, ciasto bdzie gotowe szybciej, jeli mniejszej - czas pieczenia nale偶y wydu偶y.

Po upieczeniu i ostudzeniu pokroi na mae kawaeczki.

|===

[.text-center]
== Zdjcia
