= Ciasto marchewkowe +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 1,5 h
* 20 porcji
* https://www.kwestiasmaku.com/desery/ciasta/ciasto_marchewkowe/przepis.html[link do źródła przepisu]

== Składniki
* 2 jajka
* 200 g drobnego cukru lub cukru pudru
* 150 ml oleju roślinnego
* 200 g drobno startej marchewki
* 50 g posiekanych orzechów włoskich lub pekan + do dekoracji
* 75 g drobno pokrojonego ananasa (świeżego lub z puszki) lub jabłka
* 50 g wiórków kokosowych
* 200 g mąki
* 1/2 łyżeczki proszku do pieczenia
* po 1 łyżeczce sody i cynamonu
* szczypta soli

=== Polewa:

* 125 g kremowego serka np. Twój Smak, Philadelphia
* 50 g masła (miękkiego)
* 100 g cukru pudru

|
== Przygotowanie

Jajka ocieplić w temperaturze pokojowej. Ubić je do podwojenia objętości. Dodać cukier i dalej ubijać aż masa będzie gładka i puszysta. Wciąż ubijając na wysokich obrotach, dolewać ciągłym, cieniutkim strumieniem olej.

Dodać marchewkę, ananasa, orzechy, wiórki kokosowe i delikatnie wymieszać. Piekarnik nagrzać do 150 stopni C.

Do osobnej miski przesiać mąkę, dodać proszek do pieczenia, sodę, cynamon i sól, wymieszać. Przesypać do miski z marchewką i delikatnie połączyć wszystkie składniki.

Ciasto wyłożyć do formy o średnicy 24 cm wyłożonej papierem do pieczenia. Piec przez 1 godzinę lub do suchego patyczka.


Ubić serek razem z miękkim masłem i cukrem pudrem. Włożyć na kilkanaście minut do lodówki.

Dobrze wystudzone ciasto przekroić poziomo na 2 części. Spód posmarować 1/3 ilości polewy.

Przykryć drugą częścią ciasta i rozsmarować resztę polewy. Udekorować orzechami.

|===

[.text-center]
== Zdjęcia
