= Ciasto marchewkowe  +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: 1,5 h
* 20 porcji
* https://www.kwestiasmaku.com/desery/ciasta/ciasto_marchewkowe/przepis.html[link do 藕r贸da przepisu]

== Skadniki
* 2 jajka
* 200 g drobnego cukru lub cukru pudru
* 150 ml oleju rolinnego
* 200 g drobno startej marchewki
* 50 g posiekanych orzech贸w woskich lub pekan + do dekoracji
* 75 g drobno pokrojonego ananasa (wie偶ego lub z puszki) lub jabka
* 50 g wi贸rk贸w kokosowych
* 200 g mki
* 1/2 y偶eczki proszku do pieczenia
* po 1 y偶eczce sody i cynamonu
* szczypta soli

=== Polewa:

* 125 g kremowego serka np. Tw贸j Smak, Philadelphia
* 50 g masa (mikkiego)
* 100 g cukru pudru

|
== Przygotowanie

Jajka ociepli w temperaturze pokojowej. Ubi je do podwojenia objtoci. Doda cukier i dalej ubija a偶 masa bdzie gadka i puszysta. Wci偶 ubijajc na wysokich obrotach, dolewa cigym, cieniutkim strumieniem olej.

Doda marchewk, ananasa, orzechy, wi贸rki kokosowe i delikatnie wymiesza. Piekarnik nagrza do 150 stopni C.

Do osobnej miski przesia mk, doda proszek do pieczenia, sod, cynamon i s贸l, wymiesza. Przesypa do miski z marchewk i delikatnie poczy wszystkie skadniki.

Ciasto wyo偶y do formy o rednicy 24 cm wyo偶onej papierem do pieczenia. Piec przez 1 godzin lub do suchego patyczka.


Ubi serek razem z mikkim masem i cukrem pudrem. Wo偶y na kilkanacie minut do lod贸wki.

Dobrze wystudzone ciasto przekroi poziomo na 2 czci. Sp贸d posmarowa 1/3 iloci polewy.

Przykry drug czci ciasta i rozsmarowa reszt polewy. Udekorowa orzechami.

|===

[.text-center]
== Zdjcia
