= Ciasto porzeczkowiec

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 1 godzina
* ok. 30 porcji
* https://www.kwestiasmaku.com/przepis/ciasto-porzeczkowiec[link do źródła przepisu]

== Składniki
* 3/4 szklanki oleju roślinnego
* 1/2 szklanki wody
* 1 szklanka cukru
* 3 łyżki kakao

* 5 jajek
* 1/2 szklanki cukru
* 1 i 1/2 szklanki mąki
* 1 łyżeczka proszku do pieczenia
* 1 łyżeczka sody oczyszczonej

* 200 g masła
* 1/2 szklanki cukru pudru
* 500 g twarogu tłustego (klinki), niezmielone

* 300 g dżemu porzeczkowego
* ok. 2/3 szklanki nasączenia*

* 500 ml śmietanki do deserów 36% lub 30% (b. zimna)
* 3 łyżki cukru pudru
* 1 śmietan-fix
* gorzkie kakao lub starta ciemna czekolada

|
== Przygotowanie

Do garnka wlać olej i wodę, dodać cukier oraz kakao. Wymieszać i zagotować. Przelać do czystego naczynia i całkowicie ostudzić.

Piekarnik nagrzać do 180 stopni C. Przygotować formę do pieczenia o wymiarach ok. 23 cm x 35 cm i w razie potrzeby wyłożyć ją papierem do pieczenia.

Rozdzielić białka od żółtek, ogrzać w temp. pokojowej. Białka ubić z cukrem na sztywną pianę, następnie dodawać stopniowo dodawać żółtka cały czas ubijając.

Do ubitych jajek dodać ostudzoną masę kakaową i delikatnie wymieszać szpatułką. Po masy przesiać mąkę wymieszaną z proszkiem do pieczenia oraz odą. Całość połączyć delikatnie mieszając szpatułką.

Wyłożyć do formy i wstawić do nagrzanego piekarnika. Piec przez ok. 30 minut (do suchego patyczka). Wyjąć i ostudzić.

Masło pokroić w kostkę i zostawić na ok. 10 minut do ocieplenia. Następnie ubić na puszysto z cukrem pudrem. Dodać twaróg i miksować na średnich obrotach miksera przez ok. 1 minuty do połączenia składników.

Ostudzone ciasto czekoladowe przekroić na 2 blaty.

Pierwszy, dolny blat skropić połową nasączenia, potem wyłożyć połowę dżemu, następnie całą masę twarogową i przykryć górnym blatem (blat najlepiej przenosić na podkładce). Skropić go resztą nasączenia i posmarować resztą dżemu.

Schłodzoną śmietankę ubić z cukrem pudrem. Dodać śmietan-fix i zmiksować. Wyłożyć na wierzch ciasta, posypać kakao lub startą czekoladą.

Wstawić do lodówki na około godzinę, ale najlepiej na noc.

*  likieru amaretto lub sangrii lub czerwonego wina słodkiego lub posłodzonego wytrawnego (lub herbaty w wersji bezalkoholowej)

|===

[.text-center]
== Zdjęcia
