= Ciasto drożdżowe ze śliwkami

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 2 h
* 20 porcji
* https://ilovebake.pl/przepis/ciasto-drozdzowe-ze-sliwkami [link do źródła przepisu]

== Składniki

=== Składniki na ciasto drożdżowe:

* 4 szklanki mąki tortowej
* 25 g suchych lub 50 g drożdży świeżych
* 1 szklanka mleka, ciepłego
* 1 szklanka cukru
* 200 g masła lub margaryny
* 4 jajka
* 1/3 szklanki oleju

=== Składniki na kruszonkę:

* 150 g mąki tortowej
* 50 g cukru
* 125 g masła lub margaryny, zimnej

=== Dodatkowo:

* ok. 500 g śliwek najlepiej węgierek

|
== Przygotowanie

Wszystkie składniki na ciasto powinny być w temp. pokojowej. Jeśli używamy drożdży świeżych należy wcześniej wykonać zaczyn.

Mąkę przesiewamy do dużej miski, dodajemy suche drożdże lub zaczyn ze świeżych. Wlewamy ciepłe mleko, cukier, jajka i mieszamy najlepiej dużą łyżką drewnianą. Następnie dodajemy masło o temp. pokojowej pokrojone na kawałki i wyrabiamy ciasto. Na początku nie będzie chciało się połączyć, ale z czasem zacznie być jednolite. Na koniec dłonie zwilżamy olejem i ponownie wyrabiamy, aż do wykorzystania całego tłuszczu. Wyrobione ciasto formujemy w kulę, wkładamy do miski, owijamy folią i zostawiamy na 1,5 godz do wyrośnięcia.
Wszystkie składniki na kruszonkę łączymy, aż powstaną grudki. Śliwki kroimy i pozbywamy się pestek.

Formę o wym. 24x35 cm wykładamy papierem do pieczenia. Przekładamy wyrośnięte ciasto, wyrównujemy. Układamy śliwki, jedną obok drugiej miąższem do góry. Obsypujemy kruszonką i owijamy folią, zostawiamy na ok. 30 min do napuszenia. Pieczemy w temp. 180 C przez ok. 50 min do zarumienienia wierzchu.

|===

[.text-center]
== Zdjęcia
