= Jabłecznik 🌱 +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++
:imagesdir: /Recipes/static/images

[.recipe-hero]
[.card-image-placeholder]
Brak zdjęcia przepisu 🍲

[.back-to-home-wrapper]
link:../../index.html[← Wróć do przepisów, role="back-to-home-btn"]

[.recipe-details]
* 🕒 czas przygotowania: 1 godzina
* 👥 4 porcje
* 🔗 Przepis z zeszytu mamy

[.recipe-columns]
== Składniki
* 1 kg mąki (0,70)
* 1 kostka palmy
* ½ kg cukru
* 6 jaj
* 2 łyżeczki proszku
* 2 kg jabłek

== Przygotowanie

Przygotowanie ciasta rozpoczynamy od zrobienia bazy kruchej, w tym celu na stolnicę przesiewamy mąkę (zgodnie z notatką około 700 g) wymieszaną z proszkiem do pieczenia, dodajemy posiekaną na mniejsze kawałki zimną „Palmę” i szybko rozcieramy składniki w palcach. Następnie oddzielamy żółtka od białek i do maślanej kruszonki dodajemy same żółtka oraz połowę odmierzonego cukru, po czym sprawnie zagniatamy jednolite ciasto, dzielimy je na dwie części (jedną nieco większą na spód) i chowamy do lodówki do schłodzenia. W międzyczasie obieramy jabłka, ścieramy je na tarce o grubych oczkach i opcjonalnie odciskamy z nadmiaru soku, a z pozostałych białek i reszty cukru ubijamy w osobnym naczyniu sztywną, lśniącą pianę. Większą część schłodzonego ciasta rozwałkowujemy lub wylepiamy nią dno przygotowanej formy do pieczenia, wykładamy równomiernie warstwę jabłek, na nich rozprowadzamy ubitą pianę z białek, a na sam wierzch ścieramy na tarce lub kruszymy drugą część ciasta. Tak przygotowany jabłecznik wstawiamy do piekarnika nagrzanego do 180°C i pieczemy przez około 45-50 minut, aż góra ładnie się zrumieni.

[.recipe-gallery]
== Zdjęcia

[.gallery-grid]
// Tutaj pojawią się zdjęcia
