= Kokosowy jabecznik  +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: 45 min
* 20 porcji
* https://mojewypieki.com/przepis/kokosowy-jablecznik[link do 藕r贸da przepisu]

== Skadniki
* 225 g mki pszennej
* 120 g masa, zimnego
* 30 g smalcu, zimnego
* 1/2 y偶eczki proszku do pieczenia
* 2 y偶ki cukru pudru
* 3 偶贸tka (z du偶ych jajek)

=== Nadzienie jabkowe:

* 1,3 kg jabek, jdrnych i kwanych
* 1 y偶eczka pasty z wanilii lub ziarenka z laski wanilii
* 2 y偶ki cukru
* sok wycinity z 1 maej cytryny
* 1,5 y偶ki skrobi ziemniaczanej

=== Kokosowa beza:

* 3 biaka (z du偶ych jajek)
* szczypta soli
* 150 g drobnego cukru do wypiek贸w
* 100 g wi贸rk贸w kokosowych

|
== Przygotowanie

Mk i proszek do pieczenia przesia, doda maso i smalec, posieka szybko no偶em do momentu, kiedy ciasto bdzie przypomina kruszonk. Doda 偶贸tka, cukier i szybko zagnie (mo偶na r贸wnie偶 zmiksowa w malakserze). Jeli ciasto bdzie zbyt sypkie, doda 1 y偶k zimnej wody. Uformowa kul, spaszczy, zawin w foli spo偶ywcz, zamrozi (mo偶na wykona dzie wczeniej).

Blach o wymiarach 34 x 23 cm wysmarowa masem, wyo偶y papierem do pieczenia. Na sp贸d zetrze na tarce kruche ciasto i lekko przyklepa doni. Podpiec na zoty kolor w temperaturze 180潞C przez okoo 18 minut.

Jabka obra i usun gniazda nasienne. Pokroi na cienkie plasterki bezporednio do garnka. Doda cukier, sok z cytryny, wanili i wymiesza. Podgrzewa, co pewien czas mieszajc, a偶 do lekkiego podduszenia jabek i odparowania sok贸w. Na sam koniec opr贸szy przesian skrobi ziemniaczan, wymiesza.

W misie miksera ubi biaka ze szczypt soli na sztywn pian. Stopniowo, y偶ka po y偶ce, dodawa cukier, cay czas ubijajc. Powinna powsta gsta, byszczca piana bezowa. Doda wi贸rki kokosowe i zmiksowa.

Na podpieczony sp贸d wyo偶y podduszone jabka, wyr贸wna. Bez kokosow wyo偶y na warstw jabek, wyr贸wna.

Piec w temperaturze 180潞C przez okoo 35  - 40 minut. Beza powinna by chrupica i sztywna, nie 'gumowa' przy dotyku i mikka. Upieczone ciasto wyj, wystudzi. Kokosowy jabecznik kroi na kwadraty i podawa.

|===

[.text-center]
== Zdjcia
