= Kokosowy jabłecznik

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 45 min
* 20 porcji
* https://mojewypieki.com/przepis/kokosowy-jablecznik[link do źródła przepisu]

== Składniki
* 225 g mąki pszennej
* 120 g masła, zimnego
* 30 g smalcu, zimnego
* 1/2 łyżeczki proszku do pieczenia
* 2 łyżki cukru pudru
* 3 żółtka (z dużych jajek)

=== Nadzienie jabłkowe:

* 1,3 kg jabłek, jędrnych i kwaśnych
* 1 łyżeczka pasty z wanilii lub ziarenka z laski wanilii
* 2 łyżki cukru
* sok wyciśnięty z 1 małej cytryny
* 1,5 łyżki skrobi ziemniaczanej

=== Kokosowa beza:

* 3 białka (z dużych jajek)
* szczypta soli
* 150 g drobnego cukru do wypieków
* 100 g wiórków kokosowych

|
== Przygotowanie

Mąkę i proszek do pieczenia przesiać, dodać masło i smalec, posiekać szybko nożem do momentu, kiedy ciasto będzie przypominać kruszonkę. Dodać żółtka, cukier i szybko zagnieść (można również zmiksować w malakserze). Jeśli ciasto będzie zbyt sypkie, dodać 1 łyżkę zimnej wody. Uformować kulę, spłaszczyć, zawinąć w folię spożywczą, zamrozić (można wykonać dzień wcześniej).

Blachę o wymiarach 34 x 23 cm wysmarować masłem, wyłożyć papierem do pieczenia. Na spód zetrzeć na tarce kruche ciasto i lekko przyklepać dłonią. Podpiec na złoty kolor w temperaturze 180ºC przez około 18 minut.

Jabłka obrać i usunąć gniazda nasienne. Pokroić na cienkie plasterki bezpośrednio do garnka. Dodać cukier, sok z cytryny, wanilię i wymieszać. Podgrzewać, co pewien czas mieszając, aż do lekkiego podduszenia jabłek i odparowania soków. Na sam koniec oprószyć przesianą skrobią ziemniaczaną, wymieszać.

W misie miksera ubić białka ze szczyptą soli na sztywną pianę. Stopniowo, łyżka po łyżce, dodawać cukier, cały czas ubijając. Powinna powstać gęsta, błyszcząca piana bezowa. Dodać wiórki kokosowe i zmiksować.

Na podpieczony spód wyłożyć podduszone jabłka, wyrównać. Bezę kokosową wyłożyć na warstwę jabłek, wyrównać.

Piec w temperaturze 180ºC przez około 35  - 40 minut. Beza powinna być chrupiąca i sztywna, nie 'gumowa' przy dotyku i miękka. Upieczone ciasto wyjąć, wystudzić. Kokosowy jabłecznik kroić na kwadraty i podawać.

|===

[.text-center]
== Zdjęcia
