= Metrowiec 🌱
:imagesdir: /Recipes/static/images

++++
<div class="recipe-header-actions">
    <a href="../../index.html" class="back-to-home-btn">← Wróć do przepisów</a>
    <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>
</div>
++++

[.recipe-hero]
[.card-image-placeholder]
Brak zdjęcia przepisu 🍲

[.recipe-details]
* 🕒 czas gotowania: 1 godzina
* 👥 4 porcje
* 🔗 Przepis z zeszytu mamy

[.recipe-columns]
== Składniki

* 8 jaj
* 2 szklanki. cukru
* 16 łyżek przegotowanej zimnej wody (małe)
* ½ szklanki. oleju
* 3 szklanki. mąki
* 3 łyżeczki proszku do pieczenia
* ½ kostka. palmy, 4 łyżki kakao, 4 łyżki wody, 4 łyżki cukru - zagotować.
* ½ kostka. masła rośl.
* 2 łyżki cukru
* 2 łyżki kakao

== Przygotowanie

=== Ciasto:

Jaja ubić z cukrem, dodać mąkę, proszek, wodę, oliwę. Podzielić ciasto na dwie części - do jednej dodać 2 łyżki kakao. Piec ok. 45 min.

=== Krem:

Zagotować z 1 ½ szklanki. mleka, dodać 4-5 łyżek mąki, 7 łyżeczek cukru, zapach waniliowy. Następnie ukręcić kostkę masła i dodać ostudzony tzw. budyń.

=== Polewa: (przep. Oli)

Rozgrzać, nie doprowadzić do wrzenia.

Po ostudzeniu dodać roztrzepane jajko. Kręcić pałką aż polewa będzie szklista.

[.recipe-gallery]
== Zdjęcia

[.gallery-grid]
// Tutaj pojawią się zdjęcia
