= Muffins (Pasteis de Belém) 🌱 +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++
:imagesdir: /Recipes/static/images

[.recipe-hero]
[.card-image-placeholder]
Brak zdjęcia przepisu 🍲

[.recipe-details]
* 🕒 czas gotowania: 1 godzina
* 👥 4 porcje
* 🔗 Przepis z zeszytu mamy

[.recipe-columns]
== Składniki
* 235 ml milk
* 25 g cornstarch
* 0,5 vanilla bean
* 200 g white sugar
* 6 egg yolks
* 1 (17,5 ounce) package frozen puff pastry, thawed

== Przygotowanie

Preheat oven to 375 degrees F (190 degrees C). Lightly grease 12 muffin cups and line bottom and sides with puff pastry.

In a saucepan combine milk, cornstarch, sugar and vanilla. Cook, stirring constantly until mixture thickens. Place egg yolks in a medium bowl. Slowly whisk 1/2 cup of hot milk mixture into egg yolks. Gradually add egg yolk mixture back to remaining milk mixture, whisking constantly. Cook, stirring constantly, for 5 minutes or until thickened. Remove vanilla bean.

Fill pastry-lined muffin cup with mixture and bake in preheated oven for 20 minutes or until crust is golden brown and filling is lightly browned on top.

[.recipe-gallery]
== Zdjęcia

[.gallery-grid]
// Tutaj pojawią się zdjęcia
