= Murzynek z wiśniami

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 1 h
* 20 porcji
* https://www.kwestiasmaku.com/desery/ciasta/murzynek_z_czekolada_wisniami/przepis.html[link do źródła przepisu]

== Składniki
* 200 g masła
* 1 szklanka (200 g) cukru
* 1 opakowanie cukru wanilinowego lub 2 łyżeczki ekstraktu z wanilii
* opcjonalnie: 3 łyżki kawy zbożowej (lub 3 łyżeczki kawy rozpuszczalnej)
* 100 g gorzkiej czekolady
* 3 jajka, oddzielnie żółtka od białek
* 1 i 1/2 szklanki (200 g) mąki pszennej
* 2 łyżeczki proszku do pieczenia
* 300 g wiśni (świeżych lub mrożonych, z kompotu lub syropu) + 7 łyżek soku z wiśni lub kompotu
* 3 łyżki mąki ziemniaczanej lub pszennej do obtoczenia wiśni
* 50 - 100 g czekolady

|
== Przygotowanie

Jeśli używamy mrożonych wiśni należy je wcześniej rozmrozić na sitku i osuszyć z soku. Sok zachować. Wiśnie z kompotu odcedzić, zachować część kompotu.

Tortownicę o średnicy ok. 24-25 cm posmarować masłem i wyłożyć papierem do pieczenia. Piekarnik nagrzać do 180 stopni.

Do garnka włożyć masło, roztopić na małym ogniu mieszając. Dodać cukier, cukier wanilinowy oraz kawę zbożową i wymieszać. Odstawić z ognia, dodać czekoladę i mieszając roztopić. Dodać 7 łyżek soku z wiśni i wymieszać. Masę ostudzić (może być lekko ciepła). Odłożyć pół szklanki masy na polewę. Do reszty dodać żółtka i wymieszać, odstawić.

Mąkę przesiać do czystej miski razem z proszkiem do pieczenia. Dodać ją do masy czekoladowej w 3 partiach, za każdym razem dokładnie mieszając łyżką. Białka ubić na sztywną pianę i dodać do masy, delikatnie wymieszać łyżką.

Masę wyłożyć do tortownicy. Osuszone wiśnie obtoczyć w mące ziemniaczanej i wyłożyć na powierzchni ciasta. Część wiśni powciskać do środka ciasta. Wstawić do nagrzanego piekarnika i piec przez około 40 minut. Wyjąć z piekarnika.

Do odłożonej masy na polewę dodać roztopioną czekoladę i wymieszać. Rozprowadzić po cieście.

|===

[.text-center]
== Zdjęcia
