:back-btn: +++<a href="../../index.html" class="back-to-home-btn">← Wróć do przepisów</a>+++
:toggle-switch: +++<label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++
= {back-btn} Oponki 🌱 {toggle-switch}
:imagesdir: /Recipes/static/images

[.recipe-hero]
[.card-image-placeholder]
Brak zdjęcia przepisu 🍲

[.recipe-details]
* 🕒 czas gotowania: 1 godzina
* 👥 4 porcje
* 🔗 Przepis z zeszytu mamy

[.recipe-columns]
== Składniki

* ½ kg twarogu
* ½ kg mąki
* ½ szklanki. cukru
* 4 żółtka
* 1 łyżecz sody oczysz
* ½ łyżki śmietany
* 200 g śmietanki 12%
* 50-100 g jogurtu greckiego

== Przygotowanie

Twaróg przepuścić przez praskę, po czym na stolnicy lub w misce połączyć go z mąką, cukrem, śmietaną, śmietanką 12%, jogurtem greckim, sodą oczyszczoną, odrobiną octu oraz żółtkami. Wszystkie składniki szybko zagnieść na jednolite, miękkie ciasto. Gotowe ciasto rozwałkować na grubość około 1-1,5 cm, szklanką wycinać duże krążki, a mniejszym kieliszkiem robić w środku dziurki. Oponki smażyć partiami na mocno rozgrzanym, głębokim oleju z obu stron na złoty kolor, a po usmażeniu odsączyć z nadmiaru tłuszczu na papierowym ręczniku.

[.recipe-gallery]
== Zdjęcia

[.gallery-grid]
// Tutaj pojawią się zdjęcia
