= Oponki 🌱 +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++
:imagesdir: /Recipes/static/images

[.recipe-hero]
[.card-image-placeholder]
Brak zdjęcia przepisu 🍲

[.recipe-details]
* 🕒 czas gotowania: 1 godzina
* 👥 4 porcje
* 🔗 Przepis z zeszytu mamy

[.recipe-columns]
== Składniki
* 1/2 kg twarogu
* 1/2 kg mąki
* 1/2 szklanki. cukru
* 4 żółtka
* 1 łyżecz sody oczysz
* 1/2 łyżki śmietany
* 200 g śmietanki 12%
* 50-100 g jogurtu greckiego

== Przygotowanie

Twaróg przepuścić przez praskę, po czym na stolnicy lub w misce połączyć go z mąką, cukrem, śmietaną, śmietanką 12%, jogurtem greckim, sodą oczyszczoną, odrobiną octu oraz żółtkami. Wszystkie składniki szybko zagnieść na jednolite, miękkie ciasto. Gotowe ciasto rozwałkować na grubość około 1-1,5 cm, szklanką wycinać duże krążki, a mniejszym kieliszkiem robić w środku dziurki. Oponki smażyć partiami na mocno rozgrzanym, głębokim oleju z obu stron na złoty kolor, a po usmażeniu odsączyć z nadmiaru tłuszczu na papierowym ręczniku.

[.recipe-gallery]
== Zdjęcia

[.gallery-grid]
// Tutaj pojawią się zdjęcia
