= Pierniczki

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły

* czas przygotowania: 30 minut + min. 10 godzin na leżakowanie ciasta
* czas pieczenia: 12 minut
* źródło przepisu: zajęcia babci

== Składniki

* 500 g mąki
* 150 g masła
* 150 g drobnego cukru
* 200g płynnego miodu
* 4 żółtka
* 150 g śmietany kwaśnej 18%
* 2 łyżeczki sody oczyszczonej
* łyżeczka kakao
* 20-30 g przyprawy korzennej

== Przygotowanie

W rondelku umieść 150 gramów prawdziwego masła. Wlej również 200 gramów dobrej jakości płynnego miodu. Wsyp łyżeczkę kakao oraz całą przyprawę korzenną. Rondelek umieść na palniku i ustaw małą moc. Całość podgrzewaj kilka minut do całkowitego roztopienia się masła. Słodki krem wymieszaj dokładnie. Jeśli składniki się zagotują, to nic nie szkodzi. Rondelek ze słodkim, korzennym płynem odstaw na bok do przestudzenia.

Kwaśną śmietanę 18% wymieszaj z dwiema łyżeczkami sody oczyszczonej. Śmietanę możesz zamienić na gęsty i kremowy jogurt naturalny.

W dużej misce umieść 500 gramów mąki pszennej. Dodaj też cztery żółtka średniej wielkości jajek i śmietanę wymieszaną z sodą oczyszczoną. Białka z jajek możesz wykorzystać do zrobienia bezy.

Do miski z mąką, żółtkami i śmietaną z sodą dodaj też 150 gramów drobnego cukru. Możesz też użyć cukru trzcinowego. Na koniec wlej przestudzony, słodki płyn korzenny. Zawartość rondelka może być ciepła, ale nie gorąca.

Ciasto na pierniczki świąteczne wymieszaj dokładnie łyżką. Będzie gęste i klejące, jednak po umieszczeniu go w lodówce, zrobi się idealnie plastyczne. Gotowe ciasto przykryj folią i odłóż do lodówki na minimum 10 godzin, a najlepiej na całą noc.

Po nocy spędzonej w lodówce wyjmij ciasto z miski. Będzie miało strukturę plasteliny. Dłonie oprósz mąką, a z ciasta uformuj kulę. Ciasto umieść na stolnicy lub na czystym blacie. Blat trzeba dodatkowo oprószyć mąką. Najlepiej ciasto podzielić sobie na kilka mniejszych kul wygodnych do wałkowania na placek.

Ciasto rozwałkuj na placek grubości minimum 6 mm. Możesz śmiało wycinać pierniczki grube nawet na 1 cm. Przy pomocy dowolnej foremki ze świątecznym wzorem wycinaj pierniczki.

Blaszkę wyłóż papierem do pieczenia. Wycięte pierniczki układaj obok siebie na blaszce. Między pierniczkami zachowaj spore odległości, ponieważ pierniczki rosną w piekarniku. Po wycięciu pierwszych pierniczków zagniataj resztki ciasta, dodawaj kawałek świeżego i ponownie wałkuj na placek. Wycinaj kolejną porcję pierniczków. W ten sposób wykorzystaj całe ciasto.

Każdą partię pierniczków piecz na środkowej półce w piekarniku nagrzanym do 170 stopni. Pierniczki piecz 12 minut. Po upieczeniu można je od razu wyjmować z piekarnika i układać na kratce do przestudzenia. Pierniczki świąteczne stygną bardzo szybko.

== Zdjęcia

|===