= Placek z jabłkami 🌱
:imagesdir: /Recipes/static/images

++++
<div class="recipe-header-actions">
    <a href="../../index.html" class="back-to-home-btn">← Wróć do przepisów</a>
    <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>
</div>
++++

[.recipe-hero]
[.card-image-placeholder]
Brak zdjęcia przepisu 🍲

[.recipe-details]
* 🕒 czas przygotowania: 1 godzina
* 👥 4 porcje
* 🔗 Przepis z zeszytu mamy

[.recipe-columns]
== Składniki

* mąka — 0,15
* cukier — 0,20
* m. ziemn — 0,20
* palma — 0,25
* proszek — 1 łyż.
* c. waniliowy — 1
* jabłka — 0,30

== Przygotowanie

Przygotowanie placka rozpoczynamy od utarcia miękkiej „Palmy” z cukrem oraz cukrem waniliowym na puszystą, jasną masę, do której następnie – cały czas miksując – wbijamy kolejno jajka (tradycyjnie do tej ilości składników dodaje się około 4–5 jaj). W osobnym naczyniu łączymy ze sobą mąkę pszenną, mączkę ziemniaczaną oraz łyżeczkę proszku do pieczenia, a następnie stopniowo przesiewamy suche składniki do maślanej masy, delikatnie mieszając całość szpatułką do uzyskania gładkiego ciasta. Gotowe, puszyste ciasto przekładamy do wyłożonej papierem do pieczenia formy i równomiernie wyrównujemy jego powierzchnię. Na wierzchu gęsto układamy obrane i pokrojone w cząstki lub plasterki jabłka, lekko wciskając je w masę. Całość wstawiamy do piekarnika nagrzanego do 180°C i pieczemy przez około 40-45 minut, aż ciasto ładnie wyrośnie i się zrumieni, a po ostudzeniu opcjonalnie oprószamy wierzch cukrem pudrem.

[.recipe-gallery]
== Zdjęcia

[.gallery-grid]
// Tutaj pojawią się zdjęcia
