= Racuchy z jabłkami 🌱
:imagesdir: /Recipes/static/images

++++
<div class="recipe-header-actions">
    <a href="../../index.html" class="back-to-home-btn">← Wróć do przepisów</a>
    <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>
</div>
++++

[.recipe-hero]
[.card-image-placeholder]
Brak zdjęcia przepisu 🍲

[.recipe-details]
* 🕒 czas przygotowania: 35 minut
* 👥 4 porcje
* 🔗 https://www.kwestiasmaku.com/przepis/racuchy-z-jablkami[link do źródła przepisu]

[.recipe-columns]
== Składniki

* 2 jabłka
* 200 ml mleka (niepełna 1 szklanka)
* 1 jajko
* 150 g (1 szklanka) mąki pszennej
* 1 łyżka cukru wanilinowego
* 1 łyżeczka cukru
* ½ łyżeczki proszku do pieczenia
* do smażenia: np. masło klarowane, olej kokosowy, inny olej roślinny

== Przygotowanie

Mąkę przesiać do miski, dodać cukier wanilinowy, cukier oraz proszek do pieczenia, wymieszać.

Dodać mleko i jajko i wymieszać składniki rózgą na jednolitą masę bez grudek.

Jabłka obrać, pokroić na ćwiartki, usunąć gniazda nasienne, ćwiartki przekroić wzdłuż na pół a później jeszcze na poprzeczne plasterki. Włożyć do ciasta i wymieszać.

Wykładać po około łyżce ciasta i po 3 plasterki jabłek na 1 placka na rozgrzany tłuszcz na patelni i smażyć przez około 1,5 minuty na złoty kolor. Przewrócić na drugą stronę i powtórzyć smażenie.

Podawać z cukrem pudrem, dżemem wiśniowym itp.

[.recipe-gallery]
== Zdjęcia

[.gallery-grid]
// Tutaj pojawią się zdjęcia
