= Racuchy z jabkami  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 35 minut
* 4 porcje
* https://www.kwestiasmaku.com/przepis/racuchy-z-jablkami[link do 藕r贸da przepisu]

== Skadniki

* 2 jabka
* 200 ml mleka (niepena 1 szklanka)
* 1 jajko
* 150 g (1 szklanka) mki pszennej
* 1 y偶ka cukru wanilinowego
* 1 y偶eczka cukru
* 1/2 y偶eczki proszku do pieczenia
* do sma偶enia: np. maso klarowane, olej kokosowy, inny olej rolinny

|
== Przygotowanie

Mk przesia do miski, doda cukier wanilinowy, cukier oraz proszek do pieczenia, wymiesza.

Doda mleko i jajko i wymiesza skadniki r贸zg na jednolit mas bez grudek.

Jabka obra, pokroi na wiartki, usun gniazda nasienne, wiartki przekroi wzdu偶 na p贸 a p贸藕niej jeszcze na poprzeczne plasterki. Wo偶y do ciasta i wymiesza.

Wykada po okoo y偶ce ciasta i po 3 plasterki jabek na 1 placka na rozgrzany tuszcz na patelni i sma偶y przez okoo 1,5 minuty na zoty kolor. Przewr贸ci na drug stron i powt贸rzy sma偶enie.

Podawa z cukrem pudrem, d偶emem winiowym itp.

|===

[.text-center]
== Zdjcia

