= Racuchy z jabłkami

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 35 min
* 4 porcje
* https://www.kwestiasmaku.com/przepis/racuchy-z-jablkami[link do źródła przepisu]

== Składniki
* 2 jabłka
* 200 ml mleka (niepełna 1 szklanka)
* 1 jajko
* 150 g (1 szklanka) mąki pszennej
* 1 łyżka cukru wanilinowego
* 1 łyżeczka cukru
* 1/2 łyżeczki proszku do pieczenia
* do smażenia: np. masło klarowane, olej kokosowy, inny olej roślinny

|
== Przygotowanie
Mąkę przesiać do miski, dodać cukier wanilinowy, cukier oraz proszek do pieczenia, wymieszać.

Dodać mleko i jajko i wymieszać składniki rózgą na jednolitą masę bez grudek.

Jabłka obrać, pokroić na ćwiartki, usunąć gniazda nasienne, ćwiartki przekroić wzdłuż na pół a później jeszcze na poprzeczne plasterki. Włożyć do ciasta i wymieszać.

Wykładać po około łyżce ciasta i po 3 plasterki jabłek na 1 placka na rozgrzany tłuszcz na patelni i smażyć przez około 1,5 minuty na złoty kolor. Przewrócić na drugą stronę i powtórzyć smażenie.

Podawać z cukrem pudrem, dżemem wiśniowym itp.

|===

[.text-center]
== Zdjęcia

