= Rogaliki na szybko 🌱
:imagesdir: /Recipes/static/images

++++
<div class="recipe-header-actions">
    <a href="../../index.html" class="back-to-home-btn">← Wróć do przepisów</a>
    <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>
</div>
++++

[.recipe-hero]
[.card-image-placeholder]
Brak zdjęcia przepisu 🍲

[.recipe-details]
* 🕒 czas gotowania: 1 godzina
* 👥 4 porcje
* 🔗 Przepis z zeszytu mamy

[.recipe-columns]
== Składniki

* 1 ½ kg mąki
* 4 jaja
* 2 szk. mleka
* 1 ½ kostka tłuszczu
* 6 łyżek cukru
* kostka drożdży
* szczypta soli

== Przygotowanie

W ciepłym mleku rozpuścić drożdże z łyżką cukru i odrobiną mąki, odstawiając na kilka minut do zapracowania. Tłuszcz roztopić i lekko przestudzić. Do dużej miski przesiać resztę mąki, dodać jajka, pozostały cukier, szczyptę soli, wyrośnięty rozczyn oraz roztopiony tłuszcz, a następnie wyrobić gładkie i elastyczne ciasto. Ciasto od razu podzielić na mniejsze części, każdą rozwałkować na kształt koła i pokroić na trójkąty. Na szerszą część każdego trójkąta nałożyć ulubione nadzienie, zwijać formując rogaliki, układać na blaszce i piec w rozgrzanym piekarniku na złoty kolor.

[.recipe-gallery]
== Zdjęcia

[.gallery-grid]
// Tutaj pojawią się zdjęcia
