= Sernik z Sochaczewa 🌱 +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++
:imagesdir: /Recipes/static/images

[.recipe-hero]
[.card-image-placeholder]
Brak zdjęcia przepisu 🍲

[.back-to-home-wrapper]
link:../../index.html[← Wróć do przepisów, role="back-to-home-btn"]

[.recipe-details]
* 🕒 czas przygotowania: 1 godzina
* 👥 4 porcje
* 🔗 Przepis z zeszytu mamy

[.recipe-columns]
== Składniki
* 1 kg twarogu
* 1 kostka masła i palma
* 2 ugotowane ziemniaki
* 3 łyżki mączki ziemniaczanej (czubate)
* 2 łyżki cukru
* 8 jaj
* bakalie
* olejek

=== Spód
* 2 jajka
* mąka
* cukier
* szczypta proszku do pieczenia

== Przygotowanie

Zacząć od przygotowania spodu: 2 jajka utrzeć z cukrem, dodać mąkę wymieszaną ze szczyptą proszku do pieczenia i zagnieść gładkie, miękkie ciasto. Rozwałkować je lub wylepić nim dno formy wyłożonej papierem do pieczenia, po czym odstawić.

Twaróg oraz 2 ugotowane i ostudzone ziemniaki zmielić razem w maszynce przynajmniej dwukrotnie, aby masa była idealnie gładka. Białka z 8 jaj oddzielić od żółtek. Miękkie masło (lub margarynę) utrzeć w makutrze lub mikserem z 2 łyżkami cukru i żółtkami na puszystą masę. Stopniowo dodawać zmielony twaróg z ziemniakami, cały czas ucierając. Następnie wsypać mączkę ziemniaczaną, wlać ulubiony olejek zapachowy oraz dodać bakalie.

W osobnej, czystej misce ubić 8 białek na sztywną pianę. Dodać pianę do masy serowej i bardzo delikatnie wymieszać łopatką. Puszystą masę wylać na przygotowany wcześniej surowy spód. Wstawić do piekarnika nagrzanego do 180°C i piec przez 50 minut, aż wierzch pięknie się zezłoci. Po upieczeniu studzić przy lekko uchylonych drzwiach piekarnika.

[.recipe-gallery]
== Zdjęcia

[.gallery-grid]
// Tutaj pojawią się zdjęcia
