:back-btn: +++<a href="../../index.html" class="back-to-home-btn">← Wróć do przepisów</a>+++
:toggle-switch: +++<label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++
= {back-btn} Sernik 2 🌱 {toggle-switch}
:imagesdir: /Recipes/static/images

[.recipe-hero]
[.card-image-placeholder]
Brak zdjęcia przepisu 🍲

[.recipe-details]
* 🕒 czas przygotowania: 1 godzina
* 👥 4 porcje
* 🔗 Przepis z zeszytu mamy

[.recipe-columns]
== Składniki

* 1 ½ kg twarogu | 0,75 | 1 kg
* ¾ kg cukru | 1 ½ szk | 2
* 1 budyń żółty | ½ | ⅔
* 6 łyżek kaszy mannej | 3 | 4
* 1 kostka palmy | ½ | ⅔
* 10 dag rodzynek
* olejek migdałowy

== Przygotowanie

Przygotowanie sernika rozpoczynamy od zmielenia twarogu przynajmniej dwukrotnie, aby masa była idealnie gładka, oraz od rozpuszczenia i całkowitego ostudzenia kostki „Palmy”. Tradycyjnie do tej ilości sera oddzielamy żółtka od białek z około 6–8 jajek i w dużej misce ucieramy same żółtka z cukrem na puszysty, jasny kogel-mogel. Do utartych żółtek stopniowo, partiami dodajemy zmielony twaróg, cały czas delikatnie miksując, po czym wlewamy ostudzony płynny tłuszcz oraz kilka kropel olejku migdałowego. Następnie do masy wsypujemy suchy, żółty budyń oraz kaszę manną, które zapewnią odpowiednią zwartą strukturę sernika, a na koniec dorzucamy sparzone i odsączone rodzynki, dokładnie mieszając całość łyżką. W osobnym naczyniu ubijamy pozostałe białka na sztywną pianę i bardzo delikatnie, za pomocą szpatułki, łączymy ją z masą serową, wykonując powolne ruchy od dołu do góry. Gotową, puszystą masę wylewamy do formy wyłożonej papierem do pieczenia (lub spodem z kruchych ciasteczek) i pieczemy w piekarniku nagrzanym do 170-180°C przez około 60-70 minut, a po upieczeniu studzimy sernik przy lekko uchylonych drzwiach piekarnika, aby nie opadł.

[.recipe-gallery]
== Zdjęcia

[.gallery-grid]
// Tutaj pojawią się zdjęcia
