= Skyrnik  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 10 minut
* czas pieczenia: 1 godzina
* keks贸wka 10 x 30 cm
* https://aniagotuje.pl/przepis/skyrnik-z-morelami[link do 藕r贸da przepisu]

== Skadniki

* 800 g Skyru naturalnego
* 3 du偶e lub 4 mae jajka - do 200 g po rozbiciu
* 100 g cukru
* 1 saszetka budyniu waniliowego bez cukru - 40 g
* 250 g maych moreli - okoo 5 sztuk
* 1 paska y偶ka skrobi ziemniaczanej

|
== Przygotowanie

Zacznij ju偶 nagrzewa piekarnik do 170 stopni z opcj pieczenia g贸ra/d贸 lub ustaw 160 stopni z termoobiegiem.
W jednym naczyniu umie wszystkie skadniki na mas skyrnikow. Bdzie to: 800 gram贸w Skyru naturalnego; 3 du偶e lub 4 mae jajka; 100 gram贸w zwykego cukru; saszetka budyniu waniliowego lub mietankowego bez cukru o wadze okoo 40 gram贸w. Wszystko razem miksuj kr贸tko na niskich obrotach, tylko do momentu, gdy masa zrobi si jednolita.

Keks贸wk o wymiarach wewntrznych 10 x 30 cm wy贸偶 od rodka arkuszami papieru do pieczenia. Mas skyrnikow wylej do przygotowanej formy.

Mae, dojrzae i zdrowe morele umyj, osusz i podziel na p贸, a nastpnie usu pestki. Przed wyo偶eniem na mas po贸wek owoc贸w polecam posypa z wierzchu mas skyrnikow pask y偶k skrobi ziemniaczanej, proszku budyniowego lub nawet proszku kisielowego np. o smaku cytrynowym. Nastpnie delikatnie ukadaj po贸wki moreli - jedna obok drugiej, wypuk stron do skyrnika.
Form umie mniej wicej na rodkowej p贸ce (lub o pitro ni偶ej) w piekarniku nagrzanym do 170 stopni (pieczenie g贸ra/d贸). Skyrnik z morelami piecz pen godzin. Po wyczeniu piekarnika nie uchylaj drzwiczek pieca przynajmniej przez 10 minut. Potem uchyl je nieznacznie na 30 minut. Po tym czasie otw贸rz piekarnik i wyjmij skyrnik.

Przestudzony skyrnik umie w lod贸wce pod kloszem na minimum cztery godziny, a najlepiej na ca noc. Idealn struktur osiga bowiem po schodzeniu, jednak naprawd bardzo dobry jest jeszcze lekko ciepy. Skyrnik mo偶e pod koniec wyrosn, ale podczas studzenia pewnie lekko opadnie.

Upieczony i schodzony sernik ze skyru z morelami przechowuj w lod贸wce pod przykryciem. Trzymany w chodzie (6-10 stopni, w lod贸wce) wie偶o zachowa przynajmniej przez tydzie.

|===

[.text-center]
== Zdjcia
