= Szybki piernik  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: 45 min
* 2 niedu偶e pierniki
* https://mojewypieki.com/przepis/szybki-piernik[link do 藕r贸da przepisu]

== Skadniki
* 1 szklanka miodu
* 3/4 szklanki cukru
* 1 szklanka mleka
* 100 g masa
* 4 jajka, biaka i 偶贸tka osobno
* 3 szklanki (450 g) mki pszennej
* 1 y偶ka kakao
* 30 g przyprawy korzennej do piernika
* 1 y偶eczka cynamonu
* 1 y偶ka sody oczyszczonej
* opcjonalnie - p贸 szklanki dowolnych bakalii (posiekane orzechy, namoczone w rumie rodzynki itp.)

=== Do przeo偶enia:

* powida liwkowe, masa marcepanowa, itp.

=== Polewa czekoladowa (na 2 pierniki z przepisu):

* 100 ml mietany krem贸wki 30% lub 36%
* 100 g czekolady deserowej, posiekanej

|
== Przygotowanie
Wszystkie skadniki powinny by w temperaturze pokojowej.

Mi贸d, cukier, mleko, maso, przypraw korzenn i cynamon umieci w garnku i postawi na palniku. Podgrzewa, mieszajc, do rozpuszczenia si poszczeg贸lnych skadnik贸w i otrzymania gadkiej mieszanki. Zdj z palnika i lekko przestudzi.

Do wystudzonej mieszanki doda 偶贸tka, przesia mk pszenn, kakao i sod oczyszczon. Wymiesza r贸zg kuchenn tylko do poczenia si skadnik贸w. Powstanie gste ciasto piernikowe.W osobnym naczyniu ubi na sztywno biaka i wmiesza delikatnie do ciasta, w trzech turach. Doda bakalie, wymiesza.

Ciasto przeo偶y do dw贸ch keks贸wek o wymiarach 23,5 x 13 cm ka偶da (wczeniej wysmarowanych masem i opr贸szonych mk pszenn). Piec w temperaturze 170潞C przez okoo 50 - 60 minut lub do tzw. suchego patyczka. Wyj z piekarnika, wystudzi.Wystudzone pierniki przekroi na p贸 i przeo偶y powidami liwkowymi lub mas marcepanow. Pola polew czekoladow.

=== Polewa czekoladowa (na 2 pierniki z przepisu):

mietan krem贸wk podgrza w maym garnuszku. Zdj z palnika, doda posiekan czekolad, odstawi na 2 minuty. Po tym czasie wymiesza, do roztopienia czekolady i otrzymania gadkiej polewy. Poczeka do lekkiego zgstnienia, udekorowa pierniki.

|===

[.text-center]
== Zdjcia
