= Szybki piernik

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 45 min
* 2 nieduże pierniki
* https://mojewypieki.com/przepis/szybki-piernik[link do źródła przepisu]

== Składniki
* 1 szklanka miodu
* 3/4 szklanki cukru
* 1 szklanka mleka
* 100 g masła
* 4 jajka, białka i żółtka osobno
* 3 szklanki (450 g) mąki pszennej
* 1 łyżka kakao
* 30 g przyprawy korzennej do piernika
* 1 łyżeczka cynamonu
* 1 łyżka sody oczyszczonej
* opcjonalnie - pół szklanki dowolnych bakalii (posiekane orzechy, namoczone w rumie rodzynki itp.)

=== Do przełożenia:

* powidła śliwkowe, masa marcepanowa, itp.

=== Polewa czekoladowa (na 2 pierniki z przepisu):

* 100 ml śmietany kremówki 30% lub 36%
* 100 g czekolady deserowej, posiekanej

|
== Przygotowanie
Wszystkie składniki powinny być w temperaturze pokojowej.

Miód, cukier, mleko, masło, przyprawę korzenną i cynamon umieścić w garnku i postawić na palniku. Podgrzewać, mieszając, do rozpuszczenia się poszczególnych składników i otrzymania gładkiej mieszanki. Zdjąć z palnika i lekko przestudzić.

Do wystudzonej mieszanki dodać żółtka, przesiać mąkę pszenną, kakao i sodę oczyszczoną. Wymieszać rózgą kuchenną tylko do połączenia się składników. Powstanie gęste ciasto piernikowe.W osobnym naczyniu ubić na sztywno białka i wmieszać delikatnie do ciasta, w trzech turach. Dodać bakalie, wymieszać.

Ciasto przełożyć do dwóch keksówek o wymiarach 23,5 x 13 cm każda (wcześniej wysmarowanych masłem i oprószonych mąką pszenną). Piec w temperaturze 170ºC przez około 50 - 60 minut lub do tzw. suchego patyczka. Wyjąć z piekarnika, wystudzić.Wystudzone pierniki przekroić na pół i przełożyć powidłami śliwkowymi lub masą marcepanową. Polać polewą czekoladową.

=== Polewa czekoladowa (na 2 pierniki z przepisu):

Śmietanę kremówkę podgrzać w małym garnuszku. Zdjąć z palnika, dodać posiekaną czekoladę, odstawić na 2 minuty. Po tym czasie wymieszać, do roztopienia czekolady i otrzymania gładkiej polewy. Poczekać do lekkiego zgęstnienia, udekorować pierniki.

|===

[.text-center]
== Zdjęcia
