= Tort truskawkowy +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 45 min
* 20 porcji
* https://malacukierenka.pl/tort-truskawkowy.html[link do źródła przepisu]

== Składniki
=== Biszkopt:

* 6 jajek, osobno żółtka i białka
* 170g mąki (użyłam tortowej)
* 1 łyżeczka proszku do pieczenia
* 170g cukru
* 1/3 łyżeczki aromatu śmietankowego (polecam Dr.Oetkera)
* 2-3 krople aromatu waniliowego

=== Do nasączania:

* 150g truskawek, umytych i obranych
* 8-10 łyżek wody

=== Środek:

* 400g schłodzonej śmietanki kremówki 30% lub 36%
* 250g serka mascarpone
* 600-700g truskawek, umytych i obranych
* 6 łyżeczek żelatyny
* 2-3 krople aromatu śmietankowego
* 1 łyżeczka cukru wanilinowego
* 5-7 łyżek cukru pudru (dosładzamy do własnego gustu, ja dodałam 5 bardziej kopiastych łyżek cukru pudru)

=== Wykończenie:

* 250g schłodzonej śmietanki kremówki 30% lub 36%
* 250g serka mascarpone
* około 700-900g truskawek (to już zależy od tego, jak go ozdobimy, na koronę zużyjemy około 700g)
* 1-3 łyżki cukru pudru
* 2 łyżeczki cukru wanilinowego
* 1/2 opakowania galaretki truskawkowej (w proszku)

|
== Przygotowanie
=== Biszkopt:

Białka ubić na sztywno i ciągle mieszając, dodać stopniowo połowę cukru. Miksować, aż masa będzie gęsta i lśniąca.

W drugiej misce żółtka utrzeć z resztą cukru na jasną, kremową masę. Dodać aromaty, wymieszać.

Do białek dodać żółtka i wymieszać delikatnie łyżką.

Mąkę wymieszać z proszkiem do pieczenia i przesiać na jajeczną masę. Wymieszać delikatnie łyżką.

Ciasto przełożyć do tortownicy o średnicy 23-24cm wyłożonej papierem do pieczenia, tylko dno. Wyrównać i wstawić do piekarnika nagrzanego do 160°C na funkcji termoobieg (na funkcji góra-dół 180°C). Piec przez około 50 minut. Po wyjęciu z piekarnika odstawić do całkowitego ostygnięcia.

Ostygnięty biszkopt przekroić w poziomie dwa razy, otrzymamy więc 3 krążki ciasta.

Jeden krążek ciasta włożyć z powrotem do tortownicy (zamknąć obręcz).

Zmiksować na mus 150g truskawek, dodać około 8-10 łyżek wody, wymieszać. Ciasto w tortownicy nasączyć około 5-6 łyżkami truskawkowego musu.

=== Środek:

Żelatynę wsypać do rondelka i zalać około 1/3 szklanki zimnej wody, odstawić, aby napęczniała.

Zmiksować na mus 200g truskawek, resztę pokroić na kawałeczki.

Serek przełożyć do miski i rozmieszać go łyżką. Dodać stopniowo mus z truskawek, wymieszać łyżką na jednolitą masę. Dodać aromat, cukier wanilinowy, cukier puder wymieszać.

Śmietankę ubić na sztywno.

Żelatynę w rondelku podgrzać, cały czas mieszając, aż się rozpuści (nastąpi to bardzo szybko). Dodać ją stopniowo do serka, cały czas mieszając. Następnie dodać śmietanę, wymieszać łyżką. Na końcu dodać pokrojone truskawki, wymieszać.

Połowę kremu przełożyć do na ciasto w torownicy, wyrównać. Przykryć drugim krążkiem ciasta i nasączyć go jak poprzedni. Na wierzch wyłożyć resztę kremu, wyrównać. Ostatni krążek ciasta nasączyć musem truskawkowym z wodą i stroną, na którą nakładaliśmy mus położyć na krem. Ciasto wstawić na parę godzin do lodówki, aż stężeje (najlepiej zostawić na całą noc i wykończyć na drugi dzień).

=== Wykończenie: 

Galaretkę rozpuścić w około 1/4 szklanki gorącej wody.

Serek rozmieszać łyżką, dodać cukier puder, cukier wanilinowy i wymieszać.

Śmietankę ubić na sztywno, wymieszać z serkiem.

Tort truskawkowy wyjąć ostrożnie z tortownicy i położyć na paterze. Gotowym kremem posmarować bok i wierzch tortu. Truskawki na koronę obrać i przekroić w pionie 3 razy. Układać je okręgami na wierzchu ciasta, zaczynając od krawędzi toru. Następnie posmarować je delikatnie galaretką (będą ładnie błyszczały). Resztę truskawek przepołowić i ozdobić nimi dolną cześć toru, jak na zdjęciach.Udanych wypieków:)

|===

[.text-center]
== Zdjęcia
