= Winiowy paj  +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: 1 h
* 20 porcji
* https://mojewypieki.com/przepis/wisniowy-paj[link do 藕r贸da przepisu]

== Skadniki
* 300 g mki pszennej
* 200 g masa, w temperaturze pokojowej
* 120 g drobnego cukru do wypiek贸w
* 1 y偶eczka ekstraktu z migda贸w
* 700 g wini, wie偶ych lub mro偶onych*
* 80 g cukru
* 3 - 5 y偶ek mki ziemniaczanej (paska y偶ka o pojemnoci 15 ml)
* 3 y偶ki buki tartej lub zmielonych migda贸w
* cukier puder do opr贸szenia

|
== Przygotowanie
W naczyniu umieci mikkie maso, mk, cukier i ekstrakt z migda贸w. Wyrobi midzy palcami na kruszonk, odstawi.

Form o rednicy 23 - 24 cm wyo偶y papierem do pieczenia. Dno formy lekko wylepi poow kruszonki (nie wciskamy mocno w form, raczej wysypujemy i delikatnie przyklepujemy). Podpiec w temperaturze 180潞C przez okoo 15 minut na bladozoty kolor.Ponadto:Winie wydrylowa, wymiesza z cukrem i mk ziemniaczan.

Podpieczony sp贸d r贸wnomiernie posypa buk tart lub zmielonymi migdaami. Na wierzch wysypa winie, wyr贸wna. Na g贸r wini wysypa kruszonk.

Piec w temperaturze 180潞C przez 40 - 45 minut do zezocenia kruszonki. Wyj, wystudzi.Przed podaniem opr贸szy cukrem pudrem.* Winie mro偶one najpierw odmrozi na durszlaku, wikszym sitku lub rczniczku kuchennym.

|===

[.text-center]
== Zdjcia
