= Wiśniowy paj +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 1 h
* 20 porcji
* https://mojewypieki.com/przepis/wisniowy-paj[link do źródła przepisu]

== Składniki
* 300 g mąki pszennej
* 200 g masła, w temperaturze pokojowej
* 120 g drobnego cukru do wypieków
* 1 łyżeczka ekstraktu z migdałów
* 700 g wiśni, świeżych lub mrożonych*
* 80 g cukru
* 3 - 5 łyżek mąki ziemniaczanej (płaska łyżka o pojemności 15 ml)
* 3 łyżki bułki tartej lub zmielonych migdałów
* cukier puder do oprószenia

|
== Przygotowanie
W naczyniu umieścić miękkie masło, mąkę, cukier i ekstrakt z migdałów. Wyrobić między palcami na kruszonkę, odstawić.

Formę o średnicy 23 - 24 cm wyłożyć papierem do pieczenia. Dno formy lekko wylepić połową kruszonki (nie wciskamy mocno w formę, raczej wysypujemy i delikatnie przyklepujemy). Podpiec w temperaturze 180ºC przez około 15 minut na bladozłoty kolor.Ponadto:Wiśnie wydrylować, wymieszać z cukrem i mąką ziemniaczaną.

Podpieczony spód równomiernie posypać bułką tartą lub zmielonymi migdałami. Na wierzch wysypać wiśnie, wyrównać. Na górę wiśni wysypać kruszonkę.

Piec w temperaturze 180ºC przez 40 - 45 minut do zezłocenia kruszonki. Wyjąć, wystudzić.Przed podaniem oprószyć cukrem pudrem.* Wiśnie mrożone najpierw odmrozić na durszlaku, większym sitku lub ręczniczku kuchennym.

|===

[.text-center]
== Zdjęcia
