= Sałatka "Zimowy Przysmak" 🌱 +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++
:imagesdir: /Recipes/static/images

[.recipe-hero]
[.card-image-placeholder]
Brak zdjęcia przepisu 🍲

[.recipe-details]
* 🕒 czas przygotowania: 1 godzina
* 👥 4 porcje
* 🔗 Przepis z zeszytu mamy

[.recipe-columns]
== Składniki

== Przygotowanie
2 kg ogórków gruntowych (pokroić w plastry ze skórką)

1 kg papryki czerwonej (pokroić w paski)

0,5 kg marchwi (zetrzeć na tarce o grubych oczkach)

0,5 kg cebuli (pokroić w piórka)

Wszystkie warzywa przełożyć do dużej miski, posypać 2 łyżkami soli, dokładnie wymieszać i odstawić na 2-3 godziny, by puściły sok. Po tym czasie warzywa mocno odcisnąć.

Zalewa:

1,5 szklanki cukru

1 szklanka octu

1 szklanka oleju

1 łyżeczka pieprzu czarnego mielonego

Składniki zalewy wymieszać na zimno (nie gotować), aż cukier się rozpuści. Zalać odciśnięte warzywa, dokładnie wymieszać i pozostawić w misce na kolejne 3-4 godziny, aby smaki się przegryzły. Sałatkę nakładać ciasno do słoików, uzupełniając płynem pozostałym na dnie miski. Pasteryzować przez ok. 15 minut.

[.recipe-gallery]
== Zdjęcia

[.gallery-grid]
// Tutaj pojawią się zdjęcia
