= Saatka z ososiem i mozzarell  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: 20 min
* 2 porcje
* https://smakowitedania.com/2018/04/salatka-z-rukola-wedzonym-lososiem-i-mozzarella-film.html[link do 藕r贸da przepisu]

== Skadniki
* 100 g rukoli
* 10-12 pomidork贸w papryczkowych lub koktajlowych
* 1 czerwona papryka
* 125 g sera mozzarella
* 125 g wdzonego ososia

=== Sos:

* 3 y偶ki oliwy z oliwek
* 1 y偶ka miodu
* 2 y偶ki musztardy
* 1 y偶eczka soku z cytryny
* czarny pieprz
* s贸l

|
== Przygotowanie
Do maej miseczki wlewamy oliw z oliwek, dodajemy musztard, mi贸d oraz sok z cytryny, cao doprawiamy szczypt soli oraz czarnym pieprzem i wszystko dokadnie mieszamy.

Umyte pomidorki papryczkowe lub koktajlowe przekrawamy na p贸. Ser mozzarella kroimy w wiksz kostk. Czerwon papryk papryk kroimy w kostk. Wdzonego ososia kroimy w niewielkie kawaki ale niezbyt mae.
Na paskich talerzach ukadamy umyt i osuszon rukol, na rukoli umieszczamy po贸wki pomidork贸w, pokrojon mozzarell oraz papryk a na wierzchu saatki umieszczamy pokrojonego ososia.
Saatk polewamy przygotowanym sosem i wstawiamy na p贸 godziny do lod贸wki.

|===

[.text-center]
== Zdjcia
