= Sałatka warstwowa z szynką, jajkiem i serem żółtym 🐖
:imagesdir: /Recipes/static/images

++++
<div class="recipe-header-actions">
    <a href="../../index.html" class="back-to-home-btn">← Wróć do przepisów</a>
    <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>
</div>
++++

[.recipe-hero]
[.card-image-placeholder]
Brak zdjęcia przepisu 🍲

[.recipe-details]
* 🕒 czas przygotowania: 25 minut
* 🕒 czas gotowania: 25 minut
* 👥 4 porcje
* 🔗 https://www.kwestiasmaku.com/przepis/salatka-warstwowa-z-szynka-jajkiem-i-serem-zoltym[link do źródła przepisu]

[.recipe-columns]
== Składniki

* 5 jajek
* 1 puszka kukurydzy
* 1 puszka krojonego ananasa
* 150 g sera żółtego
* 150 g szynki konserwowej
* ⅔ szklanki majonezu + ⅓ szklanki gęstej śmietany lub jogurtu greckiego

== Przygotowanie

Jajka ugotować na twardo, obrać i posiekać na desce. Na sitku odcedzić kolejno kukurydzę, potem ananasa.

Na dnie salaterki o średnicy ok. 20 cm ułożyć selera, potem kukurydzę, startą na tarce o dużych oczkach lub pokrojoną w kosteczkę lub paseczki szynkę.

Wyłożyć majonez wymieszany ze śmietaną lub jogurtem, kawałki ananasa, starty na tarce ser żółty oraz jajka. Doprawić solą i pieprzem.

[.recipe-gallery]
== Zdjęcia

[.gallery-grid]
// Tutaj pojawią się zdjęcia
