= Sałatka grecka 🌱 +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++
:imagesdir: /Recipes/static/images

[.recipe-hero]
--
[.recipe-category-label]
Dania główne

[.card-image-placeholder]
Brak zdjęcia przepisu 🍲
--

[.recipe-details]
--
[.recipe-details-item]
🕒 czas przygotowania: 15 minut

[.recipe-details-item]
👥 4 porcje

[.recipe-details-item]
🔗 https://www.kwestiasmaku.com/dania_dla_dwojga/salatka_grecka/przepis.html[link do źródła przepisu]

--

[.recipe-columns]
--
[.recipe-column-box]
=== Składniki
* 2 pomidory
* 4 ogórki gruntowe lub 2 szklarniowe
* 1/2 czerwonej cebuli
* 1/2 szklanki czarnych oliwek
* 250 g oryginalnego, greckiego sera feta
* 4 łyżeczki suszonego oregano
* 4 łyżki oliwy extra vergine
* świeżo zmielony pieprz

|

[.recipe-column-box]
=== Przygotowanie
Pomidory pokroić na ćwiartki, usunąć szypułki, następnie pokroić na jeszcze mniejsze kawałki.

Ogórki obrać (można pozostawić miejscami paseczki zielonej skórki), przekroić wzdłuż na pół a następnie na grubsze półplasterki.

Cebulę cienko poszatkować. Oliwki przekroić na połówki.

Wszystkie składniki umieścić w jednej większej salaterce lub w 4 mniejszych, doprawić świeżo zmielonym pieprzem.

Na wierzchu położyć plasterki sera feta. Posypać suszonym oregano i polać oliwą. Można doprawić solą, ale ser feta jest już dość słony.
--
