= Saatka z kurczakiem i pomaracz  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 20 minut
* 2 porcje
* https://www.kwestiasmaku.com/przepis/salatka-z-kurczakiem-pomarancza-i-suszonymi-pomidorami[link do 藕r贸da przepisu]

== Skadniki

* 2 pomaracze
* 400 g filetu z piersi kurczaka (np. poldwiczki)
* 50 g rukoli
* 50 g orzech贸w woskich
* 6 kawak贸w suszonych pomidor贸w

=== Sos

* 4 y偶ki soku z pomaraczy
* 2 y偶ki oliwy
* 2 y偶ki miodu
* 1 y偶ka musztardy dijon

|
== Przygotowanie

Pomaracze obra ze sk贸rek a nastpnie wyfiletowa (ostrym no偶em wykroi czstki mi偶szu pomidzy bonkami). Z resztek pomaraczy wycisn sok i zachowa go do sosu (okoo 4 - 5 y偶ek).

Do soku z pomaraczy doda reszt skadnik贸w sosu, czyli: oliw, mi贸d i musztard, nastpnie doprawi sol oraz pieprzem.

Filet z kurczaka pokroi na 4 mniejsze kawaki (poldwiczki zachowa w caoci). Doprawi sol oraz pieprzem i  poo偶y na rozgrzanej patelni z oliw. Sma偶y po okoo 4 minuty z ka偶dej strony. Skropi 2 y偶kami sosu i ju偶 na mniejszym ogniu sma偶y jeszcze po p贸 minuty z ka偶dej strony. Odo偶y na talerz. Pozostay sos wykorzysta do polania saatki.

Rukol opuka na sitku, osuszy i wyo偶y do salaterek.

Orzechy lekko zrumieni na patelni, grubo posieka.

Suszone pomidory wyj z zalewy i pokroi na cienkie paseczki.

Na rukoli poo偶y pokrojonego kurczaka, czstki pomaraczy, orzechy i suszone pomidory, pola pozostaym sosem.

|===

[.text-center]
== Zdjcia
