= Saatka grecka  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: 15 min
* 4 porcje
* https://www.kwestiasmaku.com/dania_dla_dwojga/salatka_grecka/przepis.html[link do 藕r贸da przepisu]

== Skadniki
* 2 pomidory
* 4 og贸rki gruntowe lub 2 szklarniowe
* 1/2 czerwonej cebuli
* 1/2 szklanki czarnych oliwek
* 250 g oryginalnego, greckiego sera feta
* 4 y偶eczki suszonego oregano
* 4 y偶ki oliwy extra vergine
* wie偶o zmielony pieprz
|
== Przygotowanie
Pomidory pokroi na wiartki, usun szypuki, nastpnie pokroi na jeszcze mniejsze kawaki.

Og贸rki obra (mo偶na pozostawi miejscami paseczki zielonej sk贸rki), przekroi wzdu偶 na p贸 a nastpnie na grubsze p贸plasterki.

Cebul cienko poszatkowa. Oliwki przekroi na po贸wki.

Wszystkie skadniki umieci w jednej wikszej salaterce lub w 4 mniejszych, doprawi wie偶o zmielonym pieprzem.

Na wierzchu poo偶y plasterki sera feta. Posypa suszonym oregano i pola oliw. Mo偶na doprawi sol, ale ser feta jest ju偶 do sony.

|===

[.text-center]
== Zdjcia
