= +++<a href="../../index.html" class="back-to-home-btn">← Wróć do przepisów</a>+++ Sałatka gyros 🐔 +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++
:imagesdir: /Recipes/static/images

[.recipe-hero]
[.card-image-placeholder]
Brak zdjęcia przepisu 🍲

[.recipe-details]
* 🕒 czas przygotowania: 30 minut
* 🕒 czas gotowania: 30 minut
* 👥 4 porcje
* 🔗 https://www.kwestiasmaku.com/przepis/salatka-gyros[link do źródła przepisu]

[.recipe-columns]
== Składniki

* 3 pojedyncze filety kurczaka
* 2 łyżki stołowe przyprawy gyros/kebab
* 1 średnia czerwona cebula
* 1 duży por
* 1 średni słoik ogórków konserwowych (np. korniszonów)
* 1 puszka kukurydzy
* 1 czerwona papryka
* ½ kapusty pekińskiej lub ⅓ lodowej
* 4 łyżki ketchupu pikantnego
* 2 łyżki oleju roślinnego
* ⅔ szklanki majonezu
* ⅓ szklanki gęstej śmietany lub jogurtu greckiego (opcjonalnie)

== Przygotowanie

Filety opłukać, osuszyć, oczyścić z błonek i kostek. Pokroić na małe paseczki lub w kostkę. Wymieszać z przyprawą gyros/kebab i odłożyć na ok. ½ godziny lub dłużej jeśli mamy czas.

W międzyczasie przygotować warzywa. Czerwoną cebulę obrać, przekroić na 4 części, następnie na plasterki, oprószyć solą.

Odciąć korzonki pora, zielone liście oraz zewnętrzną 1 - 2 warstwy. Przekroić wzdłuż na 4 części i opłukać. Posiekać na desce, włożyć na sitko i przelać wrzątkiem z czajnika, odsączyć.

Ogórki konserwowe pokroić w kosteczkę, kukurydzę odcedzić na sitku z zalewy, paprykę pokroić w kosteczkę, kapustę pekińską opłukać, osuszyć i drobno poszatkować.

Na większej patelni podgrzać olej, włożyć kurczaka i obsmażać na złoty kolor z każdej strony (w sumie ok. 10 minut). W trakcie smażenia doprawić mięso solą oraz pieprzem. Przełożyć na dno salaterki o średnicy 20 cm.

Polać ketchupem, przykryć plasterkami czerwonej cebuli, następnie układać kolejne warstwy składników: ogórki, kukurydzę, pora, paprykę, majonez wymieszany ze śmietaną lub jogurtem, a na koniec przykryć posiekaną kapustą pekińską.

[.recipe-gallery]
== Zdjęcia

[.gallery-grid]
// Tutaj pojawią się zdjęcia
