= Saata z kurczakiem  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: 30 minut
* czas sma偶enia: 10 minut
* 6 porcji
* https://aniagotuje.pl/przepis/salatka-z-kurczakiem[link do 藕r贸da przepisu]

== Skadniki
* 500 g piersi z kurczaka - 1 wiksza pier
* po p贸 y偶eczki soli i pieprzu
* y偶eczka sodkiej papryki
* y偶ka delikatnej oliwy
* 100 g szpinaku wie偶ego baby
* 100 g ulubionej mieszanki saat
* 50 g saaty rukoli
* p贸 cebuli cukrowej - okoo 80 g
* 300 g pomidork贸w cherry
* 100 g twardego sera typu parmezan
* 6 y偶ek ulubionej oliwy
* wie偶o mielony pieprz i s贸l
* kieki jarmu偶u lub sonecznika

|
== Przygotowanie
Du偶 pier z kurczaka umyj i osusz rcznikiem papierowym. Usu w贸kna i ewentualne chrzstki. Dodam jeszcze, 偶e miso warto jest wyj wczeniej z lod贸wki, by miao jednolit temperatur. Jeli miso bdzie w rodku zimne, bdzie potrzebowao du偶szej obr贸bki termicznej. 

Pier z kurczaka sma偶ona w caoci, opr贸cz podsma偶enia na patelni wymaga dodatkowego pieczenia w piekarniku. Dwie po贸wki piersi z kurczaka obtocz dokadnie w soli, pieprzu i sodkiej papryce. P贸 y偶eczki soli, p贸 y偶eczki pieprzu i jedna y偶eczka sodkiej papryki.

Nagrzej dobrze patelni z grubym dnem. Wlej y偶k oliwy i wy贸偶 oba kawaki piersi. Sma偶 je po okoo trzy minuty z obu stron na redniej mocy palnika, a nastpnie przenie do piekarnika nagrzanego do 180 stopni. Piersi potrzebuj si dopiec w rodku. Wystarczy okoo 8 minut pieczenia na rodkowej p贸ce z opcj pieczenia g贸ra/d贸. 

Piersi z kurczaka odstaw do przestudzenia. To dobry moment na zrobienie saatki.
Przygotuj sobie szeroki p贸misek. Zacznij od umycia saat. Szpinak baby, saat rukol oraz mieszank saat przepucz pod zimn, bie偶c wod. Saaty umie razem na p贸misku. Zamiast mieszanki saat mo偶esz te偶 u偶y wie偶ej roszponki lub siekanej kapusty pekiskiej.

Do saat dodaj te偶 umyte pomidorki cherry lub pomidorki koktajlowe. Ka偶d sztuk przekr贸j na p贸. Cebul obierz i pokr贸j cienkie pi贸rka. 

Na warzywa wylej 3 y偶ki delikatnej oliwy. Przed wyo偶eniem kurczaka mo偶esz te偶 doda twardy ser. Ja wybraam ser woski Parmigiano Reggiano. Ser staram w patki przy pomocy gilotynki do ser贸w i warzyw. 

Pier z kurczaka pokr贸j w plasterki i wy贸偶 na saatk. Saatk z kurczakiem polej reszt oliwy. Bd to trzy y偶ki. Jeszcze tylko symboliczne opr贸szenie wie偶o mielonym pieprzem oraz sol. Ja dodaam te偶 troch kiek贸w jarmu偶u. Jeli jednak nie masz 偶adnych kiek贸w, to mo偶esz miao pomin ten skadnik. 

W przepisie nie ma dodatku w postaci orzech贸w lub pestek, ale jeli lubisz, gdy co Ci przyjemnie chrupie, to gorco polecam doda na koniec pra偶one pestki sonecznika lub te偶 siekane orzechy woskie.

|===

[.text-center]
== Zdjcia
