= Saatka gyros  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 30 minut
* 4 porcje
* https://www.kwestiasmaku.com/przepis/salatka-gyros[link do 藕r贸da przepisu]

== Skadniki

* 3 pojedyncze filety kurczaka
* 2 y偶ki stoowe przyprawy gyros/kebab
* 1 rednia czerwona cebula
* 1 du偶y por
* 1 redni soik og贸rk贸w konserwowych (np. korniszon贸w)
* 1 puszka kukurydzy
* 1 czerwona papryka
* 1/2 kapusty pekiskiej lub 1/3 lodowej
* 4 y偶ki ketchupu pikantnego
* 2 y偶ki oleju rolinnego
* 2/3 szklanki majonezu
* 1/3 szklanki gstej mietany lub jogurtu greckiego (opcjonalnie)

|
== Przygotowanie

Filety opuka, osuszy, oczyci z bonek i kostek. Pokroi na mae paseczki lub w kostk. Wymiesza z przypraw gyros/kebab i odo偶y na ok. 1/2 godziny lub du偶ej jeli mamy czas.

W midzyczasie przygotowa warzywa. Czerwon cebul obra, przekroi na 4 czci, nastpnie na plasterki, opr贸szy sol.

Odci korzonki pora, zielone licie oraz zewntrzn 1 - 2 warstwy. Przekroi wzdu偶 na 4 czci i opuka. Posieka na desce, wo偶y na sitko i przela wrztkiem z czajnika, odsczy.

Og贸rki konserwowe pokroi w kosteczk, kukurydz odcedzi na sitku z zalewy, papryk pokroi w kosteczk, kapust pekisk opuka, osuszy i drobno poszatkowa.

Na wikszej patelni podgrza olej, wo偶y kurczaka i obsma偶a na zoty kolor z ka偶dej strony (w sumie ok. 10 minut). W trakcie sma偶enia doprawi miso sol oraz pieprzem. Przeo偶y na dno salaterki o rednicy 20 cm.

Pola ketchupem, przykry plasterkami czerwonej cebuli, nastpnie ukada kolejne warstwy skadnik贸w: og贸rki, kukurydz, pora, papryk, majonez wymieszany ze mietan lub jogurtem, a na koniec przykry posiekan kapust pekisk.

|===

[.text-center]
== Zdjcia
