= Tabbouleh, saatka z bulgurem  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 20 minut
* 2 porcje
* https://www.kwestiasmaku.com/przepis/tabbouleh[link do 藕r贸da przepisu]

== Skadniki

* 35 g surowej kaszy bulgur
* 1 du偶y pczek natki pietruszki
* 1 pomidor
* 2 gazki szczypiorku
* szczypta cynamonu
* 2 y偶ki oliwy
* sok z 1 cytryny
* s贸l i zmielony pieprz

|
== Przygotowanie

Ugotowa kasz bulgur zgodnie z instrukcj na opakowaniu. Odcedzi i wo偶y do miski.

Natk pietruszki opuka, osuszy i oderwa listki od gazek. Drobno posieka, doda do miski z kasz.

Pomidora pokroi na wiartki, wykroi szypuki, usun nasiona z kom贸r. Pozostay mi偶sz pokroi najpierw na paski, nastpnie w kosteczk. Wo偶y do miski ze skadnikami.

Doda posiekany szczypiorek, cynamon, oliw i sok z cytryny. Doprawi sol i pieprzem, wymiesza. Mo偶na podawa do da misnych, lub np. nabiera porcje saatki za pomoc lici maej saaty rzymskiej.

|===

[.text-center]
== Zdjcia
