= Bueczki czosnkowe  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 20 minut
* czas wyrastania ciasta cznie: 1 godzina 30 minut
* czas pieczenia bueczek: 20 minut
* 8 bueczek
* https://aniagotuje.pl/przepis/buleczki-czosnkowe[link do 藕r贸da przepisu]

== Skadniki

* 2,5 szklanki mki pszennej np. tortowej - 400 g
* 7 g dro偶d偶y instant - maa saszetka
* niecae p贸 szklanki wody - 120 ml
* niecae p贸 szklanki mleka - 120 ml
* po paskiej y偶eczce soli i cukru
* y偶ka mikkiego masa - 10 g
* 50 g lekko mikkiego masa
* 4 zbki czosnku - 20 g
* maa gar natki pietruszki
* p贸 paskiej y偶eczki soli

|
== Przygotowanie

Do tych bueczek szykowanych na dro偶d偶ach instant nie robi rozczynu. Do miski wsyp zatem dwie i p贸 szklanki, czyli 400 gram贸w mki pszennej tortowej, do pizzy lub te偶 uniwersalnej typ. 480 oraz po paskiej y偶eczce soli i cukru i okoo 7 gram贸w dro偶d偶y suszonych instant (maa saszetka). Dodaj te偶 y偶k mikkiego masa lub oliwy lub innego oleju rolinnego. Na koniec wlej jeszcze niepen szklank lekko ciepego pynu (mleko i woda w proporcji p贸 na p贸, czyli cznie 240 ml - niepena szklanka).
Cao wymieszaj y偶k drewnian lub silikonow szpatuk. Misk z ciastem pod buki czosnkowe przenie pod mikser z hakami do ciasta dro偶d偶owego. Ciasto wyrabiaj tak 5 minut. Ciasto po wyrobieniu powinno by jednolite, gadkie i elastyczne. Mo偶esz te偶 wyrobi ciasto rcznie, ale pamitaj, 偶e ma to trwa do dugo. Ciasto mo偶e si lekko przykleja do cianek miski. Takie ciasto mo偶na wyj i lekko obsypa mk, a nastpnie uformowa w zgrabn kul i ponownie odo偶y do miski.

Wyrobione ciasto przykryj ciereczk bawenian lub foli przezroczyst. Odstaw w ciepe miejsce do wyrastania na minimum 60 minut. Ciasto powinno w tym czasie bardzo urosn. Jeli nie ronie, to przenie je w odrobin cieplejsze miejsce (temperatura nie wy偶sza ni偶 35 stopni) lub czekaj cierpliwie nawet do 90 minut. Drewnian stolnic lub blat obsyp delikatnie mk. Wyronite ciasto podziel na osiem r贸wnych kawak贸w. Ciasto wa偶yo u mnie cznie okoo 670 gram贸w, wiec na jedn bueczk wyszo po okoo 83 gramy ciasta. Tak wiec aby otrzyma buki tej samej wielkoci polecam zwa偶y cae ciasto, a nastpnie podzieli na r贸wne kawaki. Formuj w doniach buki o lekko wydu偶onych ksztacie.
Blaszk do pieczenia (mo偶e by ta z wyposa偶enia piekarnika) wy贸偶 papierem do pieczenia. Midzy bukami zachowaj spore odstpy, poniewa偶 buki czosnkowe jeszcze wyrastaj. Bueczki odstaw do wyrastania na minimum 30 minut. Na czas wyrastania przykryj je delikatnie czyst ciereczk bawenian (mo偶e by rcznik kuchenny).

Po tym czasie ka偶d buk posmaruj delikatnie odrobin mleka lub mieszank mleka i 偶贸tka. Polecam u偶y do tego pdzelka kuchennego. Nie jest to jednak konieczne i nie trzeba niczym smarowa buek przed pieczeniem.
Maso czosnkowe zrobisz w kilka minut, wic mo偶esz si za nie zabra np. w trakcie wystarania ju偶 uformowanych buek. Wystarczy, 偶e w miseczce umiecisz do 50 gram贸w lekko mikkiego masa, cztery obrane i przecinite przez prask zbki czosnku oraz p贸 paskiej y偶eczki soli i ma gar drobno posiekanej natki pietruszki. Cao dobrze wymieszaj np. widelcem.
Wyronite bueczki (posmarowane mlekiem i 偶贸tkiem lub te偶 nie) natnij w poprzek w trzech miejscach lub te偶 tylko raz na rodku (wzdu偶 buki). Poniewa偶 maso czosnkowe nie jest super mikkie, to mo偶esz robi z niego w doniach mini waeczki i wypenia nimi nacicia. Postaraj si tak podzieli maso czosnkowe, by starczyo Ci na ka偶d bueczk.

Zacznij nagrzewa piekarnik. Ustaw opcj pieczenia g贸ra/d贸 i temperatur 190 stopni lub 180 stopni z termoobiegiem. Gotow blaszk z bukami umie na rodkowej p贸ce w dobrze nagrzanym piekarniku. Bueczki czosnkowe piecz tak okoo 20 minut. Upieczone buki s wyronite i rumiane. Po upieczeniu uchyl drzwi piekarnika na 5 minut, a nastpnie wyjmij blaszk z upieczonymi bukami.

Buki czosnkowe mo偶na kroi po cakowitym przestudzeniu. Jeli bueczki czosnkowe nie zostan zjedzone w dniu pieczenia, polecam zawin je w papier niadaniowy, a nastpnie lu藕no w torb spo偶ywcz przezroczyst i trzyma w szafce, w suchym i chodnym pomieszczeniu.

|===

[.text-center]
== Zdjcia
