= Feta zapiekana w cieście filo na słodko 🌱 +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++
:imagesdir: /Recipes/static/images

[.recipe-hero]

[.recipe-category-label]
Dania główne

[.card-image-placeholder]
Brak zdjęcia przepisu 🍲


[.recipe-details]

[.recipe-details-item]
🕒 czas przygotowania: 30 minut

[.recipe-details-item]
👥 2 porcje

[.recipe-details-item]
🔗 https://krytykakulinarna.com/feta-w-ciescie-przepis/[link do źródła przepisu]



[.recipe-columns]

[.recipe-column-box]
=== Składniki
* 400 g fety (dwa kawałki po 200 g)
* 2 łyżki sezamu (może być biały, czarny lub mieszanka)
* 5 płatów ciasta filo
* 5-6 łyżek oliwy
* 2 łyżki miodu



[.recipe-column-box]
=== Przygotowanie
Piekarnik rozgrzewamy do 220 stopni bez termoobiegu, grzanie góra/dół. Do miseczki wlewamy oliwę.

Na blacie rozkładamy ciasto filo. Płaty przekrawamy na pół, aby uzyskać dwie równe części. Na pierwszym płacie (właściwie na połówce) układamy fetę i dokładnie ją zawijamy w ciasto. Ciasto smarujemy oliwą i zawijamy fetę w kolejny płat ciasta. Ponownie smarujemy oliwą. I tak pięć razy.

Z drugim kawałkiem fety postępujemy identycznie.

Dno naczynia żaroodpornego smarujemy oliwą, układamy fetę w cieście filo i szczodrze posypujemy sezamem.

Zapiekamy w 220 stopniach bez termoobiegu przez 20 minut.

Podajemy od razu po upieczeniu obficie skropione miodem.

