= Feta zapiekana w ciecie filo na sodko   +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 30 minut
* 2 porcje
* https://krytykakulinarna.com/feta-w-ciescie-przepis/[link do 藕r贸da przepisu]

== Skadniki

* 400 g fety (dwa kawaki po 200 g)
* 2 y偶ki sezamu (mo偶e by biay, czarny lub mieszanka)
* 5 pat贸w ciasta filo
* 5-6 y偶ek oliwy
* 2 y偶ki miodu

|
== Przygotowanie

Piekarnik rozgrzewamy do 220 stopni bez termoobiegu, grzanie g贸ra/d贸. Do miseczki wlewamy oliw.

Na blacie rozkadamy ciasto filo. Paty przekrawamy na p贸, aby uzyska dwie r贸wne czci. Na pierwszym pacie (waciwie na po贸wce) ukadamy fet i dokadnie j zawijamy w ciasto. Ciasto smarujemy oliw i zawijamy fet w kolejny pat ciasta. Ponownie smarujemy oliw. I tak pi razy.

Z drugim kawakiem fety postpujemy identycznie.

Dno naczynia 偶aroodpornego smarujemy oliw, ukadamy fet w ciecie filo i szczodrze posypujemy sezamem.

Zapiekamy w 220 stopniach bez termoobiegu przez 20 minut.

Podajemy od razu po upieczeniu obficie skropione miodem.

|===

[.text-center]
== Zdjcia
