= Grzanki z mozzarella 🌱
:imagesdir: /Recipes/static/images

++++
<div class="recipe-header-actions">
    <a href="../../index.html" class="back-to-home-btn">← Wróć do przepisów</a>
    <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>
</div>
++++

[.recipe-hero]
[.card-image-placeholder]
Brak zdjęcia przepisu 🍲

[.recipe-details]
* 🕒 czas przygotowania: 3 godziny
* 👥 4 porcje
* 🔗  https://aniagotuje.pl/przepis/grzanki-z-mozzarella[link do źródła przepisu]

[.recipe-columns]
== Składniki

* grubsze kromki ulubionego pieczywa 2 sztuki - 100 g
* oliwa do grzanek 1 łyżka
* pesto domowe lub ze sklepu 20 g
* mozzarella z zalewy np. w kulkach 80 g
* pomidor 120 g
* sałata np. rzymska 2-3 listki
* limonka kilka kropel do podania
* listki bazylii do dekoracji kilka sztuk

== Przygotowanie

Grzanki z mozzarellą i pesto to doskonały sposób na urozmaicenie codziennych posiłków oraz na podanie czegoś wyjątkowego podczas spotkań z przyjaciółmi. Zachęcam do wypróbowania tego przepisu.  Czas przygotowania: 25 minutLiczba porcji: 2 grzanki

W 100 g dania:  Wartość energetyczna 203 kcal   Węglowodany 18 g    - W tym cukry 3 g   Białko 8 g   Tłuszcze 11 g  Dieta:

niskocukrowa

Składniki    grubsze kromki ulubionego pieczywa 2 sztuki - 100 g   oliwa do grzanek 1 łyżka   pesto domowe lub ze sklepu 20 g   mozzarella z zalewy np. w kulkach 80 g   pomidor 120 g   sałata np. rzymska 2-3 listki   limonka kilka kropel do podania   listki bazylii do dekoracji kilka sztuk  Składniki:  Kopiuj     Ukryj zdjęcia

Grzanki z mozzarellą

Przed szykowaniem grzanek zachęcam też do przeczytania najpierw całego wpisu. W treści podaję bowiem dużo ciekawych porad dotyczących składników oraz ich zamienników. Być może zapragniesz dodać do grzanek domowe pesto lub pomidory zastąpić Guacamole.

Krok 1: Zarumień grzanki

Do zrobienia grzanek możesz wykorzystać dowolne pieczywo: pszenne, pszenno-żytnie, jaglane, gryczane, a nawet owsiane. Pokrój chleb w grubsze kromki, najlepiej około 1,5 wysokości. Ustaw patelnię na średniej mocy i poczekaj, aż się nagrzeje. Gdy patelnia będzie gorąca, dodaj na nią oliwę lub olej do smażenia. Ja użyłam jednej łyżki oliwy, ale możesz dodać więcej, jeśli wolisz. Następnie ułóż kromki chleba na patelni. Kiedy grzanki zaczną delikatnie się rumienić, przewróć je na drugą stronę. Staraj się przesuwać je po powierzchni patelni, aby wchłonęły resztę tłuszczu.

Kontynuuj "smażenie" aż do uzyskania złocistego koloru i chrupiącej skórki z obu stron. Możesz delikatnie dociskać kromki do patelni przy pomocy płaskiej szpatułki, aby równomiernie się zrumieniły. Grzanki powinny być chrupiące, ale nie przypalone. Czas potrzebny do ich idealnego wypieczenia zależy od mocy palnika, rodzaju patelni oraz pieczywa, którego używasz.

Krok 2: Przygotuj składniki

W międzyczasie przygotuj składniki do grzanek. Dużego pomidora pokrój w grubsze plastry lub użyj mniejszych pomidorków, które możesz pokroić w cienkie plasterki albo drobną kostkę. Około 80 g mozzarelli, czy to w małych kulkach, czy dużej kulce z zalewy, będzie idealne. Jeśli masz większą mozzarellę, pokrój ją w plastry. Przygotuj też liście sałaty, które możesz zastąpić liśćmi szpinaku, rukolą czy sałatą lodową. Na koniec warto przygotować ćwiartki limonki, aby skropić gotowe grzanki odrobiną soku.

Nie zapomnij też o pesto. Może być to całkowicie dowolne pesto bazyliowe czy też inne z kolendry albo pietruszki. Polecam pesto domowe, ale te dobrej jakości ze sklepu również się sprawdzą.

Krok 3: Wykładaj składniki na grzanki

Gotowe, najlepiej jeszcze ciepłe, grzanki zdejmij z patelni i zacznij na nich układać składniki. Tutaj zostawiam całkowitą dowolność, jednak sama wolę najpierw ułożyć liście sałaty, a następnie plastry pomidora, aby uniknąć nadmiernemu wilgoceniu grzanek.

Porada: Pesto bądź samego pomidora albo jedno i drugie z powodzeniem zastąpisz gotowym guacamole.

Krok 4: Dokończ i podawaj

Na plastry pomidora wykładam po porcji pesto, a następnie kulki mozzarelli. Na górę jeszcze odrobina pesto, świeżo mielony pieprz, listki bazylii oraz kilka kropel soku z limonki. Takie pyszne grzanki z mozzarelą i pesto podawaj od razu.

Jeśli grzanki nie zostaną zjedzone zaraz po zrobieniu, to można je też zostawić na potem, nie wkładając ich do lodówki. Wystarczy wówczas podgrzać je odrobinę od spodu na suchej patelni. Zostawione na drugi dzień należy odłożyć do lodówki pod przykryciem, a następnie wyjąć wcześniej, najlepiej na godzinę przed planowanym posiłkiem i umieścić je tak jak wcześniej na suchej patelni, aby lekko podgrzać je od spodu i sprawić, aby grzanki ponownie były chrupiące.

Smacznego.


[.recipe-gallery]
== Zdjęcia

[.gallery-grid]
// Tutaj pojawią się zdjęcia
