= Guacamole  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* https://aniagotuje.pl/przepis/guacamole[link do 藕r贸da przepisu]

== Skadniki
* 3 wiksze dojrzae awokado - 650 g
* 4 y偶ki dobrej jakoci oliwy
* 6 y偶ek soku z limonki lub cytryny
* 2 rednie zbki czosnku
* p贸 mniejszej cebuli czerwonej - 60 g
* 6 pomidork贸w koktajlowych - 90 g
* spora gar wie偶ej kolendry
* przyprawy: p贸 y偶eczki soli i spora szczypta wie偶o mielonego pieprzu

|
== Przygotowanie
Guacamole to niezwykle pyszna i prosta do zrobienia pasta z dojrzaego awokado, soku z cytryny lub limonki oraz soli. Dodatkowo m贸j przepis skada si jeszcze z kilku idealnie pasujcych skadnik贸w. Rewelacja!
- wietna pasta na przyjcia
- super dip do nakadania na chipsy nachos
- rewelacyjny pomys na zdrowe danie z awokado  Czas przygotowania: 20 minut
Liczba porcji: okoo 610 g pasty

W 100 g pasty:

Warto energetyczna
185 kcal

Dieta:   bezglutenowa, wegaska, wegetariaska
Skadniki3 wiksze dojrzae awokado - 650 g4 y偶ki dobrej jakoci oliwy6 y偶ek soku z limonki lub cytryny2 rednie zbki czosnkup贸 mniejszej cebuli czerwonej - 60 g6 pomidork贸w koktajlowych - 90 gspora gar wie偶ej kolendryprzyprawy: p贸 y偶eczki soli i spora szczypta wie偶o mielonego pieprzu

Skadniki:  Kopiuj     Ukryj zdjcia

Guacamole
Szklanka ma u mnie pojemno 250 ml.
Warzywa/owoce wa偶one byy przed ewentualnym obraniem/przygotowaniem.
Kalorie policzone zostay na podstawie u偶ytych przeze mnie skadnik贸w. Jest to wic orientacyjna ilo kalorii, poniewa偶 Twoje skadniki mog mie inn ilo kalorii ni偶 te, kt贸rych u偶yam ja. Z podanej iloci skadnik贸w otrzymasz ponad 600 gram贸w pysznej pasty guacamole.
Jak woam moj rodzink na uczt, to wiedz ju偶, 偶e chodzi o przepis na guacamole :) To takie nasze "tajne" haso. W kilka sekund w salonie pojawiaj si moje Dzieci i M偶. Robi si gono i sycha tylko amanie chips贸w kukurydzianych. Dla takich cudownych moment贸w warto powici 20 minut w kuchni, prawda?











Guacamole przepis
Najpierw zawsze szykuj baz guacamole, w kt贸rej wszystkie skadniki idealnie graj ze sob kolorystyczne. I ju偶 nawet takie guacamole mo偶na miao podawa jako past na przyjcia. W podstawowej wersji guacamole znajduje si: mi偶sz z awokado, sok z cytryny i/lub limonki, czosnek, kolendra, oliwa, s贸l i pieprz. Reszt skadnik贸w ukadam na p贸misku z past :) Szalestwo smak贸w i kolor贸w!
Aby zrobi guacamole wybierz zdrowe i dojrzae awokado. U mnie byy to dwie sztuki awokado Hass i jedno zwyke, zielone awokado o cznej wadze okoo 650 gram贸w. Dojrzae awokado umyj i natnij po caoci, a偶 do pestki. Rozdziel na dwie po贸wki. Usu pestk a mi偶sz wyjmij przy pomocy y偶ki lub te偶 najpierw delikatnie zdejmij palcami tward sk贸rk. Po贸wki awokado ugniataj kawaek po kawaku przy pomocy widelca.
Tak naprawd z mi偶szem mo偶esz postpi dowolnie, zatem awokado w formie bardziej jednolitej te偶 jest super. Ostatecznie wyszo mi 450 gram贸w gotowej pasty. Moje awokado byy do du偶e, wic bardzo mo偶liwe, 偶e u Ciebie potrzebne bd a偶 cztery sztuki.






Dwa redniej wielkoci zbki czosnku obierz i przecinij przez prask prosto do ugniecionego mi偶szu z awokado. Dodaj te偶 spor gar wie偶o siekanej kolendry lub ewentualnie natki pietruszki oraz cztery y偶ki dobrej jakoci oliwy.







Do miseczki wycinij te偶 okoo 6 y偶ek wie偶o wycinitego soku z limonek lub cytryny. U mnie by to sok z jednej caej limonki oraz z po贸wki cytryny. Cao dokadnie wymieszaj.

Porada: Bardzo wa偶ne jest to, by sok z limonki lub cytryny doda jak najszybciej do mi偶szu z awokado. Dziki temu mi偶sz zachowa sw贸j pikny i wie偶y kolor i nie zrobi si szary.







Do mi偶szu z awokado dodaj jeszcze p贸 y偶eczki soli i spor szczypt wie偶o mielonego pieprzu. Wymieszaj guacamole i sprawd藕 jego smak. By mo偶e zechcesz doda wicej soli lub soku z limonki.

Porada: Jeli lubisz ostre pasty, to mo偶esz w tym momencie doda te偶 wie偶o siekan papryczk chili lub te偶 chili suszone, czy te偶 w formie sproszkowanej. Uwa偶aj na to, by nie doda go za du偶o.







Gotow baz guacamole umie na szerokim talerzu lub p贸misku.

Ma cebulk czerwon pokr贸j w drobn kostk. Tak samo drobno pokr贸j pomidorki.

Porada: Zamiast cebuli czerwonej mo偶esz u偶y cebul czosnkow (bia) lub te偶 szczypiorek. Zamiast mini pomidork贸w mo偶esz te偶 miao pokroi drobno jednego, wikszego pomidora.







Cebulk oraz pomidorki wy贸偶 na guacamole. Cao mo偶esz dodatkowo opr贸szy wie偶o mielonym kolorowym pieprzem oraz pola dodatkow porcj oliwy.







Guacamole podawaj od razu lub te偶 po schodzeniu w lod贸wce. Past guacamole mo偶esz je z chipsami kukurydzianymi o dowolnym smaku. U nas wygrywa zazwyczaj serowe Doritos.


Guacamole mo偶na te偶 zajada z plackami z tortilli oraz z kieszonkami z warzyw: listki cykorii, kawaki papryki, wydr偶one po贸wki pomidor贸w...













Smacznego.

|===

[.text-center]
== Zdjcia
