= Guacamole  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 20 minut
* okoo 610 g pasty
* https://aniagotuje.pl/przepis/guacamole[link do 藕r贸da przepisu]

== Skadniki

* 3 wiksze dojrzae awokado - 650 g
* 4 y偶ki dobrej jakoci oliwy
* 6 y偶ek soku z limonki lub cytryny
* 2 rednie zbki czosnku
* p贸 mniejszej cebuli czerwonej - 60 g
* 6 pomidork贸w koktajlowych - 90 g
* spora gar wie偶ej kolendry
* przyprawy: p贸 y偶eczki soli i spora szczypta wie偶o mielonego pieprzu

|
== Przygotowanie

Aby zrobi guacamole wybierz zdrowe i dojrzae awokado. U mnie byy to dwie sztuki awokado Hass i jedno zwyke, zielone awokado o cznej wadze okoo 650 gram贸w. Dojrzae awokado umyj i natnij po caoci, a偶 do pestki. Rozdziel na dwie po贸wki. Usu pestk a mi偶sz wyjmij przy pomocy y偶ki lub te偶 najpierw delikatnie zdejmij palcami tward sk贸rk. Po贸wki awokado ugniataj kawaek po kawaku przy pomocy widelca.
Tak naprawd z mi偶szem mo偶esz postpi dowolnie, zatem awokado w formie bardziej jednolitej te偶 jest super. Ostatecznie wyszo mi 450 gram贸w gotowej pasty. Moje awokado byy do du偶e, wic bardzo mo偶liwe, 偶e u Ciebie potrzebne bd a偶 cztery sztuki.

Dwa redniej wielkoci zbki czosnku obierz i przecinij przez prask prosto do ugniecionego mi偶szu z awokado. Dodaj te偶 spor gar wie偶o siekanej kolendry lub ewentualnie natki pietruszki oraz cztery y偶ki dobrej jakoci oliwy.

Do miseczki wycinij te偶 okoo 6 y偶ek wie偶o wycinitego soku z limonek lub cytryny. U mnie by to sok z jednej caej limonki oraz z po贸wki cytryny. Cao dokadnie wymieszaj.

Do mi偶szu z awokado dodaj jeszcze p贸 y偶eczki soli i spor szczypt wie偶o mielonego pieprzu. Wymieszaj guacamole i sprawd藕 jego smak. By mo偶e zechcesz doda wicej soli lub soku z limonki.

Gotow baz guacamole umie na szerokim talerzu lub p贸misku.

Ma cebulk czerwon pokr贸j w drobn kostk. Tak samo drobno pokr贸j pomidorki.


Cebulk oraz pomidorki wy贸偶 na guacamole. Cao mo偶esz dodatkowo opr贸szy wie偶o mielonym kolorowym pieprzem oraz pola dodatkow porcj oliwy.

Guacamole podawaj od razu lub te偶 po schodzeniu w lod贸wce. Past guacamole mo偶esz je z chipsami kukurydzianymi o dowolnym smaku. U nas wygrywa zazwyczaj serowe Doritos.

|===

[.text-center]
== Zdjcia
