= Pita +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* https://aniagotuje.pl/przepis/pita[link do źródła przepisu]

== Składniki
* 2,5 szklanki mąki pszennej tortowej - 400 g
* 5 gramów drożdży suszonych lub 15 gramów drożdży świeżych
* 1 niecała szklanka lekko ciepłej wody - 220 ml
* 1 łyżka delikatnej oliwy
* 1 płaska łyżeczka soli


|
== Przygotowanie
Najpyszniejsza pita.. najprostszy przepis.. rewelacyjne i mięciutkie chlebki z piekarnika lub z patelni. A do tego można je wypełnić ulubionym farszem. Zobacz jak z kilku składników wyczarować coś wspaniałego!
- prosty przepis na chlebek pita
- w wersji z patelni lub z piekarnika
- tylko kilka podstawowych składników  Czas przygotowania: 10 minut
Czas wyrastania: 1 godzina 30 minut
Czas prażenia chlebka: 4 minuty
Liczba porcji: 6 chlebków pita

W 1 chlebku pita:

Wartość energetyczna
254 kcal

Dieta:  wegańska, wegetariańska
Składniki2,5 szklanki mąki pszennej tortowej - 400 g5 gramów drożdży suszonych lub 15 gramów drożdży świeżych1 niecała szklanka lekko ciepłej wody - 220 ml1 łyżka delikatnej oliwy1 płaska łyżeczka soli

Składniki:  Kopiuj     Ukryj zdjęcia

Pita przepis
Szklanka ma u mnie pojemność 250 ml.
Do zrobienia chlebków pita przydadzą się: duża patelnia z grubym dnem; piekarnik lub też płyta kuchni kaflowej; wałek i odrobina mąki do podsypywania chlebków.
Kalorie policzone zostały na podstawie użytych przeze mnie składników. Jest to więc orientacyjna ilość kalorii, ponieważ Twoje składniki mogą mieć inną ilość kalorii niż te, których użyłam ja. Z podanej ilości składników wyszło mi sześć sporych chlebków pita.





Chlebek pita
Ciasto na chlebek pita szykuje się super prosto. Wystarczy umieścić razem wszystkie składniki i wyrobić je na elastyczne i jednolite ciasto.
W jednej misce umieść dwie i pół szklanki mąki pszennej, czyli równo 400 gramów mąki. Możesz użyć mąki tortowej lub też mąki typ. 00 (Tipo 00” - jest to włoskie oznaczenie na mąkę pszenną, bardzo drobno zmieloną. Taka mąka zawiera więcej glutenu, dzięki czemu ciasto jest bardzo elastyczne i łatwiejsze w wyrabianiu).
Wlej niecałą szklankę lekko ciepłej wody, czyli 220 ml wody. Wsyp płaską łyżeczkę suchych drożdży. Będzie to nie więcej niż pięć gramów drożdży. Zamiast suchych drożdży możesz też dodać 15 gramów drożdży świeżych.
Na koniec jeszcze łyżka delikatnej (nie może być gorzka) oliwy oraz płaska łyżeczka soli. Zamiast oliwy możesz użyć innego oleju roślinnego np. ryżowego lub z pestek winogron.






Ciasto wymieszaj a następnie wyrabiaj tak długo, aż drobi się idealnie gładkie. Ciasto jest dość miękkie. Miskę z ciastem przykryj ściereczką bawełnianą lub folią przezroczystą. Odstaw do wyrastania na godzinę lub nawet 90 minut - najlepiej do lekko nagrzanego wcześniej piekarnika (temperatura nie wyższa niż 35 stopni - piekarnik wyłączony). W upały miskę połóż na blacie kuchennym w cieniu. Zimą możesz też położyć miskę obok kaloryfera.







Wyrośnięte ciasto na chlebki pita przełóż na blat obsypany lekko mąką. Ciasto wyrabiaj chwilę a następnie podziel na sześć równych kawałków. Każdy kawałek uformuj w dłoniach na kształt kuli. Zrób to dokładnie, by ciasto było idealnie gładkie.







Każdą kulkę ciasta rozwałkuj ostrożnie na na placek o średnicy około 16-18 cm. Placki kładź obok siebie na desce, blacie lub papierze do pieczenia i przykryj ściereczką bawełnianą. Ważne jest to, by placki nie przywarły do deski, ponieważ mają one zachować idealnie rozwałkowany kształt. Placki pod chlebki pita można zostawić do wyrastania na 20-30 minut.






Chlebki pita możesz dokończyć szykować na dwa sposoby. Możesz je upiec w piekarniku lub też uprażyć na suchej patelni. Swoje chlebki zazwyczaj prażę na suchej i dobrze nagrzanej patelni. Wybierz niedużą patelnię z grubym dnem. Patelnię nagrzewaj na średniej mocy palnika. Niczym jej nie smaruj. Na nagrzaną patelnię kładź pojedynczo chlebki pita. Po około 1,5 do 2 minut zmień stronę i praż chlebek kolejne 1,5 - 2 minuty. Na chlebku najpierw pojawiają się małe pęcherzyki a po chwili rosną i zaczynają się ze sobą łączyć, aż utworzą kieszeń. W ten sposób upraż po kolei wszystkie chlebki.

Porada: Mam płytę indukcyjną. Patelnię nagrzewam na mocy 6. Trwa to do pięciu minut. Po umieszczeniu placka na nagrzanej patelni zwiększam moc do 7.5 i na takiej mocy prażę chlebki pita.













Aby przygotować chlebki pita w piekarniku polecam nagrzać piekarnik do 200 stopni z termoobiegiem lub 210 stopni z pieczeniem góra/dół. Na środkowej półce w piekarniku nagrzewam też czystą i suchą blachę z wyposażenia piekarnika. Na taką nagrzaną blachę bardzo ostrożnie przerzucam gotowe do pieczenia chlebki pita. Na jedno pieczenie kładę trzy chlebki.
Już po chwili chlebki zaczynają puchnąć. W większości zamieniają się w puchate poduszki. Po około 4-6 minutach pieczenia robią się rumiane i są już gotowe do wyjęcia z pieca. Zdejmuję je z blachy i od razu kładę drugą partię placków. Piekę je tak samo, jak pierwsze. Nie piecz chlebków za długo, by nie zrobiły się kruche. Mają być miękkie i puszyste.






Ciepłe chlebki pita możesz jeść nawet bez żadnych dodatków. Pita sprawdzają się idealnie do zajadania z różnymi pastami i gęstymi sosami lub też z falafelami. Kieszonki chlebków pita można dowolnie wypełniać np. smażonym kurczakiem i świeżymi warzywami i zajadać ze smakiem. Chlebek pita świetnie się sprawdza podczas szykowania kebabów. Polecam Ci coś wspaniałego, czyli kofta z orientalnymi przyprawami podawana z sosem jogurtowo miętowym oraz świeżym pomidorem.









Przestudzone chlebki pita można zawinąć w papier śniadaniowy a następnie w torbę spożywczą przezroczystą i trzymać w chlebaku do dwóch dni. Chlebek pita można też po upieczeniu zamrozić. Sprawdź też koniecznie mój przepis na podpłomyk oraz wspaniałe, puszyste bułki do burgerów. Rewelacyjny jest również doner kebab, czyli najpopularniejszy kebab w bułce pita.

Smacznego.

|===

[.text-center]
== Zdjęcia
