= Roladki tortilowe  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 20 minut
* czas chodzenia: 10 minut
* 24 roladki
* https://aniagotuje.pl/przepis/tortilla-z-serem-i-z-szynka[link do 藕r贸da przepisu]

== Skadniki

* 3 placki z tortilli pszennej
* 200 g serka kremowego serka typu Philadelphia
* 250 g szynki w plasterkach - 9 plasterk贸w
* 140 g sera w plasterkach - 9 plasterk贸w
* 100 g og贸rk贸w, konserwowych - 2 sztuki
* kilka lici saaty zwykej lub lodowej
* p贸 maej czerwonej papryki
* may pczek szczypiorku

|
== Przygotowanie

Placki wysmaruj do grubo kremowym serkiem typu Philadelphia.

Na ka偶dy placek wy贸偶 te偶 odrobin siekanego szczypiorku. Mo偶esz te偶 u偶y koperku lub natki pietruszki.

Na warstw serka wy贸偶 plasterki szynki wieprzowej lub drobiowej oraz plasterki 偶贸tego sera. Ja wybraam pyszny ser 偶贸ty kr贸lewski - podpuszczkowy, dojrzewajcy. Zar贸wno szynk jak i ser polecam zakupi ju偶 pokrojone w plasterki. Bdzie wygodniej i atwiej rozdzieli je i uo偶y na plackach z tortilli.

Na szynk i ser wy贸偶 kilka lici saaty malanej lub lodowej. Mo偶esz te偶 u偶y lici szpinaku baby. Og贸rki konserwowe pokr贸j wzdu偶 i u贸偶 na tortilli tak, jak na zdjciu. Tak samo zr贸b z papryk. Og贸rki mo偶esz zastpi papryk konserwow, za wie偶 papryk np. wie偶ym og贸rkiem. Cao mo偶esz dodatkowo opr贸szy wie偶o mielonym pieprzem oraz sol.

Gotowe tortille zwijaj powoli w cisy rulon.

Zwinite tortille mo偶na przekroi na p贸 lub na 4 kawaki albo tak jak ja, na mini roladki. Takie mini roladki s idealne jako szybka przekska na przyjcie.

Roladki mo偶na przed podaniem schodzi w lod贸wce. Nie jest to jednak konieczne. Jeli obawiasz si o to, 偶e roladki si otworz podczas np. nakadania ich na talerz, to mo偶esz w ka偶d sztuk wpi wykaaczk. W wystajcy patyczek wbij w贸wczas np. czarn lub zielon oliwk lub mini pomidorki.

|===

[.text-center]
== Zdjcia
