= Roladki tortilowe +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły

* czas przygotowania: 20 minut
* czas chłodzenia: 10 minut
* 24 roladki
* https://aniagotuje.pl/przepis/tortilla-z-serem-i-z-szynka[link do źródła przepisu]

== Składniki

* 3 placki z tortilli pszennej
* 200 g serka kremowego serka typu Philadelphia
* 250 g szynki w plasterkach - 9 plasterków
* 140 g sera w plasterkach - 9 plasterków
* 100 g ogórków, konserwowych - 2 sztuki
* kilka liści sałaty zwykłej lub lodowej
* pół małej czerwonej papryki
* mały pęczek szczypiorku

|
== Przygotowanie

Placki wysmaruj dość grubo kremowym serkiem typu Philadelphia.

Na każdy placek wyłóż też odrobinę siekanego szczypiorku. Możesz też użyć koperku lub natki pietruszki.

Na warstwę serka wyłóż plasterki szynki wieprzowej lub drobiowej oraz plasterki żółtego sera. Ja wybrałam pyszny ser żółty królewski - podpuszczkowy, dojrzewający. Zarówno szynkę jak i ser polecam zakupić już pokrojone w plasterki. Będzie wygodniej i łatwiej rozdzielić je i ułożyć na plackach z tortilli.

Na szynkę i ser wyłóż kilka liści sałaty maślanej lub lodowej. Możesz też użyć liści szpinaku baby. Ogórki konserwowe pokrój wzdłuż i ułóż na tortilli tak, jak na zdjęciu. Tak samo zrób z papryką. Ogórki możesz zastąpić papryką konserwową, zaś świeżą paprykę np. świeżym ogórkiem. Całość możesz dodatkowo oprószyć świeżo mielonym pieprzem oraz solą.

Gotowe tortille zwijaj powoli w ścisły rulon.

Zwinięte tortille można przekroić na pół lub na 4 kawałki albo tak jak ja, na mini roladki. Takie mini roladki są idealne jako szybka przekąska na przyjęcie.

Roladki można przed podaniem schłodzić w lodówce. Nie jest to jednak konieczne. Jeśli obawiasz się o to, że roladki się otworzą podczas np. nakładania ich na talerz, to możesz w każdą sztukę wpić wykałaczkę. W wystający patyczek wbij wówczas np. czarną lub zieloną oliwkę lub mini pomidorki.

|===

[.text-center]
== Zdjęcia
