= Rozczyn +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 20 min
* 1 porcja
* https://mojewypieki.com/post/jak-zrobic-rozczyn-ze-swiezych-drozdzy[link do źródła przepisu]

== Składniki
* 25 g drożdży świeżych
* 1 łyżka cukru
* 1/4 szklanki letniego mleka
* 3 łyżki mąki pszennej

|
== Przygotowanie
Do niedużego garnuszka rozkruszyć drożdże, zasypać cukrem. Zalać letnim mlekiem (nie gorącym! - zbyt wysoka temperatura zabije drożdże). Wymieszać do rozpuszczenia się drożdży.

Dodać mąkę, wymieszać, by nie było grudek.

Przykryć ściereczką i odstawić w ciepłe miejsce do wyrośnięcia, na około 20 - 30 minut.

Uwaga: składniki na rozczyn odejmujemy z przepisu na wybrane przez Was ciasto drożdżowe. Jeśli w przepisie nie ma mleka, stosujemy w zamian wodę. Rodzaj użytej mąki również zależy od mąki, jaką mamy w wybranym przepisie, nie musi być to mąka pszenna. Ilość drożdży użyta do przygotowania rozczynu (powyżej) jest przykładowa - należy użyć ilość drożdży, jaka zawarta jest w wybranym przez Was przepisie.

|===

[.text-center]
== Zdjęcia
