= Salsa pomidorowa  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 15 minut
* okoo 470 g salsy
* https://aniagotuje.pl/przepis/salsa[link do 藕r贸da przepisu]

== Skadniki

* 400 g dojrzaych pomidor贸w
* malutka czerwona cebula - okoo 80 g
* 3 zbki czosnku - 15 g
* 3 y偶ki soku z limonki
* p贸 maej papryczki chili - okoo 10 g
* gar wie偶ej kolendry
* przyprawy: paska y偶eczka soli; p贸 paskiej y偶eczki cukru; po szczypcie cynamonu, kminku i ziela angielskiego

|
== Przygotowanie

Okoo 400 gram贸w pomidor贸w bardzo drobno siekam no偶em. Jeli u偶ywam du偶ych pomidor贸w, to najpierw wykrajam twarde fragmenty przy szypuce. Latem sigam po pachnce, bardzo dojrzae i czerwone pomidory sezonowe. Poza sezonem kupuj zazwyczaj mini pomidorki: truskawkowe, cherry, koktajlowe.
Malutk, czerwon cebul obieram i bardzo drobno siekam. miao mo偶na te偶 u偶y trzech cebulek szalotek lub r贸wnie maej cebuli czosnkowej albo zwykej. Trzy zbki czosnku r贸wnie偶 obieram i osobno siekam drobniutko no偶em. Gar wie偶ej kolendry (listki i ody偶ki) przepukuj, osuszam i siekam r贸wnie drobno jak czosnek. Jeli nie masz lub nie lubisz smaku wie偶ej kolendry, to polecam w zastpstwie natk pietruszki (kolendra jest jednak wedug mnie obowizkowa ;).
Jeli chodzi o papryczki chili, to z nimi bywa bardzo r贸偶nie. Sprawdzam zawsze, jak ostre papryczki mi si trafiy i decyduj, czy posieka ca papryczk, czy tylko kawaek. Tym razem dodaam poow wie偶ej papryczki, czyli okoo 10 gram贸w. Pamitaj o tym podczas szykowania salsy.
Wyciskam jeszcze trzy y偶ki soku z limonki (czasem daj wicej). Mo偶na te偶 da sok z cytryny, ale limonka bdzie najlepsza. Na koniec jeszcze przyprawy: paska y偶eczka soli; p贸 paskiej y偶eczki cukru; po szczypcie cynamonu, kminku i ziela angielskiego. Jeli nie masz mielonego ziela, to mo偶esz pomin t przypraw.
Wszystkie skadniki na sals bardzo dokadnie wymieszaj. Salsa pomidorowa jest ju偶 gotowa.

Sals warto na 20 minut odo偶y do lod贸wki, by wszystkie smaki si przegryzy a salsa schodzia. Po tym czasie warto spr贸bowa jak smakuje i zdecydowa, czy dola wicej soku z limonki lub mo偶e dosypa odrobin soli. Jeli salsa wysza za ostra, to dodaj do niej wicej siekanych drobno pomidor贸w lub te偶 wlej sok z pomidor贸w.

Salsa jest bardzo wa偶na w kuchni meksykaskiej. To salsa nadaje wyrazistoci ka偶demu daniu. Podaje si j praktycznie do ka偶dej uczty. Podajemy j do da z u偶yciem tortilli, fasoli, ry偶u, czy tacos. Najczciej jednak podajemy j jak przeksk z chipsami nachos.

|===

[.text-center]
== Zdjcia
