= Salsa pomidorowa  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* https://aniagotuje.pl/przepis/salsa[link do 藕r贸da przepisu]

== Skadniki
* 400 g dojrzaych pomidor贸w
* malutka czerwona cebula - okoo 80 g
* 3 zbki czosnku - 15 g
* 3 y偶ki soku z limonki
* p贸 maej papryczki chili - okoo 10 g
* gar wie偶ej kolendry
* przyprawy: paska y偶eczka soli; p贸 paskiej y偶eczki cukru; po szczypcie cynamonu, kminku i ziela angielskiego

|
== Przygotowanie
Sos salsa to jedna z pyszniejszych wizyt贸wek kulinarnych Meksyku. Zapraszam Ci po m贸j ulubiony przepis na sos salsa z pomidorami, kt贸ry podaj nie tylko do chips贸w nachos.
- prosty przepis
- kilka propozycji podania
- dokadny opis szykowania i wiele porad  Czas przygotowania: 15 minut
Liczba porcji: okoo 470 g salsy

W 100 g :

Warto energetyczna
23 kcal

Dieta:   bezglutenowa, wegaska, wegetariaska
Skadniki400 g dojrzaych pomidor贸wmalutka czerwona cebula - okoo 80 g3 zbki czosnku - 15 g3 y偶ki soku z limonkip贸 maej papryczki chili - okoo 10 ggar wie偶ej kolendryprzyprawy: paska y偶eczka soli; p贸 paskiej y偶eczki cukru; po szczypcie cynamonu, kminku i ziela angielskiego

Skadniki:  Kopiuj     Ukryj zdjcia

Salsa
Warzywa/owoce wa偶one byy przed ewentualnym obraniem/przygotowaniem.
Kalorie policzone zostay na podstawie u偶ytych przeze mnie skadnik贸w. Jest to wic orientacyjna liczba kalorii, poniewa偶 Twoje skadniki mog mie inn ilo kalorii ni偶 te, kt贸rych u偶yam ja. Z podanej iloci skadnik贸w otrzymasz okoo 470 gram贸w salsy.
Moja ulubiona salsa to poczenie dw贸ch przepis贸w. Znajdziesz w niej g贸wne skadniki na sals cruda oraz kilka pysznych dodatk贸w, kt贸re s bardzo wa偶ne, przy szykowaniu salsy chipotle. To poczenie, kt贸re odpowiada mi nie tylko smakiem, ale i warunkami jakie mamy w Polsce, poniewa偶 nie wszystkie skadniki s tak atwo u nas dostpne.





Sos salsa
Okoo 400 gram贸w pomidor贸w bardzo drobno siekam no偶em. Jeli u偶ywam du偶ych pomidor贸w, to najpierw wykrajam twarde fragmenty przy szypuce. Latem sigam po pachnce, bardzo dojrzae i czerwone pomidory sezonowe. Poza sezonem kupuj zazwyczaj mini pomidorki: truskawkowe, cherry, koktajlowe.
Malutk, czerwon cebul obieram i bardzo drobno siekam. miao mo偶na te偶 u偶y trzech cebulek szalotek lub r贸wnie maej cebuli czosnkowej albo zwykej. Trzy zbki czosnku r贸wnie偶 obieram i osobno siekam drobniutko no偶em. Gar wie偶ej kolendry (listki i ody偶ki) przepukuj, osuszam i siekam r贸wnie drobno jak czosnek. Jeli nie masz lub nie lubisz smaku wie偶ej kolendry, to polecam w zastpstwie natk pietruszki (kolendra jest jednak wedug mnie obowizkowa ;).
Jeli chodzi o papryczki chili, to z nimi bywa bardzo r贸偶nie. Sprawdzam zawsze, jak ostre papryczki mi si trafiy i decyduj, czy posieka ca papryczk, czy tylko kawaek. Tym razem dodaam poow wie偶ej papryczki, czyli okoo 10 gram贸w. Pamitaj o tym podczas szykowania salsy.
Wyciskam jeszcze trzy y偶ki soku z limonki (czasem daj wicej). Mo偶na te偶 da sok z cytryny, ale limonka bdzie najlepsza. Na koniec jeszcze przyprawy: paska y偶eczka soli; p贸 paskiej y偶eczki cukru; po szczypcie cynamonu, kminku i ziela angielskiego. Jeli nie masz mielonego ziela, to mo偶esz pomin t przypraw.
Wszystkie skadniki na sals bardzo dokadnie wymieszaj. Salsa pomidorowa jest ju偶 gotowa.






Sals warto na 20 minut odo偶y do lod贸wki, by wszystkie smaki si przegryzy a salsa schodzia. Po tym czasie warto spr贸bowa jak smakuje i zdecydowa, czy dola wicej soku z limonki lub mo偶e dosypa odrobin soli. Jeli salsa wysza za ostra, to dodaj do niej wicej siekanych drobno pomidor贸w lub te偶 wlej sok z pomidor贸w.

Porada: Aby salsa miaa bardziej jednolit konsystencj, mo偶na j zmiksowa w blenderze lub malakserze. Jeli masz w swoich zapasach past z mielonych papryczek Chili Chipotle w Sosie Adobo, to mo偶esz j doda do swojej salsy.







Salsa jest bardzo wa偶na w kuchni meksykaskiej. To salsa nadaje wyrazistoci ka偶demu daniu. Podaje si j praktycznie do ka偶dej uczty. Podajemy j do da z u偶yciem tortilli, fasoli, ry偶u, czy tacos. Najczciej jednak podajemy j jak przeksk z chipsami nachos.


Poniewa偶 sals robi si bardzo prosto i szybko, to podam jeszcze kilka propozycji na inne meksykaskie salsy. By mo偶e Ty znasz zupenie inne ich wersje. Ja znam takie :)

Salsa Jalape帽o

1 maa cebulka

2 zbki czosnku

4 y偶ki piklowanych papryczek chili jalape帽o

sok z po贸wki cytryny

1/4 y偶eczki mielonego kminku

1 paska y偶eczka soli


Cebul i czosnek obierz i drobno posiekaj. Posiekaj te偶 papryczki i dodaj sok z cytryny i przyprawy. Cao wymieszaj i od贸偶 do schodzenia.

Gotowana salsa chipotle


3 suszone papryczki chili chipotle

1 rednia cebula

400 g pomidor贸w z puszki, razem z sosem

2 y偶ki brzowego cukru muscovado

3 zbki czosnku

sok z po贸wki cytryny

1 y偶ka oliwy extra virgin

przyprawy: po sporej szczypcie mielonego kminku i cynamonu; po szczypcie mielonych go藕dzik贸w lub ziela angielskiego


Suszone papryczki chili chipotle umie w niewielkim garnku. Wlej do niego tyle wody, by tylko zakry ni papryczki. Uwa偶aj na opary z garnka (nie pochylaj si nad garnkiem) i otw贸rz okno lub wcz kuchenny wentylator. Zagotuj wod z chili. Zmniejsz moc palnika i gotuj papryczki bez przykrycia, (na maej mocy) przez pi minut. Nastpnie odstaw garnek z papryczkami do przestudzenia. W trakcie studzenia papryczki jeszcze zmikn. y偶k cedzakow wyjmij papryczki z garnka. Usu gniazda nasienne a papryczki posiekaj (u偶ywaj rkawiczek).
W innym garnku umie obran i posiekan cebul oraz pomidory i cukier. Cao gotuj okoo 10 minut, a偶 sos zgstnieje. Garnek odstaw z palnika. Dodaj obrane i drobno posiekane zbki czosnku, przyprawy, sok z cytryny, oliw oraz przygotowane chili chipotle. Cao zamieszaj i sprawd藕 smak sosu. W razie potrzeby dopraw sos przez dodanie odrobiny soli. Gotowany sos salsa podawaj ciepy lub schodzony. Ten sos idealnie nadaje si do mro偶enia. Salsa ze wie偶ego ananasa
p贸 dojrzaego ananasa
sok z jednej limonki
1 zbek czosnku
1 cebulka dymka
1 maa, wie偶a papryczka chili
p贸 sodkiej czerwonej papryki
po 3 y偶ki wie偶ych listk贸w mity i kolendry
po szczypcie soli i cukru
Ostrym no偶em odetnij g贸r i d贸 ananasa. Postaw go pionowo na desce i usuwaj sk贸rk zaczynajc krojenie od g贸ry. Gdy masz ju偶 sam oczyszczony mi偶sz z rdzeniem, przepucz ananasa pod zimn wod i umyj tez desk i n贸偶. Ananasa przekr贸j na p贸. Po贸wk, kt贸r potrzebujesz do salsy przekr贸j jeszcze na p贸, by atwiej Ci byo usun twardy rdze. Mi偶sz pokr贸j w drobn kostk.
Drobno pokrojonego ananasa (razem z sokiem, kt贸ry zebra si przy krojeniu) umie w misce. Dodaj te偶 sok z limonki oraz drobno posiekan cebul dymk i papryczk chili (wczeniej dokadnie oczyszczon z gniazda nasiennego). Zwyk papryk r贸wnie偶 oczy i drobno posiekaj. Listki mity i kolendry posiekaj i dodaj do reszty skadnik贸w. Na koniec jeszcze po szczypcie soli i cukru. Wymieszaj wszystkie skadniki salsy i odstaw do schodzenia. Porada: Ananas mo偶na zastpi pomaraczami. Trzeba je jednak bardzo dokadnie obra, by otrzyma "goy" mi偶sz. T sals bardzo gorco polecam do da z ry偶em, z kurczakiem i z krewetkami. Salsa verde
450 g tomatillos z puszki
1 wie偶a zielona papryczka chili lub jalape帽o albo serrano
1 zielona papryka
1 maa cebula
1 pczek wie偶ych lici kolendry
p贸 y偶eczki mielonego kminku
p贸 paskiej y偶eczki soli
Tomatillos z puszki drobno posiekaj. Mo偶na je zastpi cierpkimi pomidorami. Do siekanych pomidor贸w dodaj te偶 drobno posiekan papryczk chili (wczeniej dokadnie oczyszczon z gniazda nasiennego). Zwyk, zielon papryk r贸wnie偶 oczy i drobno posiekaj. Mo偶esz j zastpi agodn papryczk chili w kolorze zielonym lub te偶 papryczk anaheim albo poblano. Cebul obierz i tak samo bardzo drobno posiekaj. Do skadnik贸w dodaj siekane listki kolendry oraz przyprawy. Wymieszaj wszystkie skadniki salsy verde i odstaw do schodzenia. Przed podaniem sprawd藕 smak i w razie potrzeby dodaj wicej soli.
Jaka jest Twoja ulubiona salsa i z czym j podajesz? Bardzo czsto szykuj sals z pysznym Fajitas z kurczakiem.
Smacznego!
殴r贸do przepis贸w z moimi zmianami: "Cookshelf Mexican", Marlena Spieler

|===

[.text-center]
== Zdjcia
