= Sos grzybowy  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 30 minut
* 2 - 4 porcje
* https://www.kwestiasmaku.com/zielony_srodek/grzyby/sos_grzybowy/przepis.html[link do 藕r贸da przepisu]

== Skadniki

* ok. 500 g grzyb贸w (np. borowik贸w, podgrzybk贸w, kurek, malak贸w)
* 1 cebula
* 2 zbki czosnku
* 50 g masa
* 125 ml bulionu (np. z kostki)*
* 125 ml mietanki 30%
* 1 y偶ka posiekanej natki pietruszki lub koperku
* kilka kropli soku z cytryny lub octu winnego

|
== Przygotowanie

Grzyby przebra, wybra do sosu adne, nierobaczywe grzyby. Przyci n贸偶ki w razie koniecznoci, dokadnie oczyci grzyby no偶ykiem oraz szczoteczk, unikajc w miar mo偶liwoci pukania / moczenia. Nastpnie pokroi na plasterki.

Cebul posieka w drobn kostk, czosnek przecisn przez prask lub zetrze na drobnej tarce.

Na wikszej patelni roztopi poow masa. Wo偶y cebul i zeszkli j, sma偶c na umiarkowanym ogniu, przez okoo 3 - 4 minuty. Pod koniec doda czosnek.

Zwikszy ogie, doda grzyby oraz pozostae maso. Doprawi sol oraz pieprzem i dokadnie obsma偶y, przez ok. 8 minut, od czasu do czasu mieszajc.

Wla bulion i gotowa przez okoo 2 minuty. Wla mietank, wymiesza i zagotowa. Doda posiekan natk pietruszki lub koperek i odstawi z ognia.

Sos mo偶na doprawi kwanym dodatkiem np. odrobin soku z cytryny lub octu.

|===

[.text-center]
== Zdjcia
