= +++<a href="../../index.html" class="back-to-home-btn">← Wróć do przepisów</a>+++ Sos grzybowy 🌱 +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++
:imagesdir: /Recipes/static/images

[.recipe-hero]
[.card-image-placeholder]
Brak zdjęcia przepisu 🍲

[.recipe-details]
* 🕒 czas przygotowania: 30 minut
* 🕒 czas gotowania: 30 minut
* 👥 4 porcje
* 🔗 https://www.kwestiasmaku.com/zielony_srodek/grzyby/sos_grzybowy/przepis.html[link do źródła przepisu]

[.recipe-columns]
== Składniki
* ok. 500 g grzybów (np. borowików, podgrzybków, kurek, maślaków)
* 1 cebula
* 2 ząbki czosnku
* 50 g masła
* 125 ml bulionu (np. z kostki)*
* 125 ml śmietanki 30%
* 1 łyżka posiekanej natki pietruszki lub koperku
* kilka kropli soku z cytryny lub octu winnego

== Przygotowanie
Grzyby przebrać, wybrać do sosu ładne, nierobaczywe grzyby. Przyciąć nóżki w razie konieczności, dokładnie oczyścić grzyby nożykiem oraz szczoteczką, unikając w miarę możliwości płukania / moczenia. Następnie pokroić na plasterki.

Cebulę posiekać w drobną kostkę, czosnek przecisnąć przez praskę lub zetrzeć na drobnej tarce.

Na większej patelni roztopić połowę masła. Włożyć cebulę i zeszklić ją, smażąc na umiarkowanym ogniu, przez około 3 - 4 minuty. Pod koniec dodać czosnek.

Zwiększyć ogień, dodać grzyby oraz pozostałe masło. Doprawić solą oraz pieprzem i dokładnie obsmażyć, przez ok. 8 minut, od czasu do czasu mieszając.

Wlać bulion i gotować przez około 2 minuty. Wlać śmietankę, wymieszać i zagotować. Dodać posiekaną natkę pietruszki lub koperek i odstawić z ognia.

Sos można doprawić kwaśnym dodatkiem np. odrobiną soku z cytryny lub octu.

[.recipe-gallery]
== Zdjęcia

[.gallery-grid]
// Tutaj pojawią się zdjęcia
