= Tatar ze śledzia

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 15 min 
* 2 porcje
* https://www.kwestiasmaku.com/ryby_i_owoce_morza/sledzie/tatar_ze_sledzia/przepis.html[link do źródła przepisu]

== Składniki
* 2 filety śledziowe (np. w oleju lub marynowane w occie lub wypłukanych z soli)
* 2 łyżeczki posiekanej natki
* świeżo zmielony czarny pieprz
* 1 łyżeczka musztardy
* 1 łyżeczka soku z cytryny
* szczypta brązowego cukru
* 2 łyżki marynowanej ostrej papryczki np. jalapeño, peperoni
* 3 łyżki marynowanych podgrzybków + 1 łyżka cebulki marynowanej
* 1 łyżka posiekanego szczypiorku
* olej lniany
|
== Przygotowanie
Filety marynowane w occie dokładnie osuszyć papierowym ręcznikiem, filety w oleju po prostu odsączyć i wyjąć na deskę. Każde śledzie spróbować i ocenić czy nie są za słone.

Śledzie drobniutko posiekać razem z natką pietruszki, dodać świeżo zmielony pieprz, musztardę, sok z cytryny i cukier i wszystko razem wymieszać siekając.

Posiekać też marynowane papryczki jalapeño, marynowane podgrzybki i cebulkę, szczypiorek, wszystko wymieszać ze śledziami.

Małe filiżanki smarować olejem lnianym, wypełnić tatarem i wykładać na talerzyki. Udekorować listkiem natki lub posiekanym szczypiorkiem, ewentualnie grzybkiem marynowanym.

== Zdjęcia
|===
