= Tortille placki +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 25 min
* 12 sztuk
* https://www.kwestiasmaku.com/przepis/tortille[link do źródła przepisu]

== Składniki
* 2 szklanki mąki pszennej
* 1/2 łyżeczki soli
* 3 łyżki smalcu lub oleju kokosowego lub masła
* 2/3 szklanki wrzącej wody

|
== Przygotowanie

Do miski wsypać mąkę, dodać sól i smalec lub olej kokosowy. Dodawać stopniowo wrzącą wodę (wlewać ją bezpośrednio na tłuszcz) i mieszać składniki widelcem. Połączyć je i uformować kulę. Wyrabiać przez ok. 3 minuty aż ciasto będzie gładkie. Zawinąć w folię spożywczą i odstawić na 1 godzinę w temp. pokojowej.

Ciasto podzielić na 10 lub 16 równych części i uformować kulki, odstawić na minimum 10 minut, maksymalnie na 1 i 1/2 godziny, przykryć aby nie obeschły.

Kolejno rozwałkowywać wałkiem ciasto na bardzo cieniutkie placki. Kłaść na rozgrzanej, suchej patelni. Po około 30 sekundach smażenia, gdy tortilla wypełni się pęcherzami powietrza i pokryje się brązowymi plamkami, przewrócić na drugą stronę i smażyć przez kolejne 30 sekund. Tortilla napuszy się jeszcze bardziej i znów pokryje się brązowymi plamkami, tym razem z drugiej strony.

Jeszcze raz przewrócić tortillę i jak tylko jej rozmiar się ustabilizuje, po około 15 - 30 sekundach, zdjąć z patelni i układać w stosik.

Usmażyć resztę placków jak wyżej, odpowiednio dostosowując stopień rozgrzania patelni.

Aby łatwiej było zawijać tortillę z nadzieniem lub kroić ją na chipsy, usmażone tortille trzymam przez jakiś czas zawinięte w wilgotną ściereczkę. Można je też podgrzać.

|===

[.text-center]
== Zdjęcia
