= Tortille placki  +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: 25 min
* 12 sztuk
* https://www.kwestiasmaku.com/przepis/tortille[link do 藕r贸da przepisu]

== Skadniki
* 2 szklanki mki pszennej
* 1/2 y偶eczki soli
* 3 y偶ki smalcu lub oleju kokosowego lub masa
* 2/3 szklanki wrzcej wody

|
== Przygotowanie

Do miski wsypa mk, doda s贸l i smalec lub olej kokosowy. Dodawa stopniowo wrzc wod (wlewa j bezporednio na tuszcz) i miesza skadniki widelcem. Poczy je i uformowa kul. Wyrabia przez ok. 3 minuty a偶 ciasto bdzie gadkie. Zawin w foli spo偶ywcz i odstawi na 1 godzin w temp. pokojowej.

Ciasto podzieli na 10 lub 16 r贸wnych czci i uformowa kulki, odstawi na minimum 10 minut, maksymalnie na 1 i 1/2 godziny, przykry aby nie obeschy.

Kolejno rozwakowywa wakiem ciasto na bardzo cieniutkie placki. Ka na rozgrzanej, suchej patelni. Po okoo 30 sekundach sma偶enia, gdy tortilla wypeni si pcherzami powietrza i pokryje si brzowymi plamkami, przewr贸ci na drug stron i sma偶y przez kolejne 30 sekund. Tortilla napuszy si jeszcze bardziej i zn贸w pokryje si brzowymi plamkami, tym razem z drugiej strony.

Jeszcze raz przewr贸ci tortill i jak tylko jej rozmiar si ustabilizuje, po okoo 15 - 30 sekundach, zdj z patelni i ukada w stosik.

Usma偶y reszt plack贸w jak wy偶ej, odpowiednio dostosowujc stopie rozgrzania patelni.

Aby atwiej byo zawija tortill z nadzieniem lub kroi j na chipsy, usma偶one tortille trzymam przez jaki czas zawinite w wilgotn ciereczk. Mo偶na je te偶 podgrza.

|===

[.text-center]
== Zdjcia
