= Wegański tatar

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 45 min
* 7 porcji
* https://easyvege.pl/weganski-tatar[link do źródła przepisu]

== Składniki
Tatar:

* 650-700 g surowych boczniaków (ważonych po oczyszczeniu, ale jeszcze przed myciem)
* 80-100 g ekspandowanych ziaren (np. ryż, jagły, kukurydza, ja użyłam tym razem orkiszu)
* kilka pomidorów suszonych, z oleju (użyłam 6 połówek)
* 5-7 łyżeczek koncentratu pomidorowego
* 1-2 łyżeczki łagodnej musztardy
* 100 ml wody
* 50 ml oleju
* 1 niewielka cebula cukrowa LUB 2 średniej wielkości szalotki
* 1 ząbek czosnku
* 2 łyżeczki płatków drożdżowych
* 2 łyżki sosu sojowego ciemnego
* ½ łyżeczki soli, do smaku
* ½ łyżeczki pieprzu świeżo mielonego, do smaku
* 1 solidna łyżeczka słodkiej papryki
* duża szczypta brązowego cukru
* ostre chili, do smaku

Dodatkowo:

* jako żółtko: majonez wegański + sól czarna Kala Namak + kurkuma
* ogórki kiszone
* grzybki marynowane
* cebulka cukrowa lub szalotka
* świeżo mielony pieprz
* pieczywo

|
== Przygotowanie

Boczniaki oczyszczamy najpierw na sucho z zabrudzeń, następnie płuczemy na sicie pod bieżącą wodą i pozbywamy się nadmiaru wody wielokrotnie potrząsając energicznie sitem. Nie chodzi o to, by grzyby stały się suche. Powinny zostać wilgotne! - chodzi tylko o to, by nie ciekła z nich woda.
Rozgrzewamy patelnię i smarujemy ją cieniutko olejem. Na rozgrzanej patelni układamy boczniaki, pozwalamy im się smażyć przez ok. 3 minuty. Następnie przewracamy grzyby na drugą stronę i znów podsmażamy przez ok. 3minuty. Powtarzamy partiami, do ostatniego grzybka. Tak przygotowane grzyby nie będą już surowe, ALE nie powinny być też przypieczone. Podczas podsmażania puszczą wodę, którą warto zebrać z patelni razem z grzybami.
UWAGA: Podczas smażenia NIE DOTYKAMY BOCZNIAKÓW poza tym jednym momentem, gdy je przewracamy! Ich wilgotność w połączeniu z odpowiednim smażeniem, zapewni grzybom pożądaną strukturę, podobną do struktury mięsa.

Podsmażone, ostygnięte boczniaki siekamy ostrym nożem w najdrobniejszą kosteczkę jaką potrafimy pokroić.
UWAGA: Nie próbujcie zmielić w maszynce - niestety boczniaki wtedy dużo tracą. Stają się papką, a nie o taki efekt tu chodzi.

Cebulę i suszone pomidory kroimy najdrobniej jak potrafimy. Czosnek przeciskamy przez praskę.
W dużej misce łączymy wodę, olej, koncentrat pomidorowy, musztardę, sos sojowy, płatki drożdżowe, sól, pieprz, paprykę słodką, cukier i ew. ostre chili. Mieszamy dokładnie, do uzyskania czerwonego sosu.
Do miski z czerwonym płynem wsypujemy ekspandowane ziarno i mieszamy. Spróbujcie tak wymieszać płyn z ziarnami, jakbyście starali się rozcierać ziarna z płynnym sosem. Po chwili to stanie się dużo łatwiejsze niż na początku, gdy ziarna zmiękną i wciągną płyn.
Następnie do czerwonej masy dodajemy cebulę, czosnek, pomidory suszone i boczniaki. Mieszamy wszystko dokładnie i odstawiamy na blat, na ok. 20-30 minut.
Teraz warto nastawić sobie przypomnienie w telefonie i co kilka minut mieszać tatara raz jeszcze. Każde kolejne mieszanie sprawi, że uzyskamy coraz lepszą konsystencję.
Idealnie wymieszanego tatara możemy podawać od razu LUB przed podaniem odstawić na kilka godzin do lodówki. Najpyszniejszy będzie oczywiście na drugi dzień po przyrządzeniu.

== Zdjęcia
|===
