= Kompot czereśniony

[cols=".<2a,.<2a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły

* 4 słoiki po 900 ml
* czas przygotownia: 20 minut
* czas pasteryzacji: 20 minut
* https://aniagotuje.pl/przepis/kompot-z-czeresni[Link do żródła przepisu]

== Składniki

* 2 kg czereśni
* 3 łyżki cukru
* 2 litry przegotowanej wody

|
== Przygotowanie

Zacznij od wybrania dojrzałych oraz nieuszkodzonych i nie zepsutych czereśni. Mój przepis bazuje na czereśniach o łącznej wadze 1,5 kg. Możesz śmiało podwoić, czy nawet potroić ilość owoców. Pamiętaj jednak o tym, że potrzebujesz wówczas przygotować więcej słoików oraz cukru i wody.

Czereśnie umyj pod zimną i bieżącą wodą. Polecam nawet umieścić je w dużej misce z zimną wodą i odrobiną sody oczyszczonej (mała łyżeczka). Po umyciu czereśni w lekkim roztworze przepłucz je raz jeszcze zimną wodą i usuń ogonki.

Ja nie usuwam pestek z czereśni. Jeśli jednak chcesz je wyjąć, to możesz to zrobić. Polecam wówczas rozcinać każdą czereśnię na pół przy pomocy ostrego nożyka i wyjmować pestki. 

Przygotuj też cztery czyste słoiki o pojemności 900 ml każdy. Śmiało można też użyć litrowych słoików. Słoiki powinny być idealnie czyste, a najlepiej odparzone wrzątkiem. Tak samo zakrętki. Używaj tylko nieuszkodzonych słoików i zakrętek. 
Do każdego słoika daj tyle samo czereśni. Swoje słoiki wypełniam czereśniami do około 3/4 wysokości. Do każdego słoika z owocami wsyp też cukier - po trzy łyżki (u mnie cukier drobny). Łącznie wyjdzie około 200 gramów cukru. Używam najzwyklejszego białego cukru, ale można też sięgnąć po cukier trzcinowy. 

Porada: Aby wzbogacić smak kompotu, do słoików oprócz cukru można też dodać po dwie łyżki soku z cytryny. Do słoików można też dodać więcej cukru. U mnie jest to około 50 gramów cukru na słoik, ale śmiało można dać nawet do 100 gramów cukru na słoik (4-6 łyżek). Kompot będzie wówczas znacznie słodszy. 

== Zdjęcia

|===