= Buraki po burgundzku  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: powy偶ej godziny
* 6 - 8 porcji
* https://www.jadlonomia.com/przepisy/burak-z-burgundii[link do 藕r贸da przepisu]

== Skadniki

* 6 szalotek
* 500 g maych pieczarek
* 2 marchewki
* 1 maa pietruszka
* 1 szklanka zielonej soczewicy
* 4 mae buraczki
* 100 g orzech贸w laskowych
* 5 y偶ek koncentratu pomidorowego
* 1 陆 litra bulionu warzywnego
* 1 录 szklanki czerwonego wytrawnego wina
* 3 zbki czosnku
* 4 gazki tymianku
* 2 gazki rozmarynu
* 3 licie laurowe
* s贸l i wie偶o mielony czarny pieprz
* oliwa

|
== Przygotowanie

Szalotki obra, ale nie kroi. Po kolei nadziewa ka偶d z nich na widelec i opala nad palnikiem gazowym przez kilka minut, dop贸ki nie bdzie mocno przypalona. Opalone szalotki odo偶y na bok.

Pieczarki pokroi na wiartki, te najmniejsze wystarczy przekroi na p贸. Na dnie du偶ego garnka z bardzo grubym dnem rozgrza kilka y偶ek oliwy i doda pokrojone pieczarki, poddusi przez chwil i doda opalone szalotki pokrojone w bardzo grube plastry.

Doda pokrojone w p贸-talarki marchewki, pokrojon w drobn kostk pietruszk, buraczki, pokrojone w grube paski, orzechy laskowe i drobno posiekany czosnek. Warzywa kilka razy delikatnie wymiesza, nastpnie doda soczewic, bulion, wino, przecier pomidorowy i zioa. Wsypa spor szczypt soli i gotowa na minimalnym ogniu przez przynajmniej godzin.

Po upywie godziny spr贸bowa i doda s贸l oraz pieprz do smaku. W razie potrzeby doda jeszcze p贸 szklanki bulionu i gotowa kolejne p贸 godziny.

Gotowy gulasz je z bagietk lub chlebem, koniecznie wycierajc sp贸d talerza kawakiem pieczywa. Gulasz jest lepszy z ka偶dym kolejnym dniem, szczeg贸lnie warto poczeka do trzeciego dnia.

|===

[.text-center]
== Zdjcia
