= +++<a href="../../index.html" class="back-to-home-btn">← Wróć do przepisów</a>+++ Bułeczki baozi 🌱 +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++
:imagesdir: /Recipes/static/images

[.recipe-hero]
[.card-image-placeholder]
Brak zdjęcia przepisu 🍲

[.recipe-details]
* 🕒 czas przygotowania: 2 godziny
* 🕒 czas gotowania: 2 godziny
* 👥 3 porcje
* 🔗 https://kuchnialidla.pl/baozi-azjatyckie-buleczki-z-wieprzowina[link do źródła przepisu]

[.recipe-columns]
== Składniki

* mąka pszenna - 400 g
* mleko 1,5% - 200 ml
* drożdże świeże - 12 g
* masło - 45 g
* olej słonecznikowy - 1,5 łyżki
* sól - 1 szczypta
* olej sezamowy - 1 łyżeczka

== Przygotowanie

W rondelku podgrzewamy delikatnie mleko, a potem rozpuszczamy w nim drożdże. W misce łączymy ze sobą sól, masło, mąkę oraz rozpuszczone drożdże i wyrabiamy ciasto. Miskę delikatnie smarujemy olejem sezamowym i zostawiamy w niej ciasto pod przykryciem na godzinę.

Po tym czasie ciasto dzielimy na 12 równych części, z których formujemy kulki. Każdą kulkę rozwałkowujemy na placek o średnicy około 10 cm. Na środek każdego placka nakładamy łyżkę nadzienia (np. wieprzowina Char) i zawijamy w kształt sakiewki, dokładnie zlepiamy brzegi.

Zagotowujemy wodę w garnku do gotowania na parze. Bułeczki gotujemy na parze przez około 25 minut. Po ugotowaniu czekamy chwilę, aż bułeczki lekko przestygną, a następnie podajemy.

[.recipe-gallery]
== Zdjęcia

[.gallery-grid]
// Tutaj pojawią się zdjęcia
