= Chakalaka 🌱 +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 30 min
* 2 porcje
* https://kuchnialidla.pl/chakalaka[link do źródła przepisu]

== Składniki
* cebula - 1 szt.
* curry - 3 szczypty
* papryka czerwona - 1 szt.
* ząbek czosnku - 3 szt.
* imbir świeży - 4 g
* marchew - 3 szt.
* olej rzepakowy - 2 łyżki
* papryczka chili czerwona - 1 szt.
* pieprz czarny - 1 szczypta
* pomidory krojone z puszki - 400 g
* sól - 1 szczypta
* tymianek suszony - 1 szczypta
* tymianek świeży - 10 g
* papryka żółta - 1 szt.

|
== Przygotowanie
Pokrojoną w drobną kostkę cebulę oraz drobno posiekany czosnek i imbir podsmażamy w garnku na rozgrzanym oleju. Dodajemy curry, tymianek, sól i pieprz. Mieszamy i smażymy, aż cebula się zeszkli.

Dodajemy marchew startą na tarce o dużych oczkach, chwilę podsmażamy i dodajemy pomidory oraz paprykę pokrojoną w kostkę. Mieszamy i dusimy, aż warzywa będą miękkie. W razie potrzeby ponownie doprawiamy solą i pieprzem.

Gotową chakalakę przekładamy na talerz i posypujemy z wierzchu odrobiną curry. Podajemy z kilkoma gałązkami świeżego tymianku.

|===

[.text-center]
== Zdjęcia
