= Cukinia faszerowana

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 1 h
* 4 porcje po 383 kcal
* https://www.kwestiasmaku.com/przepis/cukinia-zapiekana-z-miesem-drobiowym-i-ryzem[link do źródła przepisu]

== Składniki

* 1 łyżka oliwy
* 1 cebula
* 2 ząbki czosnku
* 400 g mielonego mięsa (np. z szynki wieprzowej, indyka)
* 1 łyżka sosu worcestershire lub sojowego
* przyprawy: sól, pieprz, słodka i ostra papryka w proszku, suszone oregano, kurkuma
* 350 ml bulionu
* 50 g ryżu
* 3 cukinie (po ok. 370 g)
* 1 łyżka natki pietruszki
* 1 jajko
* 150 g tartego sera (np. mozzarelli)

|
== Przygotowanie
Na dużej patelni na oliwie zeszklić cebulę pokrojoną w kosteczkę, pod koniec dodać starty czosnek. Zwiększyć ogień i dodać zmielone mięso. Smażyć przez 5 minut, mieszając od czasu do czasu.

Dodać sos worcestershire lub sos sojowy oraz przyprawy: sól, pieprz oraz po pół łyżeczki słodkiej i ostrej papryki, oregano oraz kurkumy. Smażyć jeszcze przez 1 minutę, następnie wlać gorący bulion, wsypać ryż i zagotować. Przykryć patelnię i dusić przez około 25 minut. Jeśli na koniec pozostał jakiś płyn, należy go wygotować bez przykrycia.

W międzyczasie przygotować cukinię: piekarnik nagrzać do 180 stopni C. Cukinię umyć, osuszyć, przekroić wzdłuż na pół i położyć na blaszce wyłożonej papierem do pieczenia, rozcięciem do góry. Piec przez 10 minut. Łyżeczką wybrać miąższ ze środka, pozostawiając około 1/2 cm brzeg. Wycięty miąższ posiekać. Połówki cukinii doprawić solą.

Do ugotowanego mięsa na patelni dodać posiekany miąższ cukinii, połowę jednego pomidora (obranego i pokrojonego w kosteczkę) i smażyć wszystko jeszcze przez ok. 5 minut. Pod koniec dodać natkę pietruszki.

Odstawić z patelni i po lekkim przestudzeniu dodać jajko, wymieszać. Powstałym farszem wypełnić wgłębienia w cukinii. Posypać tartym serem. Wstawić do piekarnika na około 25 minut, 180 stopni C.

== Zdjęcia
|===
