= Curry z kalafiora

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: do 45 minut
* 4 - 5 porcji
* https://www.jadlonomia.com/przepisy/na-przednowku-czyli-ulubione-curry-z[link do źródła przepisu]

== Składniki
* Składniki na curry:
* 1 cebula, pokrojona w kostkę
* 2 łyżeczki tartego imbiru
* 1 czubata łyżeczka mielonego kuminu
* 1 łyżeczka mielonej kolendry
* 4 goździki
* ½ łyżeczka kurkumy
* ¼ łyżeczka asofoteitydy, można zastąpić ząbkiem czosnku
* ¼ łyżeczki cynamonu
* 2 liście kafiru, można zastąpić odrobiną soku z cytryny
* olej
* 1 kalafior, podzielony na różyczki
* 1 ziemniak, obrany i pokrojony w kostkę
* 1 puszka krojonych pomidorów
* 1 ½ - 2 szklanki wody
* sól
* Składniki na ryż:
* 2 szklanki ryżu
* 3 szklanki wody
* laska cynamonu
* łyżeczka kurkumy
* łyżka dobrego oleju
* sól

|
== Przygotowanie
Na dnie dużego garnka z grubym dnem rozgrzać kilka łyżek oleju, dodać cebulę i zeszklić. Dodać wszystkie przyprawy, smażyć przez 2-3 minuty.

Następnie dodać kalafiora i ziemniaka, wszystko delikatnie, ale bardzo dokładnie wymieszać i wlać wodę oraz pomidory. Gotować na małym ogniu przez około 20 minut albo do miękkości warzyw, powinny być miękkie, ale nie rozgotowane.

W międzyczasie przygotować ryż. Do niedużego garnka dodać wszystkie składniki, garnek przykryć i gotować na małym ogniu przez 5 minut. Potem wyłączyć ogień i pozostawić ryż w garnku kolejne 15 minut - w tym czasie wchłonie wodę i będzie puszysty.

Gotowe curry spróbować, dosolić do smaku i ewentualnie dodać kilka kropel soku z cytryny. Podawać bardzo gorące, z cynamonowym ryżem.

== Zdjęcia
|===
