= Dal z soczewicy z Sri Lanki 🌱 +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły

* czas przygotowania: 10 minut + 20 minut czekania
* 4 - 6 porcji
* https://www.jadlonomia.com/przepisy/dahl-soczewicowy-ze-sri-lanki[link do źródła przepisu]

== Składniki

* 350 g soczewicy czerwonej / 2 szklanki
* 2 ½ szklanki wody
* 1 ½łyżeczki kurkumy
* Do podsmażenia:
* 1 duża cebula
* 1 ½ łyżeczki ziaren kuminu
* 1 łyżeczka kozieradki
* 1 łyżeczka czarnej gorczycy
* 30 świeżych liści curry / 3 łyżki suszonych liści curry
* ½ papryczki chili lub szczypta płatków chili
* 2 - 3 łyżki oleju
* 1 puszka kokosowego mleczka / 400 ml
* sól

|
== Przygotowanie

Soczewicę dokładnie opłukać. Następnie przełożyć do garnka, dodać odmierzoną wodę oraz kurkumą i gotować pod przykryciem na niedużym ogniu do momentu, aż soczewica będzie lekko miękka, czyli około 10 minut.

Po upływie tego czasu cebulę pokroić w drobną kostkę, a na patelni mocno rozgrzać kilka łyżek oleju. Na olej wrzucić kumin, gorczycę, kozieradkę, chili oraz cebulę i smażyć przez 3 minuty, do momentu aż będzie przezroczysta i zacznie się lekko złocić. Następnie dodać liście curry, smażyć ostatnią minutę, a gorący olej wraz z przyprawami wlać do soczewicy.

Do garnka z soczewicą dodać kokosowe mleko, pół łyżeczki soli, doprowadzić do bulgotania i pozwolić się gotować ostatnie 5 minut. Na koniec doprawić do smaku solą, podawać z ryżem lub plackami.

Suszone liście curry kupicie w Kuchniach Świata oraz każdym sklepie z żywnością orientalną. Odsyłam też do internetu, na allegro kupicie je za mniej niż 10 złotych wraz z dostawą. Mieszkańcy i mieszkanki Warszawy mogą też zaopatrzyć się za kilka złotych w świeże liście curry, sprzedaje je na Hali Mirowskiej Pan Darek w budce numer 17. Świeże liście curry są bardziej aromatyczne i wytrzymają w lodówce nawet 2 tygodnie.

Pozostałe przyprawy można kupić w sklepach zielarskich, sklepach z żywnością orientalną lub w dobrze zaopatrzonych delikatesach. Najprościej jednak jest zamówić je na Vegepacku, gdzie można za jednym zamachem kupić wszystkie na raz.

|===

[.text-center]
== Zdjęcia
