= Domowy kebab  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 45 min
* 4 porcje
* https://kuron.com.pl/artykuly/przepisy/dania-glowne/domowy-kebab[link do 藕r贸da przepisu]

== Skadniki

* 600 g udek z kurczaka bez sk贸ry i koci
* 300 g gstego jogurtu np. greckiego
* 2 zbki czosnku
* 1 y偶eczka agodnej papryki w proszku
* 1/2 y偶eczki mielonego cynamonu
* 1 paska y偶eczka mielonych ziaren kolendry
* 1/2 y偶eczki mielonego kuminu
* 1 y偶eczka koncentratu pomidorowego
* 1 y偶eczka soli
* 1/2 y偶eczki czarnego mielonego pieprzu
* sos czosnkowy (mi najbardziej pasuje Roleski)

=== Warzywa:

* wiartka biaej kapusty np. modej
* 2 dojrzae pomidory
* 1 zielony dugi og贸rek
* ewentualnie 1 czerwona cebula

|
== Przygotowanie

Zacznij od przygotowania marynaty. Jogurt wymieszaj z utartym czosnkiem, papryk, cynamonem, kolendr, kminem, koncentratem pomidorowym oraz sol i pieprzem. Nastpnie zanurz miso w marynacie, odstaw do lod贸wki na minimum 2 godziny, ale idealnie smakuj po okoo 12 godzinach. Najlepiej kurczaka zamarynowa dzie wczeniej i zostawi na noc w lod贸wce, poniewa偶 wtedy przyprawy przenikn w gb misa Po tym czasie rozgrzej piekarnik do 230 掳C z funkcj grilla. Nastpnie udka nadziej na szpadki do szaszyk贸w. Po dwie na ka偶dy kebab, bd si atwiej obraca. Naczynie do pieczenia wy贸偶 foli aluminiow, u贸偶 na nim zamarynowane miso. Dziki temu unikniesz szorowania formy. Piecz przez 30 minut w g贸rne czci piekarnika. W poowie czasu przewr贸 kebab na drug stron, dziki temu r贸wnomiernie si upiecze.

Nastpnie pokr贸j warzywa. Kapust drobno poszatkuj, pomidory i og贸rki pokr贸j w poplastry. Upieczone kebaby cienko pokr贸j. Tortille opiecz na suchej patelni grillowej, je偶eli tak posiadasz. Nastpnie na ka偶dy placek na贸偶 porcj warzyw, misa oraz solidn porcj sosu czosnkowego. Nastpnie zwi w rulon zawijajc sp贸d do rodka, aby podczas jedzenia nic z niego nie wypadao. Dla pewnoci mo偶esz kebaba zawin jeszcze w foli aluminiow lub pergamin.

|===

[.text-center]
== Zdjcia
