= Domowy kebab 2  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 45 min
* 4 porcje
* https://policzona-szama.pl/blogs/przepisy/domowy-kebab[link do 藕r贸da przepisu]

== Skadniki

=== Buka:

* mka pszenna typ 650 - 500 g
* ciepa woda - 190 ml
* jogurt naturalny - 100 g
* s贸l - 10 g
* oliwa - 10 ml
* dro偶d偶e wie偶e - 25 g / dro偶d偶e suche - 7-8 g
* 偶贸tko do posmarowania ciasta
* sezam do posypania ciasta

=== Dwie porcje misa do kebaba:

* miso z piersi indyka - 100 g
* miso z uda kurczaka - 50 g (po usuniciu tuszczu)
* oliwa - 5 ml
* przyprawa do kurczaka "Zocisty Kurczak" - 3 g,
* przyprawa Garam Masala - 3 g

=== Pi porcji sosu do kebaba:

* jogurt Skyr - 150 g
* jogurt naturalny rzadki - 100 g
* majonez - 50 g
* czosnek - 1-2 zbki

=== wie偶e dodatki wedug uznania:

* saata lodowa
* kapusta czerwona
* pomidor malinowy
* og贸rek zielony
* cebula czerwona
* feta w kostkach

|
== Przygotowanie

=== Buka do kebaba: 

Wsyp mk do miski.
Przygotuj rozczyn. W tym celu wlej ciep wod do szklanki, dodaj dro偶d偶e oraz jedn y偶k mki (odmierz j z iloci wczeniej wsypanej do miski). Dokadnie wymieszaj, do momentu a偶 w szklance nie bdzie 偶adnych grudek dro偶d偶y ani mki. Odczekaj 5-10 minut, aby dro偶d偶e zaczy dziaa.

Po upywie 5-10 minut wlej do miski jogurt naturalny oraz zawarto szklanki z przygotowanym wczeniej rozczynem. Dodaj s贸l i oliw.

Cao wymieszaj opatk. Gdy skadniki wstpnie si pocz, prze贸偶 ciasto na blat i zacznij wyrabia je rkami. Je偶eli ciasto mocno klei si do rk, mo偶na je delikatnie podsypa mk.

Dno i brzegi miski wysmaruj odrobin oliwy. Gotowe ciasto prze贸偶 do miski. Cao przykryj foli spo偶ywcz i odczekaj godzin, a偶 ciasto wyronie. W tym czasie przejd藕 do przygotowywania pozostaych skadnik贸w.

Po godzinie zagrzej piekarnik do temperatury 200掳C, grzanie g贸ra-d贸. Blach z piekarnika wy贸偶 papierem do pieczenia.

Prze贸偶 ciasto na papier do pieczenia i delikatnie je rozwakuj - tak, aby uzyskao okrgy ksztat o rednicy ok. 28-30 cm.

We藕 jajko, oddziel 偶贸tko od biaka. 呕贸tko rozmieszaj widelcem i posmaruj powierzchni buki przy u偶yciu pdzelka.
Cao posyp sezamem. Piecz okoo 25 minut w piekarniku nagrzanym do 200掳C.

Odczekaj, a偶 buka ostygnie po wyjciu z piekarnika, zanim zaczniesz j kroi.

Pokr贸j j na wiartki (je偶eli przygotowujesz mniej ni偶 cztery porcje, pozostae buki mo偶esz zamrozi).


=== Miso:

Miso z indyka oraz miso z kurczaka pokr贸j na niewielkie paski.

Miso prze贸偶 do miski, wlej oliw oraz dodaj przyprawy.

Dobrze wymieszaj miso z przyprawami, aby powstaa marynata. Pozostaw, aby nabrao temperatury pokojowej przed rozpoczciem sma偶enia.

Miso przesma偶 przy u偶yciu ceramicznej patelni grillowej bezporednio przed skadaniem kebaba. Wrzu miso na dobrze rozgrzan patelni (bez dodatku tuszczu) i sma偶 przez 2-3 minuty z ka偶dej strony.

=== Sos:

Do miseczki dodaj jogurt Skyr, rzadki jogurt naturalny oraz majonez. Wymieszaj.

Przecinij przez prask czosnek i dodaj do sosu.

=== wie偶e dodatki:

Na koniec pokr贸j wie偶e warzywa w iloci wedug uznania.

=== Cao:

Przekr贸j buk w poprzek, aby powstaa kieszonka.

rodek buki wysmaruj sosem.

Dodaj czerwon kapust, saat lodow, a nastpnie miso.

Polej miso pozosta iloci sosu.

Na g贸r dodaj pomidora, og贸rka oraz czerwon cebul.

|===

[.text-center]
== Zdjcia
