= Domowy kebab 2

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 45 min
* 4 porcje
* https://policzona-szama.pl/blogs/przepisy/domowy-kebab[link do źródła przepisu]

== Składniki
Bułka:

* mąka pszenna typ 650 - 400 g
* ciepła woda - 150 ml
* jogurt naturalny - 100 g
* sól - 10 g
* oliwa - 10 ml
* drożdże świeże - 25 g / drożdże suche - 7-8 g
* żółtko do posmarowania ciasta
* sezam do posypania ciasta


Jedna porcja mięsa do kebaba:

* mięso z piersi indyka - 100 g
* mięso z uda kurczaka - 50 g (po usunięciu tłuszczu)
* oliwa - 5 ml
* przyprawy: przyprawa do kurczaka "Złocisty Kurczak" - 2-4 g, * przyprawa Garam Masala - 2-4 g

Trzy porcje sosu do kebaba:

* jogurt Skyr - 150 g
* jogurt naturalny rzadki - 100 g
* majonez - 50 g
* czosnek - 1-2 ząbki

Świeże dodatki według uznania:

* sałata lodowa
* kapusta czerwona
* pomidor malinowy
* ogórek zielony
* cebula czerwona
* feta w kostkach

|
== Przygotowanie
Bułka do kebaba: 

Wsyp mąkę do miski.
Przygotuj rozczyn. W tym celu wlej ciepłą wodę do szklanki, dodaj drożdże oraz jedną łyżkę mąki (odmierz ją z ilości wcześniej wsypanej do miski). Dokładnie wymieszaj, do momentu aż w szklance nie będzie żadnych grudek drożdży ani mąki. Odczekaj 5-10 minut, aby drożdże zaczęły działać.

Po upływie 5-10 minut wlej do miski jogurt naturalny oraz zawartość szklanki z przygotowanym wcześniej rozczynem. Dodaj sól i oliwę.

Całość wymieszaj łopatką. Gdy składniki wstępnie się połączą, przełóż ciasto na blat i zacznij wyrabiać je rękami. Jeżeli ciasto mocno klei się do rąk, można je delikatnie podsypać mąką.

Dno i brzegi miski wysmaruj odrobiną oliwy. Gotowe ciasto przełóż do miski. Całość przykryj folią spożywczą i odczekaj godzinę, aż ciasto wyrośnie. W tym czasie przejdź do przygotowywania pozostałych składników.

Po godzinie zagrzej piekarnik do temperatury 200°C, grzanie góra-dół. Blachę z piekarnika wyłóż papierem do pieczenia.

Przełóż ciasto na papier do pieczenia i delikatnie je rozwałkuj - tak, aby uzyskało okrągły kształt o średnicy ok. 28-30 cm.

Weź jajko, oddziel żółtko od białka. Żółtko rozmieszaj widelcem i posmaruj powierzchnię bułki przy użyciu pędzelka.
Całość posyp sezamem. Piecz około 25 minut w piekarniku nagrzanym do 200°C.

Odczekaj, aż bułka ostygnie po wyjęciu z piekarnika, zanim zaczniesz ją kroić.

Pokrój ją na ćwiartki (jeżeli przygotowujesz mniej niż cztery porcje, pozostałe bułki możesz zamrozić).


Mięso:

Mięso z indyka oraz mięso z kurczaka pokrój na niewielkie paski.

Mięso przełóż do miski, wlej oliwę oraz dodaj przyprawy.

Dobrze wymieszaj mięso z przyprawami, aby powstała marynata. Pozostaw, aby nabrało temperatury pokojowej przed rozpoczęciem smażenia.

Mięso przesmaż przy użyciu ceramicznej patelni grillowej bezpośrednio przed składaniem kebaba. Wrzuć mięso na dobrze rozgrzaną patelnię (bez dodatku tłuszczu) i smaż przez 2-3 minuty z każdej strony.

Sos:

Do miseczki dodaj jogurt Skyr, rzadki jogurt naturalny oraz majonez. Wymieszaj.

Przeciśnij przez praskę czosnek i dodaj do sosu.

Świeże dodatki:

Na koniec pokrój świeże warzywa w ilości według uznania.

Całość:

Przekrój bułkę w poprzek, aby powstała kieszonka.

Środek bułki wysmaruj sosem.

Dodaj czerwoną kapustę, sałatę lodową, a następnie mięso.

Polej mięso pozostałą ilością sosu.

Na górę dodaj pomidora, ogórka oraz czerwoną cebulę.


|===

[.text-center]
== Zdjęcia
