= Domowa pizza +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 45 min
* 4 porcje
* https://www.mojewypieki.com/przepis/ciasto-do-pizzy-przepis-iii[link do źródła przepisu]

== Składniki

* 1 łyżka (12g) suchych drożdży (drożdży instant) lub 25 g świeżych drożdży
* 1,5 szklanki letniej wody
* 3,5 szklanki mąki pszennej
* 1 łyżka oliwy z oliwek
* 1,5 łyżeczki soli
|
== Przygotowanie
Mąkę przesiać, wymieszać z suchymi drożdżami (ze świeżych drożdży należy najpierw zrobić rozczyn). Dodać pozostałe składniki i wyrobić gładkie, elastyczne ciasto. Ciasto na pizzę można wyrabiać ręcznie, można też mikserem z hakiem do ciasta drożdżowego (mikserem zajmie to około 15 minut).

Z ciasta uformować kulę, umieścić w naczyniu, przykryć folią spożywczą i postawić w ciepłe miejsce do podwojenia objętości na około 1 – 1,5 godziny.

Blachę do pizzy wysmarować oliwą (dodatkową).

Wyrośnięte ciasto na pizzę uderzyć pięścią. Podzielić na 3 równe części. Uformować z nich spody na pizzę bezpośrednio na blaszce, pozostawiając nieco grubsze brzegi.

Na spód z ciasta wyłożyć sos pomidorowy, następnie nasze ulubione dodatki. Odstawić na około 20 – 30 minut w ciepłe miejsce, do wyrośnięcia spodu, choć nie jest to niezbędne – wyrośnięty spód to grubsze, bardziej ‚puchate’ ciasto na pizzę.

Piec około 15 minut w maksymalnej temperaturze piekarnika (260ºC), choć ja zazwyczaj piekę w niższej temperaturze – około 230ºC, aby pizza wyszła idealna (czas pieczenia zależy od piekarnika). Ser nakładać kilka minut przed końcem pieczenia.

Podawać gorącą.

|===

[.text-center]
== Zdjęcia
