= Domowy kebab

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 45 min
* 4 porcje
* https://kuron.com.pl/artykuly/przepisy/dania-glowne/domowy-kebab[link do źródła przepisu]

== Składniki
* 600 g udek z kurczaka bez skóry i kości
* 300 g gęstego jogurtu np. greckiego
* 2 ząbki czosnku
* 1 łyżeczka łagodnej papryki w proszku
* 1/2 łyżeczki mielonego cynamonu
* 1 płaska łyżeczka mielonych ziaren kolendry
* 1/2 łyżeczki mielonego kuminu
* 1 łyżeczka koncentratu pomidorowego
* 1 łyżeczka soli
* 1/2 łyżeczki czarnego mielonego pieprzu
* sos czosnkowy (mi najbardziej pasuje Roleski)

Warzywa:

* ćwiartka białej kapusty np. młodej
* 2 dojrzałe pomidory
* 1 zielony długi ogórek
* ewentualnie 1 czerwona cebula

|
== Przygotowanie
Zacznij od przygotowania marynaty. Jogurt wymieszaj z utartym czosnkiem, papryką, cynamonem, kolendrą, kminem, koncentratem pomidorowym oraz solą i pieprzem. Następnie zanurz mięso w marynacie, odstaw do lodówki na minimum 2 godziny, ale idealnie smakują po około 12 godzinach. Najlepiej kurczaka zamarynować dzień wcześniej i zostawić na noc w lodówce, ponieważ wtedy przyprawy przenikną w głąb mięsa Po tym czasie rozgrzej piekarnik do 230 °C z funkcją grilla. Następnie udka nadziej na szpadki do szaszłyków. Po dwie na każdy kebab, będą się łatwiej obracać. Naczynie do pieczenia wyłóż folią aluminiową, ułóż na nim zamarynowane mięso. Dzięki temu unikniesz szorowania formy. Piecz przez 30 minut w górne części piekarnika. W połowie czasu przewróć kebab na drugą stronę, dzięki temu równomiernie się upiecze.

Następnie pokrój warzywa. Kapustę drobno poszatkuj, pomidory i ogórki pokrój w połplastry. Upieczone kebaby cienko pokrój. Tortille opiecz na suchej patelni grillowej, jeżeli taką posiadasz. Następnie na każdy placek nałóż porcję warzyw, mięsa oraz solidną porcję sosu czosnkowego. Następnie zwiń w rulon zawijając spód do środka, aby podczas jedzenia nic z niego nie wypadało. Dla pewności możesz kebaba zawinąć jeszcze w folię aluminiową lub pergamin.

== Zdjęcia
|===
