= Dorsz pod śródziemnomorską kruszonką +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 35 min
* 2 porcje
* https://drive.google.com/file/d/1drmcwaGPo7P0SAIorajCTYRgiGIe1Rhj/view?usp=sharing[link do źródła przepisu]

== Składniki
* polędwica z dorsza - 1 średnia sztuka (300 g)
* orzechy włoskie - 1 łyżka (15 g)
* suszony pomidor odsączony z oleju - 1 sztuka (15 g)
* oliwki czarne - 3 sztuki (10 g)
* przyprawy: garść listków bazyli świeżej, 1 łyżka soku z cytryny, 1/2 łyżeczki skórki startej z cytryny, 1/3 łyżeczki oregano suszonego, sól i pieprz czarny do smaku

|
== Przygotowanie

Polędwice z dorsza myjemy, osuszamy i układamy na blaszce wyłożonej papierem do pieczenia lub w brytfance. Do malaksera wrzucamy orzechy włoskie, suszonego pomidora, oliwki, bazylię i przyprawy. Składniki siekamy na niezbyt jednolitą masę. Rybę obkładamy powstałą posypką, starannie ją dociskając. Wstawiamy na 220 minut do piekarnika rozgrzanego do temperatury 180 stopni C. 

|===

[.text-center]
== Zdjęcia

