= Dorsz pod śródziemnomorską kruszonką 🐟
:imagesdir: /Recipes/static/images

++++
<div class="recipe-header-actions">
    <a href="../../index.html" class="back-to-home-btn">← Wróć do przepisów</a>
    <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>
</div>
++++

[.recipe-hero]
[.card-image-placeholder]
Brak zdjęcia przepisu 🍲

[.recipe-details]
* 🕒 czas przygotowania: 35 minut
* 🕒 czas gotowania: 35 minut
* 👥 2 porcje
* 🔗 https://drive.google.com/file/d/1drmcwaGPo7P0SAIorajCTYRgiGIe1Rhj/view?usp=sharing[link do źródła przepisu]

[.recipe-columns]
== Składniki

* polędwica z dorsza - 1 średnia sztuka (300 g)
* orzechy włoskie - 1 łyżka (15 g)
* suszony pomidor odsączony z oleju - 1 sztuka (15 g)
* oliwki czarne - 3 sztuki (10 g)
* przyprawy: garść listków bazyli świeżej, 1 łyżka soku z cytryny, ½ łyżeczki skórki startej z cytryny, ⅓ łyżeczki oregano suszonego, sól i pieprz czarny do smaku

== Przygotowanie

Polędwice z dorsza myjemy, osuszamy i układamy na blaszce wyłożonej papierem do pieczenia lub w brytfance. Do malaksera wrzucamy orzechy włoskie, suszonego pomidora, oliwki, bazylię i przyprawy. Składniki siekamy na niezbyt jednolitą masę. Rybę obkładamy powstałą posypką, starannie ją dociskając. Wstawiamy na 220 minut do piekarnika rozgrzanego do temperatury 180 stopni C.

[.recipe-gallery]
== Zdjęcia

[.gallery-grid]
// Tutaj pojawią się zdjęcia
