= Dorsz pod r贸dziemnomorsk kruszonk  +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: 35 min
* 2 porcje
* https://drive.google.com/file/d/1drmcwaGPo7P0SAIorajCTYRgiGIe1Rhj/view?usp=sharing[link do 藕r贸da przepisu]

== Skadniki
* poldwica z dorsza - 1 rednia sztuka (300 g)
* orzechy woskie - 1 y偶ka (15 g)
* suszony pomidor odsczony z oleju - 1 sztuka (15 g)
* oliwki czarne - 3 sztuki (10 g)
* przyprawy: gar listk贸w bazyli wie偶ej, 1 y偶ka soku z cytryny, 1/2 y偶eczki sk贸rki startej z cytryny, 1/3 y偶eczki oregano suszonego, s贸l i pieprz czarny do smaku

|
== Przygotowanie

Poldwice z dorsza myjemy, osuszamy i ukadamy na blaszce wyo偶onej papierem do pieczenia lub w brytfance. Do malaksera wrzucamy orzechy woskie, suszonego pomidora, oliwki, bazyli i przyprawy. Skadniki siekamy na niezbyt jednolit mas. Ryb obkadamy powsta posypk, starannie j dociskajc. Wstawiamy na 220 minut do piekarnika rozgrzanego do temperatury 180 stopni C. 

|===

[.text-center]
== Zdjcia

