= Enchilada z kurczakiem 🐔
:imagesdir: /Recipes/static/images

++++
<div class="recipe-header-actions">
    <a href="../../index.html" class="back-to-home-btn">← Wróć do przepisów</a>
    <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>
</div>
++++

[.recipe-hero]
[.card-image-placeholder]
Brak zdjęcia przepisu 🍲

[.recipe-details]
* 🕒 czas przygotowania: 35 minut
* 🕒 czas gotowania: 35 minut
* 👥 4 porcje
* 🔗 https://www.kwestiasmaku.com/przepis/enchilada-z-kurczakiem[link do źródła przepisu]

[.recipe-columns]
== Składniki

* 5 dużych tortilli
* 100 g ryżu długoziarnistego
* 500 g filetu z piersi kurczaka
* 1 cebula
* 1 czerwona papryka
* ½ szklanki kukurydzy z puszki
* ½ szklanki fasoli z puszki
* 200 g tartej mozzarelli
* świeża kolendra
* papryczka chili
* 2 ząbki czosnku, starte
* ½ łyżeczki ostrej papryki
* 1 łyżeczka słodkiej papryki
* 2 łyżeczki kuminu
* 1 łyżeczka suszonego oregano
* 2 łyżeczki płatków chili
* 300 g krojonych pomidorów
* 1 łyżka koncentratu pomidorowego
* 1 ząbek czosnku
* 1 łyżeczka oliwy
* przyprawy: 1 łyżeczka suszonego oregano, ½ łyżeczki kuminu, szczypta ostrej papryki, szczypta cukru, sól, pieprz

== Przygotowanie

Nastawić do ugotowania ryż. Kurczaka pokroić na 2 cm paski. Doprawić go solą, pieprzem oraz mieszanką przypraw i nasmarować 2 łyżkami oleju roślinnego.

Rozgrzać patelnię z grubym dnem. Gdy będzie gorąca wlać łyżkę oleju, włożyć kurczaka i obsmażyć go z każdej strony, przez ok. 5 minut. Zdjąć z patelni i odłożyć na bok.

Na patelnię dodać łyżkę oleju i zeszklić pokrojoną w kosteczkę cebulę. Dodać pokrojoną w kostkę paprykę. Smażyć co chwilę mieszając przez około 3 minuty.

Dodać ugotowany ryż, odcedzoną kukurydzę i fasolę oraz podsmażone kawałki kurczaka, wszystko wymieszać.

Czosnek obrać i przekroić na pół. Włożyć do rondelka z oliwą i chwilę podsmażyć, dodać pomidory, koncentrat i przyprawy. Doprawić solą, pieprzem i zagotować. Gotować przez ok. 10 minut.

Rozłożyć farsz na tortille, posypać połową sera i listkami kolendry, zwinąć w ruloniki.

Piekarnik nagrzać do 180 stopni C. W formie lub na blaszce ułożyć zwinięte tortille łączeniem do dołu, polać sosem i posypać drugą połową sera. Zapiekać przez 20 minut. Posypać kolendrą i posiekanym chili.

[.recipe-gallery]
== Zdjęcia

[.gallery-grid]
// Tutaj pojawią się zdjęcia
