= Enchilada z kurczakiem +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 35 min
* 3 - 5 porcji
* https://www.kwestiasmaku.com/przepis/enchilada-z-kurczakiem[link do źródła przepisu]

== Składniki
* 5 dużych tortilli
* 100 g ryżu długoziarnistego
* 500 g filetu z piersi kurczaka
* 1 cebula
* 1 czerwona papryka
* 1/2 szklanki kukurydzy z puszki
* 1/2 szklanki fasoli z puszki
* 200 g tartej mozzarelli
* świeża kolendra
* papryczka chili

=== Przyprawy do kurczaka

* 2 ząbki czosnku, starte
* 1/2 łyżeczki ostrej papryki
* 1 łyżeczka słodkiej papryki
* 2 łyżeczki kuminu
* 1 łyżeczka suszonego oregano
* 2 łyżeczki płatków chili

=== Sos pomidorowy

* 300 g krojonych pomidorów
* 1 łyżka koncentratu pomidorowego
* 1 ząbek czosnku
* 1 łyżeczka oliwy
* przyprawy: 1 łyżeczka suszonego oregano, 1/2 łyżeczki kuminu, szczypta ostrej papryki, szczypta cukru, sól, pieprz

|
== Przygotowanie

Nastawić do ugotowania ryż. Kurczaka pokroić na 2 cm paski. Doprawić go solą, pieprzem oraz mieszanką przypraw i nasmarować 2 łyżkami oleju roślinnego.

Rozgrzać patelnię z grubym dnem. Gdy będzie gorąca wlać łyżkę oleju, włożyć kurczaka i obsmażyć go z każdej strony, przez ok. 5 minut. Zdjąć z patelni i odłożyć na bok.

Na patelnię dodać łyżkę oleju i zeszklić pokrojoną w kosteczkę cebulę. Dodać pokrojoną w kostkę paprykę. Smażyć co chwilę mieszając przez około 3 minuty.

Dodać ugotowany ryż, odcedzoną kukurydzę i fasolę oraz podsmażone kawałki kurczaka, wszystko wymieszać.

Czosnek obrać i przekroić na pół. Włożyć do rondelka z oliwą i chwilę podsmażyć, dodać pomidory, koncentrat i przyprawy. Doprawić solą, pieprzem i zagotować. Gotować przez ok. 10 minut.

Rozłożyć farsz na tortille, posypać połową sera i listkami kolendry, zwinąć w ruloniki.

Piekarnik nagrzać do 180 stopni C. W formie lub na blaszce ułożyć zwinięte tortille łączeniem do dołu, polać sosem i posypać drugą połową sera. Zapiekać przez 20 minut. Posypać kolendrą i posiekanym chili.

|===

[.text-center]
== Zdjęcia
