= Falafel, humus i świeże warzywa 🌱 +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: noc namaczania + 30 minut
* 4 porcje
* https://www.jadlonomia.com/przepisy/falafel-idealny[link do źródła przepisu]

== Składniki
* 300 g suchej ciecierzycy, namoczonej przez noc w zimnej wodzie
* 1 mała cebulka
* 2 ząbki czosnku
* 2 łyżki drobno posiekanej pietruszki
* 2 łyżki drobno posiekanej kolendry, można pominąć i dodać więcej pietruszki
* 1 łyżeczka mielonego kuminu
* ½ łyżeczki mielonych ziaren kolendry
* ½ łyżeczki mielonego kardamonu
* ½ łyżeczki cynamonu
* ½ łyżeczki chili
* ½ łyżeczki sody oczyszczonej
* 1 łyżeczka soli
* olej do smażenia, najlepszy będzie rzepakowy lub z pestek winogron

|
== Przygotowanie
Ciecierzycę odcedzić, opłukać i zmielić w maszynce do mielenia razem z cebulą. Do zmielonej masy dać natki, sodę, sól i resztę przypraw, jeśli nie macie mielonych przypraw, możecie też zmielić je razem z ciecierzycą. Wszystko dokładnie wymieszać i dodać 1 - 2 łyżki wody - masa jest dobra, kiedy ściśnięta w ręce łatwo przyjmuje kształt. Przykryć szczelnie folią i odstawić do lodówki na pół godziny lub dłużej.

W dużej patelni z grubym dnem rozgrzać olej, warstwa powinna mieć 2 - 3 cm. Nabierać po łyżce masy i formować małe, lekko spłaszczone kulki. Ważne jest, by dokładnie je ścisnąć, w przeciwnym wypadku będą się rozpadać.

Uformowane falafele od razu wrzucać na gorący olej na patelni i smażyć 2 - 3 minuty z każdej strony. Następnie odkładać na talerz wyłożony papierowym ręcznikiem, żeby odsączyć je z tłuszczu i od razu podawać ze świeżymi warzywami, sałatkami lub hummusem.

|===

[.text-center]
== Zdjęcia
