= Fasolka po bretońsku, bułki

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 1 h
* 6 porcji
* https://www.kwestiasmaku.com/zielony_srodek/fasolka/fasolka_po_bretonsku/przepis.html[link do źródła przepisu]

== Składniki
* 400 g suchej fasolki "Piękny Jaś" lub 2 puszki fasolki
* 250 g boczku (parzonego lub wędzonego)
* 250 g kiełbasy
* 1 duża cebula
* 2 ząbki czosnku
* 1 puszka krojonych pomidorów + 2 łyżki koncentratu pomidorowego*
* przyprawy: 3 ziela angielskie, liść laurowy, 2 płaskie łyżki suszonego majeranku

|
== Przygotowanie
Suchą fasolę wsypać do garnka, zalać zimną wodą (ok. 10 cm ponad poziom fasolki) i odstawić na noc do namoczenia.

Następnego dnia odcedzić, wlać 1 litr świeżej wody, dodać 1 łyżeczkę soli, ziele angielskie i liść laurowy i gotować pod przykryciem przez około 1 i 1/2 godziny do miękkości.

Odciąć skórę z boczku, resztę pokroić w kosteczkę. Włożyć na patelnię i co chwilę mieszając dokładnie obsmażyć, przełożyć do garnka z fasolką (lub do zagotowanej w garnku fasolki z puszki wraz z zalewą).

Na wytopionym tłuszczu dokładnie obsmażyć pokrojoną w kosteczkę kiełbasę (wcześniej obrać ją ze skórki w razie potrzeby), dodać pokrojoną w kosteczkę cebulę i smażyć jeszcze przez ok. 5 minut. Pod koniec dodać starty czosnek.

Przełożyć do garnka z fasolką i gotować przez ok. 5 minut na większym ogniu bez przykrycia.

Dodać krojone pomidory z puszki i koncentrat pomidorowy. Doprawić majerankiem, solą i świeżo zmielonym pieprzem. Gotować przez około 15 minut.

|===

[.text-center]
== Zdjęcia
