= Fish & chips z sosem tatarskim  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: 1 h
* 2 porcje
* https://www.tasteaway.pl/idealne-fish-chips-zrobisz-sobie-sam/ [link do 藕r贸da przepisu]

== Skadniki

=== Fish

* 2 du偶e kawaki dorsza podzielone na mniejsze kawaki do panierowania
* 200 ml jasnego zimnego piwa
* 1/2 y偶eczki kurkumy
* 140 gram mki pszennej uniwersalnej
* 1 y偶eczka proszku do pieczenia
* olej rzepakowy do sma偶enia

=== Chips

* 6-8 ziemniak贸w
* olej rzepakowy do sma偶enia
* s贸l do smaku

=== Sos tarski

* 2 y偶ki marynowanych grzybk贸w (lub kapar贸w)
* 1/4 czerwonej cebuli
* 1 og贸rek kiszony lub konserwowy
* 2 y偶ki posiekanego szczypiorku
* 1 y偶ka posiekanej natki
* 200 ml majonezu
* 2 y偶eczki soku z cytryny
* wie偶o zmielony pieprz

|
== Przygotowanie

=== Fish

Wyjmujemy z lod贸wki ryb, myjemy i osuszamy papierowym rcznikiem. Kroimy na takie kawaki, jakie chcemy serwowa. Ryb solimy i pieprzymy. Odkadamy.

Szykujemy panierk do ryby. W misce mieszamy piwo, mk, kurkum i proszek do pieczenia - najlepiej u偶y trzepaczki (my korzystalimy z trzepaczki elektrycznej). Panierujemy kawaki ryby w ciecie.

Na mocno rozgrzan patelni wlewamy 2 szklanki oleju rzepakowego. Rozgrzewamy do 180 stopni. Na mocno rozgrzany olej wrzucamy kawaki ryby i sma偶ymy 2-3 minuty z ka偶dej strony.

=== Chips

Ziemniaki obieramy, myjemy i kroimy na supki. Supki wrzucamy do miski z wod i zostawiamy tak na 10-15 minut.

Ziemniaki wyjmujemy z wody, wrzucamy do garnka i zalewamy wrztkiem. Doprowadzamy wod do wrzenia, ale gotujemy tylko przez 2-3 minuty. Przerzucamy ziemniaki na durszlak.

Ryb wyjmujemy, a na ten sam olej wrzucamy frytki - pamitajcie - musi by mocno rozgrzany. Sma偶ymy 4-5 minut. Sprawdzamy czy gotowe. Po wyjciu (najlepiej na papierowy rcznik) solimy.

=== Sos tatarski

Marynowane grzybki drobno posieka na desce, obok w ma kosteczk pokroi cebul oraz og贸rka, przez chwil sieka jeszcze wszystkie skadniki.
Przeo偶y do miseczki, doda posiekany szczypiorek, natk, majonez i sok z cytryny, wymiesza i doprawi pieprzem.

|===

[.text-center]
== Zdjcia
