= Flaki ォ +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 4 h
* liczba porcji: 6 porcji
* https://aniagotuje.pl/przepis/flaki[link do 藕r贸da przepisu]

== Skadniki

* 1 kg woowiny - np. szponder plus karczek
* 2,5 litra wody - 2500 ml
* 2 rednie lub wiksze marchewki - okoo 280 g
* okoo 15 cm pora - do 150 g
* kawaek korzenia selera - okoo 100 g
* 1 korze pietruszki - okoo 120 g
* przyprawy: 1 y偶eczka soli, p贸 paskiej y偶eczki pieprzu
* 1 kg flak贸w woowych - w patach lub pokrojone
* 3 zbki czosnku - okoo 15 g
* przyprawy i zioa: 3 pene y偶ki majeranku; 4 ziarna ziela angielskiego; 2 listki laurowe; po jednej paskiej y偶eczce mielonego imbiru i gaki muszkatoowej; po p贸 y偶eczki ostrej i sodkiej papryki; s贸l i pieprz - dozowane na koniec
* 5 y偶ek mki pszennej - do 70 g
* 5 y偶ek masa - do 80 g


|
== Przygotowanie

Zacznij od wstawienia bazy pod flaki, czyli rosou woowego. W du偶ym garnku umieszczam kilogram umytego woowego misa. Zawsze jest to szponder z koci oraz drugi, mniej tusty kawaek woowy. Mo偶e to by gole, karczek, czy nawet ata woowa. Od razu dodaj te偶 kawaek pora, obrane marchewki oraz pietruszk i kawaek korzenia selera. (Warzywa po obraniu myj i dopiero dodaj do garnka). Na koniec wlewam 2500 ml wody i wsypuj od razu y偶eczk soli i p贸 paskiej y偶eczki pieprzu.
Kolejno garnek przykryj przykrywk. Ustaw wy偶sz ni偶 rednia moc palnika i czekaj, a偶 bulion zacznie si gotowa. Nastpnie zmniejsz moc palnika, tylko do takiej, by bulion delikatnie "mruga". Zup gotuj tak przez cae trzy godziny, do mikkoci misa. Warzywa bd bardzo mikkie. Jeli nie bdziesz miesza w garnku, to nic si nie rozpadnie. 

Flaki w patach nale偶y bardzo dokadnie umy, a nastpnie pokroi na kilka mniejszych kawak贸w. Tak przygotowane flaki umie w lekko osolonej wodzie (woda ma cakowicie przykrywa flaki) i gotuj przez 20 minut (bez przykrywki). Po tym czasie odced藕 je i po lekkim przestudzeniu oczy z ewentualnych bonek i pozostaego tuszczu. Nastpnie pokr贸j paty na kr贸tsze paski. Tak przygotowane flaczki ponownie umie w garnku z osolon wod i gotuj przez 20 minut. Zn贸w odlej ca wod i raz jeszcze powt贸rz gotowanie flak贸w. Po trzecim gotowaniu zdecyduj, czy ich zapach Ci odpowiada, czy jednak bdziesz je obgotowywa jeszcze raz, czy nawet dwa razy. Przy ka偶dym gotowaniu bd te偶 robi si coraz miksze.
Flaki wie偶e krojone przepucz, umie w lekko osolonej wodzie (woda ma cakowicie przykrywa flaki) i gotuj przez 20 minut. Po tym czasie odced藕 je i ponownie umieci w garnku z osolon wod. 20 minut gotowania, zn贸w odcedzanie i sprawdzenie, czy zapach flak贸w jest akceptowalny. Flaki krojone szykujesz tak samo, jak wie偶e krojone. Nale偶y je jednak wczeniej naturalnie rozmrozi.

Po trzech godzinach gotowania bazy/bulionu pod flaki woowe, zdejmij przykrywk. Z brzeg贸w garnka usu ewentualne szumowiny. Najlepiej przy pomocy metalowego, szerokiego cedzaka, wy贸w z garnka wszystkie warzywa oraz cae miso. Marchew, pietruszk i selera pokr贸j na mniejsze kawaki i od贸偶 do osobnej miski. Przejrzyj te偶 miso. Usu koci, sk贸ry, tuszcz oraz w贸kna. Samo miso podziej na mae kawaki i umie w misce razem z pokrojonymi warzywami. Miso i warzywa raz jeszcze dodasz do zupy, pod koniec gotowania.

Bulion zostaw w garnku. Dodaj do niego obgotowane flaki. W garnku umie te偶: 3 obrane i pokrojone drobno zbki czosnku;  3 pene y偶ki majeranku; 4 ziarna ziela angielskiego; 2 listki laurowe; po jednej paskiej y偶eczce mielonego imbiru i gaki muszkatoowej; po p贸 y偶eczki ostrej i sodkiej papryki. Zup doprowad藕 do wrzenia, a nastpnie zmniejsz moc do takiej, by tylko lekko "mrugaa". Flaki maj si gotowa, ale nie za mocno. Flaki gotuj tak minimum 30 minut (nawet jeli paski flak贸w byy wczeniej obgotowane na tyle, 偶e flaki zd偶yy ju偶 zmikn) lub te偶 du偶ej, a偶 do mikkoci flak贸w.

Po minimum 30 minutach gotowania (w zale偶noci od tego jak dugo trzeba jeszcze gotowa flaczki) do garnka dodaj odo偶one z wywaru miso oraz pokrojone warzywa. Zamieszaj flaki i sprawd藕 ich smak. W tym momencie mo偶esz zdecydowa, ile dodasz do nich soli oraz pierzu. Jeli chcesz je dosoli, to zacznij od poowy y偶eczki. Dobrze wymieszaj flaki, sprawd藕 ich smak i dopiero wtedy dodaj ewentualnie troch wicej soli. Jeli dodajesz pieprz, to zacznij od 1/4 paskiej y偶eczki. Po ponownym zagotowaniu flaki s ju偶 gotowe do podania.

Do flak贸w mo偶na te偶 na koniec doda zasma偶k (do flak贸w pokazanych na zdjciach nie szykowaam zasma偶ki). Na maej patelni umieszczasz 5 y偶ek masa (do 80 g). Gdy tuszcz si roztopi dodajesz pi y偶ek mki (do 70 g) i od razu mieszasz zawarto patelni przy pomocy drewnianej y偶ki. Gdy tuszcz z mk zacznie si pieni przelewasz cao do garnka z gotujc si zup. Flaki od razu mieszasz i czekasz, a偶 ponownie si zagotuj. Po 2-3 minutach mo偶na je wyczy. Zasma偶k mo偶na wzbogaci o pokrojon w drobn kostk cebul. Na patelni z masem dodaj w贸wczas dodatkowe dwie y偶ki oleju do sma偶enia. Cebulk podsma偶aj kilka minut do lekkiego zarumienienia, i dopiero dodawaj mk.

|===

[.text-center]
== Zdjcia
