= Flaki +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 4 h
* liczba porcji: 6 porcji
* https://aniagotuje.pl/przepis/flaki[link do źródła przepisu]

== Składniki
* 1 kg wołowiny - np. szponder plus karczek
* 2,5 litra wody - 2500 ml
* 2 średnie lub większe marchewki - około 280 g
* około 15 cm pora - do 150 g
* kawałek korzenia selera - około 100 g
* 1 korzeń pietruszki - około 120 g
* przyprawy: 1 łyżeczka soli, pół płaskiej łyżeczki pieprzu
* 1 kg flaków wołowych - w płatach lub pokrojone
* 3 ząbki czosnku - około 15 g
* przyprawy i zioła: 3 pełne łyżki majeranku; 4 ziarna ziela angielskiego; 2 listki laurowe; po jednej płaskiej łyżeczce mielonego imbiru i gałki muszkatołowej; po pół łyżeczki ostrej i słodkiej papryki; sól i pieprz - dozowane na koniec
* 5 łyżek mąki pszennej - do 70 g
* 5 łyżek masła - do 80 g


|
== Przygotowanie
Zacznij od wstawienia bazy pod flaki, czyli rosołu wołowego. W dużym garnku umieszczam kilogram umytego wołowego mięsa. Zawsze jest to szponder z kością oraz drugi, mniej tłusty kawałek wołowy. Może to być goleń, karczek, czy nawet łata wołowa. Od razu dodaję też kawałek pora, obrane marchewki oraz pietruszkę i kawałek korzenia selera. (Warzywa po obraniu myję i dopiero dodaję do garnka). Na koniec wlewam 2500 ml wody i wsypuję od razu łyżeczkę soli i pół płaskiej łyżeczki pieprzu.
Kolejno garnek przykryj przykrywką. Ustaw wyższą niż średnia moc palnika i czekaj, aż bulion zacznie się gotować. Następnie zmniejsz moc palnika, tylko do takiej, by bulion delikatnie "mrugał". Zupę gotuj tak przez całe trzy godziny, do miękkości mięsa. Warzywa będą bardzo miękkie. Jeśli nie będziesz mieszać w garnku, to nic się nie rozpadnie. 

Flaki w płatach należy bardzo dokładnie umyć, a następnie pokroić na kilka mniejszych kawałków. Tak przygotowane flaki umieść w lekko osolonej wodzie (woda ma całkowicie przykrywać flaki) i gotuj przez 20 minut (bez przykrywki). Po tym czasie odcedź je i po lekkim przestudzeniu oczyść z ewentualnych błonek i pozostałego tłuszczu. Następnie pokrój płaty na krótsze paski. Tak przygotowane flaczki ponownie umieść w garnku z osoloną wodą i gotuj przez 20 minut. Znów odlej całą wodę i raz jeszcze powtórz gotowanie flaków. Po trzecim gotowaniu zdecyduj, czy ich zapach Ci odpowiada, czy jednak będziesz je obgotowywać jeszcze raz, czy nawet dwa razy. Przy każdym gotowaniu będą też robić się coraz miększe.
Flaki świeże krojone przepłucz, umieść w lekko osolonej wodzie (woda ma całkowicie przykrywać flaki) i gotuj przez 20 minut. Po tym czasie odcedź je i ponownie umieścić w garnku z osoloną wodą. 20 minut gotowania, znów odcedzanie i sprawdzenie, czy zapach flaków jest akceptowalny. Flaki krojone szykujesz tak samo, jak świeże krojone. Należy je jednak wcześniej naturalnie rozmrozić.

Po trzech godzinach gotowania bazy/bulionu pod flaki wołowe, zdejmij przykrywkę. Z brzegów garnka usuń ewentualne szumowiny. Najlepiej przy pomocy metalowego, szerokiego cedzaka, wyłów z garnka wszystkie warzywa oraz całe mięso. Marchew, pietruszkę i selera pokrój na mniejsze kawałki i odłóż do osobnej miski. Przejrzyj też mięso. Usuń kości, skóry, tłuszcz oraz włókna. Samo mięso podziej na małe kawałki i umieść w misce razem z pokrojonymi warzywami. Mięso i warzywa raz jeszcze dodasz do zupy, pod koniec gotowania.

Bulion zostaw w garnku. Dodaj do niego obgotowane flaki. W garnku umieść też: 3 obrane i pokrojone drobno ząbki czosnku;  3 pełne łyżki majeranku; 4 ziarna ziela angielskiego; 2 listki laurowe; po jednej płaskiej łyżeczce mielonego imbiru i gałki muszkatołowej; po pół łyżeczki ostrej i słodkiej papryki. Zupę doprowadź do wrzenia, a następnie zmniejsz moc do takiej, by tylko lekko "mrugała". Flaki mają się gotować, ale nie za mocno. Flaki gotuj tak minimum 30 minut (nawet jeśli paski flaków były wcześniej obgotowane na tyle, że flaki zdążyły już zmięknąć) lub też dłużej, aż do miękkości flaków.

Po minimum 30 minutach gotowania (w zależności od tego jak długo trzeba jeszcze gotować flaczki) do garnka dodaj odłożone z wywaru mięso oraz pokrojone warzywa. Zamieszaj flaki i sprawdź ich smak. W tym momencie możesz zdecydować, ile dodasz do nich soli oraz pierzu. Jeśli chcesz je dosolić, to zacznij od połowy łyżeczki. Dobrze wymieszaj flaki, sprawdź ich smak i dopiero wtedy dodaj ewentualnie trochę więcej soli. Jeśli dodajesz pieprz, to zacznij od 1/4 płaskiej łyżeczki. Po ponownym zagotowaniu flaki są już gotowe do podania.

Do flaków można też na koniec dodać zasmażkę (do flaków pokazanych na zdjęciach nie szykowałam zasmażki). Na małej patelni umieszczasz 5 łyżek masła (do 80 g). Gdy tłuszcz się roztopi dodajesz pięć łyżek mąki (do 70 g) i od razu mieszasz zawartość patelni przy pomocy drewnianej łyżki. Gdy tłuszcz z mąką zacznie się pienić przelewasz całość do garnka z gotującą się zupą. Flaki od razu mieszasz i czekasz, aż ponownie się zagotują. Po 2-3 minutach można je wyłączyć. Zasmażkę można wzbogacić o pokrojoną w drobną kostkę cebulę. Na patelnię z masłem dodaj wówczas dodatkowe dwie łyżki oleju do smażenia. Cebulkę podsmażaj kilka minut do lekkiego zarumienienia, i dopiero dodawaj mąkę.

|===

[.text-center]
== Zdjęcia
