= Gobki bez zawijania  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 1 godzina
* liczba porcji: okoo 21 gobk贸w z sosem
* https://aniagotuje.pl/przepis/golabki-bez-zawijania[link do 藕r贸da przepisu]

== Skadniki

* 800 g opatki wieprzowej
* 800 g kapusty (okoo p贸 g贸wki) - moda lub stara + y偶eczka soli
* 2 rednie cebule - 250 g
* 3 y偶ki oleju do usma偶enia cebuli
* 1 rednie jajko
* 100 g suchego ry偶u - niecae p贸 szklanki
* gar koperku
* po paskiej y偶eczce soli i pieprzu
* dodatkowo: olej do podsma偶enia kotlet贸w gobkowych
* 1,5 l esencjonalnego bulionu
* 2 y偶ki koncentratu pomidorowego
* p贸 szklanki przecieru pomidorowego
* paska y偶ka mki pszennej

|
== Przygotowanie

Potrzebujesz okoo 800 gram贸w misa wieprzowego. Wedug mnie najlepsza do gobk贸w bez zawijania jest opatka wieprzowa. Zakupiam do tust opatk, poniewa偶 tak wanie lubimy, ale mo偶esz te偶 wybra w sklepie znacznie chudszy kawaek misa. Na gobki bez zawijania nada si r贸wnie偶 mieszanka kark贸wki z chud szynk lub te偶  biodr贸wka, kt贸r gorco polecam. 

Miso zmiel w maszynce na rednich oczkach. Jeli nie masz maszynki, to polecam zakup misa u rze藕nika z mo偶liwoci zmielenia misa na miejscu w sklepie. 

Wa偶c kapust do tych gobk贸w u偶ywam jej tyle samo co misa, lub troch mniej. Te akurat gobki bez zawijania szykowaam z modej kapusty. Odkroiam 800 gram贸w kapusty. Po zdjciu brzydkich lici i wyciciu gba zostao mi okoo 630 gram贸w kapusty gotowej do szatkowania. 
Porada: Mo偶esz te偶 u偶y kapust star/bia oraz kapust pekisk. Postpujesz z nimi tak samo, jak z mod kapust.

Kapust trzeba bardzo, bardzo dokadnie i drobno poszatkowa. Mo偶na zrobi to no偶em, jednak zdecydowanie polecam u偶y maszynki z nakadk do drobnego siekana warzyw. Niekt贸rym udaje si zetrze kapust na tarce. 

Do startej lub posiekanej kapusty wsyp y偶eczk soli. Cao wymieszaj, ugnie i odstaw na bok, na 10-20 minut. 

Po tym czasie zacznij odciska kapust z wody. Polecam nabiera gar kapusty i odciska j mocno nad zlewem. Odcinit kapust przekadaj do miski ze zmielonym misem. Zazwyczaj odciskam okoo 150 ml wody. W ten spos贸b odcinij bardzo dokadnie ca kapust. 

Ugotuj 100 gram贸w ry偶u (jedna saszetka lub niecae p贸 szklanki suchego ry偶u). Mo偶e to by np. ry偶 Basmati lub ry偶 jaminowy. Po ugotowaniu i odsczeniu wyszo mi 290 gram贸w ry偶u. 

Przygotuj sobie redni patelni z grubym dnem. Zacznij j nagrzewa. Dodaj trzy y偶ki oleju do sma偶enia. Na patelni wy贸偶 te偶 obrane i drobno posiekane cebule. Podsma偶aj cebulk na redniej mocy palnika przez okoo 10 minut, a偶 zrobi si rumiana. 

Do miski ze zmielonym misem i posiekan i odcinit kapust dodaj te偶 ca podsma偶on cebulk oraz ugotowany i lekko przestudzony ry偶. Wbij jedno jajko i dodaj gar siekanego koperku (koperek mo偶na pomin). Wsyp po paskiej y偶eczce soli i pieprzu.

Zacznij wyrabia mas misn pod gobki bez zawijania. Ja mieszam mas domi, poniewa偶 tak jest mi najwygodniej i widz oraz czuj, czy masa jest dokadnie wymieszana. Mas misn mieszam tak przez przynajmniej pi minut, a偶 bdzie idealnie jednolita. 

Przygotuj sobie du偶 patelni z grubym dnem. Zacznij j nagrzewa. Wlej okoo piciu y偶ek oleju do sma偶enia. Z przygotowanej masy formuj kotlety. Jeden kotlet wa偶y u mnie okoo 80 gram贸w. Mas podzieliam zatem na 21 kotlet贸w. Ka偶dego kotleta formowaam w doni na idealn kulk, kt贸r nastpnie lekko wydu偶aam i spaszczaam. 

Na patelni umieszczaj po kilka kotlet贸w na raz i podsma偶aj je na rumiano z obu stron, na troch wy偶szej ni偶 rednia moc palnika (wystarczy minuta na stron).

W tej spos贸b podsma偶 wszystkie kotleciki gobkowe. 

Do du偶ego garnka wlej 1500 ml bulionu. Mo偶e to by sam ros贸 drobiowy lub te偶 nawet bulion warzywny. Wlej do niego p贸 szklanki przecieru pomidorowego (mo偶e by Passata z butelki, czy te偶 pomidorki z kartonu) i dodaj dwie y偶ki koncentratu pomidorowego. Zamiast przecieru mo偶esz u偶y dw贸j du偶ych pomidor贸w malinowych (obrane i drobno posiekane). 
Cao wymieszaj i zagotuj. Zmniejsz moc i zacznij umieszcza w garnku kotlety gobkowe. Umie wszystkie i zwiksz moc do takiej, by cao tylko lekko mrugaa. Gobki bez zawijania gotuj tak 35 minut bez przykrycia. 

Na koniec mo偶esz jeszcze zagci sos pomidorowy dodajc pask y偶k mki pszennej (Ja zazwyczaj odlewam sobie wczeniej odrobin bulionu i rozrabiam go z mk. Jednolit mieszank wlewam do garnka, lekko mieszam. Po zagotowaniu wyczam). 

Gobki bez zawijania podaj z ziemniakami lub kluskami lskimi. Kopytka oraz makaron lub kasza gryczana te偶 pasuj. W sezonie na wie偶e pomidory bardzo czsto dodaj je do sosu na sam koniec lub te偶 bezporednio na talerz przed podaniem. Polecam te偶 og贸rki kiszone i maosolne. Cao posyp te偶 koperkiem, szczypiorkiem lub natk pietruszki. 

Aby zrobi gobki bez zawijania w piekarniku wystarczy, 偶e po podsma偶eniu na patelni kotlecik贸w gobkowych uo偶ysz je jeden obok drugiego w du偶ym naczyniu 偶aroodpornym. Gobki zalej sosem pomidorowym. Sos pomidorowy to: 2 szklanki bulionu; 2 szklanki przecieru pomidorowego; 4 y偶ki koncentratu; 4 y偶ki mietanki sodkiej 30 %, po y偶eczce soli i oregano oraz p贸 y偶eczki pieprzu. Gobki bez zawijania umie na rodkowej p贸ce w piekarniku nagrzanym do 180 stopni. Ustaw opcj pieczenia g贸ra/d贸. Naczynie z gobkami piecz bez przykrycia przez okoo 35 minut. 

|===

[.text-center]
== Zdjcia
