= Gołąbki +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 1,5 h
* 14 sztuk
* https://www.kwestiasmaku.com/kuchnia_polska/golabki/przepis.html[link do źródła przepisu]

== Składniki
* 700 g mielonej wieprzowiny (łopatka, szynka lub karczek)
* 100 g ryżu
* 2 cebule
* 1 biała lub włoska kapusta
* 1,5 litra bulionu lub rosołu
* 600 g przecieru pomidorowego*
* 1 łyżka mąki
* przyprawy: sól i pieprz, 1 łyżeczka suszonego oregano, 1/2 łyżeczki papryki w proszku, 1/2 łyżeczki tymianku
* opcjonalnie: 4 łyżki gęstej śmietany 18%

|
== Przygotowanie
Mięso włożyć do większej miski. Ryż ugotować, ostudzić i dodać do mięsa. Cebulę obrać, zetrzeć na tarce, dodać do mięsa z ryżem. Doprawić solą (około pół łyżeczki), pieprzem (1/4 łyżeczki). Wszystko wymieszać i dobrze wyrobić dłonią. Uformować niewielkie podłużne kotlety.

Wyciąć głąb ze środka kapusty, następnie włożyć ją do dużego garnka z wrzątkiem (wyciętą stroną do dołu), gotować przez około 10 minut na małym ogniu. Przewrócić kapustę na drugą stronę i gotować przez ok. 5 minut. Wyjąć kapustę z wrzątku i po przestudzeniu rozebrać ją z liści, odciąć delikatnie zgrubienia z każdego liścia, następnie nakładać przygotowane porcje mięsa.

Zawijać jak krokiety (najpierw założyć liść na mięso z jednej strony, później złożyć boki do środka, następnie zwinąć jak najciaśniej do końca pozostałą część liścia). Nie cała kapusta musi być wykorzystana.

Dno dużego i najlepiej szerokiego garnka wyłożyć kilkoma liśćmi kapusty (np. takimi, które się porwały). Na wierzchu ułożyć gołąbki łączeniem do dołu. Zagotować bulion w innym garnku i zalać nim gołąbki. Postawić na gazie, przykryć i gotować przez około 45 - 60 minut aż kapusta będzie miękka. W czasie gotowania nie mieszać gołąbków, ewentualnie delikatnie potrząsnąć garnkiem.

Wywar z gołąbków przelać do innego garnka. Dodać przecier pomidorowy oraz mąkę rozmieszaną wcześniej z kilkoma łyżkami zimnej wody. Zagotować, doprawić solą, pieprzem, suszonym oregano, tymiankiem i papryką. Gotować przez 10 minut bez przykrycia.

Jeśli dodajemy śmietanę należy rozprowadzać ją stopniowo z sosem, dodając go po łyżce do śmietany jednocześnie mieszając. Przelać do garnka z gołąbkami i gotować całość przez kilka minut na małym ogniu, od czasu do czasu potrząsnąć garnkiem aby sos równomiernie się rozprowadził.

|===

[.text-center]
== Zdjęcia
