= Gołąbki bez zawijania

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* https://aniagotuje.pl/przepis/golabki-bez-zawijania[link do źródła przepisu]

== Składniki
* 800 g łopatki wieprzowej
* 800 g kapusty (około pół główki) - młoda lub stara + łyżeczka soli
* 2 średnie cebule - 250 g
* 3 łyżki oleju do usmażenia cebuli
* 1 średnie jajko
* 100 g suchego ryżu - niecałe pół szklanki
* garść koperku
* po płaskiej łyżeczce soli i pieprzu
* dodatkowo: olej do podsmażenia kotletów gołąbkowych
* 1,5 l esencjonalnego bulionu
* 2 łyżki koncentratu pomidorowego
* pół szklanki przecieru pomidorowego
* płaska łyżka mąki pszennej


|
== Przygotowanie
Niesamowicie smaczne i wyjątkowo proste w przygotowaniu gołąbki bez zawijania to trochę inna wersja tradycyjnych gołąbków. Zachęcam do wypróbowania tego przysmaku. Przepis jest bardzo czytelny, więc do działa!

- gołąbki z kapustą w kotletach

- łopatka wieprzowa, ryż i siekana kapustka

- w wersji z kapustą młodą, starą lub nawet pekińską

Czas przygotowania: 1 godzina

Liczba porcji: około 21 gołąbków z sosem





Kaloryczność kcal: 120 w 1 gołąbku



Składniki na gołąbki

Składniki na sos pomidorowy

Szklanka ma u mnie pojemność 250 ml.

Warzywa ważone były przed ewentualnym obraniem/przygotowaniem.

Kalorie policzone zostały na podstawie użytych przeze mnie składników. Jest to więc orientacyjna ilość kalorii liczona na podstawie produktów, których użyłam w danym przepisie. Z podanej ilości składników otrzymasz około 20-22 kotlecików. Podczas liczenia kaloryczności dania, nie uwzględniłam sosu.

Przed szykowaniem gołąbków bez zawijania zachęcam też do przeczytania najpierw całego wpisu. W treści podaję bowiem dużo ciekawych porad dotyczących składników oraz ich zamienników. Być może zapragniesz użyć np. kapusty pekińskiej zamiast zwykłej białej. Na koniec opisuję również jak zrobić gołąbki bez zawijania w piekarniku.

Potrzebujesz około 800 gramów mięsa wieprzowego. Według mnie najlepsza do gołąbków bez zawijania jest łopatka wieprzowa. Zakupiłam dość tłustą łopatkę, ponieważ taką właśnie lubimy, ale możesz też wybrać w sklepie znacznie chudszy kawałek mięsa. Na gołąbki bez zawijania nada się również mieszanka karkówki z chudą szynką lub też  biodrówka, którą gorąco polecam.

Mięso zmiel w maszynce na średnich oczkach. Jeśli nie masz maszynki, to polecam zakup mięsa u rzeźnika z możliwością zmielenia mięsa na miejscu w sklepie.

Porada: Możesz też użyć kapustę starą/białą oraz kapustę pekińską. Postępujesz z nimi tak samo, jak z młodą kapustą.

Całość wymieszaj i zagotuj. Zmniejsz moc i zacznij umieszczać w garnku kotlety gołąbkowe. Umieść wszystkie i zwiększ moc do takiej, by całość tylko lekko mrugała. Gołąbki bez zawijania gotuj tak 35 minut bez przykrycia.

Na koniec możesz jeszcze zagęścić sos pomidorowy dodając płaską łyżkę mąki pszennej (Ja zazwyczaj odlewam sobie wcześniej odrobinę bulionu i rozrabiam go z mąką. Jednolitą mieszankę wlewam do garnka, lekko mieszam. Po zagotowaniu wyłączam). Porada: Sprawdź smak sosu i w razie potrzeby dopraw go pod koniec pieprzem lub solą. Pasuje też słodka papryka, oregano i majeranek. Można też wlać odrobinę śmietanki 30 %.

Kto nie kocha domowych, tradycyjnych gołąbków zawijanych w liść kapusty młodej lub starej.. Otóż są cacy, co nie przepadają za kapustą i zdejmują ją z gołąbków. Kapusta idzie na bok talerza a kotlecik do buzi. Zauważyłam (pewnie nie tylko ja), że wiele osób nie podziela mojej miłości do liści kapusty okalającej gołąbki. Ja osobiście bardzo lubię gołąbki. Robiła je moja Babia i Mama i sama też dość często je szykuję. Czasem robię je z ryżem a czasem bez. Ponieważ nie każdy jest miłośnikiem kapusty, którą owija się gołąbki lub też nie każdy lubi to zajęcie, to powstał przepis na gołąbki bez zawijania. Dla tych co nie lubią zawijać i obgotowywać liści kapusty oraz dla tych, co nie przepadają za oczywistym smakiem i za widokiem liści kapusty, ale i dla tych, co lubią urozmaicenie w kuchni mam teraz gołąbki bez zawijania przepis doskonały i sprawdzony. Tak jak czasem szykujemy inaczej nasze tradycyjne schabowe, tak samo można poszaleć i zrobić takie właśnie gołąbki inaczej z kapustą szatkowaną w środku. Polecam Ci też przepis na pulpety w sosie koperkowym. koniecznie sprawdź też przepis na gołąbki z młodej kapusty z ryżem.

Moje golabki bez zawijania szykuję w garnku z lekkim bulionem z dodatkiem przecieru oraz koncentratu i tylko odrobiny dodatkowych przypraw. Zazwyczaj jest to tylko sól i pieprz. Czasem też oregano, odrobina  cukru czy też słodkiej papryki. Ilość przypraw zależny też od tego jak mocny jest mój bulion. Czasem nie doprawiam sosu wcale a czasem daję sporo przypraw. Na koniec zdarza mi się zagęszczać lekko sos mąką pszenną lub skrobią ziemniaczaną. Zaś w sezonie na świeże pomidory, pomijam przeciery i koncentraty i dodaję pokrojone w kostkę obrane, świeże pomidory malinowe.. pycha! Moje gołąbki bez zawijania tuż po uformowaniu podsmażam najpierw na patelni a potem ostrożnie przenoszę do gotującego się sosu pomidorowego. To moja ulubiona wersja. Sama uwielbiam kapustę. To jedno z bardziej uniwersalnych warzyw o szerokim wachlarzu zastosowania. Często szykuję najróżniejsze dania z kapustą w roli głównej. Kapusta zasmażana to wielki hit w naszym domu. Najlepsza z młodej kapusty. Na Święta nie ma nic lepszego niż pierogi z kapustą i grzybami. U nas każdy na nie czeka. A surówka z białej kapusty to warzywny dodatek, który towarzyszy wielu pysznym obiadkom.

Jednak mogą być różne przepisy na gołąbki bez zawijania. Również samo wykonanie może być trochę inne. Można bowiem po wstępnym obsmażeniu kotletów umieścić je w naczyniu żaroodpornym a następnie zalać sosem pomidorowym i nie gotować a piec w piekarniku. Powstaje wówczas trochę inna wersja, czyli gołąbki bez zawijania w piekarniku. Takie gołąbki mają mniej sosu, niż te gotowane w garnku. Niektórzy wybierają tę właśnie opcję np. dlatego, że boją się gotowania gołąbków w garnku a raczej tego, że gołąbki się rozpadną. Innym zwyczajnie takie pieczone bardziej smakują. Wszystko kwestia gustu, ale polecam spróbować obu wersji. Można też zamiast kapusty białej sięgnąć wówczas po kapustę pekińską. Niezależnie od tego, czy chcesz gołąbki gotować w sosie, czy zapiec w piekarniku możesz śmiało przygotować gołąbki bez zawijania z kapustą pekińską. Szykujesz je dokładnie tak samo, jak gołąbki bez zawijania z kapustą białą. Gorąco zachęcam też przy okazji do kilku innych przepisów z udziałem kapusty pekińskiej. Bardzo dobra jest moja surówka z kapusty pekińskiej. Polecam ją gorąco.



== Zdjęcia
|===
