= Gołąbki bez zawijania

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 1 godzina
* liczba porcji: około 21 gołąbków z sosem
* https://aniagotuje.pl/przepis/golabki-bez-zawijania[link do źródła przepisu]

== Składniki
* 800 g łopatki wieprzowej
* 800 g kapusty (około pół główki) - młoda lub stara + łyżeczka soli
* 2 średnie cebule - 250 g
* 3 łyżki oleju do usmażenia cebuli
* 1 średnie jajko
* 100 g suchego ryżu - niecałe pół szklanki
* garść koperku
* po płaskiej łyżeczce soli i pieprzu
* dodatkowo: olej do podsmażenia kotletów gołąbkowych
* 1,5 l esencjonalnego bulionu
* 2 łyżki koncentratu pomidorowego
* pół szklanki przecieru pomidorowego
* płaska łyżka mąki pszennej

|
== Przygotowanie
Potrzebujesz około 800 gramów mięsa wieprzowego. Według mnie najlepsza do gołąbków bez zawijania jest łopatka wieprzowa. Zakupiłam dość tłustą łopatkę, ponieważ taką właśnie lubimy, ale możesz też wybrać w sklepie znacznie chudszy kawałek mięsa. Na gołąbki bez zawijania nada się również mieszanka karkówki z chudą szynką lub też  biodrówka, którą gorąco polecam. 

Mięso zmiel w maszynce na średnich oczkach. Jeśli nie masz maszynki, to polecam zakup mięsa u rzeźnika z możliwością zmielenia mięsa na miejscu w sklepie. 

Ważąc kapustę do tych gołąbków używam jej tyle samo co mięsa, lub trochę mniej. Te akurat gołąbki bez zawijania szykowałam z młodej kapusty. Odkroiłam 800 gramów kapusty. Po zdjęciu brzydkich liści i wycięciu głąba zostało mi około 630 gramów kapusty gotowej do szatkowania. 
Porada: Możesz też użyć kapustę starą/białą oraz kapustę pekińską. Postępujesz z nimi tak samo, jak z młodą kapustą.

Kapustę trzeba bardzo, bardzo dokładnie i drobno poszatkować. Można zrobić to nożem, jednak zdecydowanie polecam użyć maszynki z nakładką do drobnego siekana warzyw. Niektórym udaje się zetrzeć kapustę na tarce. 

Do startej lub posiekanej kapusty wsyp łyżeczkę soli. Całość wymieszaj, ugnieć i odstaw na bok, na 10-20 minut. 

Po tym czasie zacznij odciskać kapustę z wody. Polecam nabierać garść kapusty i odciskać ją mocno nad zlewem. Odciśniętą kapustę przekładaj do miski ze zmielonym mięsem. Zazwyczaj odciskam około 150 ml wody. W ten sposób odciśnij bardzo dokładnie całą kapustę. 

Ugotuj 100 gramów ryżu (jedna saszetka lub niecałe pół szklanki suchego ryżu). Może to być np. ryż Basmati lub ryż jaśminowy. Po ugotowaniu i odsączeniu wyszło mi 290 gramów ryżu. 

Przygotuj sobie średnią patelnię z grubym dnem. Zacznij ją nagrzewać. Dodaj trzy łyżki oleju do smażenia. Na patelnię wyłóż też obrane i drobno posiekane cebule. Podsmażaj cebulkę na średniej mocy palnika przez około 10 minut, aż zrobi się rumiana. 

Do miski ze zmielonym mięsem i posiekaną i odciśniętą kapustą dodaj też całą podsmażoną cebulkę oraz ugotowany i lekko przestudzony ryż. Wbij jedno jajko i dodaj garść siekanego koperku (koperek można pominąć). Wsyp po płaskiej łyżeczce soli i pieprzu.

Zacznij wyrabiać masę mięsną pod gołąbki bez zawijania. Ja mieszam masę dłońmi, ponieważ tak jest mi najwygodniej i widzę oraz czuję, czy masa jest dokładnie wymieszana. Masę mięsną mieszam tak przez przynajmniej pięć minut, aż będzie idealnie jednolita. 

Przygotuj sobie dużą patelnię z grubym dnem. Zacznij ją nagrzewać. Wlej około pięciu łyżek oleju do smażenia. Z przygotowanej masy formuj kotlety. Jeden kotlet ważył u mnie około 80 gramów. Masę podzieliłam zatem na 21 kotletów. Każdego kotleta formowałam w dłoni na idealną kulkę, którą następnie lekko wydłużałam i spłaszczałam. 

Na patelni umieszczaj po kilka kotletów na raz i podsmażaj je na rumiano z obu stron, na trochę wyższej niż średnia moc palnika (wystarczy minuta na stronę).

W tej sposób podsmaż wszystkie kotleciki gołąbkowe. 

Do dużego garnka wlej 1500 ml bulionu. Może to być sam rosół drobiowy lub też nawet bulion warzywny. Wlej do niego pół szklanki przecieru pomidorowego (może być Passata z butelki, czy też pomidorki z kartonu) i dodaj dwie łyżki koncentratu pomidorowego. Zamiast przecieru możesz użyć dwój dużych pomidorów malinowych (obrane i drobno posiekane). 
Całość wymieszaj i zagotuj. Zmniejsz moc i zacznij umieszczać w garnku kotlety gołąbkowe. Umieść wszystkie i zwiększ moc do takiej, by całość tylko lekko mrugała. Gołąbki bez zawijania gotuj tak 35 minut bez przykrycia. 

Na koniec możesz jeszcze zagęścić sos pomidorowy dodając płaską łyżkę mąki pszennej (Ja zazwyczaj odlewam sobie wcześniej odrobinę bulionu i rozrabiam go z mąką. Jednolitą mieszankę wlewam do garnka, lekko mieszam. Po zagotowaniu wyłączam). 

Gołąbki bez zawijania podaję z ziemniakami lub kluskami śląskimi. Kopytka oraz makaron lub kasza gryczana też pasują. W sezonie na świeże pomidory bardzo często dodaję je do sosu na sam koniec lub też bezpośrednio na talerz przed podaniem. Polecam też ogórki kiszone i małosolne. Całość posyp też koperkiem, szczypiorkiem lub natką pietruszki. 

Aby zrobić gołąbki bez zawijania w piekarniku wystarczy, że po podsmażeniu na patelni kotlecików gołąbkowych ułożysz je jeden obok drugiego w dużym naczyniu żaroodpornym. Gołąbki zalej sosem pomidorowym. Sos pomidorowy to: 2 szklanki bulionu; 2 szklanki przecieru pomidorowego; 4 łyżki koncentratu; 4 łyżki śmietanki słodkiej 30 %, po łyżeczce soli i oregano oraz pół łyżeczki pieprzu. Gołąbki bez zawijania umieść na środkowej półce w piekarniku nagrzanym do 180 stopni. Ustaw opcję pieczenia góra/dół. Naczynie z gołąbkami piecz bez przykrycia przez około 35 minut. 

== Zdjęcia
|===
