= Grecki klopsiki w sosie pomidorowym  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* https://polikala.com/index.php/2022/11/22/keftedakia-kefetedes-greckie-klopsiki-pelne-smaku/[link do 藕r贸da przepisu]

== Skadniki

* 1 kg misa mielonego wieprzowo-woowego
* 1 cebula starta na tarce o grubych oczkach
* 2 y偶ki tuczonej lub grubo mielonej kolendry
* 1 y偶eczka mielonego kminu rzymskiego
* 1 y偶ka patk贸w chilli
* 2 zbki czosnku startego na tarce
* 2 y偶eczki soli
* 1/2 pczka mity pieprzowej (samych lici) lub 1 y偶eczka suszonej mity pieprzowej
* 1 pczek natki pietruszki
* 2-3 y偶ki buki tartej
* 1 jajko
* 2-3 y偶ki lodowatej wody
* 2-3 y偶ki mki pszennej
* 200 ml oliwy
* passata pomidorowa
* 200 g fety

|
== Przygotowanie

Do misa dodaj cebul, przyprawy, starty czosnek, s贸l oraz posiekan mit i natk pietruszki. Dokadnie wszystko wymieszaj i odstaw do lod贸wki na minimum p贸 godziny (a najlepiej na ca noc).

Wyjmij miso z lod贸wki i dodaj jajko, buk tart oraz lodowat wod.

Wyrabiaj domi tak dugo, a偶 masa zacznie klei si do rk.

Formuj klopsiki wielkoci orzecha woskiego (lub wiksze jeli wolisz) i obtaczaj je w mce, strzepujc jej nadmiar.

Na szerokiej patelni rozgrzej oliw.

Sma偶 klopsiki z ka偶dej strony na zoty kolor, nastpnie odscz je na talerzu wyo偶onym rcznikiem papierowym.

Zagotuj passat pomidorow, w贸偶 klopsiki i podgotuj przez 3 minuty. Skrusz fet i dodaj do potrawy.

|===

[.text-center]
== Zdjcia
