= Gulasz wołowy

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 3 h
* 4 porcje
* https://www.kwestiasmaku.com/przepis/gulasz-wolowy[link do źródła przepisu]

== Składniki
* 1 kg wołowiny gulaszowej
* 150 g wędzonego boczku
* 2 łyżki oleju roślinnego
* 1/2 małego pora
* 1/2 cebuli
* 2 ząbki czosnku
* 1 łyżeczka papryki słodkiej i 1/3 ostrej
* 1,5 łyżki mąki pszennej
* 1/3 szklanki czerwonego wina (opcjonalnie)
* 750 ml bulionu wołowego
* 1 mała czerwona papryka
* 150 g małych pieczarek

|
== Przygotowanie
Mięso pokroić w większą kostkę (ok. 3 - 4 cm). Boczek pokroić w kosteczkę, włożyć do dużego garnka z grubym dnem i co chwilę mieszając wytapiać go na małym ogniu przez ok. 3 minuty.

Zwiększyć ogień, wlać olej i stopniowo wkładać po kilka kawałków mięsa. Obsmażyć z każdej strony, w sumie przez ok. 10 minut. W międzyczasie doprawić solą oraz pieprzem.

Dodać posiekanego pora, pokrojoną cebulę oraz starty czosnek. Co chwilę mieszając smażyć wszystko przez ok. 5 - 8 minut, pod koniec dodając paprykę w proszku.

Posypać składniki mąką (bezpośrednio przez sitko), wymieszać i smażyć co chwilę mieszając przez ok. 5 minut.

Wlać wino jeśli go używamy a po chwili podgrzany bulion. Zagotować, przykryć pokrywą i zmniejszyć ogień. Gotować pod przykryciem na małym ogniu przez ok. 1 i 1/2 godziny. W międzyczasie potrząsać przykrytym garnkiem w celu przemieszania składników i sprawdzenia czy gulasz nie przywiera do dna.

Po podanym czasie dodać do gulaszu pokrojoną paprykę oraz pokrojone pieczarki. Wymieszać, przykryć i gotować jeszcze przez 1/2 godziny.

== Zdjęcia
|===
