= Gulasz woowy ォ +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 3 godziny
* 4 porcje
* https://www.kwestiasmaku.com/przepis/gulasz-wolowy[link do 藕r贸da przepisu]

== Skadniki

* 1 kg woowiny gulaszowej
* 150 g wdzonego boczku
* 2 y偶ki oleju rolinnego
* 1/2 maego pora
* 1/2 cebuli
* 2 zbki czosnku
* 1 y偶eczka papryki sodkiej i 1/3 ostrej
* 1,5 y偶ki mki pszennej
* 1/3 szklanki czerwonego wina (opcjonalnie)
* 750 ml bulionu woowego
* 1 maa czerwona papryka
* 150 g maych pieczarek

|
== Przygotowanie

Miso pokroi w wiksz kostk (ok. 3 - 4 cm). Boczek pokroi w kosteczk, wo偶y do du偶ego garnka z grubym dnem i co chwil mieszajc wytapia go na maym ogniu przez ok. 3 minuty.

Zwikszy ogie, wla olej i stopniowo wkada po kilka kawak贸w misa. Obsma偶y z ka偶dej strony, w sumie przez ok. 10 minut. W midzyczasie doprawi sol oraz pieprzem.

Doda posiekanego pora, pokrojon cebul oraz starty czosnek. Co chwil mieszajc sma偶y wszystko przez ok. 5 - 8 minut, pod koniec dodajc papryk w proszku.

Posypa skadniki mk (bezporednio przez sitko), wymiesza i sma偶y co chwil mieszajc przez ok. 5 minut.

Wla wino jeli go u偶ywamy a po chwili podgrzany bulion. Zagotowa, przykry pokryw i zmniejszy ogie. Gotowa pod przykryciem na maym ogniu przez ok. 1 i 1/2 godziny. W midzyczasie potrzsa przykrytym garnkiem w celu przemieszania skadnik贸w i sprawdzenia czy gulasz nie przywiera do dna.

Po podanym czasie doda do gulaszu pokrojon papryk oraz pokrojone pieczarki. Wymiesza, przykry i gotowa jeszcze przez 1/2 godziny.

|===

[.text-center]
== Zdjcia
