= Gulasz z szynki

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 1 godzina 30 minut
* liczba porcji: 1900 g gulaszu
* https://aniagotuje.pl/przepis/gulasz-wieprzowy[link do źródła przepisu]

== Składniki
* 1 kg łopatki wieprzowej
* 2 średnie czerwone papryki - 500 g
* 2 duże marchewki - 300 g
* 3 średnie cebule - 300 g
* 4 duże ząbki czosnku
* 70 g smalcu wieprzowego lub gęsiego
* 2 szklanki bulionu warzywnego lub mięsnego - 500 ml
* 3 łyżki koncentratu pomidorowego
* przyprawy: 2 łyżki słodkiej papryki, po pół łyżeczki soli i pieprzu, szczypta chili

|
== Przygotowanie
Zacznijmy od mięsa wieprzowego. Potrzebujesz około jednego kilograma mięsa (Może być trochę mniej. Wystarczy nawet 800 gramów). Najpyszniejszy gulasz wychodzi mi zawsze na łopatce wieprzowej, ale możesz też użyć samej szynki lub też wymieszać szynkę z karkówką w proporcjach pół na pół. 

Mięso pokrój na nieduże kawałki na jeden kęs. Postaraj się, by kawałki mięsa były mniej więcej tej samej wielkości, czyli do 2 x 2 cm. Do miski z kawałkami mięsa wsyp też przyprawy: 2 łyżki słodkiej papryki, po pół łyżeczki soli i pieprzu oraz symboliczna szczypta chili. Cztery duże ząbki czosnku obierz i przepuść przez praskę. Jeśli nie masz świeżego czosnku, to dodaj jedną łyżkę suszonego. Dokładnie wymieszaj mięso z przyprawami i czosnkiem.

Nagrzej dużą i głęboką patelnię i roztop na niej 20 gramów dobrej jakości smalcu wieprzowego lub gęsiego (pozostałe 50 gramów zostawiamy do usmażenia warzyw). Na patelnię wyłóż kawałki mięsa. Podsmażaj je na trochę wyższej niż średnia moc palnika przez 25 minut (taka samo długo podsmażasz zarówno szynkę, jak i łopatkę, czy mięso karkowe). Co jakiś czas zamieszaj mięso. Cały czas podsmażaj je też bez przykrywki. 

W trakcie smażenia mięsa przygotuj warzywa. Potrzebujesz dwie duże lub trzy średnie cebule, dwie większe marchewki oraz dwie średniej wielkości czerwone papryki. Cebule możesz zamienić na dużego pora. Jeśli chodzi i papryki, to możesz też zamienić jedną czerwoną paprykę na paprykę żółtą lub pomarańczową. 

Nagrzej średniej wielkości patelnię i roztop na niej pozostałe 50 gramów smalcu. Dodaj obraną i pokrojoną na małe kawałki cebulę. Ja pokroiłam ją w piórka, które przekroiłam jeszcze na pół. Podsmażaj ją tak przez pięć minut a następnie dodaj też obrane i pokrojone w półplasterki marchewki.

Całość wymieszaj i podsmażaj na trochę niższej niż średnia moc palnika przez kolejne 15 minut. Patelni nie przykrywaj przykrywką. Co parę minut zamieszaj warzywa przy pomocy drewnianej łyżki. 

Po tym czasie dodaj jeszcze oczyszczone z gniazda nasiennego i pokrojone na mniejsze kawałki papryki. Warzywa zamieszaj i smaż ostatnie 10 minut. 

Wszystkie warzywa z patelni przełóż na głęboką patelnię z podsmażonym już mięsem. Wlej też dwie szklanki (500 ml) domowego bulionu warzywnego lub mięsnego. Wymieszaj dokładnie gulasz wieprzowy i gotuj przez 20 minut na małej mocy palnika (bez przykrywki). 

Na koniec dodaj do gulaszu koncentrat pomidorowy. Ja dodałam trzy łyżki koncentratu, ale możesz dodać go trochę mniej lub więcej. Gulasz z dodatkiem koncentratu zrobi się bardziej gęsty i zawiesisty. Jeśli zamiast koncentratu dodasz np. przecier z pomidorów lub też obrane i posiekane świeże pomidory, to sos w gulaszu będzie trochę rzadszy. 

Możesz zawsze lekko zagęścić gulasz przez dodanie do niego skrobi ziemniaczanej. Wówczas płaską łyżkę skrobi/mąki ziemniaczanej wymieszaj dokładnie z kilkoma łyżkami wody lub bulionu i wlej do lekko mrugającego gulaszu. Od razu zamieszaj gulasz. Gulasz wyłącz po około jednej minucie od dodania wody ze skrobią. Sos w gulaszu powinien zgęstnieć i zrobić się bardziej szklisty. 

Zanim jednak wyłączysz gulasz, sprawdź jego smak. Być może wolisz bardziej słony gulasz i dodasz do niego trochę soli. Jeśli gulasz wieprzowy ma być ostrzejszy, to dodaj do niego więcej pieprzu lub chili. 

Gulasz wieprzowy bardzo dobrze smakuje podany z kromką ulubionego pieczywa i ogórkiem kiszonym. Do gulaszy pasują również kasze: gryczana, pęczak, kuskus. Gulasz wieprzowy smakuje świetnie z tłuczonymi ziemniakami, kopytkami i kluskami śląskimi oraz surówką z białej lub czerwonej kapusty. 

== Zdjęcia
|===
