= Kaczka po wietnamsku +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 2,5 h
* 4 porcje
* https://www.kwestiasmaku.com/kuchnia_polska/kaczka/kaczka_duszona_w_soku_pomaranczowym/przepis.html[link do źródła przepisu]

== Składniki
* 1 kaczka o wadze ok. 2-2.5 kg, sprawiona, poporcjowana na kawałki lub same udka
* 1 łyżka oliwy
* 4 ząbki czosnku
* 50 g imbiru
* 5 gwiazdek anyżu gwiazdkowego
* od 1 do 4 małych papryczki chili (w zależności od preferencji)
* 2 trawy cytrynowe
* 800 ml świeżo wyciśniętego soku z pomarańczy
* 4 łyżki sosu rybnego
* 1 łyżka brązowego cukru
* świeżo zmielony pieprz
* 8 cebulek dymek (białe części i kilka łyżek posiekanego szczypiorku)
* 1/2 łyżeczki mąki ziemniaczanej

|
== Przygotowanie

W dużym garnku z pokrywką rozgrzać łyżkę oliwy. Włożyć kawałki kaczki skórą do dołu (tyle ile się zmieści, aby następnie powtórzyć z kolejną partią mięsa) i dokładnie obsmażyć aż tłuszcz się wytopi a skórka zezłoci (ok. 6 minut). Przewrócić na drugą stronę i obsmażyć aż mięso zmieni kolor na jasnobrązowy (ok. 2 minuty).

Wyjąć obsmażone mięso i odłożyć na talerz. Z garnka ostrożnie odlać tłuszcz zostawiając jedynie ok. 1 łyżki tłuszczu w garnku (odlany tłuszcz można wykorzystywać do przysmażania, np. ziemniaków). Czosnek obrać i rozgnieść płaską częścią noża, imbir obrać i pokroić na cienkie plasterki.

W garnku, na małym ogniu podsmażyć przygotowany czosnek i imbir aż się zezłocą i uwolnią swój aromat. Dodać anyż, umyte papryczki chili (w całości), trawę cytrynową (wcześniej należy rozgnieść płaską częścią noża jej bulwę) i podsmażyć wszystko jeszcze przez minutę. Wlać sok pomarańczowy i sos rybny, dodać cukier, pieprz i obsmażone kawałki kaczki. Przykryć i gotować na małym ogniu przez ok. 2 godziny lub do miękkości mięsa. Pół godziny przed zakończeniem duszenia dodać białe części cebuli dymki.

Kaczkę wyjąć i ułożyć na podgrzanych talerzach. Z wierzchu sosu zebrać nadmiar tłuszczu, dodać mąkę ziemniaczaną wymieszaną w kilku łyżkach wody, zamieszać i zagotować. Kaczkę polać sosem, posypać szczypiorkiem, serwować z ryżem i np. sałatką z mango.

|===

[.text-center]
== Zdjęcia
