= Kaczka z jabkami, 偶urawin i rozmarynem  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 2 godziny
* 4 porcje
* https://www.kwestiasmaku.com/przepis/pieczone-udka-kaczki[link do 藕r贸da przepisu]

== Skadniki

* 4 kacze udka
* wie偶y rozmaryn
* 2 zbki czosnku
* s贸l i pieprz
* 偶urawina ze soiczka (+ troch wie偶ej jeli mamy)
* 2 jabka (odmiany szara reneta, boiken)
* 1/2 y偶eczki cynamonu
* 1 y偶ka masa + 1 y偶eczka miodu

|
== Przygotowanie

Udka wyj wczeniej z lod贸wki. Doprawi sol i pieprzem, doda obrany i przepoowiony czosnek oraz kilka kawak贸w gazek rozmarynu. Uo偶y sk贸rk do g贸ry w naczyniu lub formie do pieczenia, szczelnie przykry pokryw lub foli aluminiow i piec przez 90 minut w 180 stopniach C.

Pod koniec pieczenia zacz przygotowywa jabka: przekroi na po贸wki, obra, wydr偶y nasiona i ponacina no偶em od wypukej strony. Posypa cynamonem.

Zdj przykrycie z formy, zla tuszcz (mo偶na go wykorzysta do sma偶enia ziemniak贸w), doda jabka (naciciami do g贸ry). Wsypa wie偶 偶urawin wie偶 jeli j mamy. Udka posmarowa masem roztopionym z miodem i piec przez 20 minut tym razem bez przykrycia. Udekorowa wie偶ym rozmarynem i 偶urawin ze soiczka.

|===

[.text-center]
== Zdjcia
