= Kaszotto z grzybami lenymi  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 45 minut
* 4 porcje
* https://www.cafebabilon.pl/kaszotto-z-grzybami-lesnymi/[link do 藕r贸da przepisu]

== Skadniki

* 500 g grzyb贸w lenych, wie偶ych lub mro偶onych
* po 2 y偶ki masa i oleju
* 2 szalotki (mo偶na zastpi zwyk cebul)
* 250 g kaszy pczak
* 3 szklanki bulionu warzywnego lub grzybowego
* 1/2 pczka natki pietruszki
* s贸l, wie偶o mielony pieprz

|
== Przygotowanie

wie偶e grzyby oczy i opucz, a mro偶one wy贸偶 na sito, aby si rozmroziy. Nastpnie du偶e pokr贸j w mniejsze kawaki, mae mog pozosta w caoci.
Szalotk obierz, pokr贸j w kostk i opr贸sz sol.
Na du偶ej patelni rozgrzej maso z olejem. Dodaj szalotk i na maym ogniu sma偶 a偶 zmiknie.
Do贸偶 grzyby i such kasz, zwiksz moc palnika i sma偶 3-4 minuty. Wlej 1 szklank bulionu, dopraw sol i pieprzem. Zmniejsz ogie i gotuj, co jaki czas mieszajc. Gdy pyn si wchonie, wlej kolejn szklank bulionu, a nastpnie czynnoci powt贸rz.
Gotuj do mikkoci kaszy, w razie potrzeby podlej wod.
Przed podaniem posyp wie偶o mielonym pieprzem, a na talerzach obficie posyp natk pietruszki.

|===

[.text-center]
== Zdjcia
