= Kaszotto z kurkami 🌱 +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły

* czas przygotowania: do 30 min
* 4 porcje
* https://www.jadlonomia.com/przepisy/kaszotto-z-kurkami[link do źródła przepisu]

== Składniki

* 1 cebula
* ½ ząbka czosnku
* ½ szklanki kaszy gryczanej
* olej
* ¾ szklanki bulionu warzywnego lub wody
* 1 łyżka oleju
* 200 g kurek
* 1 duży pomidor malinowy lub 2 mniejsze
* sól i czarny pieprz
* do podania: świeża pietruszka, płatki drożdżowe, kupuję tutaj

|
== Przygotowanie

Cebulę pokroić w kostkę, czosnek bardzo dokładnie posiekać. Na dnie dużej patelni rozgrzać olej, dodać cebulę i smażyć przez 1 - 2 minuty. Następnie dodać czosnek, zamieszać i wsypać kaszę gryczaną. Smażyć przez kolejną minutę, po czym wlać bulion i patelnię przykryć, gotować przez około 15 minut do momentu, aż kasza wchłonie cały płyn.

Kiedy kasza jest prawie gotowa w czajniku zagotować wodę. Kurki umyć w zimnej wodzie, osuszyć i pokroić na połówki; a pomidora naciąć, włożyć do miski i wlać zagotowaną wodę. Po chwili pomidora wyjąć, obrać i posiekać.

Odkryć patelnię z kaszą, dolać łyżkę oleju i porządnie rozgrzać. Wrzucić kurki, smażyć 2 - 3 minuty na dużym ogniu, a na koniec dodać posiekanego pomidora, sól i czarny pieprz. Dusić przez 5 minut, podawać ze świeżą pietruszką i płatkami drożdżowymi.

Kaszotto nie może się nie udać, ale kluczowe jest dodanie do ugotowanej kaszy oleju i ponowne rozgrzanie - kurki, jak wszystkie grzyby, lubią być smażone, szybko i intensywnie. W przeciwnym wypadku będą gąbczaste i nijakie w smaku.

Jeśli nie macie płatków drożdżowych możecie kaszotto podawać z pietruszką i posiekanym, suszonym pomidorem.

|===

[.text-center]
== Zdjęcia
