= Kaszotto z grzybami leśnymi

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 45 min
* 4 porcje
* https://www.cafebabilon.pl/kaszotto-z-grzybami-lesnymi[link do źródła przepisu]

== Składniki
* 500 g grzybów leśnych, świeżych lub mrożonych
* po 2 łyżki masła i oleju
* 2 szalotki (można zastąpić zwykłą cebulą)
* 250 g kaszy pęczak
* 3 szklanki bulionu warzywnego lub grzybowego
* 1/2 pęczka natki pietruszki
* sól, świeżo mielony pieprz

|
== Przygotowanie
Świeże grzyby oczyść i opłucz, a mrożone wyłóż na sito, aby się rozmroziły. Następnie duże pokrój w mniejsze kawałki, małe mogą pozostać w całości.
Szalotkę obierz, pokrój w kostkę i oprósz solą.
Na dużej patelni rozgrzej masło z olejem. Dodaj szalotkę i na małym ogniu smaż aż zmięknie.
Dołóż grzyby i suchą kaszę, zwiększ moc palnika i smaż 3-4 minuty. Wlej 1 szklankę bulionu, dopraw solą i pieprzem. Zmniejsz ogień i gotuj, co jakiś czas mieszając. Gdy płyn się wchłonie, wlej kolejną szklankę bulionu, a następnie czynności powtórz.
Gotuj do miękkości kaszy, w razie potrzeby podlej wodą.
Przed podaniem posyp świeżo mielonym pieprzem, a na talerzach obficie posyp natką pietruszki.

|===

[.text-center]
== Zdjęcia
