= Kaszotto z indykiem, fasolką i cukinią

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 45 min
* 2 porcje
* https://www.kwestiasmaku.com/przepis/kaszotto-z-indykiem-fasolka-i-cukinia[link do źródła przepisu]

== Składniki
* 3 łyżki oliwy extra vergine
* 1/3 szklanki kaszy pęczak
* 1 cebula
* 1 łyżeczka suszonego oregano
* 200 g piersi indyka
* 4 łyżki sosu sojowego
* 60 ml białego wina
* 1 i 1/2 szklanki bulionu lub rosołu
* 200 g zielonej fasolki szparagowej
* 1 mała cukinia
* 4 łyżki posiekanego szczypiorku

|
== Przygotowanie
Na dużą patelnię wsypać kaszę, dodać łyżkę oliwy i chwilę podsmażyć. Cebulę pokroić w kosteczkę, dodać na patelnię i zeszklić mieszając od czasu do czasu przez ok. 5 minut. W międzyczasie dodać suszone oregano.

Przesunąć składniki na bok patelni, w wolne miejsce wlać 2 łyżki oliwy, włożyć zmielone mięso (lub rozdrobnione w melakserze lub drobno posiekane na desce). Polać sosem sojowym i obsmażać przez ok. 7 minut mieszając od czasu do czasu. W międzyczasie składniki z boku patelni 1 - 2 razy przemieszać.

Wymieszać wszystkie składniki na patelni i wlać białe wino, gotować ok. 2 - 3 minuty aż odparuje. Następnie wlać gorący bulion, doprawić świeżo zmielonym pieprzem i zagotować. Przykryć pokrywą i gotować pod przykryciem przez 20 minut.

Fasolkę przyciąć na końcach i pokroić na kawałki. Cukinię pokroić w kosteczkę. Fasolkę i cukinię dodać na patelnię, wymieszać i przykryć. Gotować przez ok. 7 minut pod przykryciem, w międzyczasie 1 raz składniki przemieszać. Otworzyć, wymieszać, posypać szczypiorkiem.

|===

[.text-center]
== Zdjęcia
