= Klopsiki z pieczarkami w sosie pomidorowym  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 35 minut
* 4 porcje
* https://www.kwestiasmaku.com/przepis/pulpeciki-w-sosie-pomidorowym[link do 藕r贸da przepisu]

== Skadniki

* 500 g mielonego misa (z indyka, cielcego lub wieprzowego np. z szynki)
* 1 cebula
* 2 zbki czosnku
* 1 y偶eczka suszonego oregano, 1/2 y偶eczki papryki w proszku
* 3 y偶ki buki tartej lub ugotowanej kaszy jaglanej
* 1 jajko
* 1 y偶ka sosu sojowego (opcjonalnie)
* 125 ml bulionu drobiowego lub rosou
* oliwa, maso
* 350 ml przecieru pomidorowego, passaty z butelki lub kartonu

|
== Przygotowanie

Na patelni na y偶ce oliwy zeszkli pokrojon w kosteczk cebul, pod koniec doda starty 1 zbek czosnku oraz 1 y偶k masa, suszone oregano i papryk w proszku, wymiesza i chwil razem podsma偶y. Zdj z patelni i zmieli razem z misem lub drobniej posieka na desce.

Zmielone miso wraz z podsma偶on cebul umieci w misce. Doda buk tart lub ugotowan kasz, jajko, sos sojowy, doprawi sol oraz pieprzem i dokadnie wyrobi. Wilgotnymi domi uformowa niedu偶e pulpeciki.

Rozgrza natuszczon oliw patelni i wo偶y pulpeciki. Gdy si zrumieni od spodu przewr贸ci na drug stron i powt贸rzy sma偶enie. Pod koniec na patelni doda starty drugi zbek czosnku i lekko go zrumieni.

Na patelni z pulpecikami wla gorcy bulion, przykry pokryw i gotowa przez ok. 5 - 7 minut, w midzyczasie potrzsn patelni w celu przemieszania pulpecik贸w.

Doda przecier pomidorowy i zagotowa. Gotowa bez przykrycia przez okoo 10 minut (jeli u偶ywalimy indyka) lub ok. 15 minut (w przypadku innego misa). W midzyczasie 1 - 2 razy zamiesza.

Sos spr贸bowa i doprawi w razie potrzeby sol, pieprzem, cukrem i suszonym oregano. Podawa z makaronem i tartym serem.

|===

[.text-center]
== Zdjcia
