= Klopsiki z pieczarkami w sosie pomidorowym

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 35 min
* 4 porcje
* https://www.kwestiasmaku.com/przepis/pulpeciki-w-sosie-pomidorowym[link do źródła przepisu]

== Składniki
* 500 g mielonego mięsa (z indyka, cielęcego lub wieprzowego np. z szynki)
* 1 cebula
* 2 ząbki czosnku
* 1 łyżeczka suszonego oregano, 1/2 łyżeczki papryki w proszku
* 3 łyżki bułki tartej lub ugotowanej kaszy jaglanej
* 1 jajko
* 1 łyżka sosu sojowego (opcjonalnie)
* 125 ml bulionu drobiowego lub rosołu
* oliwa, masło
* 350 ml przecieru pomidorowego, passaty z butelki lub kartonu

|
== Przygotowanie
Na patelni na łyżce oliwy zeszklić pokrojoną w kosteczkę cebulę, pod koniec dodać starty 1 ząbek czosnku oraz 1 łyżkę masła, suszone oregano i paprykę w proszku, wymieszać i chwilę razem podsmażyć. Zdjąć z patelni i zmielić razem z mięsem lub drobniej posiekać na desce.

Zmielone mięso wraz z podsmażoną cebulą umieścić w misce. Dodać bułkę tartą lub ugotowaną kaszę, jajko, sos sojowy, doprawić solą oraz pieprzem i dokładnie wyrobić. Wilgotnymi dłońmi uformować nieduże pulpeciki.

Rozgrzać natłuszczoną oliwą patelnię i włożyć pulpeciki. Gdy się zrumienią od spodu przewrócić na drugą stronę i powtórzyć smażenie. Pod koniec na patelnię dodać starty drugi ząbek czosnku i lekko go zrumienić.

Na patelnię z pulpecikami wlać gorący bulion, przykryć pokrywą i gotować przez ok. 5 - 7 minut, w międzyczasie potrząsnąć patelnią w celu przemieszania pulpecików.

Dodać przecier pomidorowy i zagotować. Gotować bez przykrycia przez około 10 minut (jeśli używaliśmy indyka) lub ok. 15 minut (w przypadku innego mięsa). W międzyczasie 1 - 2 razy zamieszać.

Sos spróbować i doprawić w razie potrzeby solą, pieprzem, cukrem i suszonym oregano. Podawać z makaronem i tartym serem.

|===

[.text-center]
== Zdjęcia
