= Kopytka 🌱 +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++
:imagesdir: /Recipes/static/images

[.recipe-hero]
--
[.recipe-category-label]
Dania główne

[.card-image-placeholder]
Brak zdjęcia przepisu 🍲
--

[.recipe-details]
--
[.recipe-details-item]
🕒 czas przygotowania: 30 minut

[.recipe-details-item]
👥 4 porcje

[.recipe-details-item]
🔗 https://www.kwestiasmaku.com/przepis/kopytka[link do źródła przepisu]

--

[.recipe-columns]
--
[.recipe-column-box]
=== Składniki
* 1 kg ziemniaków
* 200 g mąki
* 1 jajko
* 1 łyżeczka soli

|

[.recipe-column-box]
=== Przygotowanie
Ziemniaki obrać i ugotować w osolonej wodzie. Odcedzić i od razu rozgnieść praską na idealnie gładkie puree. Przełożyć do miski i całkowicie ostudzić.

Dodać mąkę, jajko oraz szczyptę soli. Połączyć składniki w jednolite ciasto.

Wyłożyć na stolnicę posypaną mąką i podzielić na 6 części. Z każdej części uformować wałeczek grubości kciuka, obtaczając go w mące.

Wałek lekko spłaszczyć i pociąć nożem na kawałki o szerokości ok. 1,5 - 2 cm.

Gotować partiami: wkładać na gotującą i osoloną wodę w dużym garnku i gotować przez ok. 3 minuty licząc od czasu wypłynięcia na powierzchnię lub do miękkości.

W trakcie gotowania delikatnie przemieszać wodę drewnianą łyżką sprawdzając czy kopytka nie przykleiły się do dna. Wyławiać łyżką cedzakową i wykładać na talerze.
--
