= Krokiety z kapust i grzybami  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 1 h
* 4 porcje
* https://www.kwestiasmaku.com/przepis/krokiety-z-kapusta-i-grzybami[link do 藕r贸da przepisu]

== Skadniki

* 40 g suszonych grzyb贸w
* 500 g kapusty kiszonej
* 1 maa marchewka
* 1 du偶a cebula
* 4 y偶ki oleju rolinnego
* 400 g pieczarek
* s贸l, zmielony pieprz, 1 listek laurowy, 2 ziela angielskie
* 1 szklanka mki pszennej
* 2 jajka
* 1 szklanka mleka
* 3/4 szklanki wody (najlepiej gazowanej)
* szczypta soli
* 3 y偶ki masa lub oleju rolinnego
* 2 jajka
* s贸l
* buka tarta
* maso klarowane do sma偶enia
* barszcz wigilijny lub barszcz czerwony

|
== Przygotowanie

Grzyby wypuka w chodnej wodzie, wo偶y do rondelka, zala 2 szklankami wody i odstawi do namoczenia na ca noc lub na kilka godzin.

Wyla wod z moczenia grzyb贸w, wla wie偶 w iloci 1 szklanki, posoli i gotowa przez ok. 20 minut. Odcedzi zachowujc oddzielnie wywar i grzyby. Grzyby drobno posieka na desce.

Kapust odcisn z soku i posieka, wo偶y do garnka i zala przecedzonym wywarem z grzyb贸w. Wla dodatkowa 1 szklank wody lub bulionu, doda listek laurowy i ziela angielskie i gotowa pod przykryciem, a偶 do mikkoci przez ok. 40 minut.

Marchewk obra, umy i zetrze na tarce o du偶ych oczkach. Doda do gotujcej si kapusty na 10 minut przed kocem jej gotowania.

Obra i posieka cebul w drobn kosteczk. Zeszkli na patelni na 2 y偶kach oleju.

Cebul i grzyby doda do ugotowanej kapusty.

Pieczarki umy, pokroi na plasterki i odparowa na patelni co chwil mieszajc. Doda 2 y偶ki oleju i sma偶y przez kilka minut w midzyczasie doprawi sol i pieprzem. Zdj z patelni i posieka, doda do kapusty.

Kapust doprawi sol, pieprzem i ewentualnie szczypt cukru. Zagotowa.

Mk wsypa do miski, doda jajka, mleko, wod i s贸l. Zmiksowa na gadkie ciasto. Doda roztopione maso lub olej rolinny i razem zmiksowa (lub wykorzysta tuszcz do smarowania patelni przed sma偶eniem ka偶dego nalenika).

Naleniki sma偶y na dobrze rozgrzanej patelni z cienkim dnem np. nalenikowej. Przewr贸ci na drug stron gdy sp贸d nalenika bdzie ju偶 adnie zrumieniony i city.

Nadzienie dzielimy na 10 czci i smarujemy nim 10 nalenik贸w. Zwijamy: najpierw zakadamy do rodka dwa przeciwlege boki nalenika na okoo 2 cm, nastpnie zwijamy lub skadamy caego nalenika. Tak przygotowane krokiety mo偶emy przechowywa w lod贸wce przez 2-3 dni, wyjmowa i sma偶y w panierce jednorazowo tyle ile akurat nam potrzeba.

Jajka roztrzepa widelcem w gbokim talerzu z dodatkiem soli. Do drugiego talerza nasypa buki tartej. Macza krokiety w jajku a nastpnie obtacza w buce tartej. Sma偶y na rozgrzanym male klarowanym  po okoo 2 minuty z ka偶dej strony, w razie potrzeby dodawa wicej masa w trakcie sma偶enia.

|===

[.text-center]
== Zdjcia
