= Krokiety z pieczarkami

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* https://www.doradcasmaku.pl/przepis-krokiety-z-pieczarkami-i-kielbaska-pieczone-w-piekarniku--364765[link do źródła przepisu]

== Składniki

Naleśniki
* jajko 2 sztuki
* mąka pszenna 250 gram
* mleko 1 szklanka
* sól szczypta
* woda gazowana do odpowiedniej konsystencji ciasta
* olej 1 łyżka

Farsz
* cebula 1 duża
* kiełbasa dowolna 100 gram
* pieczarki 0,5 kg
* sól do smaku
* Pieprz czarny mielony Prymat do smaku ale sporo

Panierka
* jajko 1 sztuka
* mleko 5 łyżek
* Bułka tarta klasyczna Prymat 5 łyżek

|
== Przygotowanie

Posiekaną cebulę i kiełbaskę podsmażyć na łyżce oleju aż cebulka lekko zmięknie.

Obrane pieczarki pokroić niezbyt drobno.dodawać partiami na patelnię z cebulką.

Pieczarki podsmażać aż wyparuje z nich cała woda. doprawić solą i świeżo mielonym czarnym pieprzem. wystudzić całość.

Składniki na ciasto zmiksować.najlepiej najpierw bez wody,następnie dodając stopniowo wodę (ciasto ma być nie za gęste aby wyszły cieniutkie naleśniki).

Smażyć cieniutkie naleśniki na nieprzywierającej patelni (nie ma potrzeby dodawania tłuszczu na patelnię).

Na naleśniku rozłożyć łyżkę farszu i zwijać,dól,boki i w górę.

Naleśniki są bardzo elastyczne nie pękają podczas zwijania. W takim stanie można je zamrozić a panierować i piec dopiero przed podaniem.

Jajko roztrzepać z dodatkiem mleka.Krokiety obtoczyć w jajku i następnie w bułce tartej.

Układać na blachę wyłożoną papierem do pieczenia.piec 45 minut w 170 stopniach (w trakcie pieczenia obrócić je na drugą stronę aby były chrupiące).

== Zdjęcia
|===
