= Kurczak w sosie mietanowym  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 1 godzina 20 minut
* 1500 g dania
* https://aniagotuje.pl/przepis/kurczak-w-sosie-smietanowym[link do 藕r贸da przepisu]

== Skadniki

* 800 g piersi z kurczaka - 1 bardzo du偶a lub 2 mae
* 20 g mki pszennej - 1 pena y偶ka
* 20 g tartego parmezanu
* 2 y偶ki masa klarowanego - do 40 g
* przyprawy: paska y偶eczka soli, p贸 paskiej y偶eczki pieprzu
* 150 ml mietanki krem贸wki 30 %
* 200 ml wody lub lekkiego bulionu
* 1 wiksza cebula - do 200 g
* 6 zbk贸w czosnku - okoo 30 g
* 30 g tartego parmezanu
* 2 y偶ki masa klarowanego - do 40 g
* natka pietruszki lub oregano - kilka listk贸w
* do oproszenia sosu: wie偶o mielony pieprz, tarty parmezan

|
== Przygotowanie

Du偶 pier z kurczaka oczy z ewentualnych chrzstek oraz 偶yek, a nastpnie pokr贸j na mniejsze kawaki o podobnej gruboci. Miso pokryj przyprawami - paska y偶eczki soli i p贸 paskiej y偶eczki pieprzu.

Do miski wsyp y偶k mki pszennej oraz zetrzyj okoo 20 gram贸w parmezanu. Ka偶dy kawaek obtocz z obu stron w mieszce mki i sera.

Nagrzej du偶 patelni z grubym dnem. Dodaj dwie y偶ki masa klarowanego lub troch wicej oliwy. Kawaki kurczaka podsma偶aj po okoo dwie minuty z ka偶dej strony na rumiano. Z patelni zdejmij miso (na chwil, na osobny talerz). Zostaw za nagrzan patelni.

Na patelni wy贸偶 kolejne dwie y偶ki tuszczu oraz obran i posiekan drobno cebul. Podsma偶aj j na redniej mocy palnika przez okoo 5 minut, aby si zeszklia. Mo偶e si lekko zarumieni. Pod koniec dodaj r贸wnie偶 obrane i pokrojone w kawaki zbki czosnku. Wymieszaj cebul z czosnkiem i podsma偶aj minut.

Kolejno wlej r贸wnie偶 150 ml mietanki krem贸wki 30 % oraz 200 ml gorcej wody. Mieszaj sos na najni偶szej mocy palnika przez okoo dwie minuty.

Po tym czasie dodaj 30-50 gram贸w startego na maych oczkach parmezanu. Wymieszaj dokadnie wszystkie skadniki. W sosie umie podsma偶one wczeniej kawaki kurczaka. Cao opr贸sz wie偶o mielonym pieprzem i siekanym oregano lub natk pietruszki. Patelni przykryj przykrywk. Zredukuj moc palnika do niskiej i du cao nie du偶ej ni偶 dwie minuty. Jeli sos wyszed zbyt gsty, zawsze mo偶na do niego wla wicej wody lub mietanki.

|===

[.text-center]
== Zdjcia
