= Kurczak z porami, puree ziemniaczane

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 35 min
* 4 porcje
* https://www.kwestiasmaku.com/zielony_srodek/pory/kurczak_z_porami_ziemniakami/przepis.html[link do źródła przepisu]

== Składniki
* 1 duży por
* 30 g masła + 2 łyżki do podsmażenia kurczaka
* 1 łyżeczka suszonego tymianku
* 400 g piersi kurczaka
* 1 łyżka mąki
* 1/4 szklanki śmietanki kremowej 30%
* cytryna do skropienia
* sól i świeżo zmielony czarny pieprz
* 500 g ziemniaków
* 2 łyżki masła
* 1 łyżka śmietanki kremówki

|
== Przygotowanie
Odciąć zielone części porów, pozostawić białą i jasno zieloną część. Przekroić wzdłuż na 4 części i dokładnie opłukać. Pokroić w poprzek na pół centymetrowe kawałki.

Roztopić masło na większej patelni lub w garnku, dodać pory, posolić, dodać połowę tymianku i smażyć na umiarkowanym ogniu przez 5 minut od czasu do czasu mieszając. Przykryć i dusić przez kolejne 10 minut lub do czasu aż pory całkowicie zmiękną (będą szkliste), w międzyczasie 1 - 2 razy przemieszać.

W międzyczasie przygotować kurczaka: piersi położyć na desce, przeciąć wzdłuż na dwa cieńsze filety, dodatkowo rozbić jeszcze najgrubsze części tłuczkiem. Posolić, doprawić pieprzem, posypać połową tymianku i obtoczyć w mące. Roztopić 2 łyżki masła na drugiej patelni i włożyć filety, obsmażyć z każdej strony po około minucie.

Do miękkich porów wlać śmietankę i zagotować na małym ogniu. Filety zdjąć z patelni i włożyć do sosu z porów, przykryć i dusić przez około 1 - 2 minuty aż mięso nie będzie już surowe. Skropić sokiem z cytryny i posypać świeżo zmielonym czarnym pieprzem. Podawać z puree ziemniaczanym.

Ugotowane w osolonej wodzie ziemniaki odcedzić, włożyć z powrotem do garnka, dodać masło i śmietankę i od razu rozgnieść praską na puree.

== Zdjęcia
|===
