= Kurczak z porami  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 35 minut
* 4 porcje
* https://www.kwestiasmaku.com/zielony_srodek/pory/kurczak_z_porami_ziemniakami/przepis.html[link do 藕r贸da przepisu]

== Skadniki

* 1 du偶y por
* 30 g masa + 2 y偶ki do podsma偶enia kurczaka
* 1 y偶eczka suszonego tymianku
* 400 g piersi kurczaka
* 1 y偶ka mki
* 1/4 szklanki mietanki kremowej 30%
* cytryna do skropienia
* s贸l i wie偶o zmielony czarny pieprz
* 500 g ziemniak贸w
* 2 y偶ki masa
* 1 y偶ka mietanki krem贸wki

|
== Przygotowanie

Odci zielone czci por贸w, pozostawi bia i jasno zielon cz. Przekroi wzdu偶 na 4 czci i dokadnie opuka. Pokroi w poprzek na p贸 centymetrowe kawaki.

Roztopi maso na wikszej patelni lub w garnku, doda pory, posoli, doda poow tymianku i sma偶y na umiarkowanym ogniu przez 5 minut od czasu do czasu mieszajc. Przykry i dusi przez kolejne 10 minut lub do czasu a偶 pory cakowicie zmikn (bd szkliste), w midzyczasie 1 - 2 razy przemiesza.

W midzyczasie przygotowa kurczaka: piersi poo偶y na desce, przeci wzdu偶 na dwa ciesze filety, dodatkowo rozbi jeszcze najgrubsze czci tuczkiem. Posoli, doprawi pieprzem, posypa poow tymianku i obtoczy w mce. Roztopi 2 y偶ki masa na drugiej patelni i wo偶y filety, obsma偶y z ka偶dej strony po okoo minucie.

Do mikkich por贸w wla mietank i zagotowa na maym ogniu. Filety zdj z patelni i wo偶y do sosu z por贸w, przykry i dusi przez okoo 1 - 2 minuty a偶 miso nie bdzie ju偶 surowe. Skropi sokiem z cytryny i posypa wie偶o zmielonym czarnym pieprzem. Podawa z puree ziemniaczanym.

Ugotowane w osolonej wodzie ziemniaki odcedzi, wo偶y z powrotem do garnka, doda maso i mietank i od razu rozgnie prask na puree.

|===

[.text-center]
== Zdjcia
