= Kurczak w sosie śmietanowym +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły

* czas przygotowania: 1 godzina 20 minut
* 1500 g dania
* https://aniagotuje.pl/przepis/kurczak-w-sosie-smietanowym[link do źródła przepisu]

== Składniki

* 800 g piersi z kurczaka - 1 bardzo duża lub 2 małe
* 20 g mąki pszennej - 1 pełna łyżka
* 20 g tartego parmezanu
* 2 łyżki masła klarowanego - do 40 g
* przyprawy: płaska łyżeczka soli, pół płaskiej łyżeczki pieprzu
* 150 ml śmietanki kremówki 30 %
* 200 ml wody lub lekkiego bulionu
* 1 większa cebula - do 200 g
* 6 ząbków czosnku - około 30 g
* 30 g tartego parmezanu
* 2 łyżki masła klarowanego - do 40 g
* natka pietruszki lub oregano - kilka listków
* do oproszenia sosu: świeżo mielony pieprz, tarty parmezan

|
== Przygotowanie

Dużą pierś z kurczaka oczyść z ewentualnych chrząstek oraz żyłek, a następnie pokrój na mniejsze kawałki o podobnej grubości. Mięso pokryj przyprawami - płaska łyżeczki soli i pół płaskiej łyżeczki pieprzu.

Do miski wsyp łyżkę mąki pszennej oraz zetrzyj około 20 gramów parmezanu. Każdy kawałek obtocz z obu stron w mieszące mąki i sera.

Nagrzej dużą patelnię z grubym dnem. Dodaj dwie łyżki masła klarowanego lub trochę więcej oliwy. Kawałki kurczaka podsmażaj po około dwie minuty z każdej strony na rumiano. Z patelni zdejmij mięso (na chwilę, na osobny talerz). Zostaw zaś nagrzaną patelnię.

Na patelnię wyłóż kolejne dwie łyżki tłuszczu oraz obraną i posiekaną drobno cebulę. Podsmażaj ją na średniej mocy palnika przez około 5 minut, aby się zeszkliła. Może się lekko zarumienić. Pod koniec dodaj również obrane i pokrojone w kawałki ząbki czosnku. Wymieszaj cebulę z czosnkiem i podsmażaj minutę.

Kolejno wlej również 150 ml śmietanki kremówki 30 % oraz 200 ml gorącej wody. Mieszaj sos na najniższej mocy palnika przez około dwie minuty.

Po tym czasie dodaj 30-50 gramów startego na małych oczkach parmezanu. Wymieszaj dokładnie wszystkie składniki. W sosie umieść podsmażone wcześniej kawałki kurczaka. Całość oprósz świeżo mielonym pieprzem i siekanym oregano lub natką pietruszki. Patelnię przykryj przykrywką. Zredukuj moc palnika do niskiej i duś całość nie dłużej niż dwie minuty. Jeśli sos wyszedł zbyt gęsty, zawsze można do niego wlać więcej wody lub śmietanki.

|===

[.text-center]
== Zdjęcia
