= Kurczak hoisin

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 30 min
* 4 porcje
* https://www.kwestiasmaku.com/przepis/kurczak-hoisin[link do źródła przepisu]

== Składniki
* 500 g filetu z kurczaka
* 2 ząbki czosnku
* 1 łyżeczka ostrej papryki
* 1/4 łyżeczki białego pieprzu
* 1 duże jajko
* ok. 6 łyżek skrobi (mąki) ziemniaczanej
* olej roślinny do smażenia
* 2 łyżki sezamu
* do podania np. ryż, brokuł
* 125 ml wody
* 60 ml sosu sojowego
* 30 ml octu ryżowego
* 1 łyżka masła orzechowego
* 1 łyżka oleju sezamowego
* 1 płaska łyżka cukru

|
== Przygotowanie
Mięso oczyścić z błonek i kostek, pokroić w małą kostkę. Doprawić solą, startym czosnkiem, ostrą papryką i białym pieprzem.

Na jednym głębokim talerzu wymieszać skrobię ziemniaczaną. Do drugiego wbić jajko i roztrzepać.

Rozgrzać wok lub głęboką większą patelnię, wlać olej (na głębokość ok. 3 mm).

Kawałki kurczaka najpierw obtoczyć w roztrzepanym jajku, następnie w skrobi ziemniaczanej.

Kłaść partiami na rozgrzany tłuszcz i smażyć przez około 2 minuty, przewrócić na drugą stronę i powtórzyć smażenie. Wyłożyć łyżką cedzakową na ręczniki papierowe. Dodać tłuszcz i usmażyć kolejną partię.

Wytrzeć patelnię ręcznikiem papierowym z resztek oleju ze smażenia, włożyć z powrotem całe mięso.

Podgrzewać przez ok. 1 - 2 minuty, następnie przesunąć mięso na bok a w wolne miejsce wlać sos hoisin (wymieszać wcześniej jego składniki).

Zagotować a następnie połączyć z mięsem i co chwilę mieszając zagotować jeszcze wszystko razem. Podawać posypując lekko zrumienionym sezamem.

== Zdjęcia
|===
