= Kurczak z mozzarellą +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 45 min
* 4 porcje
* https://www.kwestiasmaku.com/przepis/parmigiana-z-kurczaka[link do źródła przepisu]

== Składniki
* 2 filety z kurczaka (ok. 400 g)
* oliwa, masło, jajko, bułka tarta
* 1 puszka krojonych pomidorów
* 2 ząbki czosnku
* szczypta płatków chili, 2 łyżeczki suszonego oregano
* 1 kulka mozzarelli
* 1/2 szklanki tartego parmezanu lub grana padano
* listki tymianku lub bazylii

|
== Przygotowanie
Filety z kurczaka oczyścić z błonek i kostek, odkroić polędwiczkę, przekroić wzdłuż na 2 cieńsze filety, rozbić je w najgrubszej części na kotlety o mniej więcej podobnej grubości. Doprawić je solą, pieprzem i łyżeczką suszonego oregano.

Ugotować sos pomidorowy: w rondelku na łyżce oliwy delikatnie podsmażyć starty czosnek, dodać łyżeczkę suszonego oregano oraz pomidory z puszki. Doprawić solą, pieprzem, szczyptą płatków chili (lub do smaku) oraz w razie potrzeby szczyptą cukru, zagotować. Gotować przez ok. 10 minut pod uchyloną pokrywą.

Piekarnik nagrzać do 190 stopni C. Filety z kurczaka maczać w roztrzepanym jajku, następnie w bułce tartej. Obsmażyć na oliwie i maśle na złoty kolor po ok. 2 - 3 minuty z każdej strony i odłożyć na talerz.

Mozzarellę w kulce zetrzeć na tarce o większych oczkach, natomiast parmezan zetrzeć na tarce o małych oczkach. Obydwa sery wymieszać ze sobą.

Do naczynia żaroodpornego włożyć połowę sosu pomidorowego, ułożyć podsmażone filety, posypać połową mieszanki serów, następnie miejscami wyłożyć resztę sosu i całość zapiekanki posypać resztą serów. Po wierzchu posypać listkami tymianku lub bazylii.

Wstawić do nagrzanego piekarnika i piec przez 15 minut.

|===

[.text-center]
== Zdjęcia
