= Kurczak z mozzarell  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: 45 min
* 4 porcje
* https://www.kwestiasmaku.com/przepis/parmigiana-z-kurczaka[link do 藕r贸da przepisu]

== Skadniki
* 2 filety z kurczaka (ok. 400 g)
* oliwa, maso, jajko, buka tarta
* 1 puszka krojonych pomidor贸w
* 2 zbki czosnku
* szczypta patk贸w chili, 2 y偶eczki suszonego oregano
* 1 kulka mozzarelli
* 1/2 szklanki tartego parmezanu lub grana padano
* listki tymianku lub bazylii

|
== Przygotowanie
Filety z kurczaka oczyci z bonek i kostek, odkroi poldwiczk, przekroi wzdu偶 na 2 ciesze filety, rozbi je w najgrubszej czci na kotlety o mniej wicej podobnej gruboci. Doprawi je sol, pieprzem i y偶eczk suszonego oregano.

Ugotowa sos pomidorowy: w rondelku na y偶ce oliwy delikatnie podsma偶y starty czosnek, doda y偶eczk suszonego oregano oraz pomidory z puszki. Doprawi sol, pieprzem, szczypt patk贸w chili (lub do smaku) oraz w razie potrzeby szczypt cukru, zagotowa. Gotowa przez ok. 10 minut pod uchylon pokryw.

Piekarnik nagrza do 190 stopni C. Filety z kurczaka macza w roztrzepanym jajku, nastpnie w buce tartej. Obsma偶y na oliwie i male na zoty kolor po ok. 2 - 3 minuty z ka偶dej strony i odo偶y na talerz.

Mozzarell w kulce zetrze na tarce o wikszych oczkach, natomiast parmezan zetrze na tarce o maych oczkach. Obydwa sery wymiesza ze sob.

Do naczynia 偶aroodpornego wo偶y poow sosu pomidorowego, uo偶y podsma偶one filety, posypa poow mieszanki ser贸w, nastpnie miejscami wyo偶y reszt sosu i cao zapiekanki posypa reszt ser贸w. Po wierzchu posypa listkami tymianku lub bazylii.

Wstawi do nagrzanego piekarnika i piec przez 15 minut.

|===

[.text-center]
== Zdjcia
