= Leczo +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 45 min
* 4 porcje
* https://www.kwestiasmaku.com/przepis/leczo[link do źródła przepisu]

== Składniki
* 2 łyżki smalcu
* 2 cebule
* 200 g kiełbasy (np. wiejskiej, podsuszanej)
* 2 ząbki czosnku
* 3 papryki (np. żółta, czerwona, zielona)
* 2 łyżeczki słodkiej papryki w proszku
* sól i świeżo zmielony pieprz
* 1/2 łyżeczki ostrej papryki w proszku
* 1 kg pomidorów + 2 łyżki koncentratu pomidorowego (lub 500 ml przecieru pomidorowego - passaty z butelki lub kartonu)

|
== Przygotowanie
Do szerokiego garnka włożyć smalec, dodać pokrojoną w kosteczkę cebulę oraz pokrojoną na plasterki kiełbasę, smażyć co chwilę mieszając przez około 7 minut. Dodać starty na tarce lub rozgnieciony czosnek i smażyć jeszcze przez 3 minuty.

Dodać pokrojone w kostkę papryki i co chwilę mieszając smażyć przez ok. 3 minuty. Doprawić solą (ok. pół łyżeczki), świeżo zmielonym pieprzem oraz słodką i ostrą papryką w proszku.

Następnie dodać obrane i pokrojone w kostkę świeże pomidory (bez nasion ze środka komór) lub passatę pomidorową. Gotować przez około 15 minut pod uchyloną pokrywą, w międzyczasie kilka razy zamieszać. Na koniec dodać koncentrat pomidorowy jeśli używaliśmy świeżych pomidorów.

|===

[.text-center]
== Zdjęcia
