= Leczo  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 45 minut
* 4 porcje
* https://www.kwestiasmaku.com/przepis/leczo[link do 藕r贸da przepisu]

== Skadniki

* 2 y偶ki smalcu
* 2 cebule
* 200 g kiebasy (np. wiejskiej, podsuszanej)
* 2 zbki czosnku
* 3 papryki (np. 偶贸ta, czerwona, zielona)
* 2 y偶eczki sodkiej papryki w proszku
* s贸l i wie偶o zmielony pieprz
* 1/2 y偶eczki ostrej papryki w proszku
* 1 kg pomidor贸w + 2 y偶ki koncentratu pomidorowego (lub 500 ml przecieru pomidorowego - passaty z butelki lub kartonu)

|
== Przygotowanie

Do szerokiego garnka wo偶y smalec, doda pokrojon w kosteczk cebul oraz pokrojon na plasterki kiebas, sma偶y co chwil mieszajc przez okoo 7 minut. Doda starty na tarce lub rozgnieciony czosnek i sma偶y jeszcze przez 3 minuty.

Doda pokrojone w kostk papryki i co chwil mieszajc sma偶y przez ok. 3 minuty. Doprawi sol (ok. p贸 y偶eczki), wie偶o zmielonym pieprzem oraz sodk i ostr papryk w proszku.

Nastpnie doda obrane i pokrojone w kostk wie偶e pomidory (bez nasion ze rodka kom贸r) lub passat pomidorow. Gotowa przez okoo 15 minut pod uchylon pokryw, w midzyczasie kilka razy zamiesza. Na koniec doda koncentrat pomidorowy jeli u偶ywalimy wie偶ych pomidor贸w.

|===

[.text-center]
== Zdjcia
