= Makaronowa sałatka warstwowa

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowaniaL 45 min
* 2 porcje
* https://www.kwestiasmaku.com/przepis/makaronowa-salatka-warstwowa[link do źródła przepisu]

== Składniki
* 100 g makaronu świderki
* 8 kawałków suszonych pomidorów z oleju
* 125 g opakowanie mini mozzarelli
* 1/2 szklanki oliwek (zielonych lub czarnych)
* 200 g pomidorków koktajlowych
* 1 łyżka suszonego oregano
* 4 łyżki oliwy extra vergine
* 1/2 cebuli (białej lub czerwonej)
* listki bazylii z 1 doniczki

|
== Przygotowanie
Makaron ugotować w osolonej wodzie, odcedzić, włożyć na dno szklanej salaterki. Dodać posiekane suszone pomidory, następnie odcedzone kulki mozzarelli i oliwki.

Pomidorki koktajlowe pokroić na połówki, włożyć do miski, dodać suszone oregano, sól i pieprz oraz oliwę, wymieszać i całość wyłożyć na wierzch sałatki.

Cebulę obrać, przekroić na pół a następnie pokroić na cienkie plasterki, wyłożyć na wierzch sałatki, przykryć liśćmi bazylii.

== Zdjęcia
|===
