= Makaron zapiekany z boczkiem i cukinią

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* 4 porcje
* https://www.kwestiasmaku.com/przepis/makaron-zapiekany-z-cukinia-i-boczkiem[link do źródła przepisu]

== Składniki
* 250 g makaronu świderki
* 1 łyżka oliwy
* 200 g boczku wędzonego
* 1 por
* 1 nieduża cukinia
* 2 ząbki czosnku
* 2 łyżki posiekanej natki pietruszki
* 250 ml śmietanki 30% z kartonika
* 3 łyżki tartego sera twardego typu corregio, parmezan, bursztyn


|
== Przygotowanie
Makaron ugotować al dente w osolonej wodzie, odcedzić, włożyć z powrotem do garnka. Piekarnik nagrzać do 190 stopni C (jeśli danie będziemy dodatkowo zapiekać).

Na dużej patelni na oliwie zeszklić pokrojonego pora. Dodać drobno starty czosnek a następnie boczek pokrojony w kostkę.

Smażyć co chwilę mieszając przez ok. 5 minut, następnie dodać pokrojoną w kosteczkę cukinię i smażyć przez kolejne 5 minut.

Dodać posiekaną natkę pietruszki oraz śmietankę. Zagotować, doprawić solą oraz pieprzem. Dodać makaron i wymieszać.

Opcjonalnie danie można dodatkowo zapiec w piekarniku. W tym celu należy je przełożyć do naczynia żaroodpornego lub blaszki. Posypać tartym serem i zapiekać bez przykrycia przez ok. 10 minut.

Jeśli dania nie zapiekamy, możemy posypać je serem już po nałożeniu na talerze.



== Zdjęcia
|===
