= Makaron z brokułami

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* https://aniagotuje.pl/przepis/makaron-z-brokulami[link do źródła przepisu]

== Składniki
* 300 g makaronu np. Rigatoni - waga przed gotowaniem
* trochę ponad pół szklanki wody po gotowanym makaronie - około 130 ml
* 1 średni lub mały brokuł - około 580 g
* 1 spora cebula - do 220 g
* 1 ząbek czosnku - około 5 g
* 6 łyżek śmietanki kremówki 30 %
* 1 łyżka oleju do smażenia
* 1 łyżka masła klarowanego
* 1 łyżeczka skrobi ziemniaczanej lub mąki pszennej
* 40 g sera typu parmezan lub cheddar
* przyprawy: 1/3 łyżeczki soli, po 1/4 płaskiej łyżeczki pieprzu, szczypta gałki muszkatołowej
* ewentualne dodatki: sok z cytryny, ketchup, mleko, więcej tartego sera


|
== Przygotowanie
Makaron z brokułami to bardzo prosty i szybki pomysł na obiad. Jeśli szukasz ciekawego przepisu na pyszne wykorzystanie brokułów, to jestem pewna, że to danie przypadnie Ci do gustu.

- sprawdzony przepis

- fantastyczny obiad dla całej rodziny

- wiele porad oraz zdjęcia krok po kroku

Czas przygotowania: 30 minut

Czas gotowania makaronu: 12 minut

Czas gotowania bokułów: 7 minut

Liczba porcji: około 1330 g dania





Kaloryczność kcal: 150 w 100 g dania

Dieta: wegetariańska

Składniki

Szklanka ma u mnie pojemność 250 ml.

Warzywa ważone były przed ewentualnym obraniem/przygotowaniem.

Kalorie policzone zostały na podstawie użytych przeze mnie składników. Jest to więc orientacyjna liczba kalorii liczona na podstawie produktów, których użyłam w danym przepisie. Z podanej ilości składników otrzymasz około 1330 gramów dania.

Przed szykowaniem przepisu zachęcam też do przeczytania najpierw całego wpisu. W treści podaję bowiem dużo ciekawych porad dotyczących składników oraz ich zamienników. Być może zapragniesz użyć innego sera lub też makaronu lub też użyć makaronu bezglutenowego.

W pierwszej kolejności polecam ugotować brokuły. Mój brokuł ważył około 580 gramów. Odcięłam same różyczki i wyszło mi 410 gramów różyczek. W garnku zagotuj wodę. Dodaj do niej płaską łyżeczkę soli. Na wrzątek "wrzuć" różyczki brokułu i gotuj je bez przykrycia przez około siedem minut. Brokuły powinny być wystarczająco miękkie, ale jędrne jednocześnie. Po siedmiu minutach gotowania wyłów różyczki brokułu i odcedź je na sitku. Po przestudzeniu można je drobniej pokroić i umieścić w misce.

No kto nie lubi dań z makaronem w roli głównej :) Tym razem mamy makaron z brokułami i serem, więc i brokuły są równie ważne. Mój makaron z brokułami i sosem serowym jest prosty, szybki i pyszny. Mąż jakoś strasznie lubi kupować brokuły, gdy jest na zakupach. Kupuje je nawet jak nie ma ich na liście, więc muszę potem wymyślać z nimi różne dania. Być może tak mu się podobają lub kupuje mi tak dużo różnych warzyw, bo są zwyczajnie zdrowe. A im więcej kolorów, tym lepiej. W każdym razie tym razem postanowiłam zrobić makaron z sosem brokułowym. Mam już super przepisy na zupy. Zupa brokułowa jest rewelacyjna i każdy miłośnik brokułów ją już robił. Mój krem z brokuła podbił też niejedno podniebienie. Super pyszna i godna polecenie jest też sałatka z brokuła. Tak więc kolejne danie na liście brokułowych pyszności do zrobienia. Tym razem skupmy się na tym, co mam do pokazania w tym przepisie. A wiadomo, że przepisy na makaron z brokułami są i podobne z jednej strony i różne. Co jest oczywiste, to to, że w składnikach z pewnością będzie makaron i brokuły. Swój makaron z brokulami serwuję raczej z makaronem z pszenicy durum. Lubię takie sprężyste makarony. Wybieram makaron większy, czyli np. rigatoni. Można też sięgnąć po makaron w kształcie muszelek, świderków, czy penne. Nawet makaron spaghetti lub tagliatelle bardzo dobrze się sprawdzi, ponieważ szykujemy makaron z brokułami w sosie śmietanowym. A te makarony kochają sosy. Równie prosto i szybko zrobisz też super makaron z jajkiem i boczkiem lub kiełbasą. Koniecznie zerknij tez do wpisu, w którym znajdziesz moje najlepsze dania jednogarnkowe, idealne na chłodniejsze dni.

Makaron z brokułami będzie równie smaczny z użyciem makaronu gryczanego i makaronu z ciecierzycy lub soczewicy. Próbowałam każdej wersji i wszystkie mi smakują. Uwielbiam makaron z brokułami w sosie serowym i zazwyczaj w jego składzie znajduje się cebula i czosnek. Dla mnie to taka nierozłączna para. Makaron z brokułami i czosnkiem ma tę głębię smaku i zawsze daję chociaż jeden ząbeczek czosnku. Makaron z brokułem zmieniam dość często. Chodzi o to, że czasem coś zmienię. Czasem coś dodam, by zmienić odrobinę smak, lub po prostu dlatego, że ma w lodówce jakiś pasujący składnik. Już nie w wersji wegetariańskiej, ale też pysznie wychodzi makaron z brokułami i kurczakiem lub szynką. Obiadek jest pycha. Czasem dodam trochę fety, czasem dodam więcej sera cheddar lub parmezanu. Jak mam, to wleje do sosu bulion albo samo mleko. Bardzo często na mojej porcji ląduje też spory kleks z ketchupu. Mało jest go w mojej kuchni, ale tutaj tak bardzo mi pasuje do makaronu z brokułami i uwielbiam go sobie dodawać do swojej porcji. Wszystko to opisałam dokładnie w treści przepisu. Zapraszam wiec po przepis na makaron z brokułami i życzę smacznego.



== Zdjęcia
|===
