= Mielone kalafiorowe, ziemniaki, buraczki

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: do 45 minut
* 8 - 10 kotletów
* https://www.jadlonomia.com/przepisy/mielone-kalafiorowe[link do źródła przepisu]

== Składniki
* 2 ½ szklanki startego kalafiora / ½ kalafiora
* 1 duża cebula
* 1 ząbek czosnku
* 1 ½ szklanki ugotowanej kaszy jaglanej / ¾ szklanki suchej kaszy jaglanej
* ½ szklanki ziaren słonecznika, podprażonych na suchej patelni i posiekanych
* ¼ szklanki mąki ziemniaczanej
* ¼ szklanki oleju
* 2 łyżki sosu sojowego
* ½ łyżeczki syropu z agawy
* 1 ½ - 2 łyżeczki pieprzu ziołowy
* sól i czarny pieprz

|
== Przygotowanie
Piekarnik rozgrzać do 180 stopni, blachę do pieczenia wyłożyć papierem. Kalafiora wraz z łodygą zetrzeć na dużych oczkach tarki, cebulę zetrzeć na dużych oczkach tarki, a czosnek na małych oczkach. Wszystko przełożyć do bardzo dużej miski.

Do startych warzyw dodać pozostałe składniki i wszystko przy pomocy rąk porządnie zagnieść w zwartą masę, w razie potrzeby dolać łyżkę oleju więcej. Na koniec doprawić do smaku.

Umyć ręce i czystymi dłońmi formować równe, zwarte kotlety. Gotowe układać na blasze i piec przez 20 - 25 minut na złoty kolor, następnie obrócić i piec kolejne 5 minut. Podawać jak u babci z ziemniaczkami i buraczkami, albo tak jak mieszczuchy w bułce z musztardą i keczupem. Wspaniale smakują następnego dnia na zimno.

Kasza jaglana do kotletów powinna być lekko rozgotowana, wtedy łatwo się lepią.

Tarka to tarka, zostawcie blender w spokoju - to właśnie starte warzywa dodają kotletom kremowości, soczystości oraz intensywnego aromatu.

Dodajcie do masy na samym początku sporą szczyptę soli - uwolni to sok z kalafiora, dzięki czemu kotlety będą się łatwo kleić.

Nie próbujcie pomijać pieprzu ziołowego - to najważniejszy składnik, który dodaje kotletom swojskiego aromatu.

To samo dotyczy syropu z agawy - odrobina słodyczy nadaje odpowiedniej głębi smaku! Możecie zastąpić go innym słodem, ale nie próbujcie pomijać tego dodatku.

Umycie rąk po wyrobieniu masy jest bardzo ważne - dzięki temu kotlety łatwo się formują, są równe i chrupiące.

Gotowe uformowane kotlety można mrozić, upieczone można przechowywać do tygodnia w lodówce, świetnie smakują na zimno.

|===

[.text-center]
== Zdjęcia
