= Mielone kalafiorowe  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: do 45 minut
* 8 - 10 kotlet贸w
* https://www.jadlonomia.com/przepisy/mielone-kalafiorowe[link do 藕r贸da przepisu]

== Skadniki
* 2 陆 szklanki startego kalafiora / 陆 kalafiora
* 1 du偶a cebula
* 1 zbek czosnku
* 1 陆 szklanki ugotowanej kaszy jaglanej / 戮 szklanki suchej kaszy jaglanej
* 陆 szklanki ziaren sonecznika, podpra偶onych na suchej patelni i posiekanych
* 录 szklanki mki ziemniaczanej
* 录 szklanki oleju
* 2 y偶ki sosu sojowego
* 陆 y偶eczki syropu z agawy
* 1 陆 - 2 y偶eczki pieprzu zioowy
* s贸l i czarny pieprz

|
== Przygotowanie
Piekarnik rozgrza do 180 stopni, blach do pieczenia wyo偶y papierem. Kalafiora wraz z odyg zetrze na du偶ych oczkach tarki, cebul zetrze na du偶ych oczkach tarki, a czosnek na maych oczkach. Wszystko przeo偶y do bardzo du偶ej miski.

Do startych warzyw doda pozostae skadniki i wszystko przy pomocy rk porzdnie zagnie w zwart mas, w razie potrzeby dola y偶k oleju wicej. Na koniec doprawi do smaku.

Umy rce i czystymi domi formowa r贸wne, zwarte kotlety. Gotowe ukada na blasze i piec przez 20 - 25 minut na zoty kolor, nastpnie obr贸ci i piec kolejne 5 minut. Podawa jak u babci z ziemniaczkami i buraczkami, albo tak jak mieszczuchy w buce z musztard i keczupem. Wspaniale smakuj nastpnego dnia na zimno.

Kasza jaglana do kotlet贸w powinna by lekko rozgotowana, wtedy atwo si lepi.

Tarka to tarka, zostawcie blender w spokoju - to wanie starte warzywa dodaj kotletom kremowoci, soczystoci oraz intensywnego aromatu.

Dodajcie do masy na samym pocztku spor szczypt soli - uwolni to sok z kalafiora, dziki czemu kotlety bd si atwo klei.

Nie pr贸bujcie pomija pieprzu zioowego - to najwa偶niejszy skadnik, kt贸ry dodaje kotletom swojskiego aromatu.

To samo dotyczy syropu z agawy - odrobina sodyczy nadaje odpowiedniej gbi smaku! Mo偶ecie zastpi go innym sodem, ale nie pr贸bujcie pomija tego dodatku.

Umycie rk po wyrobieniu masy jest bardzo wa偶ne - dziki temu kotlety atwo si formuj, s r贸wne i chrupice.

Gotowe uformowane kotlety mo偶na mrozi, upieczone mo偶na przechowywa do tygodnia w lod贸wce, wietnie smakuj na zimno.

|===

[.text-center]
== Zdjcia
