= Mix warzyw na halibucie 🐟 +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++
:imagesdir: /Recipes/static/images

[.recipe-hero]
[.card-image-placeholder]
Brak zdjęcia przepisu 🍲

[.back-to-home-wrapper]
link:../../index.html[← Wróć do przepisów, role="back-to-home-btn"]

[.recipe-details]
* 🕒 czas gotowania: 1 godzina
* 👥 4 porcje
* 🔗 Przepis z zeszytu mamy

[.recipe-columns]
== Składniki
=== Surówka:
* por
* marchew
* cukinia
* rzodkiewka
* olej
* orzechy
* kolendra
* zioła prowansalskie
* buraki

== Przygotowanie

Por, marchew, cukinię, rzodkiewkę oraz buraki dokładnie oczyścić, pokroić w cienkie słupki lub zetrzeć na tarce, a następnie wymieszać z olejem, posiekanymi orzechami, świeżą kolendrą oraz ziołami prowansalskimi, tworząc chrupiącą surówkę. Pomidory sparzyć wrzątkiem, obrać ze skórki, pokroić w kostkę i doprawić solą, pieprzem oraz sokiem z cytryny. Filety z halibuta oprószyć solą, pieprzem i ziołami prowansalskimi, po czym usmażyć na patelni na rozgrzanej oliwie z oliwek, aż mięso stanie się rumiane i upieczone w środku. Usmażoną rybę ułożyć na talerzach, pokryć przygotowanymi pomidorami, a obok podać bogaty mix warzyw z surówki.

[.recipe-gallery]
== Zdjęcia

[.gallery-grid]
// Tutaj pojawią się zdjęcia
