= Naleśniki z kurczakiem

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 30 minut
* czas smażenia naleśników: 20 minut
* 11 sporych naleśników
* https://aniagotuje.pl/przepis/nalesniki-z-kurczakiem[link do źródła przepisu]

== Składniki
* 1 pełna szklanka i 2 łyżki mąki pszennej
* 3 średnie jajka
* 1 szklanka mleka
* 1 szklanka wody
* 4 łyżki oleju roślinnego
* szczypta soli
* 600 g piersi z kurczaka
* 200 g żółtego sera
* 1 średnia papryka - 250 g
* 1 średnia cebula - 150 g
* 2 większe ząbki czosnku
* 2 łyżki oleju roślinnego
* 2 łyżeczki mieszanki przypraw np. gyros

|
== Przygotowanie
W pierwszej kolejności polecam przygotować sobie farsz do naleśników z kurczakiem. Jedną większą pierś z kurczaka umyj pod zimną bieżącą wodą i osusz ręcznikiem papierowym. Pierś oczyść z żyłek i ewentualnych chrząstek i pokrój w kawałki nie większe niż 1-1,5 cm.

Do miski z kawałkami kurczaka wsyp dwie łyżeczki ulubionej mieszanki przypraw np. gyros i wymieszaj całość dokładnie. Możesz też skomponować własną mieszankę (sól, pieprz, słodka papryka, oregano, tymianek...).

Nagrzej dobrze średniej wielkości patelnię i dodaj cztery łyżki ulubionego oleju roślinnego do smażenia. Kawałki piersi z kurczaka umieść na patelni. 

Kawałki kurczaka podsmażaj na średniej mocy palnika nie dłużej niż 10 minut (bez przykrywki). Kilka razy przemieszaj mięso na patelni przy pomocy drewnianej łyżki. W tym czasie mięso powinno być już gotowe. Używając szczypiec przełóż kawałki usmażonego kurczaka do osobnej miseczki. Na patelni zostaw tłuszcz oraz sos. 

Umyj warzywa. Cebulę i czosnek obierz a paprykę (u mnie pół żółtej i pół czerwonej) oczyść dokładnie z gniazda nasiennego. 

Warzywa pokrój bardzo drobno.

Posiekaną cebulę, paprykę oraz czosnek umieść na tej samej patelni, na której smażony był wcześniej kurczak. Na patelni został olej oraz sos, więc nie ma potrzeby dokładania więcej tłuszczu. Podsmażaj tak warzywa przez 10 minut (bez przykrywki). Mieszaj je co jakiś czas przy pomocy drewnianej łyżki. 
 
W jednym naczyniu umieść razem przestudzone kawałki usmażonego kurczaka, podsmażone warzywa oraz starty na tarce (grube oczka) ulubiony ser żółty. 

Możesz sprawdzić smak farszu i w razie potrzeby dodać więcej soli lub też pieprzu, czy słodkiej papryki. Wszystko zależy od upodobań smakowych. 

Przyszła pora na usmażenie naleśników. Skorzystałam z mojego uniwersalnego przepisu na naleśniki. Zadecydowałam się jednak na trochę grubsze naleśniki, więc usmażyłam 11 placków zamiast 16, jakie da radę zrobić z tej ilości składników. 

Wszystkie składniki na ciasto naleśnikowe umieść w misce. Kolejność nie ma znaczenia. Miksuj ciasto przez kilka minut na gładką masę, by pozbyć się ewentualnych grudek. Gorąco polecam blender ręczny typu żyrafa, który sprawi, że ciasto będzie idealnie gładkie. 
Dobrze nagrzej płaską patelnię. Nie ustawiaj od razu najwyższej mocy palnika. Ustaw średnią moc i poczekaj, aż ciepło rozprowadzi się równo po całej powierzchni użytkowej patelni. 

Zamieszaj ciasto i małą chochlą odmierz porcję na naleśnika. Przy każdym nalewaniu porcji na naleśnika podnoszę patelnię nad palnik. Od razu poruszam patelnią tak, by ciasto rozeszło się po całej powierzchni. 

Po około 40-50 sekundach przewracaj placek na drugą stronę. Druga strona potrzebuje zazwyczaj o połowę mniej czasu. Tutaj może Ci się przydać płaska łopatka do przewracania naleśników. W ten sposób usmaż wszystkie naleśniki. Wyszło mi 11 sztuk.

Jeśli naleśnik po zdjęciu na talerz nie będzie elastyczny, to nic się nie martw. Smażąc naleśniki kładź jeden placek na drugim. Po usmażeniu wszystkich naleśników przykryj je folią lub talerzem. W ciągu kilku minut naleśniki zmiękną i zrobią się idealnie elastyczne.

Możesz już składać naleśniki z kurczakiem. Na każdy placek naleśnikowy nakładaj porcję farszu. Dodatkowo możesz też dołożyć do środka każdego naleśnika odrobinę siekanej natki pietruszki. 

Naleśniki możesz tylko złożyć na zakładkę, w rulonik, w kopertę lub tak jak ja, w formie krokieta. Złóż boki a następnie roluj naleśnik zaczynając od dłuższej strony. 

W ten sposób przygotuj sobie wszystkie naleśniki z kurczakiem. 

Naleśniki z kurczakiem zalecam przed podaniem zapiec w piekarniku lub też podsmażyć na patelni. Ja swoje naleśniki podsmażyłam na patelni z dodatkiem odrobiny masła. Podałam je ze świeżym, siekanym pomidorem i ziołami.

Naleśniki podsmażone na patelni lub zapieczone w papierniku będą nie tylko bardziej chrupiące. Ser żółty, który znajduje się w farszu będzie się ciągnął podczas jedzenia a cały farsz będzie lepiej związany.

== Zdjęcia
|===
