= Pad gra prow z wołowiną

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 45 min
* 4 porcje
* https://madameedith.com/przepis/wolowina-z-tajska-bazylia-pad-gra-prow[link do źródła przepisu]

== Składniki
* 250 g ryżu jaśminowego
* 4 łyżki oleju (użyłam rzepakowego)
* 400 g polędwicy wołowej
* 3 łyżeczki skrobi kukurydzianej
* 4 ząbki czosnku
* 1 czerwona papryka
* 1 cebula
* 1 łyżka jasnego sosu sojowego
* 1 łyżka ciemnego sosu sojowego
* 1 łyżka sosu rybnego
* 1 łyżka sosu ostrygowego
* pęczek tajskiej bazylii + 1 łyżeczka suszonej bazylii Holy (najlepiej pęczek świeżej bazylii Holy, ale trudno ją dostać poza wyspecjalizowanymi sklepami)
* pęczek kolendry

|
== Przygotowanie
Ryż gotujemy w podwójnej objętości osolonej wody.

Wołowinę drobno siekamy na cienkie i drobne paseczki - "wiórki". Mieszamy ze skrobią, która potem nieco zagęści nam sos.

Podsmażamy ją szybko na rozgrzanym oleju w woku. Przekładamy na osobny talerz.

Do woka dodajemy ponownie trochę oleju, rozgrzewamy go i wrzucamy na niego ząbki czosnku oraz posiekaną w zapałkę paprykę. Smażymy pół minuty, po czym dorzucamy drobno posiekaną cebulę. Smażymy 1-2 minuty.

Dodajemy wołowinę oraz wszystkie sosy. Mieszamy.

Wołowinę podajemy z ryżem jaśminowym. Warto posypać ją dodatkową porcją kolendry i tajskiej bazylii.

Wrzucamy suszoną bazylię Holy oraz świeże listki bazylii tajskiej. Mieszamy i zdejmujemy z ognia.

== Zdjęcia
|===
