= Pad gra prow z woowin ォ +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: 45 min
* 4 porcje
* https://madameedith.com/przepis/wolowina-z-tajska-bazylia-pad-gra-prow[link do 藕r贸da przepisu]

== Skadniki
* 250 g ry偶u jaminowego
* 4 y偶ki oleju (u偶yam rzepakowego)
* 400 g poldwicy woowej
* 3 y偶eczki skrobi kukurydzianej
* 4 zbki czosnku
* 1 czerwona papryka
* 1 cebula
* 1 y偶ka jasnego sosu sojowego
* 1 y偶ka ciemnego sosu sojowego
* 1 y偶ka sosu rybnego
* 1 y偶ka sosu ostrygowego
* pczek tajskiej bazylii + 1 y偶eczka suszonej bazylii Holy (najlepiej pczek wie偶ej bazylii Holy, ale trudno j dosta poza wyspecjalizowanymi sklepami)
* pczek kolendry

|
== Przygotowanie
Ry偶 gotujemy w podw贸jnej objtoci osolonej wody.

Woowin drobno siekamy na cienkie i drobne paseczki - "wi贸rki". Mieszamy ze skrobi, kt贸ra potem nieco zagci nam sos.

Podsma偶amy j szybko na rozgrzanym oleju w woku. Przekadamy na osobny talerz.

Do woka dodajemy ponownie troch oleju, rozgrzewamy go i wrzucamy na niego zbki czosnku oraz posiekan w zapak papryk. Sma偶ymy p贸 minuty, po czym dorzucamy drobno posiekan cebul. Sma偶ymy 1-2 minuty.

Dodajemy woowin oraz wszystkie sosy. Mieszamy.

Woowin podajemy z ry偶em jaminowym. Warto posypa j dodatkow porcj kolendry i tajskiej bazylii.

Wrzucamy suszon bazyli Holy oraz wie偶e listki bazylii tajskiej. Mieszamy i zdejmujemy z ognia.

|===

[.text-center]
== Zdjcia
