= Paella z kurczakiem

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* https://www.uwielbiamgotowac.com/2017/01/paella-z-kurczakiem.html[link do źródła przepisu]

== Składniki
* 300 g ryżu (do paelli lub risotto, arborio)
* 1 niewielka cebula
* 2 łyżki oleju
* 1 litr rosołu lub bulionu
* 40 - 50 dag piersi z kurczaka
* 1 duża czerwona papryka
* 1/2 puszki kukurydzy (lub mała puszka kukurydzy)
* 2 łyżeczki koncentratu pomidorowego
* 1 łyżeczka słodkiej papryki
* 1/2 łyżeczki kurkumy
* ew. szczypta szafranu
* sól
* pieprz
* natka pietruszki

|
== Przygotowanie
Cebulę obieram, kroję w małą kostkę i podsmażam na łyżce oleju na głębokiej, dużej patelni do zeszklenia. Paprykę myję, przekrawam, usuwam gniazda nasienne i kroję w dużą kostkę. Umytą i osuszoną pierś kurczaka kroję również w większą kostkę.

Do zeszklonej cebuli wsypuję ryż, smażę przez 1 - 2 minuty. Następnie zalewam gorącym bulionem, dodaję pokrojoną paprykę i ew. szafran, zmniejszam ogień do minimum, przykrywam pokrywką i duszę przez 12 minuty. W tym czasie nie zaglądam do ryżu i nie mieszam go.

Na drugiej patelni na łyżce oleju obsmażam kurczaka oprószonego solą, pieprzem, słodką papryką i kurkumą.

Zrumienione mięso dodaję do ugotowanego ryżu (po tych 12 minutach duszenia). Dodaję koncentrat pomidorowy i osączoną z zalewy kukurydzę. Doprawiam do smaku. Dokładnie mieszam.

Potrawę podaję w naczyniu, w których została przygotowana. Przed podaniem posypuję posiekaną natką pietruszki.

== Zdjęcia
|===
