= Paella

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* https://aniagotuje.pl/przepis/paella[link do źródła przepisu]

== Składniki
* 400 g ryżu do Paelli lub ryżu do Risotto - ponad 1,5 szklanki (waga przed ugotowaniem)
* 750 ml bulionu/rosołu drobiowego - 3 szklanki
* 1 filet piersi z kurczaka - około 230 g
* owoce morza: 425 g mieszanki owoców morza - u mnie mrożona; do 400 g krewetek; 110 g kalmarów; 200 g muli
* 120 g mrożonego groszku - około 3/4 szklanki
* 1 średniej wielkości cebula - około 200 g
* 1 średnia papryka np. czerwona - około 230 g
* 300 g mięsistych pomidorów - około 2 sztuki
* 4 ząbki czosnku - około 20 g
* 70 g dobrej jakości oliwy - niecała 1/4 szklanki
* 120 ml białego, wytrawnego wina - niecałe pół szklanki
* zioła i przyprawy: garść natki pietruszki: 1 listek laurowy; po łyżeczce soli i słodkiej papryki; pół łyżeczki pieprzu; 0,12 g szafranu
* do podania: cytryna


|
== Przygotowanie
Paella to przepyszne i bardzo popularne danie kuchni hiszpańskiej. Polecam mój ulubiony przepis na Paellę z dużą ilością owoców morza, z kawałkami kruczaka i mrożonym groszkiem.

- super dokładny przepis

- świetny pomysł na ciekawy posiłek dla gości

- wiele porad i propozycji na zamienniki produktów

Czas przygotowania: 2 godziny

Liczba porcji: 2700 g dania





Kaloryczność kcal: 175 w 100 g dania

Dieta: bezglutenowa

Składniki

Szklanka ma u mnie pojemność 250 ml.

Ryż ważony był przed ugotowaniem. 400 gramów ryżu to waga ryżu suchego.

Warzywa ważone były przed ewentualnym obraniem/przygotowaniem. Zawsze podaję wagę użytych przeze mnie warzyw. Nie trzeba jednak stosować się do wytycznych idealnie co do grama. Wagi podaję po to, by łatwiej było zorientować się, jaka mniej więcej ilość potrzebna jest do zrobienia danego dania.

Kalorie policzone zostały na podstawie użytych przeze mnie składników. Jest to więc orientacyjna ilość kalorii liczona na podstawie produktów, których użyłam w danym przepisie.  Z podanej ilości składników wychodzi około 2700 gramów Paelli. Zanim zaczniesz szykować to danie, polecam najpierw przeczytać cały przepis, by przygotować się odpowiednio wcześniej do kolejnych etapów wykonania.

Ryż do Paelli: Najlepsze będą odmiany o krótkich i zaokrąglonych ziarnach, czyli Bomba i Senia. Sprawdzą się też odmiany typowe do Risotto, czyli Arborio lub Carnaroli. Nie zalecam sięgać po "zwykły" ryż o długich ziarnach. Taki ryż rozpadnie się w trakcie szykowania Paelli, a do tego nie wchłonie wywaru i nie będzie miał bogatego smaku.

Na początek warto przygotować owoce morza do przepisu. Większość z nich jest mrożona, zatem zalecam wyjąć je wcześniej z zamrażalnika i pozostawić w misce, na blacie, aż wszystko naturalnie się rozmrozi. Można ewentualnie przyspieszyć ten proces przenosząc owoce morza do durszlaka i polewając je lekko ciepłą wodą.

Przygotowałam zatem jedną (mrożoną) mieszankę drobniejszych owoców morza o wadze łącznej 425 gramów. W tej mieszance znajdują się mule bez muszli, kalmary, ośmiornice, oraz krewetki. Dodatkowo rozmroziłam również duże krewetki o wadze około 250 gramów i zakupiłam osobno kilka krewetek świeżych (150 g), których użyłam do dekoracji Paelli. Osobno też rozmroziłam 110 gramów większych kawałków kalmarów. Uwielbiam małże w muszlach, więc dołożyłam też 200 gramów muli, które również trafiły na samą górę dania (tak jak świeże krewetki). Porada: Paella może się składać wyłącznie np. z dwóch paczek mrożonej mieszanki owoców morza lub też z jednej paczki mieszanki i jednej paczki krewetek i też wyjdzie pysznie. Poleca jednak zwrócić uwagę na skład mieszanki. Zalecam unikać mieszanek z dodatkiem paluszków karbowych. Lepiej, gdy miks składa się wyłącznie z owoców morza.

Porada: Wino można w ostateczności zamienić na tyle samo bulionu lub wody, zaś szafran zastąpić szczyptą kurkumy.

Porada: Groszek można pominąć.

Paella to oczywiście jedno z najbardziej znanych dań kuchni hiszpańskiej. Paella pochodzi z Walencji i można ją przygotowywać na wiele sposobów. Najważniejszym składnikiem jest oczywiście ryż oraz szafran. Ryż do Paelli charakteryzuje się tym, że ziarna są krótkie i zaokrąglone. Najlepszy ryz do paella to odmiana to Bomba i Senia. Nadal jednak ciężko jest u nas dostać te odmiany ryżu, a do tego są dość drogie, dlatego też używamy ryżu do Risotto. Tutaj mamy do wyboru bardziej znane odmiany, czyli ryż Arborio oraz Carnaroli. Średnioziarnisty, krótszy i zaokrąglony ryż jest idealny do takich dań jak Paellas, ponieważ wchłania dużo sosu i aromatu. Podczas dłuższego gotowania nie rozpada się tak jak ryż długo ziarnisty, który nie wchłania bulionu. Dobra paella hiszpańska powinna zatem być szykowana z odpowiedniego ryżu. Wiadomo, że najlepiej byłoby, gdyby Paella przepis oryginalny szykowana była na świeżym powietrzu. Mieszkańcy Walencji uznają wyłącznie wersję, gdzie Paella szykowana jest na płonącym drewnie, a nie na zwykłej kuchence. Dzięki temu hiszpańska paella ma wyczuwalny aromat palonego drewna, a do tego łatwiej jest uzyskać efekt zwany socarrada, czyli chrupiącą skorupkę na wierzchu Paelli. Bardzo smaczny i super pyszny jest też kurczak w cieście francuskim. Sprawdź też przepis na makaron z krewetkami.

Moja ulubiona Paella, to wersja z dużą ilością najróżniejszych owoców morza. Pyszna Paella z owocami morza nazywana jest Paella marinera. Paella valenciana to Paella z groszkiem oraz z delikatnym mięsem z kurczaka i z królika. Moja Paella z kurczakiem i z owocami morza i jeszcze z groszkiem, to taka mieszana wersja, którą szykuję najczęściej. Zawsze do Paelli dodaję krewetki. Paella z krewetkami musi być i koniec. Mogę zrezygnować z kalmarów oraz ośmiornic, ale krewetki oraz mule dodaję zawsze. Na Paella z kurczakiem przepisy są różne i niektórzy szykują Paellę tylko z kurczakiem i owocami morza. Inni dają królika i owce morza lub same krewetki. Paella morze śmiało składać się z mieszanki mrożonych owoców morza i też wyjdzie super pyszna. Zalecam jednak zwrócić uwagę na to, jaki jest skład takiej mieszanki owoców morza. Pyszna Paella owoce morza może składać się z mrożonki w której są paluszki karbowe oraz kawałki ryb, jednak warto poszukać takiej, która składa się wyłącznie z nie za małych krewetek, muli, ośmiornic oraz kalmarów. Paella danie wyjątkowe, pyszne i niesamowicie aromatyczne wychodzi zawsze wtedy, gdy postaramy się użyć jak najlepszej jakości składników i nie pomijać szafranu, czy wina. Dobry przepis na Paella musi zawierać szafran, który sprawia, że ryż zabarwia się na piękny, słoneczny kolor. Sama nazwa Paella wywodzi się z łacińskiego słowa patella. Słowo to oznacza naczynie metalowe, które służyło Rzymianom to składania darów wybranym bogom. Do Paelli ziarna ryżu warto podsmażyć. Bardzo ważne jest to, by nie mieszać Paelli w trakcie szykowania. Chodzi o moment, gdzie dodamy już ryż. Zaleca się też, by po zdjęciu Paelli z palnika/ognia odczekać przynajmniej kilka minut przed samym jej podaniem.

Tak więc Paella musi się składać z odpowiedniego ryżu. Moja ulubiona Paella, to Paella z kurczakiem i owocami morza, do której daję jeszcze warzywa. Nie zawsze, ale Paella dość często zawiera u mnie tez groszek, który dodaję raczej dla urozmaicenia kolorystycznego, niż dla smaku. Sama nie daję do Paelli mięsa z królika, ale śmiało można to zrobić lub zastąpić tym mięsem filety z kurczaka. Moja Paella składa się jeszcze z cebuli, czosnku, papryki i pomidorów. Moja Paella z kurczakiem przepis, który polecam szykować na obiad lub na wczesną kolację. Jeśli mamy taką możliwość, to warto zakupić specjalne naczynie do szykowania i od razu i podawania Paelli. W dużych restauracjach są ogromne patelnio woki do dania Paella. Paella jest wówczas podawana bezpośrednio z naczynia, w którym była szykowana. Paella może zawierać jeszcze fasolę, ale ja jej nie dodaję. Zawsze też Paella szykowana jest na oliwie. To tłuszcz, na którym smaży się przyprawy i ryż. Na Paella przepis używam zawsze wcześniej ugotowanego bulionu drobiowego. Zazwyczaj odlewam go z rosołu. Ponieważ Paella przepisy zawierają owoce morza, to bulion drobiowy można zamienić na rybny, a w ostateczności dać nawet wodę. Wino białe wytrawne lub półwytrawne nie jest konieczne, ale zawsze polecam je dodawać. Bardzo gorąco polecam też przepis na niezawodne Risotto, które można wykorzystać na wiele pysznych sposobów. Super pyszne jest domowe risotto z kurczakiem oraz wersja z grzybami, czy tylko z warzywami. Przy okazji bardzo gorąco polecam tez takie dania jak Pad Thai oraz domowe Burrito z ryżem.



== Zdjęcia
|===
