= Papryka faszerowana

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 1 h
* 4 porcje
* https://www.kwestiasmaku.com/przepis/papryka-faszerowana-mielonym-miesem-i-ryzem[link do źródła przepisu]

== Składniki
* 4 papryki
* 500 g mielonego mięsa
* 2 łyżki oliwy
* 1 cebula
* 2 ząbki czosnku
* 2 łyżki posiekanej natki
* 100 g (1 woreczek) ryżu
* 1 jajko
* 100 g żółtego sera
* 1 pomidor
* sól
* pieprz

|
== Przygotowanie
Ryż ugotować do miękkości w osolonej wodzie, ok. 10 - 15 minut lub zgodnie z instrukcją na opakowaniu.

Na patelni na oliwie zeszklić pokrojoną cebulę, dodać starty czosnek, po chwili włożyć zmielone mięso i dokładnie obsmażyć.

Mięso doprawić solą (ok. 2/3 łyżeczki), pieprzem, dodać przyprawy: czerwoną paprykę.

Dodać odcedzony ryż, wymieszać i podgrzewać przez ok. minutę. Odstawić z ognia. Po lekkim przestudzeniu dodać jajko i wymieszać.

Piekarnik nagrzać do 200 stopni C. Papryki przekroić na połówki (postawić pionowo na desce i przekroić pionowo). Usunąć nasiona. Wnętrze doprawić solą, pieprzem, skropić oliwą i ułożyć w naczyniu żaroodpornym.

Wstawić do piekarnika, do naczynia wlać ok. 1/2 szklanki wody i piec przez 35 minut.

Na każdej papryce położyć plasterek sera lub starty ser i zapiekać jeszcze przez ok. 5 - 10 minut, aż ser będzie roztopiony lub również zrumieniony.

|===

[.text-center]
== Zdjęcia
