= Pasztet z biaej fasoli  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 40 minut + 40 minut pieczenia
* 10 porcji
* https://www.jadlonomia.com/przepisy/idealny-pasztet-z-bialej-fasoli/[link do 藕r贸da przepisu]

== Skadniki
* 2 szklanki drobnej biaej fasoli, namoczonej przez noc w zimnej wodzie
* 2 du偶e cebule, pokrojone w pi贸ra
* 1 jabko, obrane i pokrojone w kostk
* 2 y偶eczki majeranku
* 1 y偶eczka tymianku
* spora szczypta gaki, startej
* 2 zbki czosnku
* y偶eczka musztardy
* 100 ml oleju + sporo do sma偶enia
* 5 czubatych y偶ek zmielonych patk贸w owsianych
* s贸l i pieprz

|
== Przygotowanie

Namoczon fasol odcedzi, opuka i ugotowa w nieosolonej wodzie do mikkoci.
W midzyczasie na patelni na minimalnym ogniu zeszkli cebul oraz jabka, powinny si lekko rozpada.
Ugotowan fasol opuka, przestudzi i poczy z podduszonymi cebulami, jabkami oraz reszt skadnik贸w. Przepuci przez maszynk do mielenia lub zmiksowa rcznym blenderem. Doprawi sol i pieprzem do smaku.
Piekarnik rozgrza do 180 stopni. Keks贸wk wysmarowa olejem, przeo偶y mas fasolow i piec przez okoo 40 minut, w poowie pieczenia mo偶na przykry wierzch pasztetu foli aluminiow - dziki temu nie bdzie zbyt spieczony i nie bdzie si kruszy. Wyjc na blat, zostawi do cakowitego wystudzenia i dopiero wtedy wyj z formy i kroi. Pyszny z dobr musztard, chrzanem, wik albo sosem tatarskim.

|===

[.text-center]
== Zdjcia
