= Pieczony kalafior z ciecierzycą +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 15 minut + 30 minut pieczenia
* 2 porcje
* https://www.jadlonomia.com/przepisy/pieczony-kalafior-z-ciecierzyca[link do źródła przepisu]

== Składniki
* 1/2 kalafiora / 600 g
* 1 puszka ciecierzycy
* 10 - 15 sztuk pomidorów koktajlowych
* Składniki sosu:
* 2 - 3 łyżki oleju
* 1 łyżka sosu sojowego
* 1/2 łyżeczki papryki wędzonej
* 1/2 łyżeczki papryki ostrej
* 1/3 łyżeczki ziaren kolendry, mielonej
* 1/4 łyżeczki syropu klonowego
* sól i pieprz
* do podania: świeża pietruszka lub koperek

|
== Przygotowanie
Piekarnik rozgrzać do 200 stopni. Kalafiora podzielić na różyczki, duże róże pokroić na mniejsze, liście pociąć. Puszkę ciecierzycy odcedzić, płyn z ciecierzycy warto zachować i zrobić z niego na przykład majonez.

W małej szklance dokładnie wymieszać wszystkie składniki sosu. Dużą blachę do pieczenia wyłożyć papierem, wysypać kalafiora oraz ciecierzycę, polać sosem i dokładnie natrzeć rękoma.

Pomidorki pokroić na połówki, dodać do kalafiora i wsunąć do gorącego piekarnika. Piec przez 10 - 15 minut, po tym czasie wymieszać i piec jeszcze 5 - 10 minut do momentu, aż kalafior zrobi się złoty i bardzo miękki. Posypać czarnym pieprzem, pietruszką lub koperkiem i zjadać. Dobrze smakuje na ciepło i na zimno.

Można podawać jako lekki lunch bez dodatków; jako bardziej sycący lunch posypane garścią pestek dyni albo jako bardzo sycący lunch z kaszą lub pieczywem.

Podpowiem też, że jeśli kaszę wstawicie w tym samym czasie co warzywa, to w pół godziny otrzymacie naprawdę porządny obiad dla kilku osób.

|===

[.text-center]
== Zdjęcia
