= Pieczony kalafior z ciecierzyc  +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: 15 minut + 30 minut pieczenia
* 2 porcje
* https://www.jadlonomia.com/przepisy/pieczony-kalafior-z-ciecierzyca[link do 藕r贸da przepisu]

== Skadniki
* 1/2 kalafiora / 600 g
* 1 puszka ciecierzycy
* 10 - 15 sztuk pomidor贸w koktajlowych
* Skadniki sosu:
* 2 - 3 y偶ki oleju
* 1 y偶ka sosu sojowego
* 1/2 y偶eczki papryki wdzonej
* 1/2 y偶eczki papryki ostrej
* 1/3 y偶eczki ziaren kolendry, mielonej
* 1/4 y偶eczki syropu klonowego
* s贸l i pieprz
* do podania: wie偶a pietruszka lub koperek

|
== Przygotowanie
Piekarnik rozgrza do 200 stopni. Kalafiora podzieli na r贸偶yczki, du偶e r贸偶e pokroi na mniejsze, licie poci. Puszk ciecierzycy odcedzi, pyn z ciecierzycy warto zachowa i zrobi z niego na przykad majonez.

W maej szklance dokadnie wymiesza wszystkie skadniki sosu. Du偶 blach do pieczenia wyo偶y papierem, wysypa kalafiora oraz ciecierzyc, pola sosem i dokadnie natrze rkoma.

Pomidorki pokroi na po贸wki, doda do kalafiora i wsun do gorcego piekarnika. Piec przez 10 - 15 minut, po tym czasie wymiesza i piec jeszcze 5 - 10 minut do momentu, a偶 kalafior zrobi si zoty i bardzo mikki. Posypa czarnym pieprzem, pietruszk lub koperkiem i zjada. Dobrze smakuje na ciepo i na zimno.

Mo偶na podawa jako lekki lunch bez dodatk贸w; jako bardziej syccy lunch posypane garci pestek dyni albo jako bardzo syccy lunch z kasz lub pieczywem.

Podpowiem te偶, 偶e jeli kasz wstawicie w tym samym czasie co warzywa, to w p贸 godziny otrzymacie naprawd porzdny obiad dla kilku os贸b.

|===

[.text-center]
== Zdjcia
