= Pieczarki w zalewie pomidorowej 🌱 +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++
:imagesdir: /Recipes/static/images

[.recipe-hero]
[.card-image-placeholder]
Brak zdjęcia przepisu 🍲

[.back-to-home-wrapper]
link:../../index.html[← Wróć do przepisów, role="back-to-home-btn"]

[.recipe-details]
* 🕒 czas gotowania: 1 godzina
* 👥 4 porcje
* 🔗 Przepis z zeszytu mamy

[.recipe-columns]
== Składniki
* 1 kg pieczarek
* 3-4 cebule - pokroić w półplasterki
* 1 l wody
* 2 płaskie łyżeczki soli
* 1 płaska łyżeczka wegety
* 4 łyżeczki cukru

=== Zalewa:

* ½ szklanki. octu
* ½ szklanki. oleju
* ½ przecieru (ketchup)
* pieprz, ziele, liść laurowy

== Przygotowanie

Oczyszczone pieczarki (bez wcześniejszego solenia) obtoczyć w roztrzepanym jajku oraz bułce tartej, a następnie usmażyć na rozgrzanym tłuszczu na złoty kolor i odsączyć. W garnku zagotować litr wody z dodatkiem dwóch płaskich łyżeczek soli, łyżeczki wegety oraz czterech łyżeczek cukru, wrzucić pokrojoną w półplasterki cebulę i krótko ją obgotować, aż lekko zmięknie, po czym odcedzić. W osobnym naczyniu przygotować właściwą zalewę: wymieszać pół szklanki octu, pół szklanki oleju oraz pół szklanki przecieru pomidorowego lub ketchupu, dodając pieprz, ziele angielskie i liść laurowy. Usmażone pieczarki oraz sparzoną cebulę ułożyć warstwowo w słoikach lub głębokim naczyniu, zalać przygotowaną pomidorową zalewą i odstawić do przegryzienia.

[.recipe-gallery]
== Zdjęcia

[.gallery-grid]
// Tutaj pojawią się zdjęcia
