= Pierogi leniwe

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 30 minut
* czas gotowania klusek łącznie: 10 minut
* czas szykowania sosu: 10 minut
* liczba porcji: 50 klusek
* https://aniagotuje.pl/przepis/kluski-leniwe[link do źródła przepisu]

== Składniki
* 500 g twarogu półtłustego
* 2 średnie jajka
* trochę ponad pół szklanki mąki pszennej - 100 g
* 2 łyżki masła
* pół płaskiej łyżeczki soli
* 1/3 szklanki śmietanki 30 %
* 2 łyżki masła
* 2 łyżki cukru waniliowego

|
== Przygotowanie
Pierogi leniwe robi się super szybko. Zacznij od zmielenia twarogu. Możesz użyć twaróg półtłusty lub tłusty w kostce, typu krajanka (w bloczkach) lub też w "trójkącie" pakowany w papier. Twaróg można zmielić w maszynce lub też przepuścić przez ręczną praskę. Do leniwych nie używam twarogu mielonego sernikowego w wiaderku, ponieważ nawet te bardzo dobrej jakości twarogi mielone nie są tak zwarte, jak te sprzedawane w kostce. 

Do miski ze zmielonym twarogiem dodaj dwie łyżki bardzo miękkiego lub roztopionego i przestudzonego masła. Oddziel białka od żółtek. Żółtka dodaj do miski z twarogiem, zaś białka umieść w czystej i suchej misce, szklanej lub metalowej. 

Porada: Dodatek masła możesz pominąć (lub dać tylko jedną łyżkę), jeśli używasz tłustego twarogu. 

Masę serową dokładnie wymieszaj łyżką. Zauważ, że nie jest luźna. Do miski wsyp trochę ponad pół szklanki mąki pszennej, czyli około 100 gramów mąki (tortowa, poznańska lub wrocławska) oraz pół płaskiej łyżeczki soli. Całość dokładnie wymieszaj. 

Białka ubijaj chwilę na sztywno przy pomocy miksera. Możesz do nich dodać szczyptę soli. Nie ubijaj samych białek za długo, by nie przebić pęcherzyków powietrza. Gdy białko zacznie zamieniać się w puszystą pianę (przypomina trochę mydlaną pianę z kąpieli w wannie) wyłącz mikser.

Pianę z białek umieść w misce z masą serową i delikatnie wmieszaj przy pomocy szpatułki. Tak, masa jest lepka i ciężko wyobrazić sobie, by formować z niej kluski. Nie dokładaj jednak więcej mąki :)

Możesz już przygotować większy garnek z gotującą się, lekko osoloną wodą. Ustaw małą moc palnika i przykryj garnek przykrywką, by w każdej chwili móc wrzucić kluski na wrzątek.

Czystą stolnicę lub blat oprósz mąką. Lekko oprósz też mąką talerz, na który będziesz układać gotowe do gotowania leniwe. Dużą łyżką nakładaj sobie spore porcje masy serowej na miejsce, w którym rozprowadzona została warstwa mąki. (Masę podziel np. na trzy części). Porcję masy serowej lekko oprósz też od góry. Suchymi dłońmi (mogą być oprószone w mące) zacznij rolować wałek o średnicy około 3 cm. Nożykiem krój po skosie kluski o podobnej wielkości. 

Pierwszą porcję klusek "wrzucaj" do garnka z gotującą się wodą. Woda nie powinna mocno bulgonić. Ma tylko delikatnie mrugać. Po chwili leniwe pierogi wypłyną na powierzchnię. Leniwe wyławiaj nie dłużej niż po minucie od ich wypłynięcia na powierzchnię. W ten sposób ugotuj wszystkie serie przygotowanych klusek. Pierogi leniwe warto dobrze odcedzić po wyłowieniu z wody.

Kluski leniwe podaję zazwyczaj polane sosem waniliowym. To bardzo prosty do zrobienia sos, ponieważ nie zagęszczam go przez dodanie żółtek szykowanych na parze. Do rondelka wlej 1/3 szklanki śmietanki 30 %, dodaj 2 łyżki masła oraz 2 łyżki cukru waniliowego. Polecam oczywiście domowy cukier waniliowy. 

Sos mieszaj, aż do zagotowania i wyłącz. 

Gorącym sosem polej umieszczone na półmisku kluski leniwe. 

Na koniec dodam jeszcze kilka ciekawych i ważnych informacji oraz porad.

Jeśli chodzi o samo formowanie klusek, to nie jest konieczne gotowanie ich w kształcie skośnych kopytek. Kluski można też nabierać przy pomocy łyżeczki a następnie przekładać na drugą łyżeczkę tworząc kluskę w kształcie małego cepelinka i takie kluseczki kłaść na wrzątek. 

Najważniejsze jest to, by nie dawać za dużo mąki do masy serowej. Masa jest klejąca co kusi, by dodać nawet dwa razy tyle mąki. Jeśli masę przełożymy na blat z mąką i damy odrobinę mąki od góry, to bez problemu uformujemy wałek miękkiego ciasta serowego. Kluseczki będą delikatne i takie zostaną po ugotowaniu. Będą to przepyszne, mięciutkie kluseczki serowe rozpływające się w ustach. 

Dość istotna uwaga na koniec.. Pierogi leniwe gotują się błyskawicznie. Nie gotuj ich dłużej, ponieważ są to delikatne kluseczki i przy zbyt długim gotowaniu mogą się rozpaść. Moc palnika nie może być za wysoka. Woda musi się gotować, ale ma tylko lekko mrugać. 

Pierogi leniwe można też podać z bułką tartą zarumienioną na maśle. Wówczas osobno rumienisz bułkę z masłem polewasz ją leniwe a na koniec posypujesz kluski cukrem zwykłym lub trzcinowym. 

Leniwe można też polać zwykłym jogurtem wymieszanym z odrobiną cukru pudru oraz  ulubionym sosem owocowym.

== Zdjęcia
|===
