= Pier z kaczki  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 20 min
* 2 porcje
* https://www.kwestiasmaku.com/kuchnia_polska/kaczka/piersi_kaczki_sos_zurawinowy/przepis.html[link do 藕r贸da przepisu]

== Skadniki

* 2 piersi kaczki ze sk贸rk (ka偶da po ok. 200 - 250 g)
* (lub - na szybko - gotowy d偶em 偶urawinowy lub bor贸wkowy)

|
== Przygotowanie

Miso ogrza w temperaturze pokojowej. Piekarnik nagrza do 200 st. C. Piersi kaczki ponacina "w kratk" od strony ze sk贸r, nie uszkadzajc misa. Doprawi wie偶o zmielonym pieprzem i sol morsk. Poo偶y na zimnej patelni z grubym dnem (np. 偶eliwnej) sk贸rk do dou i podgrzewa na umiarkowanym ogniu stopniowo wytapiajc sk贸rk. W sumie potrwa to ok. 12-14 minut. Nastpnie przewr贸ci miso sk贸rk do g贸ry i podsma偶y ok. 2 minuty.

Tak podsma偶one piersi wstawi do nagrzanego piekarnika. Jeli rczka patelni nie mo偶e by u偶ywana w piekarniku, przekadamy piersi do naczynia 偶aroodpornego (najlepiej nagrzewanego razem z piekarnikiem), sk贸rk do g贸ry. Piec przez 8 minut. Wyj piersi na talerz i odczeka 5 minut przed pokrojeniem.

W tym czasie na dobrze rozgrzanej patelni i na tuszczu wytopionym ze sk贸rki kaczki podsma偶y ziemniaczki. Gdy miso odpocznie pokroi je na cienkie i ukone plasterki.

|===

[.text-center]
== Zdjcia
