= Pierogi leniwe  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: 30 minut
* czas gotowania klusek cznie: 10 minut
* czas szykowania sosu: 10 minut
* liczba porcji: 50 klusek
* https://aniagotuje.pl/przepis/kluski-leniwe[link do 藕r贸da przepisu]

== Skadniki
* 500 g twarogu p贸tustego
* 2 rednie jajka
* troch ponad p贸 szklanki mki pszennej - 100 g
* 2 y偶ki masa
* p贸 paskiej y偶eczki soli
* 1/3 szklanki mietanki 30 %
* 2 y偶ki masa
* 2 y偶ki cukru waniliowego

|
== Przygotowanie
Pierogi leniwe robi si super szybko. Zacznij od zmielenia twarogu. Mo偶esz u偶y twar贸g p贸tusty lub tusty w kostce, typu krajanka (w bloczkach) lub te偶 w "tr贸jkcie" pakowany w papier. Twar贸g mo偶na zmieli w maszynce lub te偶 przepuci przez rczn prask. Do leniwych nie u偶ywam twarogu mielonego sernikowego w wiaderku, poniewa偶 nawet te bardzo dobrej jakoci twarogi mielone nie s tak zwarte, jak te sprzedawane w kostce. 

Do miski ze zmielonym twarogiem dodaj dwie y偶ki bardzo mikkiego lub roztopionego i przestudzonego masa. Oddziel biaka od 偶贸tek. 呕贸tka dodaj do miski z twarogiem, za biaka umie w czystej i suchej misce, szklanej lub metalowej. 

Porada: Dodatek masa mo偶esz pomin (lub da tylko jedn y偶k), jeli u偶ywasz tustego twarogu. 

Mas serow dokadnie wymieszaj y偶k. Zauwa偶, 偶e nie jest lu藕na. Do miski wsyp troch ponad p贸 szklanki mki pszennej, czyli okoo 100 gram贸w mki (tortowa, poznaska lub wrocawska) oraz p贸 paskiej y偶eczki soli. Cao dokadnie wymieszaj. 

Biaka ubijaj chwil na sztywno przy pomocy miksera. Mo偶esz do nich doda szczypt soli. Nie ubijaj samych biaek za dugo, by nie przebi pcherzyk贸w powietrza. Gdy biako zacznie zamienia si w puszyst pian (przypomina troch mydlan pian z kpieli w wannie) wycz mikser.

Pian z biaek umie w misce z mas serow i delikatnie wmieszaj przy pomocy szpatuki. Tak, masa jest lepka i ci偶ko wyobrazi sobie, by formowa z niej kluski. Nie dokadaj jednak wicej mki :)

Mo偶esz ju偶 przygotowa wikszy garnek z gotujc si, lekko osolon wod. Ustaw ma moc palnika i przykryj garnek przykrywk, by w ka偶dej chwili m贸c wrzuci kluski na wrztek.

Czyst stolnic lub blat opr贸sz mk. Lekko opr贸sz te偶 mk talerz, na kt贸ry bdziesz ukada gotowe do gotowania leniwe. Du偶 y偶k nakadaj sobie spore porcje masy serowej na miejsce, w kt贸rym rozprowadzona zostaa warstwa mki. (Mas podziel np. na trzy czci). Porcj masy serowej lekko opr贸sz te偶 od g贸ry. Suchymi domi (mog by opr贸szone w mce) zacznij rolowa waek o rednicy okoo 3 cm. No偶ykiem kr贸j po skosie kluski o podobnej wielkoci. 

Pierwsz porcj klusek "wrzucaj" do garnka z gotujc si wod. Woda nie powinna mocno bulgoni. Ma tylko delikatnie mruga. Po chwili leniwe pierogi wypyn na powierzchni. Leniwe wyawiaj nie du偶ej ni偶 po minucie od ich wypynicia na powierzchni. W ten spos贸b ugotuj wszystkie serie przygotowanych klusek. Pierogi leniwe warto dobrze odcedzi po wyowieniu z wody.

Kluski leniwe podaj zazwyczaj polane sosem waniliowym. To bardzo prosty do zrobienia sos, poniewa偶 nie zagszczam go przez dodanie 偶贸tek szykowanych na parze. Do rondelka wlej 1/3 szklanki mietanki 30 %, dodaj 2 y偶ki masa oraz 2 y偶ki cukru waniliowego. Polecam oczywicie domowy cukier waniliowy. 

Sos mieszaj, a偶 do zagotowania i wycz. 

Gorcym sosem polej umieszczone na p贸misku kluski leniwe. 

Na koniec dodam jeszcze kilka ciekawych i wa偶nych informacji oraz porad.

Jeli chodzi o samo formowanie klusek, to nie jest konieczne gotowanie ich w ksztacie skonych kopytek. Kluski mo偶na te偶 nabiera przy pomocy y偶eczki a nastpnie przekada na drug y偶eczk tworzc klusk w ksztacie maego cepelinka i takie kluseczki ka na wrztek. 

Najwa偶niejsze jest to, by nie dawa za du偶o mki do masy serowej. Masa jest klejca co kusi, by doda nawet dwa razy tyle mki. Jeli mas przeo偶ymy na blat z mk i damy odrobin mki od g贸ry, to bez problemu uformujemy waek mikkiego ciasta serowego. Kluseczki bd delikatne i takie zostan po ugotowaniu. Bd to przepyszne, miciutkie kluseczki serowe rozpywajce si w ustach. 

Do istotna uwaga na koniec.. Pierogi leniwe gotuj si byskawicznie. Nie gotuj ich du偶ej, poniewa偶 s to delikatne kluseczki i przy zbyt dugim gotowaniu mog si rozpa. Moc palnika nie mo偶e by za wysoka. Woda musi si gotowa, ale ma tylko lekko mruga. 

Pierogi leniwe mo偶na te偶 poda z buk tart zarumienion na male. W贸wczas osobno rumienisz buk z masem polewasz j leniwe a na koniec posypujesz kluski cukrem zwykym lub trzcinowym. 

Leniwe mo偶na te偶 pola zwykym jogurtem wymieszanym z odrobin cukru pudru oraz  ulubionym sosem owocowym.

|===

[.text-center]
== Zdjcia
