= Pierogi gyoza +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 45 min
* 4 porcje
* https://miss-gaijin.pl/gyoza-najlepszy-przepis-na-japonskie-pierozki[link do źródła przepisu]

== Składniki
* ¼ szklanki wody
* 1 łyżka oleju roślinnego
* 1 łyżka oleju sezamowego

=== Ciasto:

* 240 g mąki uniwersalnej
* ½ łyżeczki soli
* 120 ml wody

Lub gotowe ciasto na gyozę ze sklepu

=== Farsz:

* 280 g zmielonego mięsa
* 2-3 duże liście białej kapusty (ok 120g)
* 15 g zielonej cebulki
* 1 duży ząbek czosnku
* 2 cm imbiru
* 1 łyżka mirin
* 1 łyżka oleju sezamowego
* 1 łyżka sosu sojowego
* 1 łyżeczka soli
* Świeżo zmielony pieprz

=== Sos:

* 2 łyżki octu ryżowego
* 2 łyżki sosu sojowego
* 2-3 krople oleju chili - la-yu

|
== Przygotowanie
Jeżeli nie macie gotowego ciasta na gyozę to zacznijcie właśnie od tego. Dokładnie odmierzcie mąkę i przesiejcie ją do miski. Do przegotowanej, wciąż ciepłej wody dodajcie sól i wymieszajcie. Powoli dodawajcie wodę do mąki mieszając szpatułką lub drewnianą łyżką aż będziecie mogli uformować z ciasta kulę. Jeżeli ciasto będzie zbyt twarde dodajcie jeszcze odrobinę wody. Wyrabiajcie przez 10 minut (nie mniej!), aż stanie się gładkie. Zawińcie w folię i włóżcie do lodówki na 10 minut. Po wyciągnięciu z lodówki dobrze rozwałkujcie na posypanym skrobią ziemniaczaną blacie i wytnijcie szklanką cieniutkie plasterki jak na pierogi. Gotowe ciasto przykryjcie ręcznikiem by nie wyschło.

Białą kapustę siekamy na drobne kawałeczki, a zieloną cebulkę w cienkie plasterki. Ząbek czosnku oraz imbir ścieramy. Wszystko razem wkładamy do miski i dodajemy pozostałe składniki farszu. Pamiętajcie by dobrze doprawić wszystko solą i pieprzem by nadzienie nie było mdłe w smaku. Gdy wszystko ze sobą wymieszacie możecie odrobinkę skosztować, czy jest wystarczająco słone. Mieszanie możecie zacząć szpatułką, jednak zakończcie ugniatając rękoma do czasu aż będzie kleiste.

Do nadziewania użyjcie małej łyżeczki. Na jedną rękę połóżcie kawałek ciasta, a na jego środku ułóżcie łyżeczkę farszu. Krawędzie posmarujcie palcem wodą by dobrze się kleiły. Złóżcie ciasto na pół nad wypełnieniem, ale nie sklejajcie jeszcze do końca. Kciukiem i palcem wskazującym zacznijcie fałdować górną część ciasta robiąc takie jakby zakładki. Po każdej ze stron zróbcie 3-4 fałdki i sklejcie z dolną częścią.

Na patelni rozgrzejcie łyżkę oleju roślinnego. Ułóżcie pierożki płaską stroną do dołu. Smażcie około 3 minuty na średnim ogniu, aż spody będą złocisto- brązowe. Następnie wlejcie na patelnię ¼ szklanki wody i szybko przykryjcie pokrywką. Gotujcie pierożki na parze przez kolejne 2-3 minuty. Gdy woda wyparuje dodajcie łyżkę oleju sezamowego i poruszajcie pierożkami po patelni tak by dostał się on pod nie. Smażcie tak długo aż od spodu staną się chrupiące.

W tym czasie możecie przygotować sos. Po prostu wlewacie wszystkie składniki do spodeczka i mieszacie zachowując podane wyżej proporcje. Uważajcie jednak z olejem chili, gdyż jest on bardzo ostry! 2-3 krople wystarczą.

|===

[.text-center]
== Zdjęcia
