= Pierogi z kapustą i grzybami 🌱 +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 1,5 h
* ok. 80 sztuk
* https://www.kwestiasmaku.com/kuchnia_polska/pierogi/pierogi_z_kapusta/przepis.html[link do źródła przepisu]

== Składniki
* 1 słoik litrowy suszonych grzybów (ok. 100 g)
* 1 kg kiszonej kapusty
* 1 marchewka
* 1 pietruszka
* 3 łyżki oleju
* 3 cebule
* 600 g mąki pszennej
* 1/2 łyżeczki soli
* 400 ml wrzącej wody
* 50 g masła
* 3 cebule
* kilka łyżek oleju roślinnego

|
== Przygotowanie
Grzyby opłukać, zalać zimną wodą i odstawić na 6 godzin lub na całą noc. Następnego dnia zagotować, dodać obraną marchewkę, pietruszkę i gotować aż będą miękkie. Pod koniec gotowania doprawić solą i pieprzem.

Kapustę odcisnąć i ugotować w 300 ml wody do miękkości z dodatkiem soli do smaku (ok. 45 minut), dokładnie odcisnąć.

Grzyby, marchewkę i pietruszkę odcedzić, zachowując wywar (wykorzystać do np. do zupy grzybowej). Bardzo dobrze odcisnąć z wody i razem z kapustą zmielić w maszynce do mięsa o bardzo dużych oczkach, ok 1 cm średnicy (lub drobno posiekać na desce).

Na patelni na oleju zeszklić cebule, dodać do farszu. Składniki farszu dobrze wyrobić, łącząc wszystko razem, doprawić solą i pieprzem.

Mąkę przesiać do miski, dodać sól. Do gorącej wody włożyć masło i roztopić, stopniowo wlewać do mąki, mieszając wszystko łyżką. Połączyć składniki i wyłożyć je na podsypaną mąką stolnicę.

Zagniatać ciasto przez około 10 minut aż będzie gładkie i miękkie. Ciasto włożyć do miseczki, szczelnie przykryć i odstawić na 30 minut.

Ciasto podzielić na 4 części, kolejno rozwałkowywać na placki. Małą szklanką wycinać kółeczka, na środek nakładać farsz, składać na pół i zlepiać brzegi w pierogi.

Gotować do miękkości, przez około 3 minuty, ale najlepiej sprawdzić czy pierogi są już miękkie, odławiając jednego na łyżkę cedzakową i dotykając palcem.

Podawać z zeszkloną na oleju pokrojoną w drobną kostkę cebulą.

|===

[.text-center]
== Zdjęcia
