= Pierogi z mięsem

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 1,5 h
* ok. 100 sztuk
* https://www.kwestiasmaku.com/kuchnia_polska/pierogi/pierogi_z_miesem/przepis.html [link do źródła przepisu]

== Składniki
* 500 g ugotowanego mięsa z rosołu
* ugotowane warzywa z zupy (1 marchewka, 1/2 pietruszki)
* 300 g pieczarek
* 1 duża cebula
* 1 łyżka masła
* 1 jajko (opcjonalnie)
|
== Przygotowanie
Przygotować ciasto na pierogi z podwójnej porcji.

Pieczarki oczyścić szczoteczką lub gąbką, pokroić na mniejsze części. Cebulę obrać i pokroić w drobną kosteczkę. Pieczarki i cebulę wrzucić na dobrze rozgrzaną patelnię z dodatkiem masła i na większym ogniu odparować i zrumienić co chwilę mieszając.

Mięso drobiowe (bez skóry), wołowe (razem z tłuszczem), pieczarki, cebulę oraz warzywa z wywaru zmielić w maszynce do mięsa, dokładnie wyrobić, doprawić solą i pieprzem. Jeśli nadzienie wyszło za rzadkie, można podsmażyć je na patelni, jeśli za sztywne, można dodać troszkę rosołu. Do nadzienia dodać jajko i wymieszać.

Szklanką wycinać kółka z rozwałkowanego ciasta, na środek nakładać po jednej pełnej łyżce farszu (lub tyle ile się zmieści). Składać ciasto na pół i zlepiać dokładnie brzegi, uważając aby nadzienie nie dostało się w miejsce sklejenia.

Gotowe pierogi układać na stolnicy lub blacie podsypanych mąką. Przykryć ściereczką do czasu gotowania, aby nie obeschły.

W dużym garnku zagotować osoloną wodę, i jak będzie mocno wrzała, włożyć pierwszą partię pierogów. Po ponownym zagotowaniu zmniejszyć ogień do średniego i gotować pierogi do miękkości ciasta.

Wyławiać łyżką cedzakową i układać na talerzach. Podawać z wody lub odsmażać (ostudzone, wysuszone pierogi). Pierogi z wody można polewać roztopionym masłem a odsmażane posypać skwarkami i podawać z kwaśną śmietaną.

|===

[.text-center]
== Zdjęcia
