= Pierś z kaczki z sosem pomarańczowym 🦆 +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 45 min
* 2 - 4 porcje
* https://www.kwestiasmaku.com/kuchnia_polska/kaczka/piersi_kaczki_z_sosem_pomaranczowym/przepis.html[link do źródła przepisu]

== Składniki
* 2 piersi kaczki ze skórką (po około 200 - 250 g), świeże lub mrożone
* 2 łyżki klarowanego masła lub oleju roślinnego
* 1/3 szklanki białego lub różowego wina
* 2 pomarańcze podzielone na cząstki i obrane z błonek
* skóra starta z 1 pomarańczy
* 3 łyżki dżemu pomarańczowego
* 1 łyżka drobno startego imbiru
* 2 łyżki miodu
* 1  łyżka rodzynek królewskich
* 1 łyżeczka przyprawy piernikowej lub 1/2 łyżeczki cynamonu
* 1/3 łyżeczki suszonego estragonu (opcjonalnie)

|
== Przygotowanie
Piersi rozmrozić jeśli były mrożone, osuszyć papierowymi ręcznikami. Skórkę ponacinać na krzyż aż do mięsa. Piekarnik nagrzać do 200 stopni C. Rozgrzać patelnię na średnim ogniu, włożyć klarowane masło lub wlać olej, ułożyć piersi skórką do dołu i smażyć przez 4 minuty na średnim ogniu, aż skórka będzie złota.

Następnie przełożyć piersi na drugą stronę i smażyć przez 1 minutę. Piersi ułożyć skórką do góry w naczyniu żaroodpornym lub blaszce i wstawić do piekarnika (zlać tłuszcz z patelni do miseczki, patelni nie myć).

Kaczkę piec przez 15 minut (średnio wysmażone mięso) lub 18 minut (dobrze wysmażone mięso). Piersi wyjąć na talerz, przykryć folią aluminiową i odstawić na kilka minut. Gdy mięso odpocznie pokroić je na cienkie i ukośne plasterki. Gdy mięso odpoczywa (przed pokrojeniem) robimy sos pomarańczowy.

Sos pomarańczowo-imbirowy: Do miski włożyć wszystkie składniki sosu, na dno miski wsypując rodzynki i estragon jeśli go używamy, tak aby moczyły się w soku. Odstawić do czasu gdy kaczka będzie gotowa.

Soki, które wypłynęły z mięsa wlewamy na patelnię po kaczce, dodajemy wino i gotujemy na większym ogniu aż płyn prawie całkowicie się zredukuje. Gdy na patelni pozostanie około 1 łyżki gęstego płynu, dodajemy wszystkie składniki sosu pomarańczowego wymieszane w miseczce i zagotowujemy. Po kilkunastu sekundach gotowania odstawiamy patelnię z ognia (sos powinien trochę zgęstnieć). Dodajemy ugotowany ciepłu ryż i pokrojoną w plasterki pierś kaczki. Zamiast do patelni, wszystkie składniki dania można od razu ułożyć na talerzach.

|===

[.text-center]
== Zdjęcia
