= Pierogi z misem  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 1,5 h
* ok. 100 sztuk
* https://www.kwestiasmaku.com/kuchnia_polska/pierogi/pierogi_z_miesem/przepis.html[link do 藕r贸da przepisu]

== Skadniki

* 500 g ugotowanego misa z rosou
* ugotowane warzywa z zupy (1 marchewka, 1/2 pietruszki)
* 300 g pieczarek
* 1 du偶a cebula
* 1 y偶ka masa
* 1 jajko (opcjonalnie)
|
== Przygotowanie

Przygotowa ciasto na pierogi z podw贸jnej porcji.

Pieczarki oczyci szczoteczk lub gbk, pokroi na mniejsze czci. Cebul obra i pokroi w drobn kosteczk. Pieczarki i cebul wrzuci na dobrze rozgrzan patelni z dodatkiem masa i na wikszym ogniu odparowa i zrumieni co chwil mieszajc.

Miso drobiowe (bez sk贸ry), woowe (razem z tuszczem), pieczarki, cebul oraz warzywa z wywaru zmieli w maszynce do misa, dokadnie wyrobi, doprawi sol i pieprzem. Jeli nadzienie wyszo za rzadkie, mo偶na podsma偶y je na patelni, jeli za sztywne, mo偶na doda troszk rosou. Do nadzienia doda jajko i wymiesza.

Szklank wycina k贸ka z rozwakowanego ciasta, na rodek nakada po jednej penej y偶ce farszu (lub tyle ile si zmieci). Skada ciasto na p贸 i zlepia dokadnie brzegi, uwa偶ajc aby nadzienie nie dostao si w miejsce sklejenia.

Gotowe pierogi ukada na stolnicy lub blacie podsypanych mk. Przykry ciereczk do czasu gotowania, aby nie obeschy.

W du偶ym garnku zagotowa osolon wod, i jak bdzie mocno wrzaa, wo偶y pierwsz parti pierog贸w. Po ponownym zagotowaniu zmniejszy ogie do redniego i gotowa pierogi do mikkoci ciasta.

Wyawia y偶k cedzakow i ukada na talerzach. Podawa z wody lub odsma偶a (ostudzone, wysuszone pierogi). Pierogi z wody mo偶na polewa roztopionym masem a odsma偶ane posypa skwarkami i podawa z kwan mietan.

|===

[.text-center]
== Zdjcia
