= Pierś z kaczki +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 20 min
* 2 porcje
* https://www.kwestiasmaku.com/kuchnia_polska/kaczka/piersi_kaczki_sos_zurawinowy/przepis.html[link do źródła przepisu]

== Składniki
* 2 piersi kaczki ze skórką (każda po ok. 200 - 250 g)
* (lub - na szybko - gotowy dżem żurawinowy lub borówkowy)

|
== Przygotowanie
Mięso ogrzać w temperaturze pokojowej. Piekarnik nagrzać do 200 st. C. Piersi kaczki ponacinać "w kratkę" od strony ze skórą, nie uszkadzając mięsa. Doprawić świeżo zmielonym pieprzem i solą morską. Położyć na zimnej patelni z grubym dnem (np. żeliwnej) skórką do dołu i podgrzewać na umiarkowanym ogniu stopniowo wytapiając skórkę. W sumie potrwa to ok. 12-14 minut. Następnie przewrócić mięso skórką do góry i podsmażyć ok. 2 minuty.

Tak podsmażone piersi wstawić do nagrzanego piekarnika. Jeśli rączka patelni nie może być używana w piekarniku, przekładamy piersi do naczynia żaroodpornego (najlepiej nagrzewanego razem z piekarnikiem), skórką do góry. Piec przez 8 minut. Wyjąć piersi na talerz i odczekać 5 minut przed pokrojeniem.

W tym czasie na dobrze rozgrzanej patelni i na tłuszczu wytopionym ze skórki kaczki podsmażyć ziemniaczki. Gdy mięso odpocznie pokroić je na cienkie i ukośne plasterki.

|===

[.text-center]
== Zdjęcia
