= Placek po węgiersku +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 2,5 h
* 1 porcja placek
* 6 - 8 porcji gulasz
* https://www.kwestiasmaku.com/przepis/placek-po-wegiersku[link do źródła przepisu]

== Składniki

Gulasz węgierski:

* 1 kg łopatki wieprzowej lub szynki
* 100 g parzonego lub gotowanego boczku
* 1 duża cebula
* 2 średnie marchewki
* 1 papryka
* 2 łyżki oliwy
* 2 łyżki smalcu (lub oliwy)
* 4 łyżeczki mielonej słodkiej papryki
* 1 łyżeczka mielonej ostrej papryki
* 3 łyżeczki suszonego czosnku niedźwiedziego (można pominąć)
* ok. 1 l gorącego bulionu lub rosołu
* 2 łyżki sosu sojowego
* 2 listki laurowe
* 3 ziela angielskie
* 2 łyżki koncentratu pomidorowego
* 200 g pieczarek
* 2 łyżki masła
* 2 łyżki mąki

Placek:

* 1/2 kg ziemniaków
* 1/2 łyżki mąki pszennej
* 1/4 cebuli
* 1 jajko
* sól
* 5 łyżek oleju roślinnego do smażenia
* do podania: śmietana i natka pietruszki

|
== Przygotowanie

Gulasz węgierski:

Mięso pokroić w kostkę ok. 1,5 cm. Boczek pokroić w małą kostkę. Cebulę obrać i pokroić w kosteczkę. Marchewkę obrać i pokroić na plasterki. Paprykę pokroić w kostkę.

W szerokim garnku rozgrzać łyżkę oliwy, dodać boczek i cebulę, zeszklić ją. Dodać drugą łyżkę oliwy, włożyć marchewkę i paprykę i mieszając podsmażać wszystko przez kilka minut.

W międzyczasie na oddzielnej patelni rozgrzać smalec (lub oliwę) i obsmażyć kawałki mięsa. Doprawić je solą i pieprzem i przenieść do garnka z warzywami. Jeśli mamy można całość podlać ok. 1/3 szklanki wina (czerwonego lub białego) i na większym ogniu chwilę odparować.

Zawartość garnka doprawić mieloną papryką i jeśli mamy czosnkiem niedźwiedzim. Wlać gorący bulion (lub rosół) w ilości aby zakryło składniki. Dodać sos sojowy, ziele angielskie i listek laurowy, przykryć i dusić na małym ogniu ok. 1 i 1/2 godziny, do miękkości mięsa. Na koniec dodać koncentrat pomidorowy i podsmażone na złoto pokrojone pieczarki.

Na patelni dobrze rozgrzać masło, dodać mąkę i chwilę podsmażyć mieszając. Przełożyć do garnka, dokładnie wymieszać i zagotować.

Placek:

Przygotować i podgrzać porcję gulaszu węgierskiego.

Ziemniaki obrać i zetrzeć na tarce o małych oczkach. Zostawić je na ok. 5 minut bez mieszania po czym w dłoniach dokładnie odcisnąć z soku. Do odciśniętych ziemniaków dodać mąkę, drobno startą cebulę, jajko oraz dwie szczypty soli, wymieszać.

Rozgrzać patelnię (śr. 20-22 cm), wlać 3 łyżki oleju. Wyłożyć całą masę ziemniaczaną na rozgrzany olej i rozprowadzić ją na równy placek. Smażyć na średnim ogniu przez ok. 4 minuty na złoty kolor, przewrócić na drugą stronę, dodać pozostałe 2 łyżki oleju i powtórzyć smażenie (ok. 3 minuty).

Przełożyć na talerz, nałożyć gorący gulasz i złożyć na pół. Po wierzchu polać gęstą śmietaną i posypać natką.

|===

[.text-center]
== Zdjęcia
