= Placki ziemniaczane  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: 30 minut
* ok. 12 sztuk
* https://www.kwestiasmaku.com/przepis/placki-ziemniaczane[link do 藕r贸da przepisu]

== Skadniki
* 1/2 kg ziemniak贸w
* 1/2 y偶ki mki pszennej
* 1/4 cebuli
* 1 jajko
* s贸l
* olej rolinny do sma偶enia

|
== Przygotowanie

Ziemniaki i cebul obra i zetrze na tarce o maych oczkach bezporednio do wikszej i paskiej miski. Zostawi je w misce bez mieszania, misk delikatnie przechyli i odstawi tak na ok. 5 minut.

W midzyczasie odlewa zbierajcy si sok, delikatnie przytrzymujc mas, nadal ich nie miesza. Na koniec docisn doni do miski i odla jeszcze wicej soku. Doda mk, jajko oraz dwie szczypty soli.

Rozgrza patelni, wla olej. Mas ziemniaczan wymiesza. Nakada porcje masy (2 y偶ki) na rozgrzany olej i rozprowadza j na do cienki placek. Sma偶y na rednim ogniu przez ok. 2 - 3 minuty na zoty kolor, przewr贸ci na drug stron i powt贸rzy sma偶enie.

|===

[.text-center]
== Zdjcia
