= Placki z cukinii +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 25 min
* 2 porcje, 10 sztuk
* https://www.kwestiasmaku.com/zielony_srodek/cukinia/placki_z_cukinii/przepis.html[link do źródła przepisu]

== Składniki
* 3 łyżki (30 g) mąki pszennej
* 1 jajko
* 2 łyżki mleka
* 300 g cukinii (1 mała)
* 1/4 niedużej cebuli
* 1 łyżka koperku lub świeżych ziół lub natki pietruszki
* olej roślinny lub oliwa

|
== Przygotowanie
Mąkę wsypać do miski, wymieszać ze szczyptą soli, świeżo zmielonym pieprzem, a następnie z roztrzepanym jajkiem (najlepiej za pomocą rózgi). Wlać mleko i wymieszać na jednolite ciasto.

Odważyć potrzebną ilość cukinii (nie więcej!). Umyć, osuszyć, odciąć końce i zetrzeć na dużych oczkach tarki. Tak samo zetrzeć cebulę. Cukinię i cebulę po starciu delikatnie odcisnąć w dłoniach z nadmiaru wody.

Cukinię i cebulę oraz posiekaną zieleninę dodać do ciasta i wymieszać łyżką.

Rozgrzać patelnię z olejem lub oliwą. Nakładać po łyżce (nie więcej!) masy i smażyć placuszki przez około 2 - 3 minuty. Gdy będą ładnie zrumienione, przewrócić na drugą stronę i smażyć jeszcze przez około 2 minuty.

|===

[.text-center]
== Zdjęcia
