= Potrawka z udka kurczaka z warzywami, ryż

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 35 min
* 4 porcje
* https://www.przyslijprzepis.pl/przepis/potrawka-z-kurczaka-i-warzyw-1[link do źródła przepisu]

== Składniki
* 500 g udek z kurczaka (bez skóry i kości; można zastąpić je piersią),
* 2 małe marchewki,
* 2 małe pietruszki,
* ćwierć małego selera,
* duża cebula,
* 2 ząbki czosnku,
* pół małego brokułu,
* kilka łyżek mrożonego groszku,
* 1/3 szklanki pokrojonej w drobną kostkę dyni (użyłam mrożonej),
* ok. 2 szklanek bulionu drobiowego, jarzynowego lub wody,
* opcjonalnie 1-2 łyżki śmietanki 18%,
* opcjonalnie 1-2 łyżki mąki do zagęszczenia sosu,
* przyprawy do smaku: sól, pieprz, zioła prowansalskie, słodka papryka i/lub ostra papryka
* świeże zioła do posypania potrawy (natka pietruszki lub/i koperek)

|
== Przygotowanie
Pokroić mięso w kostkę, doprawić solą, pieprzem i ziołami prowansalskimi. Obsmażyć na małej ilości tłuszczu do lekkiego zarumienienia, odłożyć. Na patelnię po mięsie wrzucić plastry marchewki, seler i pietruszkę pokrojone w kostkę oraz drobno posiekaną cebulę. Smażyć kilka minut, dodać drobno posiekany czosnek. Po chwili dodać mięso, zalać całość płynem (tyle, by lekko zakrył składniki), doprawić i dusić na małym ogniu ok. 20-30 minut (lub do czasu, aż mięso i warzywa będą miękkie). W zależności od tego, jak miękki ma być brokuł, dodać go na początku lub w połowie duszenia. Na 5 minut przed końcem dodać groszek oraz dynię. Aby sos był gęstszy, można dodać mąkę rozmieszaną w małej ilości wody lub/i śmietanki. Posypać świeżymi ziołami. Podawać z kaszą, makaronem lub ryżem.

|===

[.text-center]
== Zdjęcia
