= Pstrąg pieczony w całości +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 1 h
* 4 porcje
* https://www.alemeksyk.eu/smaki-swiata/item/712-pstrag-pieczony-z-maslem-i-cytryna-przepis-tescia.html[link do źródła przepisu]

== Składniki
* 4 średnie wypatroszone pstrągi (tęczowy lub łososiowy)
* 2 cytryny
* 1 limonka
* kilka ząbków czosnku
* sól
* pieprz
* 1/4 kostki masła (50 g)
* 4 ząbki czosnku
* świeża kolendra
* świeża pietruszka
* sól i pieprz

|
== Przygotowanie
Pstrągi dokładnie patroszymy, czyścimy i myjemy. Generalnie są dwie szkoły czyszczenia, jedni rybę skrobią z łusek, inni natomiast jedynie czyszczą wierzchnią warstwę śluzu, którym powleczone są łuski. My wykonujemy jedynie tę drugą czynność... wychodzimy z założenia, że i tak przecież zjada się samo mieso, a skóra wędruje do kosza.

Suszymy papierowymi ręcznikami. Robimy kilka nacięć na jednym boku pstrąga.


Solimy i pieprzymy do smaku, zarówno z wierzchu (głównie nacięcia, w tym miejscu mięso najlepiej wchłonie sól) jak i w środku.

Wkładamy do środka po jednym nieobranym, jedynie zgniecionym ząbku czosnku, lepiej uwolni swój aromat.

Cytrynę i limonkę kroimy na plasterki i wkładamy do każdego pstrąga po kilka plasterków.


Dokładamy świeżą pietruszkę lub kolendrę, w zależności co kto lubi. My najczęściej używamy kolendry ogrodowej, jest znacznie intensywniejsza w smaku i aromacie.

Na koniec skrapiamy sokiem z cytryny.

W brzuszki wkładamy również kawałeczki masła. Na wierzch ryb, w nacięcia sypiemy odrobine pieprzu i również wkładamy małe kawałeczki masła. Resztą roztopionego masła smarujemy skórę.

Pstrągi układamy na blaszce wyłożonej papierem do pieczenia, wkładamy do piekarnika nagrzanego do 200 stopni i pieczemy około 35 - 40 minut.

Pstrąga można jeść samego, ale jednak preferujemy bardziej klasyczną polską wersję, z ziemniaczkami i duszona cebulką :)

|===

[.text-center]
== Zdjęcia
