= Pstrg pieczony w caoci  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: 1 h
* 4 porcje
* https://www.alemeksyk.eu/smaki-swiata/item/712-pstrag-pieczony-z-maslem-i-cytryna-przepis-tescia.html[link do 藕r贸da przepisu]

== Skadniki
* 4 rednie wypatroszone pstrgi (tczowy lub ososiowy)
* 2 cytryny
* 1 limonka
* kilka zbk贸w czosnku
* s贸l
* pieprz
* 1/4 kostki masa (50 g)
* 4 zbki czosnku
* wie偶a kolendra
* wie偶a pietruszka
* s贸l i pieprz

|
== Przygotowanie
Pstrgi dokadnie patroszymy, czycimy i myjemy. Generalnie s dwie szkoy czyszczenia, jedni ryb skrobi z usek, inni natomiast jedynie czyszcz wierzchni warstw luzu, kt贸rym powleczone s uski. My wykonujemy jedynie t drug czynno... wychodzimy z zao偶enia, 偶e i tak przecie偶 zjada si samo mieso, a sk贸ra wdruje do kosza.

Suszymy papierowymi rcznikami. Robimy kilka naci na jednym boku pstrga.


Solimy i pieprzymy do smaku, zar贸wno z wierzchu (g贸wnie nacicia, w tym miejscu miso najlepiej wchonie s贸l) jak i w rodku.

Wkadamy do rodka po jednym nieobranym, jedynie zgniecionym zbku czosnku, lepiej uwolni sw贸j aromat.

Cytryn i limonk kroimy na plasterki i wkadamy do ka偶dego pstrga po kilka plasterk贸w.


Dokadamy wie偶 pietruszk lub kolendr, w zale偶noci co kto lubi. My najczciej u偶ywamy kolendry ogrodowej, jest znacznie intensywniejsza w smaku i aromacie.

Na koniec skrapiamy sokiem z cytryny.

W brzuszki wkadamy r贸wnie偶 kawaeczki masa. Na wierzch ryb, w nacicia sypiemy odrobine pieprzu i r贸wnie偶 wkadamy mae kawaeczki masa. Reszt roztopionego masa smarujemy sk贸r.

Pstrgi ukadamy na blaszce wyo偶onej papierem do pieczenia, wkadamy do piekarnika nagrzanego do 200 stopni i pieczemy okoo 35 - 40 minut.

Pstrga mo偶na je samego, ale jednak preferujemy bardziej klasyczn polsk wersj, z ziemniaczkami i duszona cebulk :)

|===

[.text-center]
== Zdjcia
