= Pulpety w sosie koperkowym

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 1 h
* 4 porcje
* https://www.kwestiasmaku.com/kuchnia_polska/pulpeciki_w_sosie_koperkowym/przepis.html[link do źródła przepisu]

== Składniki
* 1 mała czerstwa bułka (np. kajzerka)
* mleko lub woda do namoczenia bułki
* 500 g mięsa mielonego*
* 1 średnia cebula
* 1 jajko
* 1 łyżeczka soli + 1/2 łyżeczki mielonego pieprzu
* mąka pszenna do obtoczenia
* 2 łyżki oleju
* 500 ml wody
* 1 średnia marchewka
* 1 mała pietruszka
* 1 łyżeczka masła
* 1 - 2 łyżeczki mąki
* 1 łyżka posiekanego koperku

|
== Przygotowanie
Bułkę zalać mlekiem lub wodą, odstawić do namoczenia na około 15 minut. Do większej miski włożyć zmielone mięso, dodać obraną i startą na tarce (o dużych oczkach) cebulę, jajko, sól i pieprz oraz odciśniętą bułkę. Wszystko dobrze wymieszać. Uformować niewielkie kulki, otoczyć je w mące.

Wywar: w szerokim, większym garnku zagotować wodę, dodać obraną i startą na tarce marchewkę oraz pietruszkę, lekko posolić i dodać masło.

Pulpeciki krótko podsmażyć na oleju, a po obsmażeniu wkładać do wrzącego wywaru.

Zmniejszyć ogień do minimum i gotować powoli, na małym ogniu, pod przykryciem, przez około 20 minut.

W razie potrzeby można zagęścić sos mąką, którą przesiewamy przez sitko, bezpośrednio do wywaru. Możemy też rozprowadzić mąkę najpierw z 2 łyżkami wody, później dodać kilka łyżek wywaru i po wymieszaniu wszystko wlać do garnka z pulpecikami, następnie zagotować.

Na koniec dodać posiekany koperek i odstawić z ognia.

|===

[.text-center]
== Zdjęcia
