= Pęczotto z burakami i kozim serem +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 2 h
* 2 porcje
* https://kuchnialidla.pl/peczotto-z-burakiem-i-kozim-serem[link do źródła przepisu]

== Składniki
* wino białe - 100 ml
* bulion warzywny - 700 ml
* cebula - 1 szt.
* ząbek czosnku - 2 szt.
* kasza pęczak - 250 g
* burak - 2 szt.
* oliwa z oliwek - 2 łyżki
* ser kozi - 150 g
* natka pietruszki - 2 łyżki
|
== Przygotowanie
Umyte buraki w skórkach układamy na blasze wyłożonej papierem do pieczenia. Pieczemy ok. 40-60 minut (do miękkości) w piekarniku rozgrzanym do 180°C. Studzimy i obieramy.

Cebulę pokrojoną w kostkę smażymy na oliwie na rozgrzanej patelni. Gdy się zeszkli, dodajemy czosnek pokrojony w plasterki. Smażymy ok. 3 minuty.

Dodajemy surową kaszę pęczak i prażymy chwilę, mieszając, tak, by oliwa w całości pokryła ziarna. Dodajemy buraki starte na tarce o drobnych oczkach. Dokładnie mieszamy.

Całość zalewamy winem. Odparowujemy, mieszając.

Gdy wino odparuje, zalewamy kaszę pierwszą porcją bulionu. Gotujemy, cały czas mieszając, aż płyn odparuje. Czynność powtarzamy, aż pęczak będzie ugotowany al dente - ten etap powinien trwać ok. 20 minut.

Gotowe pęczotto przekładamy na talerze. Na wierzchu układamy kawałki koziego sera (lub sera feta) i listki ulubionych, świeżych ziół (np. pietruszki lub lubczyku).

|===

[.text-center]
== Zdjęcia
