= Quesadilla  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++ 3

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 35 min
* 4 porcje
* https://www.alemeksyk.eu/przepisy-meksykanskie/na-bazie-tortilli/quesadillas/item/607-quesadilla-z-kurczakiem-z-chipotle-w-sosie-adobo-przepis.html[link do źródła przepisu]

== Składniki
* 4 tortille pszenne (średnica ok 15 cm)
* 1 pierś z kurczaka
* 2 papryczki chipotle w sosie adobo (z puszki)
* 2 łyżki stołowe soku z pomarańczy
* 1 łyżka stołowa oliwy z oliwek
* pęczek kolendry
* 1/2 cebuli czerwonej
* kukurydza z puszki

|
== Przygotowanie
Na początku zabieramy się za przygotowanie piersi z kurczaka. Kroimy go w drobną kosteczkę i przekładamy do miseczki. Wystarczy, że pokroimy w kosteczkę o wielkości 1cm x 1cm.

Przekładamy do miseczki.

Następnie wyjmujemy z puszki papryczki chipotle (są to wędzone papryczki jalapeno) i kroimy je bardzo drobno. Tak pokrojone papryczki przekładamy do kurczaka. Do nadania większej głębi wędzonego smaku możemy dodać łyżeczkę sosu adobo, w którym marynują się chipotle. 

Dodajemy odrobinę oliwy z oliwek (ok. 1 stołowej łyżki).

Limonkę kroimy na pół i wyciskamy sok, którym skrapiamy kurczaka.

Podobnie robimy z sokiem z pomarańczy. Do tej ilości kurczaka wystarczą 2 łyżki stołowe soku. Jeśli nie mamy pod ręką świeżego cytrusa, możemy spokojnie użyć soku z kartonu. Pozwoli to nadać mięsu przyjemnego cytrusowego smaku.

Wszystko ze sobą mieszamy.

Tak przygotowany mix przekładamy na rozgrzaną patelnię.

Jak kurczak zacznie nam się smażyć, dodajemy jeszcze niecałą łyżeczkę oregano i wszystko ze sobą podsmażamy od czasu do czasu mieszając.

Pamiętajcie aby patelnia była bardzo rozgrzana inaczej kurczak nam się nie usmaży, a poddusi w płynie który z niego wyjdzie.

W czasie jak kurczak nam się smaży, możemy zabrać się za przygotowanie pozostałych składników do quesadilli. Do tego będzie nam potrzebny ser cheddar, który ucieramy na dużych oczkach tarki.

Kroimy cebulę w drobna kostkę.

Szatkujemy świeżą kolendrę.

Tak przygotowane składniki możemy zacząć rozkładać na tortillach. Tym razem użyliśmy niewielkich tortilli, o średnicy ok. 15 cm.

Na początek układamy na jednej połowie placka starty ser. Drugą połową tortilli będziemy przykrywać, więc na niej nic nie umieszczamy.

Na ser rozkładamy w kolejności usmażonego kurczaka, kukurydzę i kolendrę. Na koniec ponownie posypujemy wszystko serem, dzięki czemu nadzienie będzie spójne i nie będzie się rozsypywać.

Przykrywany drugą częścią tortilli.

Tak przygotowane quesadillas są gotowe do smażenia/grillowania. My używamy do tego patelni grillowej, dzięki czemu uzyskujemy dodatkowy super efekt opalonego rusztu.

Ile należy podpiekać tortillę? To wszystko zależy od temperatury rusztu. Musicie zwyczajnie obserwować stopień przypieczenia tortilli oraz trzeba pamiętać o tym aby ser się rozpuścił.

Pamiętajcie, żeby po tym czasie jak tortilla się przyrumieni/podpiecze trzeba ja przełożyć na drugą stronę i powtórzyć czynność.

Tak przygotowane quesadillas można przeciąć na pół (w trójkąty) lub podawać w całości z dodatkiem sals.

|===

[.text-center]
== Zdjęcia
