= Quesadilla  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++ 2

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 35 min
* 4 porcje
* https://www.alemeksyk.eu/przepisy-meksykanskie/na-bazie-tortilli/quesadillas/item/773-chrupiaca-quesadilla-z-szarpanym-kurczakiem-w-pikantnym-sosie-pomidorowym-adobo.html[link do źródła przepisu]

== Składniki
* ser cheddar (ok. 300 g)
* 1 pierś z kurczaka
* 1 świeży pomidor (może być ze skórką)
* 1 mała cebula czerwona (opcjonalnie można użyć białą)
* ząbek czosnku
* 2 łyżeczki marynaty z papryczek chipotle adobo (opcjonalnie można użyć suszonej wędzonej ostrej papryki - wtedy 1 łyżeczka)
* tortille kukurydziane
* masło klarowane (opcjonalnie oliwa z oliwek)
* świeża kolendra
* pół łyżeczki mielonych nasion kolendry,
* pół łyżeczki mielonego kminu rzymskiego
* pół łyżeczki wędzonej mielonej papryki
* sól i pieprz

|
== Przygotowanie
Na początek gotujemy pierś kurczaka. Do garnka wkładamy pierś kurczaka i wlewamy wodę w ilości tak aby zakryła mięso. Do smaku możemy dodać dwa - trzy nasiona ziela angielskiego i listek laurowy oraz sól i pieprz do smaku. Gotujemy około 30 minut na średnim ogniu. Po tym czasie mięso wyjmujemy i przekładamy na deskę do ostygnięcia.

W tym czasie przygotowujemy sos pomidorowy, który nada kurczakowi smaku i aromatu.

Pomidora kroimy na mniejsze części. Łatwiej i szybciej się zblenduje. Podobnie robimy z cebulą i czosnkiem. Wszystko wrzucamy do blendera. Na koniec dodajemy marynatę adobo z papryczek chipotle. Bardziej odważni mogą dodać całą papryczkę chipotle, ale trzeba się liczyć z tym, że danie będzie dość pikantne. Takie papryczki można dostać w większości hipermarketów.

Blendujemy wszystko do uzyskania jednolitej konsystencji.

Jak już mamy przygotowany sos, a kurczak nam się wystudził na tyle, że można go rozrywać palcami bez ryzyka poparzenia, rwiemy go na mniejsze części. Wystarczy do tego zwykły widelec i palce.

Teraz rozgrzewamy patelnię, a na niej łyżkę oliwy z oliwek.

Wrzucamy przyprawy: kolendrę, kmin, sól, pieprz i wędzoną paprykę. Wszystko lekko podsmażamy dla wydobycia głębszego smaku.

Teraz dodajemy mięso kurczaka i lekko podsmażamy przez około 3 minuty, od czasu do czasu mieszając i uważając aby mięso się nie przypaliło.

Następnie dolewamy zawartość blendera. I wszystko razem smażymy do czasu, aż cały płyn się zredukuje, a kurczak uzyska czerwonawy kolor.

Gdy kurczaka mamy już gotowego, możemy go zdjąć z ognia do ostygnięcia.

Teraz należy zabrać się za przygotowywanie pozostałych składników do quesadilli.

Ser ucieramy na tarce z grubymi oczkami. Cebulę kroimy w piórka. Świeżą kolendrę szatkujemy.

quesadilla kurczak chipotle 11

W tym czasie można również przygotować salsy, ale spokojnie można to również zrobić na samym początku, jeszcze na długo przed przygotowywaniem quesadilli.

Bierzemy teraz placek tortilli. Generalnie są dwa sposoby przygotowywania quesadilli.

Pierwszy sposób jest taki, że na całym placku rozkładamy wszystkie składniki i przykrywamy drugim plackiem tortilli. Trzeba się jednak liczyć z tym, że przy odwracaniu mogą pojawić pewne trudności, ponieważ część farszu może wlecieć.

Jest jeszcze drugi sposób, który bardziej preferujemy i stosujemy najczęściej. Na połowie tortilli rozkładamy farsz, najpierw ser, na ser kładziemy mięso, cebulę, posypujemy świeżą kolendrą, ponownie posypujemy serem i na koniec składamy tortillę na pół. O wiele łatwiej się przewraca na patelni, bez ryzyka wypadnięcia nadzienia.

Na patelni rozgrzewamy odrobinę masła klarowane i układamy na nim quesadillę. Przysmażamy do momentu, aż tortilla uzyska rumiany kolor. Uważajcie aby jej nie przypalić.

Następnie odwracamy i przysmażamy z drugiej strony również do momentu aż tortilla stanie się rumiana.

Zdejmujemy z patelni i rozkładamy na desce do krojenia. Quesadillę kroimy na trójkąty, tak jak robi się z to z pizzą.

|===

[.text-center]
== Zdjęcia
