= Quesadilla +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 45 min
* 4 porcje
* https://www.kwestiasmaku.com/przepis/quesadilla-z-kurczakiem-i-warzywami[link do źródła przepisu]

== Składniki
* 300 g filetu z kurczaka
* 2 łyżki oliwy
* 1 cebula
* 1 papryka
* mała puszka (200 g) kukurydzy
* 300 g tartej mozzarelli (twardszej i żółtej, nie białej z zalewy)
* 2 łyżeczki masła
* 4 duże tortille (śr. 25 cm)
* 2 ząbki czosnku, starte
* 1/2 łyżeczki ostrej papryki
* 1 łyżeczka słodkiej papryki
* 1 łyżeczka kuminu
* 1/2 łyżeczki suszonego oregano
* 1 łyżeczka płatków chili

|
== Przygotowanie
Kurczaka pokroić na wąskie paski dł. ok. 2 cm. Doprawić solą, pieprzem oraz wszystkimi przyprawami. Polać łyżką oleju roślinnego i dokładnie wymieszać, odstawić.

Cebulę pokroić w piórka, paprykę - podobnie jak kurczaka - na wąskie paski dł. ok. 2 cm. Doprawić solą i zeszklić na patelni na łyżce oleju, odłożyć na talerz.

Na rozgrzaną patelnię włożyć kurczaka i obsmażyć przez ok. 4 minuty. Przełożyć na oddzielny talerz.

Na dużej patelni rozgrzać i rozprowadzić łyżeczkę masła. Położyć placek tortilli i wyłożyć na niego połowę wszystkich składników farszu - kurczaka (bez soków z mięsa), podsmażone warzywa, kukurydzę i tarty ser. Przykryć drugim plackiem tortilli i podsmażać na małym ogniu ok. 2 minuty, aż tortilla na spodzie się zrumieni.

Podgrzaną z jednej strony quesadillę przełożyć na drugą stronę* i ponownie podsmażyć na maśle do zrumienienia. Powtórzyć z pozostałymi dwoma plackami tortilli i drugą połową farszu.

Podgrzane quesadille kroić nożem na kawałki jak pizzę, podawać z wybranymi dodatkami.

|===

[.text-center]
== Zdjęcia
