= Quesadilla 2  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: 35 min
* 4 porcje
* https://www.alemeksyk.eu/przepisy-meksykanskie/na-bazie-tortilli/quesadillas/item/773-chrupiaca-quesadilla-z-szarpanym-kurczakiem-w-pikantnym-sosie-pomidorowym-adobo.html[link do 藕r贸da przepisu]

== Skadniki
* ser cheddar (ok. 300 g)
* 1 pier z kurczaka
* 1 wie偶y pomidor (mo偶e by ze sk贸rk)
* 1 maa cebula czerwona (opcjonalnie mo偶na u偶y bia)
* zbek czosnku
* 2 y偶eczki marynaty z papryczek chipotle adobo (opcjonalnie mo偶na u偶y suszonej wdzonej ostrej papryki - wtedy 1 y偶eczka)
* tortille kukurydziane
* maso klarowane (opcjonalnie oliwa z oliwek)
* wie偶a kolendra
* p贸 y偶eczki mielonych nasion kolendry,
* p贸 y偶eczki mielonego kminu rzymskiego
* p贸 y偶eczki wdzonej mielonej papryki
* s贸l i pieprz

|
== Przygotowanie
Na pocztek gotujemy pier kurczaka. Do garnka wkadamy pier kurczaka i wlewamy wod w iloci tak aby zakrya miso. Do smaku mo偶emy doda dwa - trzy nasiona ziela angielskiego i listek laurowy oraz s贸l i pieprz do smaku. Gotujemy okoo 30 minut na rednim ogniu. Po tym czasie miso wyjmujemy i przekadamy na desk do ostygnicia.

W tym czasie przygotowujemy sos pomidorowy, kt贸ry nada kurczakowi smaku i aromatu.

Pomidora kroimy na mniejsze czci. atwiej i szybciej si zblenduje. Podobnie robimy z cebul i czosnkiem. Wszystko wrzucamy do blendera. Na koniec dodajemy marynat adobo z papryczek chipotle. Bardziej odwa偶ni mog doda ca papryczk chipotle, ale trzeba si liczy z tym, 偶e danie bdzie do pikantne. Takie papryczki mo偶na dosta w wikszoci hipermarket贸w.

Blendujemy wszystko do uzyskania jednolitej konsystencji.

Jak ju偶 mamy przygotowany sos, a kurczak nam si wystudzi na tyle, 偶e mo偶na go rozrywa palcami bez ryzyka poparzenia, rwiemy go na mniejsze czci. Wystarczy do tego zwyky widelec i palce.

Teraz rozgrzewamy patelni, a na niej y偶k oliwy z oliwek.

Wrzucamy przyprawy: kolendr, kmin, s贸l, pieprz i wdzon papryk. Wszystko lekko podsma偶amy dla wydobycia gbszego smaku.

Teraz dodajemy miso kurczaka i lekko podsma偶amy przez okoo 3 minuty, od czasu do czasu mieszajc i uwa偶ajc aby miso si nie przypalio.

Nastpnie dolewamy zawarto blendera. I wszystko razem sma偶ymy do czasu, a偶 cay pyn si zredukuje, a kurczak uzyska czerwonawy kolor.

Gdy kurczaka mamy ju偶 gotowego, mo偶emy go zdj z ognia do ostygnicia.

Teraz nale偶y zabra si za przygotowywanie pozostaych skadnik贸w do quesadilli.

Ser ucieramy na tarce z grubymi oczkami. Cebul kroimy w pi贸rka. wie偶 kolendr szatkujemy.

quesadilla kurczak chipotle 11

W tym czasie mo偶na r贸wnie偶 przygotowa salsy, ale spokojnie mo偶na to r贸wnie偶 zrobi na samym pocztku, jeszcze na dugo przed przygotowywaniem quesadilli.

Bierzemy teraz placek tortilli. Generalnie s dwa sposoby przygotowywania quesadilli.

Pierwszy spos贸b jest taki, 偶e na caym placku rozkadamy wszystkie skadniki i przykrywamy drugim plackiem tortilli. Trzeba si jednak liczy z tym, 偶e przy odwracaniu mog pojawi pewne trudnoci, poniewa偶 cz farszu mo偶e wlecie.

Jest jeszcze drugi spos贸b, kt贸ry bardziej preferujemy i stosujemy najczciej. Na poowie tortilli rozkadamy farsz, najpierw ser, na ser kadziemy miso, cebul, posypujemy wie偶 kolendr, ponownie posypujemy serem i na koniec skadamy tortill na p贸. O wiele atwiej si przewraca na patelni, bez ryzyka wypadnicia nadzienia.

Na patelni rozgrzewamy odrobin masa klarowane i ukadamy na nim quesadill. Przysma偶amy do momentu, a偶 tortilla uzyska rumiany kolor. Uwa偶ajcie aby jej nie przypali.

Nastpnie odwracamy i przysma偶amy z drugiej strony r贸wnie偶 do momentu a偶 tortilla stanie si rumiana.

Zdejmujemy z patelni i rozkadamy na desce do krojenia. Quesadill kroimy na tr贸jkty, tak jak robi si z to z pizz.

|===

[.text-center]
== Zdjcia
