= Quesadilla 4

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 35 min
* 4 porcje
* https://www.alemeksyk.eu/przepisy-meksykanskie/na-bazie-tortilli/quesadillas/item/831-wegetarianska-quesadilla-z-pieczarkami-i-czarna-fasola-przepis.html[link do źródła przepisu]

== Składniki
* tortille kukurydziane rozm. 18 cm
* 1 czerwona cebula lub biała ze szczypiorem
* 1/2 puszki czarnej fasoli
* 200 g pieczarek
* ser cheddar
* 1 łyżka masła klarowanego
* salsa pomidorowa

|
== Przygotowanie
Przygotowanie quesadilli rozpoczynamy od podsmażenia pieczarek. Najpierw je obieramy i tniemy na plasterki. Następnie rozgrzewamy na patelni łyżkę masła klarowanego (można również użyć zwykłego) i wrzucamy pokrojone pieczarki. Smażymy na bardzo mocno rozgrzanej patelni. Od czasu do czasu mieszamy, ale pozwalamy, żeby pieczarki lekko się nawet przyprażyły.

Zdejmujemy pieczarki z patelni i pozostawiamy do ostygnięcia.

W międzyczasie przygotowujemy resztę składników. Fasolę z puszki warto odsączyć z płynów, a nawet dobrze ją lekko przepłukać. Można do tego użyć zwykłego sitka i bieżącej wody.

Ser ucieramy na grubych oczkach tarki.

Cebulę kroimy w piórka.

Szczypior w kawałki grubości 1 cm. Warto używać grubego szczypioru, jeśli użyjecie szczypiorku cienkiego nic wielkiego się nie stanie, efekt smakowy będzie zachowany, jedynie zostanie zaburzony efekt wizualny. Gruby szczypior znacznie lepiej się prezentuje w quesadilli.

Jak już mamy przygotowane wszystkie składniki quesadilli, zabieramy się za składanie.

Na połowę tortilli układamy starty ser, następnie rozrzucany na nim pieczarki, trochę fasoli, trochę szczypioru i cebulę pokrojoną w piórka.

Następnie posypujemy kolejną warstwą sera i składamy tortille na pół. Tak samo postępujemy z resztą tortilli.

Rozgrzewamy patelnię, a na niej łyżeczkę masła klarowanego. Można nie używać masła, można układać quesadillę na suchej patelni, ale masło sprawi, że tortilla zyska ładniejszy rumiany kolor, będzie bardziej chrupiąca i zyska na walorach smakowych...

Quesadillę smażymy z obu stron po około 1,5 do 2 minut z każdej strony. Wszystko zależy od stopnia nagrzania patelni. Musicie jednak obserwować czy tortilla zyskała ładny przypieczony kolor (nie spalony) i czy ser w środku się wystarczająco roztopił.

Zdejmujemy z patelni i dajemy chwilę odpocząć na desce (około 1 minuty) aby ser związał wszystkie składni i przy krojeniu quesadilli, jej zawartość się nie rozsypywała.

Tak przygotowana quesadilla jest gotowa do podania.

Można jeszcze przeciąć na pół lub w trójkąciki. Podawać z salsami np. pomidorową. Zobacz jak przygotować salsę pomidorową.

|===

[.text-center]
== Zdjęcia
