= Quinotto z czerwon fasol i papryk  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 50 minut
* 2 porcje
* https://drive.google.com/file/d/1Z9ZqAq8x4MTHByM5vwEB_yQHJAp-0u3r/view?usp=sharing[link do 藕r贸da przepisu]

== Skadniki

* komosa ry偶owa - niecae 2/3 szklanki (120 g)
* fasola czerwona konserwowa - 1 puszka (260 g)
* papryka 偶贸ta - 1/2 sztuki (70 g)
* papryka zielona - 1/2 sztuki (70 g)
* papryka czerwona - 1/2 sztuki (70 g)
* czerwona cebula - 1/2 sztuki (50 g)
* bulion warzywny lub woda - 1 szklanka (250 ml)
* oliwa z oliwek - 1 y偶ka (10 g)
* przyprawy: 1 zabek czosnku, 1/2 y偶eczki papryki sodkiej, 1/2 y偶eczki kminu rzymskiego mielonego, 1/4 y偶eczki kolendry mielonej, chili, s贸l i pieprz czerny do smaku
* kolendra wie偶a lub natka pietruszki do podania

|
== Przygotowanie

Fasol odcedzamy. Na rozgrzanej oliwie szklimy pokrojony w cienkie plasterki czosnek i posiekan wn dosy drobn kostk cebul. Dorzucamy pokrojone w kostk papryki. Sma偶ymy przez 2-4 minuty. Po tym czasie na patelni wsypujemy komose ry偶ow (u偶yam tr贸jkolorowej) i pra偶ymy przez minut. Dodajemy przyprawy, podlewamy bulionem lub wod i dusimy pod przykryciem okoo 35 minut na bardzo maym ogniu. Dokadamy fasol i mieszamy. Na koniec danie posypujemy posiekan kolendr lub natk pietruszki. 

|===

[.text-center]
== Zdjcia

