= Quinotto z czerwoną fasolą i papryką

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 50 min
* 2 porcje
* https://drive.google.com/file/d/1Z9ZqAq8x4MTHByM5vwEB_yQHJAp-0u3r/view?usp=sharing[link do źródła przepisu]

== Składniki
* komosa ryżowa - niecałe 2/3 szklanki (120 g)
* fasola czerwona konserwowa - 1 puszka (260 g)
* papryka żółta - 1/2 sztuki (70 g)
* papryka zielona - 1/2 sztuki (70 g)
* papryka czerwona - 1/2 sztuki (70 g)
* czerwona cebula - 1/2 sztuki (50 g)
* bulion warzywny lub woda - 1 szklanka (250 ml)
* oliwa z oliwek - 1 łyżka (10 g)
* przyprawy: 1 zabek czosnku, 1/2 łyżeczki papryki słodkiej, 1/2 łyżeczki kminu rzymskiego mielonego, 1/4 łyżeczki kolendry mielonej, chili, sól i pieprz czerny do smaku
* kolendra świeża lub natka pietruszki do podania

|
== Przygotowanie
Fasolę odcedzamy. Na rozgrzanej oliwie szklimy pokrojony w cienkie plasterki czosnek i posiekaną wn dosyć drobną kostkę cebulę. Dorzucamy pokrojone w kostkę papryki. Smażymy przez 2-4 minuty. Po tym czasie na patelnię wsypujemy komose ryżową (użyłam trójkolorowej) i prażymy przez minutę. Dodajemy przyprawy, podlewamy bulionem lub wodą i dusimy pod przykryciem około 35 minut na bardzo małym ogniu. Dokładamy fasolę i mieszamy. Na koniec danie posypujemy posiekaną kolendrą lub natką pietruszki. 

== Zdjęcia
|===
