= Ratatuj

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 45 min
* 4 porcje
* https://przepisyjoli.com/2017/08/ratatuj[link do źródła przepisu]

== Składniki
* 2 cukinie (u mnie zielona i żółta)
* 2 małe bakłażany lub jeden większy
* 2 duże pomidory
* 1 duża cebula
* 1 ząbek czosnku
* 3 łyżki oleju z ryżu o smaku czosnku SoRiso

Sos:

* 500 ml passaty pomidorowej
* 2 łyżki oleju z ryżu o smaku czosnku SoRiso
* po ½ łyżeczki soli, pieprzu, słodkiej papryki, bazylii, oregano

|
== Przygotowanie
Warzywa umyć, osuszyć i pokroić w bardzo cienkie plasterki (najłatwiej jest użyć tarki do jarzyn). Plastry bakłażana posolić i odstawić na około 30 minut, po tym czasie je opłukać i osuszyć papierowym ręcznikiem.
Passatę pomidorową wlać do miseczki, dodać olej z ryżu o smaku czosnku SoRiso, przyprawy i wymieszać.

Na dno naczynia do zapiekania (u mnie okrągła blaszka o średnicy 30 cm) wylać sos pomidorowy, na sosie układać naprzemiennie plasterki warzyw, tak żeby zachodziły na siebie. Wierzch warzyw skropić 3 łyżkami oleju z ryżu o smaku czosnku SoRiso. Naczynie do zapiekania przykryć (przykrywką lub folią aluminiową) i wstawić do piekarnika nagrzanego do 180 stopni (grzanie góra i dół) i piec 45-50 min. 10 minut przed końcem pieczenia zdjąć przykrywkę z naczynia.
Ratatuj podawać od razu po upieczeniu.

|===

[.text-center]
== Zdjęcia
