= Risotto z szpinakiem i krewetkami +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 30 min
* 4 porcje
* https://www.doradcasmaku.pl/przepis-risotto-ze-szpinakiem-i-krewetkami-411771[link do źródła przepisu]

== Składniki
* szalotka 3 szt.
* oliwa 3 łyżki
* masło 82% 140 g
* ryż 300 g
* sól morska jodowana drobnoziarnista Prymat 1 i ½ łyżeczki
* pieprz czarny mielony Prymat 1 szczypta
* wino białe wytrawne 200 ml
* bulion 1 i ½ l
* mrożony szpinak 200 g
* czosnek suszony Prymat ½ łyżeczki
* oregano suszone Prymat ½ łyżeczki
* krewetki mrożone 100 g
* sól do smaku
* parmezan starty 150 g
* orzeszki pinii 50 g

|
== Przygotowanie
Szalotki posiekaj w drobną kostkę i zeszklij na oliwie i 20 g masła.

Dodaj suchy ryż i smaż przez ok. 2 minuty, często mieszając, aż do zmiany koloru.

Dopraw solą i pieprzem. Dodaj białe wino i chwilę podgotuj.

Dodaj tyle bulionu, by nieznacznie przykrył ryż i zamieszaj. Kiedy część płynu wyparuje, stopniowo dodawaj więcej, cały czas mieszając. Gotuj przez ok. 15 minut.

Dodaj mrożony szpinak, dopraw suszonym czosnkiem, oregano i wymieszaj.

Na patelni rozpuść 20 g masła. Dodaj krewetki, dopraw solą i smaż przez ok. 3 minuty.

Do risotto dodaj 150 g startego parmezanu i 100 g masła. Całość dobrze wymieszaj.

Gotowe danie udekoruj krewetkami i orzeszkami pinii.

|===

[.text-center]
== Zdjęcia
