= Roladki z kurczaka z serem, pieczarkami pieczone w boczku +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 45 min
* 3 porcje
* https://www.kwestiasmaku.com/przepis/roladki-z-kurczaka-z-pieczarkami-i-serem-pieczone-w-boczku[link do źródła przepisu]

== Składniki
* 3 pojedyncze filety z kurczaka
* 1 łyżeczka przyprawy do kurczaka np. gyros
* ok. 150 g wędzonego boczku (cienko pokrojony, paczkowany)
* 150 g pieczarek
* 1/2 cebuli
* 1 łyżka masła
* 1 i 1/2 łyżki musztardy francuskiej (ziarnistej)
* 70 g tartego sera żółtego np. mozzarelli
* 1 łyżka oliwy extra
* 1/2 cukinii

|
== Przygotowanie
Filety oczyścić z kostek i chrząstek jeśli takie się znajdują. Naciąć każdy filet z boku tworząc głębszą kieszonkę na nadzienie. Doprawić solą, pieprzem i natrzeć przyprawą.

Pieczarki umyć, osuszyć i pokroić najpierw na 4 części, następnie na plasterki. Wrzucić na patelnię i mieszając co chwilę smażyć do czasu aż całkowicie odparują. Gdy na patelni nie będzie już wody, dodać łyżkę masła oraz pokrojoną w kosteczkę cebulę. Dalej smażyć aż pieczarki i cebula zaczną się rumienić. W międzyczasie doprawić solą i pieprzem.

W kieszonki kurczaka nakładać tarty ser, pieczarki oraz po pół łyżeczki musztardy francuskiej. Złączyć nacięcie kurczaka i zawinąć roladki w plasterki boczku. Ułożyć je łączeniem do góry w naczyniu żaroodpornym posmarowanym oliwą. Polać łyżeczką oliwy każdą roladkę.

Piekarnik nagrzać do 200 stopni C. Cukinię pokroić w kostkę, doprawić solą, pieprzem, wymieszać z łyżeczką oliwy i łyżeczką musztardy francuskiej. Dodać do naczynia z kurczakiem i wstawić do nagrzanego piekarnika. Piec przez 25 minut.

|===

[.text-center]
== Zdjęcia
