= Ryba z porami  +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: 45 min
* 4 porcje
* https://www.kwestiasmaku.com/przepis/ryba-z-porami[link do 藕r贸da przepisu]

== Skadniki
* 600 g filet贸w ryby (np. mintaj, dorsz, halibut)
* 1 por
* 1/3 y偶eczki nasion kopru woskiego
* 1 y偶ka oliwy
* 2 y偶ki masa
* 1 y偶ka posiekanego koperku
* 5 y偶ek mietanki 30%
|
== Przygotowanie
Ryb pokroi na porcje i umieci w naczyniu 偶aroodpornym. Doprawi sol, pieprzem, posypa nasionami kopru woskiego i wysmarowa oliw.

Piekarnik nagrza do 200 stopni C.

Odci zielone koce pora, reszt przekroi wzdu偶 na p贸 i dokadnie opuka. Cienko posieka na desce.

Wo偶y na patelni, doprawi sol i pieprzem i co chwil mieszajc dusi przez ok. 8 minut. Pod koniec doda maso.

Wla p贸 szklanki wody lub bulionu, zagotowa i przykry. Dusi przez ok. 5 minut do mikkoci.

Zdj pokryw, doda mietank oraz koperek, wymiesza i zagotowa. Wyo偶y na ryb i wstawi do piekarnika. Piec przez 20 minut (bez przykrycia).



|===

[.text-center]
== Zdjcia
