= Ryż z krewetkami na ostro +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 45 min
* 3 porcje
* https://www.kwestiasmaku.com/przepis/ryz-smazony-z-krewetkami-na-ostro[link do źródła przepisu]

== Składniki
* 200 g (2 woreczki) ryżu basmati
* ok. 200 g obranych krewetek (ok. 450 g w pancerzach)
* 1 łyżka startego czosnku
* 2 łyżki świeżo startego imbiru
* 2 łyżki oleju roślinnego np. kokosowego + 1 łyżka masła
* 1 łyżeczka kminu rzymskiego
* 1/2 łyżeczki imbiru w proszku
* 1 łyżeczka płatków chili + do posypania
* szczypta cynamonu
* świeża kolendra i/lub mięta
* świeżo zmielony czarny pieprz i sól morska

|
== Przygotowanie
Ugotować ryż zgodnie z instrukcją na opakowaniu, uważając aby go nie przegotować, lepiej aby był lekko twardawy w środku. Odcedzić i wyłożyć na duży talerz lub tacę, ostudzić (można przygotować wcześniej).

Krewetki oczyścić z pancerzy, jelit i ogonków, opłukać i osuszyć. Czosnek i imbir obrać i zetrzeć na drobnej tarce.

Na większej patelni na 2 łyżkach oleju delikatnie podsmażyć imbir i czosnek (nie rumienić). Dodać krewetki oraz przyprawy: kmin rzymski, imbir w proszku, cynamon, płatki chili oraz świeżo zmielony pieprz. Krótko smażyć co chwilę mieszając (przez ok. 2 minuty krewetki surowe, przez ok. 1 minutę podgotowane). Pod koniec doprawić solą.

Wyjąć krewetki łyżką cedzakową na talerz. Na patelnię zaś włożyć ryż i smażyć mieszając przez ok. 3 - 4 minuty aż cały się podgrzeje i miejscami zacznie się rumienić.

Dodać krewetki, wymieszać i razem podgrzać. Wyłożyć na talerze i udekorować miętą (można ją też posiekać i posypać po wierzchu dania) i/lub kolendrą.

|===

[.text-center]
== Zdjęcia
