= Schabowy własnym w sosie z cebulą

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: powyżej 1 h
* 2 porcje
* https://www.doradcasmaku.pl/przepis-schab-w-sosie-wlasnym-300432[link do źródła przepisu]

== Składniki

* schab bez kości 300-400 gramów
* cebula 1 sztuka
* Sól morska jodowana drobnoziarnista Prymat 1 łyżeczka
* Pieprz biały mielony Prymat 1/2 łyżeczki
* mąka 1-2 łyżka
* śmietana kwaśna 1-2 łyżki
* natka pietruszki do posypania
* woda 150 mililitrów

|
== Przygotowanie

Schab pokroić w plastry o grubości 1-2 cm.

Kawałki mięsa położyć na suchej dobrze nagrzanej patelni. Mięso powinno prawie się przypalić, nabrać koloru mocno brązowego z obydwu stron. To właśnie te przypalone soki nadadzą wyjątkowego smaku sosowi.

Gdy mięso jest dość dobrze przyrumienione, dodać posiekaną cebulę i zalać wodą tak, aby przykrywało mięso. Doprawić solą i pieprzem do smaku. Przykryć pokrywką i dusić na małym ogniu około 40-60 minut. W razie potrzeby dolać wody (gdyby się wygotowała).

Gdy mięso jest miękkie, zagęścić sos łyżką mąki wymieszaną z 50 ml zimnej wody. Następnie dodać łyżkę śmietany, posiekaną natkę pietruszki, zamieszać i wyłączyć źródło ciepła. Sos i schab gotowy - smacznego!

== Zdjęcia
|===
