= Schab nadziewany mozarellą i pieczarkami +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 90 min
* 6 porcje
* https://kuchnia.wp.pl/roladki-schabowe-z-pieczarkami-i-mozzarella-6831350896240769c[link do źródła przepisu]

== Składniki
* 1 kg schabu
* ½ kg pieczarek
* 1 cebula
* 2 ząbki czosnku
* 125 g mozzarelli (kulka)
* bułka tarta do panierki
* 2 jajka
* olej do smażenia
* sól, pieprz

|
== Przygotowanie
Mięso kroję w plastry, rozbijam, doprawiam solą oraz pieprzem.

Cebulę, czosnek obieram, drobno kroję i smażę na rozgrzanym oleju.

Do cebuli dodaję umyte, pokrojone w plasterki pieczarki. Smażę około 10 minut, następnie doprawiam pieprzem oraz solą.

Na każdym kawałku mięsa na środku układam plasterek mozzarelli oraz łyżkę grzybów.

Mięso zwijam w roladki, obtaczam w bułce tartej, w roztrzepanym widelcem jajku i ponownie w bułce tartej.

Roladki smażę z każdej strony na rozgrzanym oleju.

Gotowe, podaję z ulubioną surówką i ziemniakami.

|===

[.text-center]
== Zdjęcia

