= Schabowy wasnym w sosie z cebul  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: powy偶ej 1 h
* 2 porcje
* https://www.doradcasmaku.pl/przepis-schab-w-sosie-wlasnym-300432[link do 藕r贸da przepisu]

== Skadniki

* schab bez koci 300-400 gram贸w
* cebula 1 sztuka
* s贸l morska jodowana drobnoziarnista Prymat 1 y偶eczka
* Pieprz biay mielony Prymat 1/2 y偶eczki
* mka 1-2 y偶ka
* mietana kwana 1-2 y偶ki
* natka pietruszki do posypania
* woda 150 mililitr贸w

|
== Przygotowanie

Schab pokroi w plastry o gruboci 1-2 cm.

Kawaki misa poo偶y na suchej dobrze nagrzanej patelni. Miso powinno prawie si przypali, nabra koloru mocno brzowego z obydwu stron. To wanie te przypalone soki nadadz wyjtkowego smaku sosowi.

Gdy miso jest do dobrze przyrumienione, doda posiekan cebul i zala wod tak, aby przykrywao miso. Doprawi sol i pieprzem do smaku. Przykry pokrywk i dusi na maym ogniu okoo 40-60 minut. W razie potrzeby dola wody (gdyby si wygotowaa).

Gdy miso jest mikkie, zagci sos y偶k mki wymieszan z 50 ml zimnej wody. Nastpnie doda y偶k mietany, posiekan natk pietruszki, zamiesza i wyczy 藕r贸do ciepa. Sos i schab gotowy - smacznego!

|===

[.text-center]
== Zdjcia
