= Schab nadziewany mozzarell i pieczarkami  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 90 minut
* 6 porcje
* https://kuchnia.wp.pl/roladki-schabowe-z-pieczarkami-i-mozzarella-6831350896240769c[link do 藕r贸da przepisu]

== Skadniki

* 1 kg schabu
* 陆 kg pieczarek
* 1 cebula
* 2 zbki czosnku
* 125 g mozzarelli (kulka)
* buka tarta do panierki
* 2 jajka
* olej do sma偶enia
* s贸l, pieprz

|
== Przygotowanie

Miso kroj w plastry, rozbijam, doprawiam sol oraz pieprzem.

Cebul, czosnek obieram, drobno kroj i sma偶 na rozgrzanym oleju.

Do cebuli dodaj umyte, pokrojone w plasterki pieczarki. Sma偶 okoo 10 minut, nastpnie doprawiam pieprzem oraz sol.

Na ka偶dym kawaku misa na rodku ukadam plasterek mozzarelli oraz y偶k grzyb贸w.

Miso zwijam w roladki, obtaczam w buce tartej, w roztrzepanym widelcem jajku i ponownie w buce tartej.

Roladki sma偶 z ka偶dej strony na rozgrzanym oleju.

Gotowe, podaj z ulubion sur贸wk i ziemniakami.

|===

[.text-center]
== Zdjcia

