= Seleryba +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: do godziny
* 6 porcji
* https://www.jadlonomia.com/przepisy/seleryba[link do źródła przepisu]

== Składniki
* 1 kg selera
* 2 litry bulionu warzywnego
* 2 arkusze nori + 5 arkuszy do owijania kotletów
* 2 łyżki sosu sojowego
* 4 liście laurowe
* 2 ziela angielskie
* 1 łyżeczka ziaren kolendry
* sól i czarny pieprz
* oraz do smażenia: mleko roślinne lub woda, mąka pszenna lub ryżowa i olej roślinny

|
== Przygotowanie
Seler obrać, przekroić na pół i pokroić na 1 cm plastry. W dużym garnku zagotować bulion razem z 2 arkuszami wodorostów nori, liśćmi laurowymi, zielem angielskim, kolendrą oraz sosem sojowym. Do gotującego się bulionu dodać plastry selera i gotować do momentu, aż będą bardzo miękkie, czyli około 15 - 20 minut.

Miękkie plastry selera delikatnie wyjąć i chwilę ostudzić. W tym czasie arkusze nori pociąć na węższe paski, następnie naszykować dwie miseczki, do jednej wlać trochę mleka, a do drugiej wsypać mąkę.

Każdy plaster selera oprószać solą i pieprzem, następnie owijać paskiem nori i na chwilę moczyć w mleku, dzięki temu wodorosty zmiękną i lepiej przylepią się do selera. Tak przygotowany plaster selera delikatnie zanurzać w mące.

Na dużej patelni mocno rozgrzać olej i układać gotowe plastry selera. Obsmażać z każdej strony przez około 2 - 3 minuty, podawać z ziemniakami, surówką lub wigilijną kapustą.

|===

[.text-center]
== Zdjęcia
