= Seleryba  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: do godziny
* 6 porcji
* https://www.jadlonomia.com/przepisy/seleryba[link do 藕r贸da przepisu]

== Skadniki
* 1 kg selera
* 2 litry bulionu warzywnego
* 2 arkusze nori + 5 arkuszy do owijania kotlet贸w
* 2 y偶ki sosu sojowego
* 4 licie laurowe
* 2 ziela angielskie
* 1 y偶eczka ziaren kolendry
* s贸l i czarny pieprz
* oraz do sma偶enia: mleko rolinne lub woda, mka pszenna lub ry偶owa i olej rolinny

|
== Przygotowanie
Seler obra, przekroi na p贸 i pokroi na 1 cm plastry. W du偶ym garnku zagotowa bulion razem z 2 arkuszami wodorost贸w nori, limi laurowymi, zielem angielskim, kolendr oraz sosem sojowym. Do gotujcego si bulionu doda plastry selera i gotowa do momentu, a偶 bd bardzo mikkie, czyli okoo 15 - 20 minut.

Mikkie plastry selera delikatnie wyj i chwil ostudzi. W tym czasie arkusze nori poci na w偶sze paski, nastpnie naszykowa dwie miseczki, do jednej wla troch mleka, a do drugiej wsypa mk.

Ka偶dy plaster selera opr贸sza sol i pieprzem, nastpnie owija paskiem nori i na chwil moczy w mleku, dziki temu wodorosty zmikn i lepiej przylepi si do selera. Tak przygotowany plaster selera delikatnie zanurza w mce.

Na du偶ej patelni mocno rozgrza olej i ukada gotowe plastry selera. Obsma偶a z ka偶dej strony przez okoo 2 - 3 minuty, podawa z ziemniakami, sur贸wk lub wigilijn kapust.

|===

[.text-center]
== Zdjcia
