= Skrzydełka w miodzie 🐔
:imagesdir: /Recipes/static/images

++++
<div class="recipe-header-actions">
    <a href="../../index.html" class="back-to-home-btn">← Wróć do przepisów</a>
    <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>
</div>
++++

[.recipe-hero]
[.card-image-placeholder]
Brak zdjęcia przepisu 🍲

[.recipe-details]
* 🕒 czas przygotowania: 1 godzina
* 🕒 czas gotowania: 1 godzina
* 👥 4 porcje
* 🔗 https://www.winiary.pl/przepisy/soczyste-skrzydelka-z-miodem[link do źródła przepisu]

[.recipe-columns]
== Składniki

* 1 kg skrzydełek
* 2 WINIARY POMYSŁ NA… soczyste skrzydełka z miodem

== Przygotowanie

Umyj dokładnie skrzydełka. W opakowaniu Pomysł na... znajdziesz woreczek i zapinkę. Umieść skrzydełka w woreczku, dodaj zawartość opakowania i zamknij zapinką.

Delikatnie obracając woreczek, równomiernie rozprowadź przyprawę na skrzydełkach.

Włóż woreczek do żaroodpornego naczynia i wstaw do piekarnika rozgrzanego do temperatury 200°C. Piecz na najniższym poziomie około 50 minut.

Po wyjęciu z piekarnika ostrożnie odetnij końcówkę z zapinką. Soczyste skrzydełka idealnie komponują się z sałatką Coleslaw i domowymi frytkami.

[.recipe-gallery]
== Zdjęcia

[.gallery-grid]
// Tutaj pojawią się zdjęcia
