= Szwedzkie klopsiki +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 1 h
* 6 porcji
* https://www.kwestiasmaku.com/kuchnia_polska/wieprzowina/szwedzkie_klopsiki/przepis.html[link do źródła przepisu]

== Składniki
* 1 szklanka dokładnie rozdrobnionego miąższu bułki lub chleba
* 2 i 1/3 szklanki bulionu wołowego
* 4 łyżki masła
* 1 duża drobno posiekana cebula
* 2 cienkie plasterki boczku, zmielone lub drobno posiekane
* 400 g drobno zmielonej wołowiny (np. udziec)
* 400 g drobno zmielonej wieprzowiny (np. łopatka)
* 4 jajka
* 1 płaska łyżka soli
* 1 i 1/2 łyżeczki świeżo zmielonego pieprzu
* 1 i 1/2 łyżeczki cukru
* 1 łyżeczka roztartego w moździerzu lub zmielonego ziela angielskiego
* 1/2 łyżeczki zmielonej gałki muszkatołowej
* 2 łyżki mąki
* 2 łyżki śmietanki kremowej 30%
* gotowy ze słoiczka dżem z borówki
* chrupiące ziemniaczki z pieca

|
== Przygotowanie
W dużej misce wymieszać okruszki chleba z 1/3 szklanki bulionu. Na dużej patelni roztopić 1 łyżkę masła na średnim ogniu, dodać cebulę i smażyć przez ok. 10 minut na złoty kolor. W razie potrzeby rozdrobnić w melakserze lub zmielić razem z mięsem. Przełożyć do miski z chlebem.

Na patelnię włożyć boczek i obsmażać aż się wytopi i będzie chrupiący, w razie potrzeby dodatkowo rozdrobnić w melakserze lub zmielić razem z mięsem. Przełożyć do miski.

Do miski dodać: mięso wołowe i wieprzowe, jajka, sól, pieprz, cukier, zmielone ziele angielskie i gałkę muszkatołową. Wymieszać dłońmi na jednolitą masę.

Nabierać po 1 łyżce mięsa i wilgotnymi dłońmi lepić kuleczki, układać je na desce lub tacy. Do patelni dodać 1 łyżkę masła i na średnim ogniu obsmażać klopsiki partiami z każdej strony na brązowy kolor, przez około 6 - 8 minut każdą partię. Odkładać na talerz i dokładać na patelnię masła przed smażeniem kolejnej partii.

Mąkę wymieszać z 4 łyżkami wody, następnie połączyć z resztą (2 szklankami) bulionu. Wlać do szerokiego garnka i zagotować często mieszając, dodać klopsiki, przykryć i gotować na małym ogniu przez około 5 - 6 minut aż klopsiki będą ugotowane. Odstawić z ognia i wymieszać ze śmietanką.

|===

[.text-center]
== Zdjęcia
