= Tortilki ser bekon ala kfc +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 35 min
* 6 sztuk
* https://www.youtube.com/watch?v=1Q6_Gvsri9k[link do źródła przepisu]

== Składniki
* pierś z kurczaka - 720 g
* wrapy - 6 szt.
* chipsy STRONG EXTRA HOT Pepperoni - 40 g
* Doritos HOT Pepper - 40 g
* panko - 80 g

=== Sos:

* maślanka - 120 g
* czosnek 2 ząbki
* jogurt grecki - 160 g
* skyr - 300 g
* musztarda sarepska - 40 g

=== Warzywa:

* 1/2 sałata lodowa
* pomidor

=== Przyprawy:

* papryka słodka - 6 g
* papryka ostra - 6 g
* papryka wędzona - 4 g
* czosnek suszony - 8 g
* mieszanka ziół
* sól - 4 g
* pieprz
* 6 plasterków sera
* 6 plasterków bekonu

|
== Przygotowanie

Zaczynam od kurczaka. Staram się kroić piersi na 60 g kawałki.

Teraz marynata, zaprawa musztarda 100 g ,do tego wleję na razie 200 ml maślanki, aby lepiej się mieszało. No i nasze przyprawy (mnóstwo prochu), które dadzą świetny smak.
Mamy tutaj 3 rodzaje papryk: jest słodka, jest wędzona, jest ostra

Mamy suszony czosnek, po prostu sól, nieco świeżo mielonego pieprzu

Dodaję resztę maślanki około 100 g oraz nutkę ziół, o mało bym zapomniał. Jedna pełna łyżka gotowej mieszanki

Dokładnie wymieszajcie - jest gęstość i niesamowity smak, uwierzcie mi.

Przelewamy teraz całość do naszych kawałków kurczaka.

I dokładnie obtaczamy każdą część.

Odstawiamy na bok, niech się marynuje, niech się temperatura podnosi.

I robimy panierkę. Do robota kuchennego czy dużego blendera, u mnie NINJA z dużym kielichem. Wrzucam 100 g STRONG EXTRA HOT PEPPERONI.

Do tego 100 g, czyli cała paczka, DORITOS również hot, ostra papryka.

I miksujemy, aż uzyskamy drobne ziarno podobne wielkością do panko. Bo nasze chipsy z panko zmieszamy proporcją jeden do jeden

No i do osobnej dużej miski na panierkę. Lądują nasze zmiksowane chipsy oraz cała paczka panko 200 g. Dostajemy 400 g świetnej panierki.

Bierzemy ruszt od piekarnika i działamy. Każdy zamarynowany wcześniej kawałek kurczaka moczymy w panierce. Suchą ręką dobrze oblepiamy z obu stron. I przekładamy na ruszt. Ja po jednej kratce do piekarnika, dokładnie połowa mojego kurczaka

Zaraz wsuwam w piekarnik

Już możecie rozgrzewać 200 stopni, termoobieg od 15 do 20 minut. Tajemnica miękkiego i soczystego mięsa razem z chrupką panierką. Pamiętajcie, mięso musi mieć jak najwyższą temperaturę. Zbliżoną do pokojowej, kiedy tylko wsuwacie do piekarnika Mięsko, kurczaczek pięknie się obrabia, możemy w tym czasie przygotować sos.

Po prostu wrzucamy 5 kubeczków jogurtu typu Skyr. Do tego cały jogurt grecki 400 g. Doprawiamy solą oraz świeżo mielonym pieprzem. Dodamy nieco czosnku. 4 ząbki surowego czosnku na taką ilość spokojnie wystarczą. Dokładnie mieszamy i gotowy.

Czyli sałata lodowa, połowa główki pokrojona w kosteczkę. Tak samo pomidor. Sos oraz dodatki przyszykowane, kurczak przypieczony.

Zaraz komponujemy. Na początek sos. Dzieląc wszystkie składniki sosu dostaję około 75 g na 1 porcję. Rozsmarowuje dokładnie po każdym. Na to sałata lodowa, pół główki idealnie wystarczyło oraz pomidor. Duże, dwa malinowe pomidory również się sprawdziły. Pora na króla naszego odcinka pikantne kawałki kurczaka. Po dwa na twistera. Rozkładam po jednym, aby później wizualnie dopasować kawałki

|===

[.text-center]
== Zdjęcia
