= Tortilki ser bekon ala KFC  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 35 min
* 6 sztuk
* https://www.youtube.com/watch?v=1Q6_Gvsri9k[link do 藕r贸da przepisu]

== Skadniki

* pier z kurczaka - 720 g
* wrapy - 6 szt.
* chipsy STRONG EXTRA HOT Pepperoni - 40 g
* Doritos HOT Pepper - 40 g
* panko - 80 g

=== Sos:

* malanka - 120 g
* czosnek 2 zbki
* jogurt grecki - 160 g
* skyr - 300 g
* musztarda sarepska - 40 g

=== Warzywa:

* 1/2 saata lodowa
* pomidor

=== Przyprawy:

* papryka sodka - 6 g
* papryka ostra - 6 g
* papryka wdzona - 4 g
* czosnek suszony - 8 g
* mieszanka zi贸
* s贸l - 4 g
* pieprz
* 6 plasterk贸w sera
* 6 plasterk贸w bekonu

|
== Przygotowanie

Zaczynam od kurczaka. Staram si kroi piersi na 60 g kawaki.

Teraz marynata, zaprawa musztarda 100 g ,do tego wlej na razie 200 ml malanki, aby lepiej si mieszao. No i nasze przyprawy (mn贸stwo prochu), kt贸re dadz wietny smak.
Mamy tutaj 3 rodzaje papryk: jest sodka, jest wdzona, jest ostra

Mamy suszony czosnek, po prostu s贸l, nieco wie偶o mielonego pieprzu

Dodaj reszt malanki okoo 100 g oraz nutk zi贸, o mao bym zapomnia. Jedna pena y偶ka gotowej mieszanki

Dokadnie wymieszajcie - jest gsto i niesamowity smak, uwierzcie mi.

Przelewamy teraz cao do naszych kawak贸w kurczaka.

I dokadnie obtaczamy ka偶d cz.

Odstawiamy na bok, niech si marynuje, niech si temperatura podnosi.

I robimy panierk. Do robota kuchennego czy du偶ego blendera, u mnie NINJA z du偶ym kielichem. Wrzucam 100 g STRONG EXTRA HOT PEPPERONI.

Do tego 100 g, czyli caa paczka, DORITOS r贸wnie偶 hot, ostra papryka.

I miksujemy, a偶 uzyskamy drobne ziarno podobne wielkoci do panko. Bo nasze chipsy z panko zmieszamy proporcj jeden do jeden

No i do osobnej du偶ej miski na panierk. Lduj nasze zmiksowane chipsy oraz caa paczka panko 200 g. Dostajemy 400 g wietnej panierki.

Bierzemy ruszt od piekarnika i dziaamy. Ka偶dy zamarynowany wczeniej kawaek kurczaka moczymy w panierce. Such rk dobrze oblepiamy z obu stron. I przekadamy na ruszt. Ja po jednej kratce do piekarnika, dokadnie poowa mojego kurczaka

Zaraz wsuwam w piekarnik

Ju偶 mo偶ecie rozgrzewa 200 stopni, termoobieg od 15 do 20 minut. Tajemnica mikkiego i soczystego misa razem z chrupk panierk. Pamitajcie, miso musi mie jak najwy偶sz temperatur. Zbli偶on do pokojowej, kiedy tylko wsuwacie do piekarnika Misko, kurczaczek piknie si obrabia, mo偶emy w tym czasie przygotowa sos.

Po prostu wrzucamy 5 kubeczk贸w jogurtu typu Skyr. Do tego cay jogurt grecki 400 g. Doprawiamy sol oraz wie偶o mielonym pieprzem. Dodamy nieco czosnku. 4 zbki surowego czosnku na tak ilo spokojnie wystarcz. Dokadnie mieszamy i gotowy.

Czyli saata lodowa, poowa g贸wki pokrojona w kosteczk. Tak samo pomidor. Sos oraz dodatki przyszykowane, kurczak przypieczony.

Zaraz komponujemy. Na pocztek sos. Dzielc wszystkie skadniki sosu dostaj okoo 75 g na 1 porcj. Rozsmarowuje dokadnie po ka偶dym. Na to saata lodowa, p贸 g贸wki idealnie wystarczyo oraz pomidor. Du偶e, dwa malinowe pomidory r贸wnie偶 si sprawdziy. Pora na kr贸la naszego odcinka pikantne kawaki kurczaka. Po dwa na twistera. Rozkadam po jednym, aby p贸藕niej wizualnie dopasowa kawaki

|===

[.text-center]
== Zdjcia
