= Wegeburgerki 🌱 +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* Czas przygotowania: 20 minut + 30 minut pieczenia
* 10 burgerów
* https://www.jadlonomia.com/przepisy/najlepsze-wegeburgery-na-swiecie[link do źródła przepisu]

== Składniki

* 2 szklanki startej marchewki
* 1 ½ szklanki ugotowanej kaszy jaglanej / ¾ suchej kaszy jaglanej
* ½ szklanki prażonego słonecznika
* ½ szklanki prażonego sezamu
* 1 czerwona cebula
* ½ szklanki bułki tartej
* ¼ szklanki oleju
* 3 łyżki mąki
* 2 łyżki sosu sojowego
* 2 łyżeczki kolendry
* 2 łyżeczki pietruszki
* łyżeczka suszonego imbiru albo 3 cm świeżego korzenia startego drobno na tarce
* ¼ łyżeczki chili
* sól i czarny pieprz

=== Burgery:

* 5 bułek, hamburgerowych lub zwykłych
* spora czerwona cebula
* spory pomidor
* kilka plasterków zielonego ogórka
* kilka liści sałaty
* mała garść rukoli
* kilka łyżek dobrego, ekologicznego keczupu
* odrobina musztardy

|
== Przygotowanie
Wszystkie składniki wrzucamy do dużej miski i mieszamy rękami, aż do uzyskania klejącej masy. Jeżeli masa nie klei się wystarczająco, wystarczy dodać jeszcze więcej oleju i mąki.
Lepimy kotlety i układamy je na blasze wyłożonej papierem do pieczenia. Pieczemy 30 minut w temperaturze 200 stopni, w połowie czasu pieczenia (albo po upływie 20 minut) delikatnie obracając kotlety na drugą stronę.

=== Burgery:
Bułki chwilę grilluję w piekarniku, następnie każdą przecinam i smaruję obydwie połówki odrobiną keczupu oraz jeszcze mniejsza ilością musztardy, do środka wkładam warzywa i kotleta. Gotowe! Elegancko serwuję na talerzu albo zawijam w serwetkę i zabieram burgera na spacer po dzielni.
|===

[.text-center]
== Zdjęcia
