= Wieprzowina po chińsku

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 30 min
* 2 porcje
* https://www.kwestiasmaku.com/kuchnia_polska/wieprzowina/wieprzowina_po_chinsku/przepis.html[link do źródła przepisu]

== Składniki
* 300 g polędwiczki wieprzowej
* 1 łyżka mąki ziemniaczanej
* 1/2 czerwonej papryki
* 1 cebula szalotka lub 1/4 cebuli
* 1/2 marchewki
* 1/2 pora
* 2 ząbki czosnku
* 1 mała papryczka chili
* 3 cm kawałek imbiru
* 2 łyżki oleju roślinnego
* 3 łyżki octu ryżowego (lub sok wyciśnięty z 1/2 cytryny)
* 3 łyżki wody
* 5 łyżek sosu sojowego
* 3 łyżki cukru (np. trzcinowego)

|
== Przygotowanie
Odciąć białą błonę na zewnętrznej stronie polędwiczki. Mięso przekroić wzdłuż na pół, następnie w poprzek włókien na jak najcieńsze plasterki. Doprawić solą i pieprzem, obtoczyć w mące ziemniaczanej. Nastawić ryż na gotowanie.

Przygotować warzywa: paprykę pokroić w kostkę, cebulę obrać i pokroić w nieco większą kostkę, marchewkę obrać i pokroić wzdłuż na cienkie słupki, tak samo pokroić pora.

Papryczkę chili przekroić wzdłuż, usunąć pestki, następnie drobno posiekać. Czosnek i imbir obrać i zetrzeć na drobnej tarce.

Przygotować sos: wymieszać wszystkie składniki w miseczce.

W woku lub w wysokiej i dużej patelni rozgrzać 1 łyżkę oleju, włożyć wszystkie przygotowane warzywa i mieszając smażyć na większym ogniu przez około 4 minuty. Warzywa wyjąć i odłożyć na talerz.

Na patelnię dodać drugą łyżkę oleju i włożyć polędwiczkę, zwiększyć ogień do dużego i smażyć przez około 3 minuty co chwilę mieszając aby równomiernie się obsmażała.

Włożyć z powrotem warzywa i wszystko wymieszać, następnie wlać sos. Gotować przez około 2 minuty aż sos zgęstnieje, w międzyczasie co chwilę zamieszać. Wyłożyć danie na talerze, obok położyć ryż, posypać szczypiorkiem i podawać.


== Zdjęcia
|===
