= Wołowina po burgundzku 🥩 +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++
:imagesdir: /Recipes/static/images

[.recipe-hero]

[.recipe-category-label]
Dania główne

[.card-image-placeholder]
Brak zdjęcia przepisu 🍲


[.recipe-details]

[.recipe-details-item]
🕒 czas przygotowania: 3,5 godziny

[.recipe-details-item]
👥 8 porcji

[.recipe-details-item]
🔗 https://www.kwestiasmaku.com/przepis/boeuf-bourguignon-wolowina-po-burgundzku[link do źródła przepisu]



[.recipe-columns]

[.recipe-column-box]
=== Składniki
* 1,5 kg wołowiny (np. karkówka, łopatka)
* 150 g wędzonego boczku
* 2 łyżki oleju roślinnego
* 50 g masła
* 2 ząbki czosnku
* 2 marchewki
* 1 por
* 1 cebula
* 2 łyżki mąki pszennej
* sól i pieprz
* 500 ml bulionu wołowego
* 500 ml czerwonego wytrawnego wina
* 2 łyżki koniaku (opcjonalnie)
* 1 łyżka koncentratu pomidorowego
* 1 listek laurowy
* kilka gałązek tymianku oraz natki pietruszki
* 8 małych cebulek szalotek lub 24 małych marynowanych cebulek
* 200 g małych pieczarek



[.recipe-column-box]
=== Przygotowanie
Mięso pokroić na większe kawałki (ok. 4 - 5 cm). Na dużą patelnię z grubym dnem włożyć pokrojony w kosteczkę boczek i powoli smażyć aż do zrumienienia. Wyjąć na talerz pozostawiając tłuszcz.

Wlać łyżkę oleju oraz dodać połowę masła, partiami obsmażyć z każdej strony kawałki mięsa, po obsmażeniu odkładać na talerz.

Włożyć na patelnię pozostały tłuszcz i podsmażyć starty czosnek, pokrojoną na plasterki marchewkę i pora oraz drobno posiekaną cebulę. Posypać mąką, doprawić solą oraz pieprzem, jeszcze chwilę podsmażyć.

Przełożyć składniki z patelni do większego naczynia żaroodpornego. Wlać bulion, wino, koniak oraz koncentrat, zagotować. Dodać listek laurowy, posiekane łodyżki tymianku i posiekaną natkę, następnie włożyć podsmażone mięso i boczek.

Po ponownym zagotowaniu przykryć naczynie i wstawić do nagrzanego do 150 stopni C piekarnika. Zapiekać przez ok. 2 i 1/2 godziny.

Na patelni na reszcie masła podsmażyć obrane cebulki szalotki i pieczarki w całości (cebulek marynowanych nie podsmażamy). Dodać do gulaszu, wymieszać i piec tym razem bez przykrycia przez około 30 minut, do czasu aż mięso będzie już całkowicie miękkie.

