= Zapiekanka z łososiem 🐟
:imagesdir: /Recipes/static/images

++++
<div class="recipe-header-actions">
    <a href="../../index.html" class="back-to-home-btn">← Wróć do przepisów</a>
    <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>
</div>
++++

[.recipe-hero]
[.card-image-placeholder]
Brak zdjęcia przepisu 🍲

[.recipe-details]
* 🕒 czas gotowania: 1 godzina
* 👥 4 porcje
* 🔗 Przepis z zeszytu mamy

[.recipe-columns]
== Składniki

* 250 g sucharów
* 125 g masła
* 50 g cebuli prażonej
* oregano
* sól

=== Masa serowa
* 50 dag sera mascarpone x utrzeć
* 20 dag selera korzeń - ugotować, zmiksować
* 2 łyżki chrzanu
* 3 jaja x
* pieprz, sól
* 30 dag pomidorów cherry
* ocet jabłkowy
* bazylia
* 150 g łososia wędzonego

== Przygotowanie

Suchary drobno pokruszyć (np. w malakserze lub wałkiem w woreczku), wymieszać z prażoną cebulą, oregano oraz szczyptą soli. Masło rozpuścić, zalać nim przygotowane suchary i dokładnie wymieszać. Otrzymaną masą wylepić spód naczynia żaroodpornego lub formy do zapiekania, wyrównać i lekko docisnąć.

Obrany korzeń selera ugotować do miękkości w lekko osolonej wodzie z dodatkiem odrobiny octu jabłkowego (dzięki temu zachowa jasny kolor), a następnie dokładnie zmiksować na gładkie purée i ostudzić. W dużej misce utrzeć ser mascarpone z jajkami, dodać ostudzony seler, chrzan oraz doprawić do smaku solą, pieprzem i posiekaną bazylią. Całość zmiksować na jednolitą masę.

Wędzonego łososia porwać na mniejsze kawałki, a pomidorki cherry przekroić na połówki. Na przygotowany wcześniej spód z sucharów wyłożyć połowę masy serowej. Rozłożyć na niej kawałki łososia oraz część pomidorków, po czym przykryć resztą masy serowej. Na wierzchu ułożyć pozostałe połówki pomidorków cherry, lekko wciskając je w masę. Całość wstawić do piekarnika nagrzanego do 180°C i zapiekać przez około 35-40 minut, aż masa serowa dobrze się zetnie i lekko zezłoci z wierzchu. Przed krojeniem odstawić na kilka minut, aby zapiekanka lekko przestygła.

[.recipe-gallery]
== Zdjęcia

[.gallery-grid]
// Tutaj pojawią się zdjęcia
