= Zapiekanka ukaszkowa  ォ +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 1 h 40 min
* 6 porcji
* https://kuchnialidla.pl/zapiekanka-z-miesem-i-ziemniakami[link do 藕r贸da przepisu]

== Skadniki

* cebula - 1 szt.
* pieprz czarny - 1 szczypta
* gaka muszkatoowa mielona - 1 szczypta
* korze pietruszki - 1 szt.
* marchew - 2 szt.
* olej sonecznikowy - 2 y偶ki
* pieczarka - 250 g
* natka pietruszki - 20 g
* s贸l - 1 szczypta
* wino czerwone - 100 ml
* zioa prowansalskie - 1 y偶ka
* ciecierzyca ugotowana - 200 g
* pomidory krojone z puszki - 400 g
* zbek czosnku - 2 szt.
* miso mielone woowo-wieprzowe - 1 kg
* sos Worcester - 30 ml
* pieprz czarny - 1 szczypta
* gaka muszkatoowa mielona - 1 szczypta
* jajko - 3 szt.
* maso - 100 g
* mleko - 100 ml
* s贸l - 1 szczypta
* ziemniak - 1 kg
* ser cheddar - 100 g
|
== Przygotowanie

Marchew i pietruszk pokrojone w kostk sma偶ymy w garnku na rozgrzanym oleju. Doprawiamy sol i pieprzem. Dodajemy cebul pokrojon w kostk i posiekany czosnek. Sma偶ymy, mieszajc. Usma偶one warzywa przekadamy na talerz.

Pieczarki pokrojone w plasterki sma偶ymy na rozgrzanym oleju na patelni. Doprawiamy sol i pieprzem, przekadamy do podsma偶onych wczeniej warzyw.

Miso kadziemy na odrobin oleju rozgrzanego w garnku po warzywach. Doprawiamy sol i pieprzem. Sma偶ymy z obu stron na zoty kolor, od czasu do czasu mieszajc.

Przysma偶one miso doprawiamy zioami prowansalskimi, gak muszkatoow i sosem worcestershire. Dolewamy wino, odparowujemy. Dodajemy pomidory pelati i odrobin wody (tyle, by pokrya miso). Dusimy ok. 20-30 minut, od czasu do czasu mieszajc.

Ugotowane, przecinite przez prask ziemniaki przekadamy do garnka i przyprawiamy gak muszkatoow.

Dodajemy maso i mleko. Delikatnie podgrzewamy i mieszamy do uzyskania jednolitej masy. Pur茅e doprawiamy sol i pieprzem, mieszamy i zdejmujemy z ognia. Dodajemy 偶贸tka jaj i dokadnie mieszamy. 

Do uduszonego misa dodajemy podsma偶one warzywa i pieczarki. Dodajemy ciecierzyc i posiekan natk pietruszki. Mieszamy.

Mas misno-warzywn przekadamy do naczynia 偶aroodpornego, rozprowadzamy r贸wnomiernie i wyr贸wnujemy.

Na wierzch wykadamy pur茅e, kt贸re r贸wnie偶 rozprowadzamy po caej powierzchni i lekko dociskamy. Pieczemy ok. 20-30 minut w piekarniku rozgrzanym do temperatury 180掳C. Po tym czasie zapiekank posypujemy z wierzchu serem startym na tarce o grubych oczkach i zapiekamy przez kolejne 20 minut.

|===

[.text-center]
== Zdjcia
