= Zapiekanka makaronowa +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 2

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 35 min
* 4 porcje
* https://www.kwestiasmaku.com/przepis/zapiekanka-makaronowa-z-kurczakiem-i-warzywami[link do źródła przepisu]

== Składniki
* 150 g makaronu, np. kokardki
* 2 łyżki oliwy extra vergine
* 400 g filetu z kurczaka
* 1 cebula
* 3 ząbki czosnku
* 300 g cukinii (1 średnia)
* 1 czerwona papryka
* 400 g pomidorów krojonych z puszki (lub świeżych bez pestek i skórek, pokrojonych w kosteczkę)
* 150 g mozzarelli
* przyprawy: 1 łyżeczka oregano, 2 łyżeczki przyprawy curry, 1 łyżeczka papryki, 1/3 łyżeczki ostrej papryki, 1/2 łyżeczki kurkumy

|
== Przygotowanie
Makaron wrzucić na wrzątek i gotować chwilę krócej niż al dente. Piekarnik nagrzać do 180 stopni C. W małej salaterce wymieszać wszystkie przyprawy.

Kurczaka pokroić w kosteczkę, doprawić solą, pieprzem oraz połową przypraw. Na patelni rozgrzać łyżkę oliwy, włożyć kurczaka i krótko podsmażyć mieszając, po czym przełożyć na oddzielny talerz.

Na patelnię wlać łyżkę oliwy i zeszklić pokrojoną w kosteczkę cebulę, pod koniec dodać pokrojony na cienkie plasterki czosnek.

Dodać pokrojoną w kosteczkę cukinię i mieszając smażyć przez ok. 3 minuty. Dodać pokrojoną w kostkę paprykę oraz resztę przypraw. Wymieszać i smażyć przez kolejne 3 minuty.

Dodać pomidory, w razie potrzeby doprawić solą i pieprzem, wymieszać i zagotować. Dodać ugotowany makaron i podsmażonego kurczaka, wymieszać i wyłożyć do naczynia żaroodpornego.

Przykryć pokrywą lub folią aluminiową i wstawić do piekarnika na 20 minut. Posypać tartą mozzarellą i zapiekać jeszcze przez ok. 5 minut bez przykrycia.

|===

[.text-center]
== Zdjęcia
