= Zapiekanka łukaszkowa +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 1 h 40 min
* 6 porcji
* https://kuchnialidla.pl/zapiekanka-z-miesem-i-ziemniakami[link do źródła przepisu]

== Składniki
* cebula - 1 szt.
* pieprz czarny - 1 szczypta
* gałka muszkatołowa mielona - 1 szczypta
* korzeń pietruszki - 1 szt.
* marchew - 2 szt.
* olej słonecznikowy - 2 łyżki
* pieczarka - 250 g
* natka pietruszki - 20 g
* sól - 1 szczypta
* wino czerwone - 100 ml
* zioła prowansalskie - 1 łyżka
* ciecierzyca ugotowana - 200 g
* pomidory krojone z puszki - 400 g
* ząbek czosnku - 2 szt.
* mięso mielone wołowo-wieprzowe - 1 kg
* sos Worcester - 30 ml
* pieprz czarny - 1 szczypta
* gałka muszkatołowa mielona - 1 szczypta
* jajko - 3 szt.
* masło - 100 g
* mleko - 100 ml
* sól - 1 szczypta
* ziemniak - 1 kg
* ser cheddar - 100 g
|
== Przygotowanie
Marchew i pietruszkę pokrojone w kostkę smażymy w garnku na rozgrzanym oleju. Doprawiamy solą i pieprzem. Dodajemy cebulę pokrojoną w kostkę i posiekany czosnek. Smażymy, mieszając. Usmażone warzywa przekładamy na talerz.

Pieczarki pokrojone w plasterki smażymy na rozgrzanym oleju na patelni. Doprawiamy solą i pieprzem, przekładamy do podsmażonych wcześniej warzyw.

Mięso kładziemy na odrobinę oleju rozgrzanego w garnku po warzywach. Doprawiamy solą i pieprzem. Smażymy z obu stron na złoty kolor, od czasu do czasu mieszając.

Przysmażone mięso doprawiamy ziołami prowansalskimi, gałką muszkatołową i sosem worcestershire. Dolewamy wino, odparowujemy. Dodajemy pomidory pelati i odrobinę wody (tyle, by pokryła mięso). Dusimy ok. 20-30 minut, od czasu do czasu mieszając.

Ugotowane, przeciśnięte przez praskę ziemniaki przekładamy do garnka i przyprawiamy gałką muszkatołową.

Dodajemy masło i mleko. Delikatnie podgrzewamy i mieszamy do uzyskania jednolitej masy. Purée doprawiamy solą i pieprzem, mieszamy i zdejmujemy z ognia. Dodajemy żółtka jaj i dokładnie mieszamy. 

Do uduszonego mięsa dodajemy podsmażone warzywa i pieczarki. Dodajemy ciecierzycę i posiekaną natkę pietruszki. Mieszamy.

Masę mięsno-warzywną przekładamy do naczynia żaroodpornego, rozprowadzamy równomiernie i wyrównujemy.

Na wierzch wykładamy purée, które również rozprowadzamy po całej powierzchni i lekko dociskamy. Pieczemy ok. 20-30 minut w piekarniku rozgrzanym do temperatury 180°C. Po tym czasie zapiekankę posypujemy z wierzchu serem startym na tarce o grubych oczkach i zapiekamy przez kolejne 20 minut.

|===

[.text-center]
== Zdjęcia
