= Zapiekanka ziemniaczana  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: 1 godzina
* czas pieczenia zapiekanki: 40 minut
* 6 porcji
* https://aniagotuje.pl/przepis/zapiekanka-ziemniaczana-z-kielbasa[link do 藕r贸da przepisu]

== Skadniki
* 1 kg ziemniak贸w - waga przed obraniem
* opakowanie kiebasy morliskiej z szynki - 540 g
* 2 rednie cebule - okoo 400 g
* 150 g sera 偶贸tego - w kostce lub w plasterkach
* okoo 1/3 szklanki mietanki 30 % - 90 g
* 2 rednie jajka
* 3 y偶ki oleju do sma偶enia
* przyprawy: po paskiej y偶eczce soli i sodkiej papryki; p贸 paskiej y偶eczki pieprzu; szczypta gaki muszkatoowej; 2 y偶eczki czosnku; 1 y偶eczka papryki wdzonej
* dodatki: gar pomidork贸w koktajlowych oraz natka pietruszki lub szczypiorek

|
== Przygotowanie

Ziemniaki nale偶y obra i pokroi w plasterki nie grubsze ni偶 1 cm.

Przepukane plasterki ziemniak贸w zalej w garnku zimn wod. Wsyp pask y偶k soli. Garnek przykryj przykrywk i ustaw wysok moc palnika. Gdy ziemniaki zaczn si gotowa zmniejsz moc palnika i gotuj je okoo 5-8 minut liczc od zagotowania wody. Plasterki ziemniak贸w powinny by na wp贸 ugotowane. Odlej wod a plasterki ziemniak贸w odstaw do lekkiego przestudzenia.

W trakcie gotowania ziemniak贸w zacznij szykowa cebule. Nagrzej du偶 patelni z grubym dnem. Zmniejsz moc palnika do troch wy偶szej ni偶 rednia. Dodaj trzy y偶ki oleju rolinnego do sma偶enia. Na patelni wy贸偶 ca obran i posiekan cebul. Odrobin zmniejsz moc palnika i sma偶 cebulk przez okoo 10 minut, a偶 zrobi si szklista i lekko rumiana. Co par minut zamieszaj cao przy pomocy drewnianej y偶ki.

Podsma偶on cebulk prze贸偶 do osobnej miseczki.

Potrzebujesz jedno opakowanie, czyli 540 gram贸w kiebasy morliskiej z szynki (lub troch mniej). Bd to trzy kiebasy o dugoci okoo 20 cm ka偶da. Morliny posiadaj te偶 w ofercie kiebas lsk oraz kiebas z piersi z kurczaka, kt贸re r贸wnie偶 sprawdz si w tej zapiekance. 
Kiebas pokr贸j w plasterki o gruboci o okoo 5 mm i umie je na patelni po cebuli. Plasterki kiebasy podsma偶aj na lekko rumiano z obu stron. Zajo mi to okoo 20 minut. Do podsma偶ania kiebasy nie u偶ywaam ju偶 dodatkowego tuszczu na patelni. 

Naczynie do zapiekania wysmaruj od rodka odrobin oleju lub masa klarowanego. U mnie byo to naczynie ceramiczne o rednicy 28 cm. Mo偶esz te偶 u偶y dowolnego innego naczynia 偶aroodpornego z wy偶szym rantem. Wybierz naczynie o pojemnoci okoo dw贸ch litr贸w. 

Do natuszczonej od wewntrz formy wy贸偶 wszystkie podgotowane i przestudzone plasterki ziemniak贸w.

Kolejno roz贸偶 te偶 cz sera a na ser podsma偶on cebulk oraz kiebas.

U偶yam sera 偶贸tego w plasterkach, wic wyo偶yam cztery plasterki sera na warstw ziemniak贸w a nastpnie cebulk i plasterki kiebasy. Jeli u偶ywasz sera w kostce, to na ziemniaki roz贸偶 cz startego na grubych oczkach sera a nastpnie cebulk i kiebas. 

Do maego naczynia wlej okoo 1/3 szklanki mietanki krem贸wki 30 % oraz wbij dwa jajka. Wsyp przyprawy: po paskiej y偶eczce soli i sodkiej papryki; p贸 paskiej y偶eczki pieprzu; szczypta gaki muszkatoowej i ewentualnie odrobina chili (jeli lubisz). Cao dokadnie wymieszaj przy pomocy r贸zgi kuchennej (na jednolity pyn). 

Na warstw cebulki z kiebas wy贸偶 drug poow sera (tartego lub w plasterkach) a nastpnie wlej te偶 pyn mleczno jajeczny z przyprawami. Pyn postaraj si wylewa r贸wno na caej powierzchni zapiekanki. 

Naczynie z gotow do pieczenia zapiekank ziemniaczan z kiebas umie w piekarniku nagrzanym do 180 stopni. Wybierz rodkow p贸k z opcj pieczenia g贸ra/d贸. Zapiekank ziemniaczan piecz bez przykrycia przez 40 minut (lub du偶ej, jeli ziemniaki nie byy po tym czasie mikkie). 

|===

[.text-center]
== Zdjcia
