= Zapiekanka makaronowa +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 1 h
* 3 porcje
* https://www.kuchnia-domowa.pl/przepisy/dania-glowne/148-zapiekanka-makaronowa-z-szynka[link do źródła przepisu]

== Składniki
* ok. 170 g makaronu (użyłam cienkie rurki)
* 150 g szynki
* 150 g startego sera żółtego typu Ementaler lub Gouda
* 500 ml bulionu mięsnego lub warzywnego
* 100 ml słodkiej, płynnej śmietanki 30- 36%
* sól, pieprz, słodka papryka i dowolne zioła
* 2 łyżki koncentratu pomidorowego
* 1 łyżka mąki pszennej

|
== Przygotowanie
 
Surowy makaron wsypać na naczynia żaroodpornego.

Szynkę pokroić w małą kostkę. Wyłożyć na makaron.

Bulion i śmietanę zagotować. Dodać koncentrat pomidorowy. Wymieszać.

Mąkę wymieszać z małą ilością wody (ok. 2- 3 łyżki) tak, aby nie było grudek. Dodać do bulionu, mieszając i gotować 1 minutę. Przyprawić do smaku solą, pieprzem, papryką i ziołami. (Sos będzie rzadki).

Sosem zalać makaron i szynkę. (Dokładnie przykryć cały makaron, aby ładnie ugotował się w sosie). Posypać startym serem. (Ser zatopi się częściowo w sosie).

Odkryte naczynie żaroodporne wstawić do nagrzanego piekarnika i piec przez ok. 30 minut w temperaturze 200°C, grzałka góra- dół.

|===

[.text-center]
== Zdjęcia
