= Zapiekanka makaronowa  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 1 godzina
* 3 porcje
* https://www.kuchnia-domowa.pl/przepisy/dania-glowne/148-zapiekanka-makaronowa-z-szynka[link do 藕r贸da przepisu]

== Skadniki

* ok. 170 g makaronu (u偶yam cienkie rurki)
* 150 g szynki
* 150 g startego sera 偶贸tego typu Ementaler lub Gouda
* 500 ml bulionu misnego lub warzywnego
* 100 ml sodkiej, pynnej mietanki 30- 36%
* s贸l, pieprz, sodka papryka i dowolne zioa
* 2 y偶ki koncentratu pomidorowego
* 1 y偶ka mki pszennej

|
== Przygotowanie
 
Surowy makaron wsypa na naczynia 偶aroodpornego.

Szynk pokroi w ma kostk. Wyo偶y na makaron.

Bulion i mietan zagotowa. Doda koncentrat pomidorowy. Wymiesza.

Mk wymiesza z ma iloci wody (ok. 2- 3 y偶ki) tak, aby nie byo grudek. Doda do bulionu, mieszajc i gotowa 1 minut. Przyprawi do smaku sol, pieprzem, papryk i zioami. (Sos bdzie rzadki).

Sosem zala makaron i szynk. (Dokadnie przykry cay makaron, aby adnie ugotowa si w sosie). Posypa startym serem. (Ser zatopi si czciowo w sosie).

Odkryte naczynie 偶aroodporne wstawi do nagrzanego piekarnika i piec przez ok. 30 minut w temperaturze 200掳C, grzaka g贸ra- d贸.

|===

[.text-center]
== Zdjcia
