= Zapiekanka makaronowa ze szparagami +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 35 minut
* 2 - 3 porcje
* https://www.kwestiasmaku.com/przepis/zapiekanka-makaronowa-ze-szparagami-i-lososiem-wedzonym[link do źródła przepisu]

== Składniki
* 2 szklanki makaronu kokardki
* 1 pęczek (500 g) szparagów
* 100 g wędzonego łososia
* pęczek koperku
* pęczek szczypiorku
* 2 łyżki masła
* 2 łyżki mąki pszennej
* 300 ml mleka
* 1/3 łyżeczki tartej gałki muszkatołowej
* 50 g tartego parmezanu lub grana padano

|
== Przygotowanie


Piekarnik nagrzać do 190 stopni C.

Zagotować osoloną wodę w dużym garnku. Wrzucić makaron i gotować al dente (wg. instrukcji na opakowaniu). Na ostatnią minutę gotowania makaronu dodać do niego szparagi: należy je wcześniej opłukać, odłamać twarde końce (same złamią się w odpowiednim miejscu), pokroić na desce na kawałki.

W czasie gdy makaron się gotuje przygotować sos: w garnku roztopić masło, dodać mąkę i wymieszać drewnianą łyżką, następnie smażyć przez ok. 2 minuty. Dodać mleko i wymieszać rózgą, następnie zagotować co chwilę mieszając. Gotować przez ok. 2 minuty. Doprawić solą, pieprzem oraz gałką muszkatołową. Odstawić z ognia, dodać starty ser i wymieszać do rozpuszczenia.

Makaron wraz ze szparagami odcedzić i wyłożyć do wysmarowanej oliwą formy żaroodpornej.

Na wierzchu ułożyć kawałki łososia wędzonego a następnie wyłożyć sos.

Wstawić do nagrzanego piekarnika i piec przez 15 minut bez przykrycia.

Po upieczeniu posypać posiekanym koperkiem i szczypiorkiem.

|===

[.text-center]
== Zdjęcia
