= Zielone curry z groszkiem cukrowym  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: 45 min
* 4 porcje
* https://kuchnialidla.pl/zielone-curry-z-groszkiem-cukrowym[link do 藕r贸da przepisu]

== Skadniki
* pieprz biay - 1 szczypta
* cebula - 1 szt.
* cukier - 1 szczypta
* kurczak filety z piersi - 2 szt.
* maso - 1 y偶ka
* olej rzepakowy - 2 y偶ki
* pieczarka - 200 g
* s贸l - 1 szczypta
* szczypior cebuli - 24 g
* limonka - 1 szt.
* mleczko kokosowe - 200 ml
* zielona pasta curry - 2 y偶ki
* groszek cukrowy - 100 g
* zbek czosnku - 1 szt.
* ry偶 jaminowy - 200 g

|
== Przygotowanie
Piersi kurczaka kroimy w paski o szerokoci 0,5 cm. Doprawiamy sol i pieprzem. Sma偶ymy na rozgrzanym oleju na zoty kolor.

Pieczarki kroimy w wiartki i podsma偶amy na rozgrzanym male. Dodajemy drobno posiekan cebul i czosnek. Na tej samej patelni podgrzewamy past curry. Dodajemy mleczko kokosowe i odrobin wody. Redukujemy, a偶 sos zgstnieje.

Do curry dodajemy podsma偶onego kurczaka i surowy groszek. Doprawiamy sol, pieprzem, cukrem, otart sk贸rk i sokiem z limonki. Posypujemy posiekanym szczypiorkiem.

Podajemy z ugotowanym ry偶em jaminowym.

|===

[.text-center]
== Zdjcia
