= Zielone curry z groszkiem cukrowym

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 45 min
* 4 porcje
* https://kuchnialidla.pl/zielone-curry-z-groszkiem-cukrowym[link do źródła przepisu]

== Składniki
* pieprz biały - 1 szczypta
* cebula - 1 szt.
* cukier - 1 szczypta
* kurczak filety z piersi - 2 szt.
* masło - 1 łyżka
* olej rzepakowy - 2 łyżki
* pieczarka - 200 g
* sól - 1 szczypta
* szczypior cebuli - 24 g
* limonka - 1 szt.
* mleczko kokosowe - 200 ml
* zielona pasta curry - 2 łyżki
* groszek cukrowy - 100 g
* ząbek czosnku - 1 szt.
* ryż jaśminowy - 200 g

|
== Przygotowanie
Piersi kurczaka kroimy w paski o szerokości 0,5 cm. Doprawiamy solą i pieprzem. Smażymy na rozgrzanym oleju na złoty kolor.

Pieczarki kroimy w ćwiartki i podsmażamy na rozgrzanym maśle. Dodajemy drobno posiekaną cebulę i czosnek. Na tej samej patelni podgrzewamy pastę curry. Dodajemy mleczko kokosowe i odrobinę wody. Redukujemy, aż sos zgęstnieje.

Do curry dodajemy podsmażonego kurczaka i surowy groszek. Doprawiamy solą, pieprzem, cukrem, otartą skórką i sokiem z limonki. Posypujemy posiekanym szczypiorkiem.

Podajemy z ugotowanym ryżem jaśminowym.

== Zdjęcia
|===
