= Ziemniaki faszerowane +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 1 h 45 min
* 4 porcje
* https://www.winiary.pl/przepisy/ziemniaki-faszerowane-serem-szynka-lub-boczkiem-z-sosem-czosnkowym[link do źródła przepisu]

== Składniki
* 4 ziemniaki
* 3 łyżki oleju rzepakowego
* trochę soli i pieprzu do smaku
* 4 plastrów szynki
* 100 g sera edamskiego
* 1 łyżeczka szczypiorku
* 50 g majonezu dekoracyjnego
* 150 g jogurtu greckiego
* 1 ząbek czosnku

|
== Przygotowanie

Rozgrzej piekarnik do 200°C. Spore ziemniaki podobnej wielkości umyj dokładnie i osusz. Nie obieraj.

Przy pomocy ostrego noża natnij ziemniaki w poprzek w odstępach ok. 0,5 centymetrowych, ale nie do końca ziemniaka.

Przy pomocy pędzelka albo ręcznika papierowego natrzyj ziemniaki olejem rzepakowym albo oliwą, możesz też włożyć w szparki kawałki masła. Posól i popieprz.

Włóż ziemniaki do brytfanki i piecz ok. 45-60 minut (w zależności od wielkości ziemniaków), aż ziemniaczki będą zarumienione.

Wyjmij z piekarnika, włóż kawałki sera w ziemniaki i włóż z powrotem na ok. 5 minut, aż ser się pięknie roztopi.

W międzyczasie na patelni podsmaż szynkę lub boczek, pokrojone w kostkę i zrób sos czosnkowy (wymieszaj składniki), posiekaj też szczypiorek.

Ziemniaki wyjmij z piekarnika i podawaj posypane skwareczkami, z sosem i szczypiorkiem.

|===

[.text-center]
== Zdjęcia
