= Ziemniaki faszerowane  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 1 godzina 45 minut
* 4 porcje
* https://www.winiary.pl/przepisy/ziemniaki-faszerowane-serem-szynka-lub-boczkiem-z-sosem-czosnkowym[link do 藕r贸da przepisu]

== Skadniki

* 4 ziemniaki
* 3 y偶ki oleju rzepakowego
* troch soli i pieprzu do smaku
* 4 plastr贸w szynki
* 100 g sera edamskiego
* 1 y偶eczka szczypiorku
* 50 g majonezu dekoracyjnego
* 150 g jogurtu greckiego
* 1 zbek czosnku

|
== Przygotowanie

Rozgrzej piekarnik do 200掳C. Spore ziemniaki podobnej wielkoci umyj dokadnie i osusz. Nie obieraj.

Przy pomocy ostrego no偶a natnij ziemniaki w poprzek w odstpach ok. 0,5 centymetrowych, ale nie do koca ziemniaka.

Przy pomocy pdzelka albo rcznika papierowego natrzyj ziemniaki olejem rzepakowym albo oliw, mo偶esz te偶 wo偶y w szparki kawaki masa. Pos贸l i popieprz.

W贸偶 ziemniaki do brytfanki i piecz ok. 45-60 minut (w zale偶noci od wielkoci ziemniak贸w), a偶 ziemniaczki bd zarumienione.

Wyjmij z piekarnika, w贸偶 kawaki sera w ziemniaki i w贸偶 z powrotem na ok. 5 minut, a偶 ser si piknie roztopi.

W midzyczasie na patelni podsma偶 szynk lub boczek, pokrojone w kostk i zr贸b sos czosnkowy (wymieszaj skadniki), posiekaj te偶 szczypiorek.

Ziemniaki wyjmij z piekarnika i podawaj posypane skwareczkami, z sosem i szczypiorkiem.

|===

[.text-center]
== Zdjcia
