= Zrazy wołowe +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 2 h
* 6 porcji
* https://kuchnialidla.pl/zwijane-zrazy-wolowe[link do źródła przepisu]

== Składniki
* cebula - 2 szt.
* pieprz czarny - 1 szczypta
* ogórek kiszony - 2 szt.
* olej - 2 łyżki
* smalec - 50 g
* sól - 1 szczypta
* majeranek suszony - 1 szczypta
* woda - 250 ml
* musztarda dijon - 1 łyżka
* boczek wędzony w plastrach - 100 g
* mąka pszenna - 20 g
* udziec wołowy - 1000 g

|
== Przygotowanie
Cebulę kroimy w piórka, a ogórki kiszone w cienkie paski. Podsmażamy na odrobinie smalcu, doprawiamy solą i pieprzem.

Mięso kroimy w plastry o szerokości ok. 1,5 cm i rozbijamy tłuczkiem. Każdy plaster mięsa smarujemy musztardą i posypujemy majerankiem. Układamy kolejno plastry boczku oraz podsmażoną cebulę z ogórkiem. Zrazy zwijamy i związujemy sznurkiem. Oprószamy mąką i obsmażamy z każdej strony na rozgrzanym smalcu na brązowy kolor. Układamy w naczyniu żeliwnym, podlewamy wodą i dusimy na wolnym ogniu do miękkości przez ok. 1,5 godziny.

Zrazy wyjmujemy. Powstały sos redukujemy, doprawiamy musztardą i majerankiem.

|===

[.text-center]
== Zdjęcia
