= Zrazy wołowe 🥩
:imagesdir: /Recipes/static/images

++++
<div class="recipe-header-actions">
    <a href="../../index.html" class="back-to-home-btn">← Wróć do przepisów</a>
    <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>
</div>
++++

[.recipe-hero]
[.card-image-placeholder]
Brak zdjęcia przepisu 🍲

[.recipe-details]
* 🕒 czas przygotowania: 2 godziny
* 🕒 czas gotowania: 2 godziny
* 👥 4 porcje
* 🔗 https://kuchnialidla.pl/zwijane-zrazy-wolowe[link do źródła przepisu]

[.recipe-columns]
== Składniki

* cebula - 2 szt.
* pieprz czarny - 1 szczypta
* ogórek kiszony - 2 szt.
* olej - 2 łyżki
* smalec - 50 g
* sól - 1 szczypta
* majeranek suszony - 1 szczypta
* woda - 250 ml
* musztarda dijon - 1 łyżka
* boczek wędzony w plastrach - 100 g
* mąka pszenna - 20 g
* udziec wołowy - 1000 g

== Przygotowanie

Cebulę kroimy w piórka, a ogórki kiszone w cienkie paski. Podsmażamy na odrobinie smalcu, doprawiamy solą i pieprzem.

Mięso kroimy w plastry o szerokości ok. 1,5 cm i rozbijamy tłuczkiem. Każdy plaster mięsa smarujemy musztardą i posypujemy majerankiem. Układamy kolejno plastry boczku oraz podsmażoną cebulę z ogórkiem. Zrazy zwijamy i związujemy sznurkiem. Oprószamy mąką i obsmażamy z każdej strony na rozgrzanym smalcu na brązowy kolor. Układamy w naczyniu żeliwnym, podlewamy wodą i dusimy na wolnym ogniu do miękkości przez ok. 1,5 godziny.

Zrazy wyjmujemy. Powstały sos redukujemy, doprawiamy musztardą i majerankiem.

[.recipe-gallery]
== Zdjęcia

[.gallery-grid]
// Tutaj pojawią się zdjęcia
