= Zrazy woowe ォ +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: 2 h
* 6 porcji
* https://kuchnialidla.pl/zwijane-zrazy-wolowe[link do 藕r贸da przepisu]

== Skadniki
* cebula - 2 szt.
* pieprz czarny - 1 szczypta
* og贸rek kiszony - 2 szt.
* olej - 2 y偶ki
* smalec - 50 g
* s贸l - 1 szczypta
* majeranek suszony - 1 szczypta
* woda - 250 ml
* musztarda dijon - 1 y偶ka
* boczek wdzony w plastrach - 100 g
* mka pszenna - 20 g
* udziec woowy - 1000 g

|
== Przygotowanie
Cebul kroimy w pi贸rka, a og贸rki kiszone w cienkie paski. Podsma偶amy na odrobinie smalcu, doprawiamy sol i pieprzem.

Miso kroimy w plastry o szerokoci ok. 1,5 cm i rozbijamy tuczkiem. Ka偶dy plaster misa smarujemy musztard i posypujemy majerankiem. Ukadamy kolejno plastry boczku oraz podsma偶on cebul z og贸rkiem. Zrazy zwijamy i zwizujemy sznurkiem. Opr贸szamy mk i obsma偶amy z ka偶dej strony na rozgrzanym smalcu na brzowy kolor. Ukadamy w naczyniu 偶eliwnym, podlewamy wod i dusimy na wolnym ogniu do mikkoci przez ok. 1,5 godziny.

Zrazy wyjmujemy. Powstay sos redukujemy, doprawiamy musztard i majerankiem.

|===

[.text-center]
== Zdjcia
