= Łosoś z sosem koperkowym

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 35 min
* 2 porcje
* https://www.kwestiasmaku.com/przepis/losos-z-sosem-koperkowym[link do źródła przepisu]

== Składniki
* 350 g filetu z łososia
* 1 łyżka sosu sojowego
* 1 łyżka soku z cytryny
* 1 łyżeczka oleju roślinnego
* 1 łyżeczka syropu klonowego lub miodu
* 3/4 szklanki bulionu, rosołu
* szczypta kurkumy
* 3/4 łyżki mąki
* 1/4 szklanki śmietanki kremówki 30%
* po szczypcie białego i czarnego pieprzu oraz granulowanego czosnku
* 1/2 łyżki masła
* 1/2 pęczka koperku
* 1/2 łyżeczki soku z cytryny
* ziemniaki np. młode
* szparagi (po ok. 6 sztuk na porcję) lub brokuły, fasolka szparagowa (mogą być mrożone)

|
== Przygotowanie
Filet łososia przekroić na 2 porcje, położyć na desce skórką do dołu i przeciągając nożem między skórką a mięsem odciąć skórę pozostawiając ją na desce. Filety opłukać i włożyć do głębokiego talerza, doprawić solą, pieprzem, skropić sosem sojowym, sokiem z cytryny, olejem roślinnym i syropem klonowym lub miodem. Wymieszać, przewrócić na drugą stronę i zostawić do zamarynowania na min. 1 godzinę.

Piekarnik nagrzać do 250 stopni C, łososia ułożyć w żaroodpornym naczyniu, polać resztą marynaty i piec przez 15 minut.

Bulion zagotować z kurkumą. W miseczce dokładnie rozprowadzić mąkę w śmietance, następnie wlewać ją do bulionu ciągle mieszając, zagotować na małym ogniu.

W międzyczasie doprawić solą, białym i czarnym pieprzem oraz czosnkiem w proszku. Gotować przez ok. 1 minutę co chwilę mieszając.

Dodać masło, sok z cytryny i posiekany koperek, podgrzewać jeszcze przez chwilę ciągle mieszając. Odstawić z ognia.

Szparagi ugotować w wodzie (można w wodzie po ziemniakach) - ok. 3,5 minuty. Fasolkę i brokuły (podzielić na różyczki) gotować przez ok. 8 minut (mrożone ok. 5 minut).

Na talerze położyć upieczonego łososia, obok zielone dodatki, ziemniaczki i polać sosem koperkowym.

|===

[.text-center]
== Zdjęcia
