= oso teriyaki  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* 4 porcje
* https://www.kwestiasmaku.com/kuchnia_polska/dania_z_grilla/losos_teriyaki/przepis.html[link do 藕r贸da przepisu]

== Skadniki
* 4 filety z ososia, po ok. 200 g
* 1/2 szklanki sosu teriyaki*
* sok z 1/2 limonki
* 3 y偶ki syropu klonowego (lub 2 y偶ki miodu lub 4 y偶eczki cukru trzcinowego)
* 1 starty zbek czosnku
* 1 y偶eczka startego imbiru
* 1 y偶eczka drobno posiekanej chili
* 2 y偶eczki oleju sezamowego
* 4 y偶eczki ziaren sezamu

|
== Przygotowanie

ososia opuka, osuszy papierowym rcznikiem, peset wyj oci. W wikszej misce wymiesza sos teriyaki, sok z limonki, syrop klonowy (lub mi贸d lub cukier), czosnek, imbir i chilli. Wo偶y ososia i dokadnie wysmarowa marynat. Odstawi na 1/2 - 1 godzin na blat kuchenny.

ososia wyj z marynaty. Marynat wla do rondelka i gotowa przez okoo 10 - 15 minut, a偶 zgstnieje. Powstay sos teriyaki przecedzi przez sitko, a nastpnie wymiesza z olejem sezamowym. Na suchej patelni, na maym ogniu zrumieni ziarna sezamu.

ososia uo偶y sk贸rk do dou na grillu (lub patelni grillowej) i grillowa przez okoo 8 minut, a偶 miso bdzie wysma偶one do 2/3 wysokoci filetu, a sk贸rka bdzie chrupica. Nastpnie przewr贸ci na drug stron i grillowa jeszcze przez okoo 2 minuty.

Zdj sk贸rk z filet贸w, pola ciepym sosem teriyaki i posypa zrumienionym sezamem.

|===

[.text-center]
== Zdjcia
