= oso z sosem koperkowym  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: 35 min
* 2 porcje
* https://www.kwestiasmaku.com/przepis/losos-z-sosem-koperkowym[link do 藕r贸da przepisu]

== Skadniki
* 350 g filetu z ososia
* 1 y偶ka sosu sojowego
* 1 y偶ka soku z cytryny
* 1 y偶eczka oleju rolinnego
* 1 y偶eczka syropu klonowego lub miodu
* 3/4 szklanki bulionu, rosou
* szczypta kurkumy
* 3/4 y偶ki mki
* 1/4 szklanki mietanki krem贸wki 30%
* po szczypcie biaego i czarnego pieprzu oraz granulowanego czosnku
* 1/2 y偶ki masa
* 1/2 pczka koperku
* 1/2 y偶eczki soku z cytryny
* ziemniaki np. mode
* szparagi (po ok. 6 sztuk na porcj) lub brokuy, fasolka szparagowa (mog by mro偶one)

|
== Przygotowanie
Filet ososia przekroi na 2 porcje, poo偶y na desce sk贸rk do dou i przecigajc no偶em midzy sk贸rk a misem odci sk贸r pozostawiajc j na desce. Filety opuka i wo偶y do gbokiego talerza, doprawi sol, pieprzem, skropi sosem sojowym, sokiem z cytryny, olejem rolinnym i syropem klonowym lub miodem. Wymiesza, przewr贸ci na drug stron i zostawi do zamarynowania na min. 1 godzin.

Piekarnik nagrza do 250 stopni C, ososia uo偶y w 偶aroodpornym naczyniu, pola reszt marynaty i piec przez 15 minut.

Bulion zagotowa z kurkum. W miseczce dokadnie rozprowadzi mk w mietance, nastpnie wlewa j do bulionu cigle mieszajc, zagotowa na maym ogniu.

W midzyczasie doprawi sol, biaym i czarnym pieprzem oraz czosnkiem w proszku. Gotowa przez ok. 1 minut co chwil mieszajc.

Doda maso, sok z cytryny i posiekany koperek, podgrzewa jeszcze przez chwil cigle mieszajc. Odstawi z ognia.

Szparagi ugotowa w wodzie (mo偶na w wodzie po ziemniakach) - ok. 3,5 minuty. Fasolk i brokuy (podzieli na r贸偶yczki) gotowa przez ok. 8 minut (mro偶one ok. 5 minut).

Na talerze poo偶y upieczonego ososia, obok zielone dodatki, ziemniaczki i pola sosem koperkowym.

|===

[.text-center]
== Zdjcia
