= Sałatka z łososiem i mozzarellą

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 20 min
* 2 porcje
* https://smakowitedania.com/2018/04/salatka-z-rukola-wedzonym-lososiem-i-mozzarella-film.html[link do źródła przepisu]

== Składniki
* 100 g rukoli
* 10-12 pomidorków papryczkowych lub koktajlowych
* 1 czerwona papryka
* 125 g sera mozzarella
* 125 g wędzonego łososia

Sos:
* 3 łyżki oliwy z oliwek
* 1 łyżka miodu
* 2 łyżki musztardy
* 1 łyżeczka soku z cytryny
* czarny pieprz
* sól

|
== Przygotowanie
Do małej miseczki wlewamy oliwę z oliwek, dodajemy musztardę, miód oraz sok z cytryny, całość doprawiamy szczyptą soli oraz czarnym pieprzem i wszystko dokładnie mieszamy.

Umyte pomidorki papryczkowe lub koktajlowe przekrawamy na pół. Ser mozzarella kroimy w większą kostkę. Czerwoną paprykę paprykę kroimy w kostkę. Wędzonego łososia kroimy w niewielkie kawałki ale niezbyt małe.
Na płaskich talerzach układamy umytą i osuszoną rukolę, na rukoli umieszczamy połówki pomidorków, pokrojoną mozzarellę oraz paprykę a na wierzchu sałatki umieszczamy pokrojonego łososia.
Sałatkę polewamy przygotowanym sosem i wstawiamy na pół godziny do lodówki.

== Zdjęcia
|===
