= Bucatini alla amatriciana +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 25 min
* 4 porcji
* https://www.chilliczosnekioliwa.pl/2022/01/bucatini-all-amatriciana.html[link do źródła przepisu]

== Składniki
* 150 g guanciale - wędzonego podgardla (można zamienić na pancettę)
* 1 łyżka oliwy
* 1/2 łyżeczki chili w płatkach
* 1/2 łyżeczki świeżo zmielonego czarnego pieprzu
* 60 ml białego wytrawnego wina
* 1 puszka (400 g) całych pomidorów
* sól do smaku
* 400 g makaronu bucatini (lub spaghetti)
* 50 g Pecorino Romano do posypania
* opcjonalnie - świeża bazylia lub natka pietruszki do przystrojenia

|
== Przygotowanie

Zgromadź wszystkie składniki. Z guanciale usuń skórę, następnie pokrój je na plastry o grubości 1 cm, a te na paski o szerokości ok. 1/2 cm. Jeśli masz guanciale w cienkich plasterkach, to pokrój je na paski.

Na dużej patelni rozgrzej oliwę i wrzuć na nią guanciale. Smaż często mieszając, aż guanciale się przyrumieni, ok. 7-8 min.

Dopraw chilli w płatkach oraz pieprzem i smaż jeszcze chwilkę.

Teraz wlej na patelnię wino. Gotuj często mieszając, pozwalając aby większość wina odparowała. Jednocześnie zeskrobuj kawałeczki guanciale z patelni.

Dodaj pomidory z puszki, rozgniatając je wcześniej w dłoniach lub widelcem. Zmniejsz ogień do małego i gotuj sos przez ok. 10 min., aż zgęstnieje. Spróbuj sosu i w razie potrzeby dopraw go solą i pieprzem.

W międzyczasie zagotuj duży garnek osolonej wody. Wrzuć do niego bucatini i gotuj 2 minuty krócej, niż podaje czas na opakowaniu. Odcedź makaron pozostawiając 1/2 szklanki wody z gotowania.

Gdy sos zgęstnieje, wrzuć do niego makaron razem z wodą z gotowania i szybko mieszaj, aby dokładnie obtoczył się sosem. Gotuj przez ok. 2 minuty.

Makaron przełóż na talerze i posyp startym serem Pecorino. Jeśli chcesz możesz go udekorować listkami bazylii lub natki pietruszki. Podawaj od razu.

|===

[.text-center]
== Zdjęcia
