= Bucatini alla amatriciana  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 25 minut
* 4 porcji
* https://www.chilliczosnekioliwa.pl/2022/01/bucatini-all-amatriciana.html[link do 藕r贸da przepisu]

== Skadniki

* 150 g guanciale - wdzonego podgardla (mo偶na zamieni na pancett)
* 1 y偶ka oliwy
* 1/2 y偶eczki chili w patkach
* 1/2 y偶eczki wie偶o zmielonego czarnego pieprzu
* 60 ml biaego wytrawnego wina
* 1 puszka (400 g) caych pomidor贸w
* s贸l do smaku
* 400 g makaronu bucatini (lub spaghetti)
* 50 g Pecorino Romano do posypania
* opcjonalnie - wie偶a bazylia lub natka pietruszki do przystrojenia

|
== Przygotowanie

Zgromad藕 wszystkie skadniki. Z guanciale usu sk贸r, nastpnie pokr贸j je na plastry o gruboci 1 cm, a te na paski o szerokoci ok. 1/2 cm. Jeli masz guanciale w cienkich plasterkach, to pokr贸j je na paski.

Na du偶ej patelni rozgrzej oliw i wrzu na ni guanciale. Sma偶 czsto mieszajc, a偶 guanciale si przyrumieni, ok. 7-8 minut.

Dopraw chili w patkach oraz pieprzem i sma偶 jeszcze chwilk.

Teraz wlej na patelni wino. Gotuj czsto mieszajc, pozwalajc aby wikszo wina odparowaa. Jednoczenie zeskrobuj kawaeczki guanciale z patelni.

Dodaj pomidory z puszki, rozgniatajc je wczeniej w doniach lub widelcem. Zmniejsz ogie do maego i gotuj sos przez ok. 10 minut., a偶 zgstnieje. Spr贸buj sosu i w razie potrzeby dopraw go sol i pieprzem.

W midzyczasie zagotuj du偶y garnek osolonej wody. Wrzu do niego bucatini i gotuj 2 minuty kr贸cej, ni偶 podaje czas na opakowaniu. Odced藕 makaron pozostawiajc 1/2 szklanki wody z gotowania.

Gdy sos zgstnieje, wrzu do niego makaron razem z wod z gotowania i szybko mieszaj, aby dokadnie obtoczy si sosem. Gotuj przez ok. 2 minuty.

Makaron prze贸偶 na talerze i posyp startym serem Pecorino. Jeli chcesz mo偶esz go udekorowa listkami bazylii lub natki pietruszki. Podawaj od razu.

|===

[.text-center]
== Zdjcia
