= Cannelloni

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 45 min
* 4 porcje
* https://www.kwestiasmaku.com/pasta/cannelloni_z_miesem/przepis.html[link do źródła przepisu]

== Składniki
* 18 rurek cannelloni, około 200 g
* 3 łyżki oliwy extra vergine
* 1 cebula
* 1 ząbek czosnku
* 2 łodygi selera naciowego
* 1 marchewka
* 150 g pancetty lub wędzonego boczku
* 500 g mielonego mięsa wołowego (lub wołowo-wieprzowego)
* 1 szklanka białego wina
* 140 g (4 łyżki) koncentratu pomidorowego
* 1 szklanka gorącego bulionu np. wołowego
* 1 puszka (400 g) pomidorów pelati lub passaty pomidorowej
* 1/2 łyżeczki suszonego oregano (opcjonalnie)
* 30 g masła
* 2 łyżki mąki
* 300 ml mleka
* 1/3 łyżeczki gałki muszkatołowej
* 1/2 szklanki tartego parmezanu

|
== Przygotowanie
Sos boloński: na oliwie, w większym garnku, zeszklić na umiarkowanym ogniu drobno posiekaną cebulę i czosnek, dodać posiekany w drobną kosteczkę seler naciowy oraz startą na drobnej tarce marchewkę. Obsmażyć, następnie przesunąć warzywa na bok i w wolne miejsce włożyć pokrojony w kosteczkę boczek. Zrumienić co jakiś czas mieszając, na koniec wymieszać z warzywami.

Przesunąć wszystko na bok garnka i partiami wkładać mięso: włożyć 1/3 część mięsa i dokładnie obsmażyć mieszając co chwilę, aż zmieni kolor z czerwonego na brązowy. Następnie wymieszać z warzywami i boczkiem, przesunąć na bok, powtórzyć z resztą mięsa.

Wlać wino i gotować na średnim ogniu przez 3 minuty, dodać koncentrat pomidorowy uprzednio rozprowadzony w 3 łyżkach gorącego bulionu, dokładnie wymieszać. Wlać resztę gorącego bulionu, zagotować, dodać passatę pomidorową lub zmiksowane pomidory pelati z puszki. Doprawić solą, pieprzem i oregano. Przykryć i gotować na małym ogniu przez 2 godziny. Od czasu do czasu zamieszać.

Sos beszamelowy: roztopić masło na patelni lub w garnku, dodać mąkę i smażyć przez około 2 minuty na umiarkowanym ogniu ciągle mieszając. Stopniowo wlewać mleko cały czas mieszając aż sos zgęstnieje i będzie gładki. Doprawić solą, gałką muszkatołową, dodać połowę startego sera, wymieszać i podgrzać aż ser się rozpuści, odstawić z ognia.

Piekarnik nagrzać do 180 stopni. Przygotować formę żaroodporną (lub dwie mniejsze) i wyłożyć ją suchymi rurkami cannelloni. Stawiać pionowo kolejne rurki i napełniać je farszem mięsnym. Przewracać je na bok i układać jedną przy drugiej. Przykryć sosem beszamelowym, posypać resztą sera i wstawić do nagrzanego piekarnika. Piec przez 23 minuty. Pod koniec można przełączyć na grill i przez chwilkę piec aby lekko zrumienić wierzch, ale nie jest to konieczne.

|===

[.text-center]
== Zdjęcia
