= Makaron z pieczonymi pomidorami 🌱 +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++
:imagesdir: /Recipes/static/images

[.recipe-hero]
[.card-image-placeholder]
Brak zdjęcia przepisu 🍲

[.recipe-details]
* 🕒 czas przygotowania: 35 minut
* 🕒 czas gotowania: 35 minut
* 👥 2 porcje
* 🔗 https://www.kwestiasmaku.com/przepis/makaron-z-pieczonymi-pomidorami[link do źródła przepisu]

[.recipe-columns]
== Składniki
* 250 g makaronu (np. większego jak Rigatoni, Peccheri)
* 600 g pomidorów
* 1 ząbek czosnku
* ok. pół szklanki listków bazylii
* 1 kulka białej mozzarelli (np. burrata lub zwykła)
* sól morskia i świeżo zmielony pieprz
* 4 łyżki oliwy extra vergine

== Przygotowanie
Piekarnik nagrzać do 190 stopni C. Pomidory umyć, pokroić w nieco większą kostkę, włożyć do odpowiednio dużego naczynia żaroodpornego.

Dodać obrany i pokrojony na cienkie plasterki czosnek a między pomidory wcisnąć połowę porwanych liści bazylii.

Skropić oliwą, doprawić solą morską i pieprzem. Piec bez przykrycia przez ok. 20 minut. Na 2 - 3 minuty przed końcem posypać pokrojoną w kostkę mozzarellą.

W międzyczasie ugotować makaron w osolonej wodzie. Odcedzić, wyłożyć do głębokich talerzy. Na wierzch wyłożyć pomidory (wcześniej można usunąć z nich skórkę) wraz z sokami z pieczeni i mozzarellę. Posypać resztą bazylii, doprawić w razie potrzeby solą.

[.recipe-gallery]
== Zdjęcia

[.gallery-grid]
// Tutaj pojawią się zdjęcia
