= +++<a href="../../index.html" class="back-to-home-btn">← Wróć do przepisów</a>+++ Makaron z krewetkami 🦐 +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++
:imagesdir: /Recipes/static/images

[.recipe-hero]
[.card-image-placeholder]
Brak zdjęcia przepisu 🍲

[.recipe-details]
* 🕒 czas przygotowania: 25 minut
* 🕒 czas gotowania: 25 minut
* 👥 2 porcje
* 🔗 https://www.kwestiasmaku.com/przepis/makaron-z-krewetkami[link do źródła przepisu]

[.recipe-columns]
== Składniki
* 200 g mrożonych krewetek
* 125 g makaronu np. tagliatelle
* 1 łyżka oliwy extra vergine
* ⅓ cebuli
* ½ łyżki masła
* ½ łyżeczki suszonego oregano
* 2 ząbki czosnku
* 6 pomidorków koktajlowych
* 2 łyżki posiekanej natki pietruszki
* 125 ml śmietanki 30%

== Przygotowanie
Krewetki rozmrozić, oczyścić jeśli jest konieczność, oderwać ogonki, opłukać i osuszyć.

Makaron ugotować w osolonej wodzie zgodnie z instrukcją na opakowaniu.

Na dużej patelni na łyżce oliwy poddusić pokrojoną w kosteczkę cebulę. Dodać masło, oregano i starty czosnek, chwilę razem podsmażyć.

Dodać krewetki i smażyć przez ok. 1 minutę co chwilę mieszając, doprawić solą oraz pieprzem.

Dodać pokrojone na ćwiartki pomidorki koktajlowe oraz natkę pietruszki. Wymieszać i smażyć razem przez pół minuty.

Wlać śmietankę i zagotować. Gotować przez ok. 1 minutę aż sos zgęstnieje, doprawić świeżo zmielonym pieprzem oraz solą w razie potrzeby.

Dodać odcedzony makaron i wszystko razem podgrzać.

[.recipe-gallery]
== Zdjęcia

[.gallery-grid]
// Tutaj pojawią się zdjęcia
