= Makaron z brokuami  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: 30 minut
* czas gotowania makaronu: 12 minut
* czas gotowania broku贸w: 7 minut
* liczba porcji: okoo 1330 g dania
* https://aniagotuje.pl/przepis/makaron-z-brokulami[link do 藕r贸da przepisu]

== Skadniki
* 300 g makaronu np. Rigatoni - waga przed gotowaniem
* troch ponad p贸 szklanki wody po gotowanym makaronie - okoo 130 ml
* 1 redni lub may broku - okoo 580 g
* 1 spora cebula - do 220 g
* 1 zbek czosnku - okoo 5 g
* 6 y偶ek mietanki krem贸wki 30 %
* 1 y偶ka oleju do sma偶enia
* 1 y偶ka masa klarowanego
* 1 y偶eczka skrobi ziemniaczanej lub mki pszennej
* 40 g sera typu parmezan lub cheddar
* przyprawy: 1/3 y偶eczki soli, po 1/4 paskiej y偶eczki pieprzu, szczypta gaki muszkatoowej
* ewentualne dodatki: sok z cytryny, ketchup, mleko, wicej tartego sera

|
== Przygotowanie
W pierwszej kolejnoci polecam ugotowa brokuy. M贸j broku wa偶y okoo 580 gram贸w. Odciam same r贸偶yczki i wyszo mi 410 gram贸w r贸偶yczek. W garnku zagotuj wod. Dodaj do niej pask y偶eczk soli. Na wrztek "wrzu" r贸偶yczki brokuu i gotuj je bez przykrycia przez okoo siedem minut. Brokuy powinny by wystarczajco mikkie, ale jdrne jednoczenie. Po siedmiu minutach gotowania wy贸w r贸偶yczki brokuu i odced藕 je na sitku. Po przestudzeniu mo偶na je drobniej pokroi i umieci w misce.

Kolejno polecam ugotowa makaron i zacz szykowa sos (najlepiej makaron gotowa r贸wnoczenie z szykowaniem sosu). Do garnka wlej wod i doprowad藕 j do wrzenia. Na ugotowanie 300 gram贸w makaronu potrzebujesz 10 szklanek wody. Wod pos贸l dopiero, gdy zacznie si gotowa. Do wrztku wsyp te偶 pask y偶k soli. W garnku umie makaron i gotuj al dente. Makaron gotuj zazwyczaj o minut lub dwie du偶ej, ni偶 zaleca producent na opakowaniu. Tym razem jednak gotowaam go tak dugo, jak wskazyway zalecenia na opakowaniu, czyli 12 minut.

Ugotowany makaron powinien by spr偶ysty, ale mikki. Uwaga - podczas odlewania wody z makaronu odlej p贸 szklanki wody, w kt贸rej gotowa si makaron. U偶yjesz jej do sosu. Ugotowany makaron prze贸偶 na durszlak i od razu z powrotem do garnka, w kt贸rym si gotowa lub do miski. Makaron ma by mokry. Po ugotowaniu makaron wa偶y u mnie okoo 585 gram贸w.

Porada: U偶yam makaron Rigatoni, ale mo偶esz te偶 miao ugotowa inny makaron: widerki, muszelki, kopytka, czy nawet spaghetti lub tagliatelle. Mo偶esz te偶 sign po makaron gryczany lub makaron z ciecierzycy lub soczewicy. 

Nagrzej redniej wielkoci patelni z grubszym dnem. Na patelni umie y偶k masa klarowanego oraz wlej y偶k oliwy lub oleju do sma偶enia. Cebul obierz i posiekaj drobno. Umie j na patelni z tuszczem i podsma偶aj na redniej mocy palnika przez okoo 10 minut. Cebula ma si zeszkli. Mo偶e si te偶 lekko zarumieni. Po tym czasie na patelni dodaj te偶 niedu偶y zbek czosnku, kt贸ry wczeniej obierz i przecinij przez prask. Zmniejsz moc palnika do niskiej i podgrzewaj cebul z czosnkiem nie du偶ej ni偶 pi minut (uwa偶aj, by czosnek si nie rumieni, poniewa偶 mo偶e si zrobi gorzki). 

Na patelni z podsma偶on cebul z czosnkiem dodaj przyprawy: 1/3 y偶eczki soli, po 1/4 paskiej y偶eczki pieprzu, szczypta gaki muszkatoowej. W osobnym naczyniu wymieszaj ze sob: przestudzone p贸 szklanki wody po gotowanym makaronie, sze y偶ek mietanki krem贸wki 30 % oraz jedn y偶eczk skrobi ziemniaczanej lub mki pszennej. Dokadnie rozetrzyj mk w pynie, by cao miaa gadk konsystencj. Pyn wlej na patelni. Dodaj r贸wnie偶 okoo 40 gram贸w drobno startego sera typu parmezan lub cheddar.

Mieszaj sos i podgrzewaj go na troch wy偶szej ni偶 rednia moc palnika, a偶 sos zgstnieje i zacznie si delikatnie gotowa. Jeli sos jest za gsty, to dodaj troch zwykego mleka, bulionu (warzywny lub drobiowy jeli jadasz miso) lub wody. Sprawd藕 te偶 smak sosu i w razie potrzeby dodaj wicej soli lub pieprzu. 

Makaron z brokuami mo偶esz poda na dwa sposoby. Mo偶esz cay sos z patelni wyla do miski z ugotowanym makaronem. Nastpnie doo偶y jeszcze pokrojone drobniej kawaki brokuu. Cao wymiesza i podawa lub umieci w naczyniu do zapiekania. Od g贸ry posypa makaron z brokuami tartym serem i zapiec w piekarniku z grzak od g贸ry - wystarczy 10 minut w temperaturze 180 stopni.

Drugi spos贸b zastosowaam poni偶ej. Do prawie gotowego sosu dodaj cz pokrojowych drobniej r贸偶yczek brokuu. Cao zamieszaj, zagotuj i wycz. 

Makaron roz贸偶 na talarze. Na makaron wy贸偶 po porcji sosu, a na sam g贸r reszt posiekanych broku贸w. Cao opr贸sz wie偶o mielonym pieprzem lub posyp dodatkow porcj tartego sera. Podawaj jeszcze gorce.

|===

[.text-center]
== Zdjcia
