= Makaron ze szpinakiem 🌱
:imagesdir: /Recipes/static/images

++++
<div class="recipe-header-actions">
    <a href="../../index.html" class="back-to-home-btn">← Wróć do przepisów</a>
    <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>
</div>
++++

[.recipe-hero]
[.card-image-placeholder]
Brak zdjęcia przepisu 🍲

[.recipe-details]
* 🕒 czas przygotowania: 25 minut
* 🕒 czas gotowania: 25 minut
* 👥 2 porcje
* 🔗 https://www.kwestiasmaku.com/przepis/makaron-ze-szpinakiem[link do źródła przepisu]

[.recipe-columns]
== Składniki

* 150 g makaronu np. świderki, fusilli, penne
* ½ cebuli
* 2 ząbki czosnku
* 1 łyżka oliwy
* ½ łyżki masła
* 150 g szpinaku
* ⅓ szklanki śmietanki 30%
* ⅓ szklanki tartego parmezanu

== Przygotowanie

Makaron ugotować al dente w osolonej wodzie. Szpinak opłukać i odcedzić.

Na patelni na oliwie i maśle zeszklić pokrojoną w kosteczkę cebulę (ok. 5 - 7 minut). Doprawić solą, dodać przeciśnięty przez praskę czosnek i smażyć jeszcze przez ok. 2 minuty.

Dodać szpinak i mieszając podgrzewać przez ok. 1 minutę aż zwiędnie.

Wlać śmietankę, doprawić świeżo zmielonym pieprzem i solą, całość zagotować. Dodać odcedzony makaron i wymieszać.

Połączyć z ⅓ ilości sera, resztę wykorzystać do posypania makaronu.

[.recipe-gallery]
== Zdjęcia

[.gallery-grid]
// Tutaj pojawią się zdjęcia
