= +++<a href="../../index.html" class="back-to-home-btn">← Wróć do przepisów</a>+++ Makaron z cukinią i bakłażanem 🌱 +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++
:imagesdir: /Recipes/static/images

[.recipe-hero]
[.card-image-placeholder]
Brak zdjęcia przepisu 🍲

[.recipe-details]
* 🕒 czas gotowania: 1 godzina
* 👥 4 porcje
* 🔗 Przepis z zeszytu mamy

[.recipe-columns]
== Składniki

* 350g makaronu muszelki
* 1 cukinia } ugrillować
* 1 bakłażan } ugrillować
* 1 p. bazylii
* 50g tartego sera / grand padano
* orzeszki ziemne
* parmezan

== Przygotowanie

Makaron muszelki ugotować al dente w osolonej wodzie według instrukcji na opakowaniu, a następnie odcedzić. Cukinię oraz bakłażana pokroić w plastry lub podłużne paski i ugrillować na patelni grillowej bądź w piekarniku, aż będą miękkie i powstaną na nich ciemne paski. W międzyczasie przygotować ekspresowe pesto lub posypkę: orzeszki ziemne uprażyć na suchej patelni, a pęczek bazylii drobno posiekać lub zblendować z tartym serem grana padano i odrobiną oliwy. Ugotowany, gorący makaron wymieszać z ugrillowanymi warzywami oraz przygotowaną bazylią i serem. Przed podaniem każdą porcję obficie posypać chrupiącymi orzeszkami ziemnymi oraz dodatkową porcją tartego parmezanu.

[.recipe-gallery]
== Zdjęcia

[.gallery-grid]
// Tutaj pojawią się zdjęcia
