= Makaron z pulpecikami  ォ +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* 4 porcje
* https://www.kwestiasmaku.com/przepis/makaron-z-pulpecikami-w-sosie-pomidorowym[link do 藕r贸da przepisu]

== Skadniki

* 1 may ziemniak
* 400 g mielonego misa woowo-wieprzowego
* 1 maa cebula
* 5 gazek natki pietruszki
* 1 mae jajko
* mka, oliwa extra vergine
* 500 ml przecieru pomidorowego (passaty z butelki)
* kilka lici bazylii
* po ok. 75 g makaronu na porcj
* wie偶o starty parmezan lub grana padano
* s贸l, pieprz, cukier
* mka do obtoczenia

|
== Przygotowanie

Ziemniaka obra, przekroi na p贸 i ugotowa w osolonej wodzie. Odcedzi, dokadnie odparowa i rozgnie prask na puree.

Do zmielonego misa, dodajemy do niego obran i start na drobnej tarce cebul i drobno posiekane listki natki. Miso wymiesza i wyrobi dodajc puree ziemniaczane, s贸l i pieprz do smaku oraz jajko.

Wilgotnymi domi odrywa po okoo p贸 y偶ki misa i odkada na desk. Nastpnie formowa kuleczki wielkoci orzecha woskiego i obtoczy je w mce. W midzyczasie nastawi osolon wod na makaron i ugotowa go al dente.

Gdy wszystkie kuleczki bd ju偶 uformowane, rozgrza du偶 patelni z 4 y偶kami oliwy, stopniowo wkada pulpeciki i sma偶y do czasu a偶 bd dobrze zrumienione. Dopiero wtedy przewr贸ci je na drug stron podwa偶ajc delikatnie opatk. Po ponownym dokadnym podsma偶eniu zrumienia jeszcze z innych stron. W sumie sma偶ymy przez ok. 10 - 12 minut.

Zrobi miejsce na patelni przesuwajc delikatnie cz pulpecik贸w. W wolne miejsce wla przecier pomidorowy, doprawi go sol, pieprzem i y偶eczk cukru. Doda posiekan bazyli, wymiesza i rozprowadzi sos po caej patelni. Po zagotowaniu przykry patelni pokryw i gotowa jeszcze przez ok. 5 - 8 minut a偶 sos bdzie gsty. Jeli jest za bardzo gsty, mo偶na rozciecza go wod z makaronu lub zwyk wod.

Pulpeciki podawa z makaronem i tartym serem. Potraw mo偶na przygotowa wczeniej i odgrzewa.

|===

[.text-center]
== Zdjcia
