= Makaron ze szpinakiem 🌱 +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 25 min
* 2 porcje
* https://www.kwestiasmaku.com/przepis/makaron-ze-szpinakiem[link do źródła przepisu]

== Składniki
* 150 g makaronu np. świderki, fusilli, penne
* 1/2 cebuli
* 2 ząbki czosnku
* 1 łyżka oliwy
* 1/2 łyżki masła
* 150 g szpinaku
* 1/3 szklanki śmietanki 30%
* 1/3 szklanki tartego parmezanu

|
== Przygotowanie
Makaron ugotować al dente w osolonej wodzie. Szpinak opłukać i odcedzić.

Na patelni na oliwie i maśle zeszklić pokrojoną w kosteczkę cebulę (ok. 5 - 7 minut). Doprawić solą, dodać przeciśnięty przez praskę czosnek i smażyć jeszcze przez ok. 2 minuty.

Dodać szpinak i mieszając podgrzewać przez ok. 1 minutę aż zwiędnie.

Wlać śmietankę, doprawić świeżo zmielonym pieprzem i solą, całość zagotować. Dodać odcedzony makaron i wymieszać.

Połączyć z 1/3 ilości sera, resztę wykorzystać do posypania makaronu.

|===

[.text-center]
== Zdjęcia
