= Makaron penne z rukolą i oliwkami 🌱 +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++
:imagesdir: /Recipes/static/images

[.recipe-hero]
[.card-image-placeholder]
Brak zdjęcia przepisu 🍲

[.back-to-home-wrapper]
link:../../index.html[← Wróć do przepisów, role="back-to-home-btn"]

[.recipe-details]
* 🕒 czas gotowania: 1 godzina
* 👥 4 porcje
* 🔗 Przepis z zeszytu mamy

[.recipe-columns]
== Składniki
* 400g makaronu pióra
* 5-6 łyżek oliwy
* 1 czerwona cebula
* 6 ząbków czosnku
* 1 gałązka rozmarynu
* 10-15 czarnych oliwek
* 250g rukoli
* sól i pieprz
* pół cytryny

== Przygotowanie

Makaron ugotować al dente w osolonej wodzie, a następnie odcedzić. Na dużej patelni rozgrzać oliwę, dodać posiekaną czerwoną cebulę, pokrojony w plasterki czosnek oraz gałązkę rozmarynu i całość krótko podsmażyć, aż warzywa zaczną pachnieć. Następnie na patelnię wrzucić świeżą rukolę oraz pokrojone na połówki czarne oliwki. Do warzyw dodać ugotowany makaron penne i całość dokładnie wymieszać, podsmażając na małym ogniu przez około 3-4 minuty, aż rukola lekko zwiędnie. Na koniec danie doprawić do smaku solą oraz pieprzem i przed podaniem obficie skropić sokiem wyciśniętym z połówki cytryny.

[.recipe-gallery]
== Zdjęcia

[.gallery-grid]
// Tutaj pojawią się zdjęcia
