= Makaron chiński z krewetkami +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 20 min
* 4 porcje
* http://blogzapetytem.pl/2018/04/09/makaron-chinski-z-krewetkami-i-warzywami[link do źródła przepisu]

== Składniki
* 15 sztuk krewetek (obranych, bez pancerzy i ogonów)
* 200g makaronu chińskiego Chow Mein lub Mie lub VonTon (waga po ugotowaniu)
* 1 marchew
* 1 mały por
* 1 cebula
* Po kawałku papryki czerwonej, zielonej i żółtej
* pół szklanki groszku konserwowego lub mrożonego
* opcjonalnie: grzyby chińskie, kiełki fasoli mung, pędy bambusa
* 2 ząbki czosnku
* 2 łyżki posiekanej natki pietruszki
* 1 łyżka oleju
* 1 łyżka masła
* 1 łyżeczka startego imbiru
* 1 łyżeczka brązowego cukru
* 3 łyżki sosu sojowego
* pół łyżeczki sosu chilli
* sól morska
* do posypania: ziarna sezamu

|
== Przygotowanie
Makaron przygotowujemy według przepisu na opakowaniu, odsączamy i przepłukujemy zimną wodą

Marchew i papryki kroimy w słupki a por i cebulę w krążki. Na patelni lub w woku rozgrzewamy łyżkę oleju roślinnego i podsmażamy na nim warzywa (marchew, papryki, por, cebulę, groszek i opcjonalnie grzyby, pędy oraz kiełki). Całość dusimy kilka minut, aż warzywa zmiękną

Makaron przekładamy do woka lub na patelnie z warzywami i całość razem przesmażamy. Sos sojowy mieszamy z cukrem, sosem chilli oraz imbirem i  dodajemy do potrawy, mieszamy

Na patelni, na łyżce masła podsmażamy krewetki z przeciśniętym czosnkiem i posiekaną natką pietruszki, delikatnie solimy. Krewetki smażymy przez około 2 minuty, ciągle mieszając

Podsmażone krewetki przekładamy do makaronu z warzywami, mieszamy i wszystko razem przez chwilę podsmażamy. Podajemy posypane podprażonym na suchej patelni sezamem

|===

[.text-center]
== Zdjęcia
