= Makaron z pieczonymi pomidorami  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 35 minut
* 2 porcje
* https://www.kwestiasmaku.com/przepis/makaron-z-pieczonymi-pomidorami[link do 藕r贸da przepisu]

== Skadniki

* 250 g makaronu (np. wikszego jak Rigatoni, Peccheri)
* 600 g pomidor贸w
* 1 zbek czosnku
* ok. p贸 szklanki listk贸w bazylii
* 1 kulka biaej mozzarelli (np. burrata lub zwyka)
* s贸l morskia i wie偶o zmielony pieprz
* 4 y偶ki oliwy extra vergine

|
== Przygotowanie

Piekarnik nagrza do 190 stopni C. Pomidory umy, pokroi w nieco wiksz kostk, wo偶y do odpowiednio du偶ego naczynia 偶aroodpornego.

Doda obrany i pokrojony na cienkie plasterki czosnek a midzy pomidory wcisn poow porwanych lici bazylii.

Skropi oliw, doprawi sol morsk i pieprzem. Piec bez przykrycia przez ok. 20 minut. Na 2 - 3 minuty przed kocem posypa pokrojon w kostk mozzarell.

W midzyczasie ugotowa makaron w osolonej wodzie. Odcedzi, wyo偶y do gbokich talerzy. Na wierzch wyo偶y pomidory (wczeniej mo偶na usun z nich sk贸rk) wraz z sokami z pieczeni i mozzarell. Posypa reszt bazylii, doprawi w razie potrzeby sol.

|===

[.text-center]
== Zdjcia
