= Pesto alla trapanese 🌱 +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++
:imagesdir: /Recipes/static/images

[.recipe-hero]
--
[.recipe-category-label]
Dania główne

[.card-image-placeholder]
Brak zdjęcia przepisu 🍲
--

[.recipe-details]
--
[.recipe-details-item]
🕒 czas przygotowania: 45 minut

[.recipe-details-item]
👥 4 porcje

[.recipe-details-item]
🔗 https://rafalcook.com/2022/06/11/pesto-alla-trapanese[link do źródła przepisu]

--

[.recipe-columns]
--
[.recipe-column-box]
=== Składniki
* pomidorki koktajlowe 250-300 gram
* czosnek 1-2 ząbki
* parmigiano Reggiano 30-50 gram
* płatki migdałowe prażone 50 gram
* świeża bazylia duża garść
* oliwa z oliwek 50-70 ml
* płatki chili do smaku
* sól do smaku
* pieprz świeżo zmielony do smaku
* maccheroni 500 gram
* woda z gotowania makaronu

|

[.recipe-column-box]
=== Przygotowanie
Przede wszystkim pesto alla trapanese jest niezwykle proste i pyszne zarazem.
Po pierwsze włóż składniki do blendera ❗ oczywiście bez makaronu ? i zblenduj.
Po drugie ugotuj makaron według instrukcji na opakowaniu na al dente.
Na koniec przełóż pesto do miski, dodaj gotowy makaron i odrobinę wody z gotowania makaronu i bardzo dobrze wymieszaj.
Nałóż, posyp Parmigiano Reggiano, dopraw pieprzem, dodaj świeżą bazylię i oczywiście zajadaj.
--
