= Ragu alla bolonese +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 3 h
* 6 porcji
* https://madameedith.com/przepis/ragu-bolognese[link do źródła przepisu]

== Składniki
* oliwa z oliwek
* 1 średnia cebula
* 1 średnia marchewka
* 50 g boczku (najlepiej włoskiego - pancetty)
* 500 g mielonego mięsa (można użyć dowolnego: wołowiny, wieprzowiny, cielęciny lub jagnięciny, a najlepiej mieszanki)
* 200 ml czerwonego wina (wytrawnego)
* 200 g koncentratu pomidorowego
* 250 ml bulionu (może być warzywny, a może także rosół)
* 200 ml mleka
* 1 płaska łyżeczka soli
* pieprz
* gruby makaron - najlepiej tagiatelle lub pappardelle
* świeżo stary parmezan
* odrobina posiekanej natki pietruszki i/lub bazylii

|
== Przygotowanie
Cebulę, marchewkę myjemy i kroimy w drobną kostkę.

W żeliwnym garnku rozgrzewamy kilka łyżek oliwy. Wrzucamy warzywa, podsmażamy ok. 10 minut.

Dodajemy pokrojony w drobne paseczki boczek oraz mięso mielone. Przesmażamy wraz z warzywami ok. 15 minut. Mięso powinno się wręcz lekko przypalić i zbrązowieć, by nabrało głębszego smaku umami. Nie martwcie się tym, że będzie suche - podczas powolnego gotowania w sosie nabierze delikatności.

Dodajemy wino i smażmy ok. 2-5 minut aż płyn nieco odparuje.

Wlewamy koncentrat pomidorowy i bulion. Zagotowujemy i zmniejszamy ogień, by sos tylko lekko pyrkotał. Dusimy po przykryciem (u mnie moc palnika 3 na 9), mieszając od czasu do czasu przez 90 minut.

Mleko podgrzewamy i dodajemy małymi partiami do sosu. Dokładnie mieszamy. Zostawiamy na małym gazie na 45 minut. Na końcu doprawiamy solą i pieprzem do smaku.

Ragu serwujemy z szerokim makaronem. Przed podaniem posypujemy parmezanem i opcjonalnie natką pietruszki lub posiekaną bazylią.

Jeśli robicie ragu dzień wcześniej, przed podaniem podgrzejcie je. Jeśli będzie bardzo gęste, wówczas warto dodać odrobinę wody z gotowania makaronu, by rozluźnić sos.

|===

[.text-center]
== Zdjęcia
