= Spaghetti pomodoro  +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: 25 min
* 4 porcje
* https://italia-by-natalia.pl/spaghetti-pomodoro-spaghetti-napoli-przepis[link do 藕r贸da przepisu]

== Skadniki
* 500 g makaronu spaghetti
* 2 puszki krojonych pomidor贸w bez sk贸ry (cznie 800 g) lub odpowiednia ilo przetartych wie偶ych pomidor贸w (bez sk贸rki)
* oliwa z oliwek
* okoo 5 zbk贸w czosnku
* pieprz i s贸l do smaku
* kilka listk贸w wie偶ej bazylii
* opcjonalnie ok 100 g parmigiano reggiano (parmezanu) lub grana padano w kawaku
* opcjonalnie y偶eczka cukru

|
== Przygotowanie
Jeli zdecydujecie si u偶y wie偶ych pomidor贸w, to warto zacz od sparzenia ich, zdjcia sk贸rki i pokrojenia. Nastpnie wstawiamy wod na makaron z dodatkiem szczypty soli. Do du偶ej, gbokiej patelni wlewamy oliw z oliwek w takiej iloci, aby przykry dno. Czosnek siekamy drobno i wsypujemy do garnka, chwil pru偶ymy. Nastpnie dodajemy pomidory, s贸l i pieprz. Cz przepis贸w podaje, by doda do sosu r贸wnie偶 troch cukru. Ja nigdy nie dodaj, bo unikam cukru tam, gdzie mo偶na si bez niego oby, nie mniej jednak dodajcy twierdz, 偶e poprawia smak. Gotujemy okoo dwudziestu minut na maym ogniu. W midzyczasie do wrzcej wody wrzucamy makaron. Przez minut lub dwie gotujemy pod przykryciem, aby obni偶ona wrzuceniem makaronu temperatura w garnku si podniosa, po czym bezwzgldnie zdejmujemy pokrywk. Skrobia uwalniana z makaronu powoduje pienienie si wrztku, dlatego bez zdjcia pokrywki wykipienie macie jak w banku. Makaron gotujemy do momentu, a偶 bdzie al dente, czyli jeszcze troszk twardy, ale na tyle mikki, by mo偶na go byo bez wikszego problemu pogry藕. Do sosu dodajemy odrobin wody z gotowania makaronu, po czym odcedzamy makaron (nie polewamy go jednak zimn wod) lub wyjmujemy z wody, wrzucamy do sosu i chwil podrzucamy patelni, by makaron dobrze przeszed aromatem sosu. Gotowe danie ozdabiamy wie偶 bazyli. Ja mam w zwyczaju dodatkowo podrze kilka listk贸w i posypa nimi danie. Wedug niekt贸rych przepis贸w dodaje si wie偶 bazyli do sosu jeszcze w garnku. Opcjonalnie mo偶na posypa nao偶one na talerz danie wie偶o utartym serem.

|===

[.text-center]
== Zdjcia
