= Spaghetti napoli  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 25 minut
* 4 porcje
* https://italia-by-natalia.pl/spaghetti-pomodoro-spaghetti-napoli-przepis[link do 藕r贸da przepisu]

== Skadniki

* 500 g makaronu spaghetti
* 2 puszki krojonych pomidor贸w bez sk贸ry (cznie 800 g) lub odpowiednia ilo przetartych wie偶ych pomidor贸w (bez sk贸rki)
* oliwa z oliwek
* okoo 5 zbk贸w czosnku
* 1 du偶a cebula
* pieprz i s贸l do smaku
* kilka listk贸w wie偶ej bazylii
* dwie szczypty suszonego oregano
* opcjonalnie ok 100 g parmigiano reggiano (parmezanu) lub grana padano w kawaku
* opcjonalnie y偶eczka cukru

|
== Przygotowanie

Przygotowujemy sos ze wie偶ych pomidor贸w lub korzystamy z puszek. Identycznie jak w przypadku poprzedniego przepisu wlewamy oliw z oliwek do du偶ej, gbokiej patelni w takiej iloci, aby przykry dno. Cebul i czosnek siekamy drobno, wsypujemy na patelni, chwil pru偶ymy. Dodajemy pomidory, s贸l, pieprz i suszone oregano, opcjonalnie odrobin cukru. Gotujemy okoo dwudziestu minut na maym ogniu. W midzyczasie gotujemy makaron al dente. Do sosu dodajemy odrobin wody z gotowania makaronu, po czym odcedzamy makaron (nie polewamy go jednak zimn wod) lub wyjmujemy z wody, wrzucamy makaron do sosu i chwil podrzucamy patelni, by makaron dobrze przeszed aromatem sosu. Gotowe danie ozdabiamy wie偶 bazyli. asuchy uprzednio posypuj wie偶o utartym parmezanem lub grana padano.

|===

[.text-center]
== Zdjcia
