= Spaghetti pomodoro +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 25 min
* 4 porcje
* https://italia-by-natalia.pl/spaghetti-pomodoro-spaghetti-napoli-przepis[link do źródła przepisu]

== Składniki
* 500 g makaronu spaghetti
* 2 puszki krojonych pomidorów bez skóry (łącznie 800 g) lub odpowiednia ilość przetartych świeżych pomidorów (bez skórki)
* oliwa z oliwek
* około 5 ząbków czosnku
* pieprz i sól do smaku
* kilka listków świeżej bazylii
* opcjonalnie ok 100 g parmigiano reggiano (parmezanu) lub grana padano w kawałku
* opcjonalnie łyżeczka cukru

|
== Przygotowanie
Jeśli zdecydujecie się użyć świeżych pomidorów, to warto zacząć od sparzenia ich, zdjęcia skórki i pokrojenia. Następnie wstawiamy wodę na makaron z dodatkiem szczypty soli. Do dużej, głębokiej patelni wlewamy oliwę z oliwek w takiej ilości, aby przykryć dno. Czosnek siekamy drobno i wsypujemy do garnka, chwilę prużymy. Następnie dodajemy pomidory, sól i pieprz. Część przepisów podaje, by dodać do sosu również trochę cukru. Ja nigdy nie dodaję, bo unikam cukru tam, gdzie można się bez niego obyć, nie mniej jednak dodający twierdzą, że poprawia smak. Gotujemy około dwudziestu minut na małym ogniu. W międzyczasie do wrzącej wody wrzucamy makaron. Przez minutę lub dwie gotujemy pod przykryciem, aby obniżona wrzuceniem makaronu temperatura w garnku się podniosła, po czym bezwzględnie zdejmujemy pokrywkę. Skrobia uwalniana z makaronu powoduje pienienie się wrzątku, dlatego bez zdjęcia pokrywki wykipienie macie jak w banku. Makaron gotujemy do momentu, aż będzie al dente, czyli jeszcze troszkę twardy, ale na tyle miękki, by można go było bez większego problemu pogryźć. Do sosu dodajemy odrobinę wody z gotowania makaronu, po czym odcedzamy makaron (nie polewamy go jednak zimną wodą) lub wyjmujemy z wody, wrzucamy do sosu i chwilę podrzucamy patelnią, by makaron dobrze przeszedł aromatem sosu. Gotowe danie ozdabiamy świeżą bazylią. Ja mam w zwyczaju dodatkowo podrzeć kilka listków i posypać nimi danie. Według niektórych przepisów dodaje się świeżą bazylię do sosu jeszcze w garnku. Opcjonalnie można posypać nałożone na talerz danie świeżo utartym serem.

|===

[.text-center]
== Zdjęcia
