= Spaghetti napoli +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 25 min
* 4 porcje
* https://italia-by-natalia.pl/spaghetti-pomodoro-spaghetti-napoli-przepis[link do źródła przepisu]

== Składniki
* 500 g makaronu spaghetti
* 2 puszki krojonych pomidorów bez skóry (łącznie 800 g) lub odpowiednia ilość przetartych świeżych pomidorów (bez skórki)
* oliwa z oliwek
* około 5 ząbków czosnku
* 1 duża cebula
* pieprz i sól do smaku
* kilka listków świeżej bazylii
* dwie szczypty suszonego oregano
* opcjonalnie ok 100 g parmigiano reggiano (parmezanu) lub grana padano w kawałku
* opcjonalnie łyżeczka cukru

|
== Przygotowanie
Przygotowujemy sos ze świeżych pomidorów lub korzystamy z puszek. Identycznie jak w przypadku poprzedniego przepisu wlewamy oliwę z oliwek do dużej, głębokiej patelni w takiej ilości, aby przykryć dno. Cebulę i czosnek siekamy drobno, wsypujemy na patelnię, chwilę prużymy. Dodajemy pomidory, sól, pieprz i suszone oregano, opcjonalnie odrobinę cukru. Gotujemy około dwudziestu minut na małym ogniu. W międzyczasie gotujemy makaron al dente. Do sosu dodajemy odrobinę wody z gotowania makaronu, po czym odcedzamy makaron (nie polewamy go jednak zimną wodą) lub wyjmujemy z wody, wrzucamy makaron do sosu i chwilę podrzucamy patelnią, by makaron dobrze przeszedł aromatem sosu. Gotowe danie ozdabiamy świeżą bazylią. Łasuchy uprzednio posypują świeżo utartym parmezanem lub grana padano.

|===

[.text-center]
== Zdjęcia
