= Hiszpańska zupa z ciecierzycy

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 35 min
* 3 porcje
* https://drive.google.com/file/d/14iUc0uXoa3jIrczjVeJHunoLzb19HLlx/view?usp=share_link[link do źródła przepisu]

== Składniki
* ciecierzyca konserwowa - 1 duży słoik (400 g)
* cebula - 1 sztuka (100 g)
* papryka zielona - 1 sztuka (140 g)
* seler naciowy - 1 łodyga (45 g)
* batat - 1 sztuka (200 g)
* pomidory krojone - 1 szklanka (250 g)
* bulion warzywny lub woda - 4 szklanki (1 l)
* komosa ryżowa (najlepiej czerwona) - 1/2 szklanki (100 g)
* oliwa z oliwek - 1 łyżka (10 g)
* przyprawy: 2 zabki czosnku, 1/2 małej papryczki chili świeżej, 1/2 łyżeczki kminu rzymskiego mielonego, 1//3 łyżeczki kolendry mielonej, 1 łyżeczka papryki słodkiej, 1/2 łyżeczki papryki wędzonej, sok z limonki, sól i pieprz czarny do smaku
* kolendra świeża lub natka pietruszki - 1 niewielki pęczek (30 g)

|
== Przygotowanie
Ciecierzycę płuczemy i odsączamy. W garnku nma oliwie szklimy pokrojoną w dużą kostkę cebulę. Dodajemy przeciśnięty prze praskę czosnek., drobno posiekane chili, kmin rzymski i kolendrę mieloną, smażymy około 2 minut. Do garnka wrzucamy pokrojone w centymetrową kostkę paprykę, seler naciowy i batat. Smażymy 5 minut, co jakiś czas mieszając. Dodajemy pomidory, wlewamy bulion lub wodę i doprowadzamy do wrzenia. Wsypujemy komosę ryżową oraz papryki słodką i wędzoną. Gotujemy około 20 minut. Po tym czasie dodajemy ciecierzycę. Zupę doprawiamy sokiem z limonki, solą i pieprzem. Nalewamy do miseczek i posypujemy posiekaną zieleniną.

|===

[.text-center]
== Zdjęcia

