= Zapiekany ros贸  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: 2,5 h
* 8 porcje
* https://szefowakuchni.pl/przepis/pieczony-rosol/[link do 藕r贸da przepisu]

== Skadniki

* ulubione miso na ros贸 (u mnie porcja drobiowa: 2 udka z kurczaka, 2 skrzydeka, korpus + 1 podudzie z indyka)
* cebula
* 4 marchewki
* por
* korze pietruszki
* kawaek selera
* 3 zbki czosnku
* 2 licie laurowe
* s贸l, pieprz, ziele angielskie, ziarenka pieprzu
* ulubiony makaron do rosou

|
== Przygotowanie

Na blaszce do pieczenia uo偶y miso, oraz wszystkie warzywa (wiksze kawaki przekroi na poow). Cao posypa spor iloci soli oraz pieprzu. Wo偶y do piekarnika rozgrzanego do 200'C na okoo 1 godzin, a偶 wszystko adnie si zarumieni. Czas pieczenia mo偶e si r贸偶ni w zale偶noci od piekarnika oraz wielkoci skadnik贸w.

Po tym czasie miso oraz warzywa przeo偶y do du偶ego garnka, zala wod tak aby przykry wszystkie skadniki (u mnie 3,5 litra). Doda licie laurowe, ziele angielskie, ziarenka pieprzu oraz y偶k soli. Cao gotowa na maym ogniu (ros贸 ma delikatnie pyrka) przez okoo 2 -2,5 godziny.

Na kocu sprawdzi smak i ewentualnie doprawi sol. Podawa z ulubionym makaronem.


|===

[.text-center]
== Zdjcia
