= Zupa fasolkowa 🌱 +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 35 min
* 4 porcje
* https://www.kwestiasmaku.com/przepis/zupa-fasolkowa[link do źródła przepisu]

== Składniki
* 1 łyżka oliwy
* 1 łyżka masła
* 1 cebula
* 1/2 pora
* 1 ząbek czosnku
* 1 marchewka
* 1 mała pietruszka
* 3 ziemniaki
* 1 i 1/2 litra bulionu (drobiowego lub jarzynowego)
* 1/2 łyżeczki kurkumy w proszku
* 400 g zielonej lub żółtej fasolki szparagowej (poza sezonem mrożonej)
* 1 łyżka posiekanego koperku
* 200 g śmietany 18% lub 80 ml śmietanki 18% z kartonika (do zup i sosów)

|
== Przygotowanie

W garnku na oliwie i maśle poddusić pokrojoną w kosteczkę cebulę. Pora opłukać, obrać z zewnętrznych grubszych warstw i odciąć zielone końce. Pozostałą białą i jasnozieloną część przekroić wzdłuż na 4 części, opłukać je i pokroić na plasterki.

Dodać do garnka z cebulą i razem podsmażać przez ok. 2 minuty. Pod koniec dodać przeciśnięty przez praskę czosnek.

Dodać obraną i pokrojoną na cienkie plasterki marchewkę oraz pietruszkę wymieszać. Ziemniaki obrać i pokroić w kostkę. Dodać do garnka i mieszając podsmażać ok. 2 minuty.

Wlać gorący bulion, doprawić solą i pieprzem, dodać kurkumę i zagotować. Przykryć i gotować przez ok. 15 minut. W połowie gotowania dodać opłukaną na sitku (i rozmrożoną jeśli używamy mrożonej) zieloną fasolkę.

Odstawić z ognia i dodać posiekany koperek oraz śmietanę (gęstą z kubka należy wcześniej zahartować kilkoma łyżkami zupy, natomiast słodką śmietankę z kartonika można wlać bezpośrednio do zupy).

|===

[.text-center]
== Zdjęcia
