= Zupa barszcz z uszkami  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 1 h
* 6 porcji
* https://www.kwestiasmaku.com/kuchnia_polska/wigilia/barszcz_wigilijny_z_uszkami/przepis.html[link do 藕r贸da przepisu]

== Skadniki

* 40 g suszonych borowik贸w
* 1 cebula
* 2 zbki czosnku
* 3 listki laurowe, 4 ziela angielskie, 10 ziaren pieprzu
* 2 kg czerwonych burak贸w
* 1/2 korzenia selera
* 1 jabko (np. szara reneta)
* 3 y偶ki octu spirytusowego 10%
* s贸l morska (okoo 1/2 y偶ki) i wie偶o zmielony czarny pieprz (okoo 1 y偶eczki)
* 3 y偶ki cukru
* opcjonalnie: 3 go藕dziki, kawaek kory cynamonu, kawaek gwiazdki any偶u
* warto doda: 250 - 500 ml zakwasu (kwasu) burakowego

|
== Przygotowanie

Do garnka wla 500 ml wody, wsypa suszone borowiki. Na palniku kuchenki opali nieobran cebul oraz 1 zbek czosnku.

Cebul i czosnek przekroi na p贸 i doda do grzyb贸w. Zagotowa na umiarkowanym ogniu, nastpnie zmniejszy ogie do minimum, przykry i na minimalnym ogniu gotowa przez okoo 25 minut (wywar ma tylko lekko mruga a nie mocno si gotowa).

W midzyczasie doda do wywaru licie laurowe, ziele angielskie i pieprz ziarnisty.

Buraki i selera umy, obra ze sk贸rki, nastpnie zetrze na tarce (na du偶ych oczkach, jak do sur贸wki) lub posieka w melakserze. Jabko razem ze sk贸rk zetrze na tarce.

Starte buraki, selera i jabko wo偶y do du偶ego garnka (warzyw bdzie do sporo), doda 2,5 litry wody oraz wywar z grzybami. Przykry garnek i zagotowa na minimalnym ogniu (zagotowanie ma trwa okoo 20 minut). W midzyczasie doda go藕dziki, cynamon i any偶 jeli ich u偶ywamy.

Po zagotowaniu trzyma wywar jeszcze na minimalnym ogniu przez okoo 10 minut. Na koniec doda ocet i wymiesza. Odstawi z ognia.

Do barszczu warto doda wywar grzybowy pozostay po uszkach (niekoniecznie cay) oraz 250 ml kwasu burakowego.

Barszcz odstawi na okoo godzin. W midzyczasie mo偶na zacz przygotowywa uszka.

Do barszczu doda s贸l (do smaku), pieprz mielony, cukier oraz wie偶y posiekany zbek czosnku, zn贸w zostawi na minimum godzin ale najlepiej do czasu cakowitego ostudzenia.

Barszcz przecedzi i schowa do lod贸wki. Nastpnego dnia lub przed podaniem podgrza, spr贸bowa i w razie potrzeby doprawi sol i pieprzem.

|===

[.text-center]
== Zdjcia
