= Zupa kalafiorowa  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 35 min
* 4 porcje
* https://www.kwestiasmaku.com/przepis/zupa-kalafiorowa-z-ziemniakami-i-marchewka[link do 藕r贸da przepisu]

== Skadniki

* 2 y偶ki oliwy
* 1 y偶ka masa
* 1 cebula
* 2 marchewki
* 5 ziemniak贸w
* 500 g kalafiora (wie偶ego lub mro偶onego)
* 1,5 litra bulionu drobiowego lub rosou
* 2 y偶ki posiekanego koperku
* 2 y偶ki posiekanego szczypiorku
* 200 g gstej mietany z kubka 18%

|
== Przygotowanie

Na oliwie i male zeszkli pokrojon w kosteczk cebul, doda obran i pokrojon na cienkie plasterki marchewk i sma偶y co chwil mieszajc przez 2 minuty.

Doda obrane i pokrojone w kosteczk ziemniaki i zn贸w podsma偶a je przez ok. 5 - 7 minut, od czasu do czasu mieszajc. Doprawi sol oraz pieprzem.

Doda wie偶ego kalafiora pokrojonego na mae r贸偶yczki i jeszcze przez chwil razem podsma偶a (kalafiora mro偶onego dodajemy p贸藕niej). Wla gorcy bulion i zagotowa. Przykry i gotowa przez ok. 20 minut do mikkoci warzyw. W poowie tego czasu doda mro偶one r贸偶yczki kalafiora, wczeniej opukane na sitku pod gorc wod.

Zup odstawi z ognia, doda posiekany koperek i szczypiorek. mietan wymiesza z kilkoma y偶kami zimnej wody, p贸藕niej z kilkoma y偶kami wywaru. Po zahartowaniu mietany dodawa j stopniowo do zupy cay czas mieszajc. Podawa z pieczywem.

|===

[.text-center]
== Zdjcia
