= Zupa ros贸  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 1 godzina
* 4 porcje
* https://www.kwestiasmaku.com/kuchnia_polska/rosol/przepis.html[link do 藕r贸da przepisu]

== Skadniki

* 1 kurczak o wadze okoo 2 kg 
* 3 litry wody
* 2 woszczyzny:
* przyprawy: 1 y偶ka soli morskiej, 3 ziarenka ziela angielskiego, 1 li laurowy, 4 cae ziarenka pieprzu

|
== Przygotowanie

Jeli mamy caego kurczaka nale偶y go pokroi na czci - odci szyj, skrzydeka, uda. Korpus pozostawi razem z piersiami.

Wszystkie czci opuka, nastpnie wo偶y do du偶ego garnka i zala zimn wod. Posoli i zagotowa na rednim ogniu.

Po zagotowaniu zmniejszy ogie i zszumowa wywar. Zmniejszy ogie i gotowa na maym ogniu (ros贸 ma tylko "mruga") pod lekko uchylon pokryw przez okoo 1 i 1/2 godziny.

W midzyczasie przygotowa warzywa: marchewk, pietruszk i selera obra (lub dla wikszego aromatu - tylko dokadnie umy). Cebul, pora i natk opuka (cebuli nie obiera, jej uski nadadz zupie adnego koloru).

Warzywa wo偶y do rosou i zagotowa. Doda przyprawy: ziele angielskie, li laurowy i czarny pieprz. Zmniejszy ogie i gotowa na maym ogniu przez okoo 1 godzin lub do 1 i 1/2 godziny.

Ros贸 podawa gorcy, z ugotowanym makaronem, posiekan natk, pokrojon na cienkie plasterki marchewk z rosou oraz kawakami misa z kurczaka.

|===

[.text-center]
== Zdjcia

