= Zupa kalafiorowa

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 35 min
* 4 porcje
* https://www.kwestiasmaku.com/przepis/zupa-kalafiorowa-z-ziemniakami-i-marchewka[link do źródła przepisu]

== Składniki
* 2 łyżki oliwy
* 1 łyżka masła
* 1 cebula
* 2 marchewki
* 5 ziemniaków
* 500 g kalafiora (świeżego lub mrożonego)
* 1,5 litra bulionu drobiowego lub rosołu
* 2 łyżki posiekanego koperku
* 2 łyżki posiekanego szczypiorku
* 200 g gęstej śmietany z kubka 18%

|
== Przygotowanie
Na oliwie i maśle zeszklić pokrojoną w kosteczkę cebulę, dodać obraną i pokrojoną na cienkie plasterki marchewkę i smażyć co chwilę mieszając przez 2 minuty.

Dodać obrane i pokrojone w kosteczkę ziemniaki i znów podsmażać je przez ok. 5 - 7 minut, od czasu do czasu mieszając. Doprawić solą oraz pieprzem.

Dodać świeżego kalafiora pokrojonego na małe różyczki i jeszcze przez chwilę razem podsmażać (kalafiora mrożonego dodajemy później). Wlać gorący bulion i zagotować. Przykryć i gotować przez ok. 20 minut do miękkości warzyw. W połowie tego czasu dodać mrożone różyczki kalafiora, wcześniej opłukane na sitku pod gorącą wodą.

Zupę odstawić z ognia, dodać posiekany koperek i szczypiorek. Śmietanę wymieszać z kilkoma łyżkami zimnej wody, później z kilkoma łyżkami wywaru. Po zahartowaniu śmietany dodawać ją stopniowo do zupy cały czas mieszając. Podawać z pieczywem.

== Zdjęcia
|===
