= Zupa grochowa 2

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* 4
							porcje
* https://zakochanewzupach.pl/zupa-grochowa-z-luskanego-grochu[link do źródła przepisu]

== Składniki
* ingredient_quantity recipe ingredient
* 2 l woda
* 2 ziemniaki
* 60 g marchewka
* 1 kawałek por
* 1 kawałek seler
* 1 pietruszka
* 1 gałązka świeży lubczyk lub łyżeczka suszonego
* 1 gałązka seler bulwiasty
* 2 szklanek żółty groch łuskany połówki
* 1 szczypta sól morska
* trochę pieprz czarny ziarnisty
* 1 łyżka oliwa
* 2 łyżek suszony majeranek
* 1 pęczek natka pietruszki


|
== Przygotowanie

Groch płuczę na sicie, zalewam 2 l wody i zagotowuję.

Zdejmuję łyżką cedzakową pianę, która zebrała się po zagotowaniu grochu i gotuję.

W tym czasie ziemniaki kroję w kostkę, a marchewkę, seler i pietruszkę ścieram na tarce o dużych oczkach.

Dodaję warzywa do zupy, dorzucam do garnka listek laurowy i ziele angielskie, gałązkę lubczyku i selera bulwiastego, łyżeczkę soli i gotuję przez 30 minut.

W tym czasie pora kroję w półtalarki, a następnie rozdrabniam nożem na mniejsze kawałki i wrzucam na lekko rozgrzaną na patelni oliwę.

Delikatnie podsmażam na małej mocy płyty, a zanim por się zrumieni, dodaję czosnek przeciśnięty przez praskę i na pół minuty zwiększam moc płyty.

Zdejmuję patelnię z płyty, dodaję pora z czosnkiem do garnka z zupą grochową.

Kiedy minie czas gotowania zupy, sprawdzam, czy groch na pewno jest miękki, dodaję majeranek i doprawiam świeżo zmielonym pieprzem.

Zupę podaję z natką pietruszki.


== Zdjęcia
|===
