= Zupa krupnik +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 1 h
* 4 porcje
* https://www.kwestiasmaku.com/przepis/krupnik[link do źródła przepisu]

== Składniki
* 1 ćwiartka kurczaka (ok. 500 g) lub skrzydło indyka
* 2 litry bulionu lub wody
* 1 cebula
* 3 ziela angielskie
* 1 listek laurowy
* 3 łyżki kaszy jęczmiennej (perłowej, drobnej, do zup)
* 1 łyżka ryżu
* 4 - 5 średnich ziemniaków
* 1 duża marchewka
* 1 mała pietruszka
* kawałek selera i pora
* szczypta kurkumy (opcjonalnie)
* 1 łyżka posiekanego koperku

|
== Przygotowanie
Mięso opłukać i włożyć do dużego garnka. Wlać 2 litry bulionu lub wody, zagotować, a następnie zszumować.

Dodać obraną cebulę, ziele angielskie i listek laurowy, doprawić solą.

Gotować na umiarkowanym ogniu pod przykryciem przez ok. 30 minut.

Dodać kaszę oraz ryż i gotować przez ok. 10 minut.

Dodać obrane i pokrojone w kostkę ziemniaki oraz marchewkę - obraną i startą na większych oczkach tarki.

Dodać obraną pietruszkę w całości, kawałeczek selera i pora.

Doprawić zmielonym pieprzem, solą w razie potrzeby i kurkumą. Gotować przez ok. 30 minut.

Pod koniec dodać posiekany świeży koperek.

Mięso wyjąć z zupy, usunąć skórę i kości, resztę pokroić na kawałki i włożyć z powrotem do zupy. Podawać z pieczywem.

|===

[.text-center]
== Zdjęcia
