= Zupa krem z groszku z grzankami 🌱
:imagesdir: /Recipes/static/images

++++
<div class="recipe-header-actions">
    <a href="../../index.html" class="back-to-home-btn">← Wróć do przepisów</a>
    <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>
</div>
++++

[.recipe-hero]
[.card-image-placeholder]
Brak zdjęcia przepisu 🍲

[.recipe-details]
* 🕒 czas przygotowania: 32 minut
* 👥 5 porcji
* 🔗 https://zakochanewzupach.pl/zupa-krem-z-zielonego-groszku-czyli-zielono-mi[link do źródła przepisu]

[.recipe-columns]
== Składniki

* 800 g mrożonego zielonego groszku
* 2 cebule duże
* 2 łyżki oliwa z czosnkiem
* 3 łyżki bulionu warzywnego w słoiku winiary
* 1 l wody
* 1 szczypta kozieradki do smaku
* 0,5 cytryny
* 1 szczypta soli do smaku
* 1 szczypta pieprzu ziołowego do smaku
* 150 g śmietany 18%
* 1 bagietka
* trochę pasty z oliwek
* trochę kiełek do dekoracji

== Przygotowanie

Cebulę kroimy w piórka lub kostkę (zostanie zmiksowana z zupą).

W garnku rozgrzewamy olej z czosnkiem i ziołami i wrzucamy pokrojoną cebulę. Szklimy ją na złoty kolor.

Dorzucamy groszek i całość zalewamy bulionem warzywnym.

Gotujemy na małym ogniu pod przykryciem do momentu aż groszek będzie miękki ( gotuje się dosyć szybko).

Na około 5 minut przed końcem gotowania zupę doprawiamy do smaku solą, pieprzem i kozieradką. Dodajemy też sok z ½ cytryny.

Zupę zabielamy śmietanką (część zostawiamy do dekoracji) i przecieramy przez sitko lub dokładnie miksujemy blenderem.

Pieczywo kroimy na małe porcje i wkładamy do tostera (najlepiej jeśli będzie tylko delikatnie przypieczone).

Każdą kromkę smarujemy pastą z oliwek i dekorujemy kiełkami.

[.recipe-gallery]
== Zdjęcia

[.gallery-grid]
// Tutaj pojawią się zdjęcia
