= Zupa groch贸wka  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 1 godzina
* 4 porcje
* https://www.kwestiasmaku.com/przepis/zupa-grochowa-z-ziemniakami-i-kielbasa[link do 藕r贸da przepisu]

== Skadniki

* 150 g grochu uskanego po贸wki 偶贸tego
* 1 y偶ka masa
* 1 cebula
* 1 listek laurowy, 1 ziele angielskie, 1 y偶eczka kminku, 2 y偶eczki majeranku
* 1 marchewka
* 3 ziemniaki
* 15 cm kawaek kiebasy
* 1 litr bulionu np. wieprzowego, drobiowego
* 1 y偶ka posiekanej natki

|
== Przygotowanie

Dzie wczeniej zala groch 1 litrem zimnej wody i odstawi do namoczenia na ca noc. Nastpnego dnia odcedzi, zala wie偶 wod (kilka centymetr贸w ponad poziom grochu), doda p贸 y偶eczki soli i zagotowa. Zmniejszy ogie i gotowa pod lekko uchylon pokryw przez okoo 45 minut lub do mikkoci (groch mo偶e si czciowo rozpa i rozgotowa).

W du偶ym garnku na male zeszkli pokrojon w kosteczk cebul. Doda listek laurowy, ziele angielskie, kminek, majeranek oraz obran i pokrojon w kosteczk marchewk. Mieszajc sma偶y przez ok. 5 minut.

Doda obrane i pokrojone w kosteczk ziemniaki oraz obran i pokrojon w kosteczk kiebas i chwil razem podsma偶a.

Zala gorcym bulionem i zagotowa. Doda ugotowany groch (wraz z pozosta wod z gotowania), doprawi pieprzem, wymiesza i w razie potrzeby doprawi sol.

Przykry i gotowa przez ok. 15 minut do mikkoci warzyw, pod koniec doda posiekan natk pietruszki. Podawa z pieczywem.

|===

[.text-center]
== Zdjcia
