= Zupa grzybowa 50 zotych grzyb贸w  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: 35 min
* 4 - 5 porcji
* https://www.kwestiasmaku.com/przepis/zupa-krem-grzybowa-z-suszonych-grzybow[link do 藕r贸da przepisu]

== Skadniki
* 70 g grzyb贸w suszonych (borowik贸w i/lub podgrzybk贸w)
* 1,5 litra bulionu (np. grzybowy, warzywny, misny)
* 1 y偶ka oleju rolinnego
* 1 cebula
* 1 marchewka
* 2 ziemniaki
* zioa: po 1 y偶eczce tymianku, czbru i majeranku
* pczek natki pietruszki
* 250 ml mietanki 30%
* do podania: grzaneczki z chleba

|
== Przygotowanie
Suszone grzyby opuka pod bie偶c chodn wod, wo偶y do miski, zala bulionem i odstawi na noc do namoczenia.

Do wikszego garnka wla oliw i zeszkli pokrojon w kosteczk cebul.

Nastpnie doda obran i start na tarce marchewk i podsma偶a przez ok. 2 minuty.

Doda obrane i pokrojone w kostk ziemniaki oraz zioa. Mieszajc co chwil podsma偶a przez minut.

Wla namoczone grzyby wraz z bulionem. Zagotowa na du偶ym ogniu. Doprawi sol i pieprzem (ok. p贸 y偶eczki).

Po zagotowaniu zmniejszy ogie i gotowa pod przykryciem przez ok. 20 minut (do mikkoci skadnik贸w).

Odstawi z ognia i zmiksowa z dodatkiem oderwanych listk贸w natki pietruszki oraz mietanki.

Zup mo偶na zawekowa (wla gorc do soik贸w) i po ostudzeniu przechowa przez kilka dni w lod贸wce. Lub te偶 od razu podawa z grzankami (chleb pokroi w ma kosteczk, rozo偶y na blaszce i suszy w piekarniku nagrzanym do 160 stopni C, a偶 bdzie chrupicy).

|===

[.text-center]
== Zdjcia
