= Zupa fasolowa 🌱 +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++
:imagesdir: /Recipes/static/images

[.recipe-hero]
--
[.recipe-category-label]
Dania główne

[.card-image-placeholder]
Brak zdjęcia przepisu 🍲
--

[.recipe-details]
--
[.recipe-details-item]
🕒 czas przygotowania: 35 minut

[.recipe-details-item]
👥 4 porcje

[.recipe-details-item]
🔗 https://zakochanewzupach.pl/zupa-fasolowa-tradycyjna-z-boczkiem-i-kielbasa[link do źródła przepisu]

--

[.recipe-columns]
--
[.recipe-column-box]
=== Składniki
* 1 puszka białej fasoli
* 1 opakowanie zupy fasolowej
* 3 ziemniaki
* 1 mała marchewka
* 1 pietruszka
* 1 kawałek selera
* 1 łyżka majeranku
* 1 szczypta soli do smaku
* 1 szczypta pieprzu do smaku
* 10 dag boczku wędzonego
* 10 dag kiełbaski
* 1 łyżka świeżo posiekanej natki pietruszki

|

[.recipe-column-box]
=== Przygotowanie
Ziemniaki, marchewkę, pietruszkę i kawałek selera obieramy. Ziemniaki kroimy w kostkę, pozostałe warzywa ścieramy na tarce o dużych oczkach.

Tak przygotowane warzywa przekładamy do garnka, zalewamy 0,7 l wody, gotujemy niecałe 10 minut.

Zawartość opakowania z zupą fasolową rozprowadzamy w szklance zimnej wody, dodajemy do garnka z warzywami, gotujemy 7 minut, od czasu do czasu mieszając.

Na suchej patelni lekko rumienimy pokrojony w kosteczkę boczek i kiełbaskę.

Do zupy dodajemy fasolkę z puszki, łyżkę majeranku i podsmażony z kiełbasą boczek. Chwilę gotujemy, zestawiamy z kuchenki. W razie konieczności doprawiamy solą i pieprzem.

Zupę podajemy ze świeżo posiekaną natką pietruszki.
--
