= Zupa warzywna  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 35 min
* 4 porcje
* https://www.kwestiasmaku.com/przepis/zupa-jarzynowa[link do 藕r贸da przepisu]

== Skadniki

* 2 mieszanki mieszanki wiosennej
* 500 g kiebasy
* 500 g ziemniak贸w
* 1/2 cebuli
* 1 y偶ka masa
* 1/2 y偶ki oliwy extra vergine
* 1 i 1/2 litra bulionu jarzynowego lub drobiowego
* 1/3 szklanki mietany 18% lub 30%
* koperek lub natka pietruszki lub bazylia
|
== Przygotowanie

W szerokim wikszym garnku na male i oliwie zeszkli pokrojon w kosteczk cebul. Doda mieszank wiosenn i mieszajc podsma偶a przez ok. 3 minuty.

Doda obrane i pokrojone w kosteczk ziemniaki i zn贸w podsma偶a przez ok. 3 minuty co chwil mieszajc.

Doda gorcy bulion i zagotowa. Gotowa pod przykryciem przez ok. 5 minut.

Doprawi sol oraz wie偶o zmielonym pieprzem.

Doda pokrojon w kostk kiebas.

Gotowa pod przykryciem przez ok. 15 minut a偶 warzywa bd mikkie. Na koniec doda posiekany koperek (lub natk czy licie bazylii).

Zup odstawi z ognia i zaprawi mietan (najpierw wymiesza j ze stopniowo dodawanym wywarem, w iloci okoo szklanki, nastpnie przela do garnka z zup i wymiesza). Podawa z pieczywem.

|===

[.text-center]
== Zdjcia

