= Zupa grochowa 2

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 1 h 21 min
* 4 porcje
* https://zakochanewzupach.pl/zupa-grochowa-z-luskanego-grochu[link do źródła przepisu]

== Składniki
* 2 l wody
* 2 ziemniaki
* 60 g marchewki
* 1 kawałek pora
* 1 kawałek selera
* 1 pietruszka
* 1 gałązka świeżego lubczyk lub łyżeczka suszonego
* 1 gałązka selera bulwiastego
* 2 szklanki żółtego grochu łuskanego połówki
* 1 szczypta soli morskiej
* trochę pieprzu czarnego ziarnistego
* 1 łyżka oliwy
* 2 łyżek suszonego majeranku
* 1 pęczek natki pietruszki

|
== Przygotowanie

Groch płuczę na sicie, zalewam 2 l wody i zagotowuję.

Zdejmuję łyżką cedzakową pianę, która zebrała się po zagotowaniu grochu i gotuję.

W tym czasie ziemniaki kroję w kostkę, a marchewkę, seler i pietruszkę ścieram na tarce o dużych oczkach.

Dodaję warzywa do zupy, dorzucam do garnka listek laurowy i ziele angielskie, gałązkę lubczyku i selera bulwiastego, łyżeczkę soli i gotuję przez 30 minut.

W tym czasie pora kroję w półtalarki, a następnie rozdrabniam nożem na mniejsze kawałki i wrzucam na lekko rozgrzaną na patelni oliwę.

Delikatnie podsmażam na małej mocy płyty, a zanim por się zrumieni, dodaję czosnek przeciśnięty przez praskę i na pół minuty zwiększam moc płyty.

Zdejmuję patelnię z płyty, dodaję pora z czosnkiem do garnka z zupą grochową.

Kiedy minie czas gotowania zupy, sprawdzam, czy groch na pewno jest miękki, dodaję majeranek i doprawiam świeżo zmielonym pieprzem.

Zupę podaję z natką pietruszki.

== Zdjęcia
|===
