= Zupa krem z groszku z grzankami  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 32 minut
* 5 porcji
* https://zakochanewzupach.pl/zupa-krem-z-zielonego-groszku-czyli-zielono-mi[link do 藕r贸da przepisu]

== Skadniki

* 800 g mro偶ony zielony groszek
* 2 cebula du偶a
* 2 y偶ek oliwa z czosnkiem
* 3 y偶ek bulion warzywny w soiku winiary
* 1 l woda
* 1 szczypta kozieradka do smaku
* 0.5 cytryna
* 1 szczypta s贸l do smaku
* 1 szczypta pieprz zioowy do smaku
* 150 g mietana 18%
* 1 bagietka
* troch pasta z oliwek
* troch kieki do dekoracji

|
== Przygotowanie

Cebul kroimy w pi贸rka lub kostk (zostanie zmiksowana z zup).

W garnku rozgrzewamy olej z czosnkiem i zioami i wrzucamy pokrojon cebul. Szklimy j na zoty kolor.

Dorzucamy groszek i cao zalewamy bulionem warzywnym.

Gotujemy na maym ogniu pod przykryciem do momentu a偶 groszek bdzie mikki ( gotuje si dosy szybko).

Na okoo 5 minut przed kocem gotowania zup doprawiamy do smaku sol, pieprzem i kozieradk. Dodajemy te偶 sok z 1/2 cytryny.

Zup zabielamy mietank (cz zostawiamy do dekoracji) i przecieramy przez sitko lub dokadnie miksujemy blenderem.

Pieczywo kroimy na mae porcje i wkadamy do tostera (najlepiej jeli bdzie tylko delikatnie przypieczone).

Ka偶d kromk smarujemy past z oliwek i dekorujemy kiekami.

|===

[.text-center]
== Zdjcia
