= Zupa serkowa z klopsami +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 35 min
* 4 porcje
* https://www.winiary.pl/przepisy/zupa-z-serkow-topionych-zwz[link do źródła przepisu]
== Składniki

* 3 kostki rosołowe
* 1 l wody
* 300 g serka topionego
* 2 cebule dymki ze szczypiorem
* 3 ząbki czosnku
* 200 ml śmietany 30%
* 0.25 łyżeczki papryki ostrej mielonej
* 1 szczypta soli do smaku
* 1 szczypta pieprzu biały do smaku
* 3 łyżki świeżo posiekanej natki pietruszki
* trochę pieczywo
* 3 łyżki oliwy z oliwek

=== Na klopsy
* 500 g mięsa mielonego
* sól i pieprz do smaku
* 1 cebula

|
== Przygotowanie
Cebulę i czosnek obierz oraz drobno posiekaj. Szczypiorek posiekaj.

W garnku o grubym dnie rozgrzej oliwę i zeszklij cebulę. Dodaj czosnek i całość podsmaż przez ok. 5 minut.

Składniki zalej gorącym bulionem, dodaj pokrojone w mniejsze kawałki serki topione i dokładnie wymieszaj.

Uformuj klopsy z mięsa mielonego, pokrojonej na drobną kostkę cebuli, soli i pieprzu. Dodaj klopsy do zupy.

Gotuj aż do całkowitego rozpuszczenia serków.

Zestaw garnek z ognia i dodaj śmietankę. Zupę z serków topionych dopraw solą, pieprzem i ostrą papryką do smaku.

Teraz czas na grzanki - kromki chleba pokrój w niedużą kostkę. W misce wymieszaj oliwę z oliwek, przeciśnięty przez praskę czosnek. Do tak przygotowanej oliwy wrzuć kawałki pieczywa i dokładnie wymieszaj.

Grzanki podsmaż na patelni na złoty kolor.

Zupę z serków topionych posyp grzankami, posiekaną natką pietruszki i szczypiorkiem.

|===

[.text-center]
== Zdjęcia

