= Zupa krem z groszku z grzankami

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 32 min
* 5 porcji
* https://zakochanewzupach.pl/zupa-krem-z-zielonego-groszku-czyli-zielono-mi[link do źródła przepisu]

== Składniki
* 800 g mrożony zielony groszek
* 2 cebula duża
* 2 łyżek oliwa z czosnkiem
* 3 łyżek bulion warzywny w słoiku winiary
* 1 l woda
* 1 szczypta kozieradka do smaku
* 0.5 cytryna
* 1 szczypta sól do smaku
* 1 szczypta pieprz ziołowy do smaku
* 150 g śmietana 18%
* 1 bagietka
* trochę pasta z oliwek
* trochę kiełki do dekoracji

|
== Przygotowanie

Cebulę kroimy w piórka lub kostkę (zostanie zmiksowana z zupą).

W garnku rozgrzewamy olej z czosnkiem i ziołami i wrzucamy pokrojoną cebulę. Szklimy ją na złoty kolor.

Dorzucamy groszek i całość zalewamy bulionem warzywnym.

Gotujemy na małym ogniu pod przykryciem do momentu aż groszek będzie miękki ( gotuje się dosyć szybko).

Na około 5 minut przed końcem gotowania zupę doprawiamy do smaku solą, pieprzem i kozieradką. Dodajemy też sok z 1/2 cytryny.

Zupę zabielamy śmietanką (część zostawiamy do dekoracji) i przecieramy przez sitko lub dokładnie miksujemy blenderem.

Pieczywo kroimy na małe porcje i wkładamy do tostera (najlepiej jeśli będzie tylko delikatnie przypieczone).

Każdą kromkę smarujemy pastą z oliwek i dekorujemy kiełkami.

|===

[.text-center]
== Zdjęcia
