= Zupa grochowa 2  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 1 godzina 21 minut
* 4 porcje
* https://zakochanewzupach.pl/zupa-grochowa-z-luskanego-grochu[link do 藕r贸da przepisu]

== Skadniki

* 2 l wody
* 2 ziemniaki
* 60 g marchewki
* 1 kawaek pora
* 1 kawaek selera
* 1 pietruszka
* 1 gazka wie偶ego lubczyk lub y偶eczka suszonego
* 1 gazka selera bulwiastego
* 2 szklanki 偶贸tego grochu uskanego po贸wki
* 1 szczypta soli morskiej
* troch pieprzu czarnego ziarnistego
* 1 y偶ka oliwy
* 2 y偶ek suszonego majeranku
* 1 pczek natki pietruszki

|
== Przygotowanie

Groch pucz na sicie, zalewam 2 l wody i zagotowuj.

Zdejmuj y偶k cedzakow pian, kt贸ra zebraa si po zagotowaniu grochu i gotuj.

W tym czasie ziemniaki kroj w kostk, a marchewk, seler i pietruszk cieram na tarce o du偶ych oczkach.

Dodaj warzywa do zupy, dorzucam do garnka listek laurowy i ziele angielskie, gazk lubczyku i selera bulwiastego, y偶eczk soli i gotuj przez 30 minut.

W tym czasie pora kroj w p贸talarki, a nastpnie rozdrabniam no偶em na mniejsze kawaki i wrzucam na lekko rozgrzan na patelni oliw.

Delikatnie podsma偶am na maej mocy pyty, a zanim por si zrumieni, dodaj czosnek przecinity przez prask i na p贸 minuty zwikszam moc pyty.

Zdejmuj patelni z pyty, dodaj pora z czosnkiem do garnka z zup grochow.

Kiedy minie czas gotowania zupy, sprawdzam, czy groch na pewno jest mikki, dodaj majeranek i doprawiam wie偶o zmielonym pieprzem.

Zup podaj z natk pietruszki.

|===

[.text-center]
== Zdjcia
