= Zupa og贸rkowa  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: 30 min
* 4 porcje
* https://www.kwestiasmaku.com/przepis/zupa-ogorkowa[link do 藕r贸da przepisu]

== Skadniki
* 1 y偶ka masa
* 1 y偶ka oliwy
* 1 maa cebula
* 1 marchewka
* 1,5 litra bulionu (np. drobiowy, warzywny, ros贸)
* 300 g ziemniak贸w (3 sztuki)
* 4 rednie kiszone og贸rki
* 150 g mietany 18%
* 4 y偶ki posiekanego szczypiorku

|
== Przygotowanie
W garnku na male i oliwie zeszkli pokrojon w kosteczk cebul. Doda obran i pokrojon w kosteczk marchewk i mieszajc sma偶y przez ok. 3 minuty.

Wla gorcy bulion i zagotowa. Przykry, zmniejszy ogie i gotowa przez ok. 5 minut.

Doda obrane i pokrojone w kosteczk ziemniaki i gotowa przez ok. 10 minut.

Doda starte na tarce obrane og贸rki oraz 1/2 szklanki soku z kiszonych og贸rk贸w (zalewy) jeli mamy. Gotowa przez ok. 10 minut. Odstawi z ognia.

Doda szczypiorek oraz zaprawion mietan (najpierw wymieszan z 2 y偶kami wody, potem z kilkoma y偶kami wywaru).

|===

[.text-center]
== Zdjcia
