= Zupa brokułowa z ryżem i koperkiem 🌱 +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++
:imagesdir: /Recipes/static/images

[.recipe-hero]
--
[.recipe-category-label]
Dania główne

[.card-image-placeholder]
Brak zdjęcia przepisu 🍲
--

[.recipe-details]
--
[.recipe-details-item]
🕒 czas przygotowania: 45 minut

[.recipe-details-item]
👥 4 porcje

[.recipe-details-item]
🔗 https://zakochanewzupach.pl/zupa-brokulowa-z-ryzem-i-koperkiem[link do źródła przepisu]

--

[.recipe-columns]
--
[.recipe-column-box]
=== Składniki
* 0.5 brokuła świeżego
* 1 marchewka
* 1 pietruszka
* 1 kawałek selera
* 1 kawałek pora
* 1 kostka rosołu drobiowego
* 1 l wody
* 50 g ryżu jaśminowego
* 1 łyżka masła
* 1 pęczek koperka
* 0.25 szklanki śmietany

|

[.recipe-column-box]
=== Przygotowanie
Marchewkę, pietruszkę i seler ścieramy na tarce o dużych oczkach, por kroimy w cienkie plasterki i siekamy.

Podduszamy warzywa ma maśle, dorzucając dwie gałązki koperku.

Dodajemy 1 l wody, zagotowujemy.

Dodajemy przepłukany na sicie ryż, ponownie zagotowujemy, dodajemy kostkę rosołu drobiowego, brokuła podzielonego na małe różyczki i gotujemy 10 minut. Pod koniec gotowania dodajemy połowę posiekanego koperku.

Zestawiamy garnek z zupą z kuchenki, odstawiamy pod pokrywką na 10 minut.

Zupę brokułową z ryżem zabielamy śmietaną, podajemy z koperkiem.
--
