= Zupa serkowa z klopsami  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y

* czas przygotowania: 35 min
* 4 porcje
* https://www.winiary.pl/przepisy/zupa-z-serkow-topionych-zwz[link do 藕r贸da przepisu]
== Skadniki

* 3 kostki rosoowe
* 1 l wody
* 300 g serka topionego
* 2 cebule dymki ze szczypiorem
* 3 zbki czosnku
* 200 ml mietany 30%
* 0.25 y偶eczki papryki ostrej mielonej
* 1 szczypta soli do smaku
* 1 szczypta pieprzu biay do smaku
* 3 y偶ki wie偶o posiekanej natki pietruszki
* troch pieczywo
* 3 y偶ki oliwy z oliwek

=== Na klopsy
* 500 g misa mielonego
* s贸l i pieprz do smaku
* 1 cebula

|
== Przygotowanie

Cebul i czosnek obierz oraz drobno posiekaj. Szczypiorek posiekaj.

W garnku o grubym dnie rozgrzej oliw i zeszklij cebul. Dodaj czosnek i cao podsma偶 przez ok. 5 minut.

Skadniki zalej gorcym bulionem, dodaj pokrojone w mniejsze kawaki serki topione i dokadnie wymieszaj.

Uformuj klopsy z misa mielonego, pokrojonej na drobn kostk cebuli, soli i pieprzu. Dodaj klopsy do zupy.

Gotuj a偶 do cakowitego rozpuszczenia serk贸w.

Zestaw garnek z ognia i dodaj mietank. Zup z serk贸w topionych dopraw sol, pieprzem i ostr papryk do smaku.

Teraz czas na grzanki - kromki chleba pokr贸j w niedu偶 kostk. W misce wymieszaj oliw z oliwek, przecinity przez prask czosnek. Do tak przygotowanej oliwy wrzu kawaki pieczywa i dokadnie wymieszaj.

Grzanki podsma偶 na patelni na zoty kolor.

Zup z serk贸w topionych posyp grzankami, posiekan natk pietruszki i szczypiorkiem.

|===

[.text-center]
== Zdjcia

