= Zupa warzywna 🌱
:imagesdir: /Recipes/static/images

++++
<div class="recipe-header-actions">
    <a href="../../index.html" class="back-to-home-btn">← Wróć do przepisów</a>
    <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>
</div>
++++

[.recipe-hero]
[.card-image-placeholder]
Brak zdjęcia przepisu 🍲

[.recipe-details]
* 🕒 czas przygotowania: 35 minut
* 🕒 czas gotowania: 35 minut
* 👥 4 porcje
* 🔗 https://www.kwestiasmaku.com/przepis/zupa-jarzynowa[link do źródła przepisu]

[.recipe-columns]
== Składniki

* 2 mieszanki mieszanki wiosennej
* 500 g kiełbasy
* 500 g ziemniaków
* ½ cebuli
* 1 łyżka masła
* ½ łyżki oliwy extra vergine
* 1 i ½ litra bulionu jarzynowego lub drobiowego
* ⅓ szklanki śmietany 18% lub 30%
* koperek lub natka pietruszki lub bazylia

== Przygotowanie

W szerokim większym garnku na maśle i oliwie zeszklić pokrojoną w kosteczkę cebulę. Dodać mieszankę wiosenną i mieszając podsmażać przez ok. 3 minuty.

Dodać obrane i pokrojone w kosteczkę ziemniaki i znów podsmażać przez ok. 3 minuty co chwilę mieszając.

Dodać gorący bulion i zagotować. Gotować pod przykryciem przez ok. 5 minut.

Doprawić solą oraz świeżo zmielonym pieprzem.

Dodać pokrojoną w kostkę kiełbasę.

Gotować pod przykryciem przez ok. 15 minut aż warzywa będą miękkie. Na koniec dodać posiekany koperek (lub natkę czy liście bazylii).

Zupę odstawić z ognia i zaprawić śmietaną (najpierw wymieszać ją ze stopniowo dodawanym wywarem, w ilości około szklanki, następnie przelać do garnka z zupą i wymieszać). Podawać z pieczywem.

[.recipe-gallery]
== Zdjęcia

[.gallery-grid]
// Tutaj pojawią się zdjęcia
