= Zupa buraczkowa

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 35 min
* 4 porcje
* https://zakochanewzupach.pl/zupa-buraczkowa-ze-smietana[link do źródła przepisu]

== Składniki
* 6 buraki
* 4 ziemniaki
* 1 marchewka
* 1 pietruszka
* 1 kawałek selera
* 1 kawałek pora
* 2 ząbki czosnku w łupinkach
* 1 gałązka lubczyku
* 1 gałązka selera korzeniowego
* 3 gałązki natki pietruszki
* 1 l wody
* 3 łyżki bulionu drobiowego w słoiku
* 4 łyżki śmietany 12% lub 18%
* 1 listek laurowy
* 3 kulki ziela angielskiego
* 1 szczypta soli morskiej
* 1 szczypta kwasku cytrynowego spożywczego
* 1 szczypta cukru do smaku
* trochę natki pietruszki do posypania zupy

|
== Przygotowanie

Buraczki myjemy, obieramy, kroimy w kostkę, wrzucamy na gotujący się wywar.

Marchewkę, pietruszkę i seler myjemy, obieramy, kroimy w kostkę, oddajemy do garnka z buraczkami.

Dodajemy do garnka z zupą pokrojone w kostkę ziemniaki, ząbki czosnku w łupinkach oraz świeże zioła i por związane nicią przeznaczoną do celów kulinarnych (zioła można też związać liściem pora).

Doprawiamy zupę solą, dodajemy listek laurowy, ziele angielskie. Gotujemy zupę do miękkości warzyw.

Wyciągamy z zupy zioła, ząbki czosnku, ziele angielskie i listek laurowy.

Ugotowaną zupę buraczkową zakwaszamy odrobiną kwasku cytrynowego, można też doprawić zupę cukrem, gdyby buraczki były mało słodkie.

Śmietanę hartujemy odrobiną gorącej zupy, dodajemy do garnka, mieszamy.

Zupę buraczkową podajemy posypaną świeżo posiekaną natką pietruszki.

|===

[.text-center]
== Zdjęcia
