= Zupa pieczarkowa  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: 35 min
* 4 porcje
* https://kuron.com.pl/artykuly/przepisy/rozne-przepisy/zupa-pieczarkowa[link do 藕r贸da przepisu]

== Skadniki
* 1,7 l wywaru drobiowego
* 3 mae marchewki
* 1 pietruszka
* Kawaek selera
* 1 cebula
* 2 y偶ki masa
* 400 g pieczarek
* 2 ziemniaki
* 125 ml mietanki 18%
* 2 y偶ki posiekanego koperku
* s贸l, pieprz

|
== Przygotowanie
Do wywaru dodaj pokrojone warzywa: marchew, pietruszk i seler. Gotuj na maym ogniu okoo 15, a偶 warzywa zmikn.

W tym czasie na male, podsma偶 cebul pokrojon w kostk. Kiedy si delikatnie zrumieni, dodaj pieczarki pokrojone w p贸plasterki. Sma偶 a偶 caa woda odparuje, a pieczarki si zrumieni.

Dodaj podsma偶on cebul i pieczarki do wywaru.

Nastpnie dodaj ziemniaki pokrojone w kostk. Gotuj do mikkoci okoo 15 minut.

Po tym czasie dodaj mietan, posiekany koperek, dopraw sol i pieprzem do smaku.

Zamiast ziemniak贸w pieczarkowa r贸wnie dobrze smakuje z makaronem.

|===

[.text-center]
== Zdjcia
