= Zupa pomidorowa +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 1 h
* 4 porcje
* https://www.kwestiasmaku.com/kuchnia_polska/zupy/zupa_pomidorowa/przepis.html[link do źródła przepisu]

== Składniki
* 2 ćwiartki kurczaka
* 2 litry wody
* 1/2 łyżeczki soli
* włoszczyzna (marchewka, pietruszka, kawałeczek pora, plasterek selera)
* 200 g koncentratu pomidorowego
* 250 ml śmietany 18% z kartonika (do zup i sosów)
* szczypta zmielonego pieprzu
* 200 g makaronu

|
== Przygotowanie
Mięso włożyć do garnka, dodać szczyptę soli, zalać zimną wodą i zagotować na większym ogniu.

W międzyczasie zdejmować łyżką cedzakową wytrącone na powierzchni "szumowiny". Zmniejszyć ogień do minimum i gotować na małym ogniu przez około 1/2 godziny. Dodać obraną i opłukaną włoszczyznę (marchewkę i pietruszkę pokroić w kostkę) i gotować przez następne 20 minut.

Dodać pomidory, dokładnie wymieszać i zagotować.

Zmniejszyć ogień i stopniowo dodawać śmietanę - aby uniknąć zwarzenia najlepiej wcześniej wymieszać ją w oddzielnym naczyniu (np. kubku) z kilkoma łyżkami zimnej wody a następnie ze stopniowo dodawanym gorącym wywarem (około 1/3 szklanki). Całość delikatnie podgrzać. Doprawić do smaku pieprzem.

Ugotować makaron osobno.

|===

[.text-center]
== Zdjęcia
