= Zupa warzywna

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 35 min
* 4 porcje
* https://www.kwestiasmaku.com/przepis/zupa-jarzynowa[link do źródła przepisu]

== Składniki
* 2 mieszanki mieszanki wiosennej
* 500 g kiełbasy
* 500 g ziemniaków
* 1/2 cebuli
* 1 łyżka masła
* 1/2 łyżki oliwy extra vergine
* 1 i 1/2 litra bulionu jarzynowego lub drobiowego
* 1/3 szklanki śmietany 18% lub 30%
* koperek lub natka pietruszki lub bazylia
|
== Przygotowanie

W szerokim większym garnku na maśle i oliwie zeszklić pokrojoną w kosteczkę cebulę. Dodać mieszankę wiosenną i mieszając podsmażać przez ok. 3 minuty.

Dodać obrane i pokrojone w kosteczkę ziemniaki i znów podsmażać przez ok. 3 minuty co chwilę mieszając.

Dodać gorący bulion i zagotować. Gotować pod przykryciem przez ok. 5 minut.

Doprawić solą oraz świeżo zmielonym pieprzem.

Dodać pokrojoną w kostkę kiełbasę.

Gotować pod przykryciem przez ok. 15 minut aż warzywa będą miękkie. Na koniec dodać posiekany koperek (lub natkę czy liście bazylii).

Zupę odstawić z ognia i zaprawić śmietaną (najpierw wymieszać ją ze stopniowo dodawanym wywarem, w ilości około szklanki, następnie przelać do garnka z zupą i wymieszać). Podawać z pieczywem.

|===

[.text-center]
== Zdjęcia

