= Zupa krem z marchewki z grzankami 🌱 +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 35 min
* 4 porcje
* https://www.kwestiasmaku.com/przepis/zupa-krem-marchewkowa[link do źródła przepisu]

== Składniki
* 1 łyżka masła
* 1 łyżka oliwy
* 1 cebula
* 1 ząbek czosnku
* 1/2 małego pora
* 500 g marchewki
* 300 g ziemniaków
* 500 ml bulionu jarzynowego lub drobiowego
* przyprawy: 1 łyżeczka kurkumy oraz 1/2 łyżeczki przyprawy curry
* 250 ml mleka (krowiego lub kokosowego)

|
== Przygotowanie
Do garnka włożyć łyżkę masła i łyżkę oliwy, dodać pokrojoną w kosteczkę cebulę i co chwilę mieszając smażyć na małym ogniu przez ok. 2 minuty.

Teraz dodawać stopniowo resztę warzyw, co chwilę mieszając i smażąc wszystko w sumie przez ok. 10 minut.

Najpierw dodać pokrojony na plasterki czosnek a za chwilę umytego i pokrojonego na plasterki pora.

Później obraną i pokrojoną na cienkie plasterki marchewkę i obrane i pokrojone w kosteczkę ziemniaki. W międzyczasie doprawić warzywa solą.

Zalać gorącym bulionem, dodać przyprawy (kurkumę i curry) i zagotować, przykryć pokrywą i gotować ok. 15 minut do miękkości warzyw.

Dodać mleko i zmiksować na krem.

|===

[.text-center]
== Zdjęcia
