= Zupa pieczarkowa

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 35 min
* 4 porcje
* https://kuron.com.pl/artykuly/przepisy/rozne-przepisy/zupa-pieczarkowa[link do źródła przepisu]

== Składniki
* 1,7 l wywaru drobiowego
* 3 małe marchewki
* 1 pietruszka
* Kawałek selera
* 1 cebula
* 2 łyżki masła
* 400 g pieczarek
* 2 ziemniaki
* 125 ml śmietanki 18%
* 2 łyżki posiekanego koperku
* sól, pieprz

|
== Przygotowanie
Do wywaru dodaj pokrojone warzywa: marchew, pietruszkę i seler. Gotuj na małym ogniu około 15, aż warzywa zmiękną.

W tym czasie na maśle, podsmaż cebulę pokrojoną w kostkę. Kiedy się delikatnie zrumieni, dodaj pieczarki pokrojone w półplasterki. Smaż aż cała woda odparuje, a pieczarki się zrumienią.

Dodaj podsmażoną cebulę i pieczarki do wywaru.

Następnie dodaj ziemniaki pokrojone w kostkę. Gotuj do miękkości około 15 minut.

Po tym czasie dodaj śmietanę, posiekany koperek, dopraw solą i pieprzem do smaku.

Zamiast ziemniaków pieczarkowa równie dobrze smakuje z makaronem.

|===

[.text-center]
== Zdjęcia
