= Zupa kurkowa z makaronem  +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: 37 min
* 2 porcje
* https://zakochanewzupach.pl/zupa-kurkowa-z-makaronem[link do 藕r贸da przepisu]

== Skadniki
* 30 dag wie偶e kurki
* 2 cebula
* 1 zbek czosnek
* 0.5 kg woda lub wywar warzywny
* 0.25 szklanka sodka mietanka
* 10 dag ulubiony makaron
* 1 y偶ka maso
* 2 ziarenka ziela angielskiego
* 1 li laurowy
* 1 szczypta kurkuma
* 4 gazek tymianek
* 1 szczypta s贸l morska i pieprz czarny do smaku

|
== Przygotowanie

Kurki dokadnie oczyszczamy, wiksze okazy kroimy w kawaki, mniejsze pozostawiamy w caoci.

Cebule kroimy w drobn kostk, opr贸szamy sol, podduszamy na male z dodatkiem licia laurowego i ziela angielskiego.

Kiedy cebula si zeszkli, dodajemy posiekany czosnek, a po chwili, gdy uwolni sw贸j aromat, dodajemy kurki i gazk tymianku. Dusimy, a偶 odparuje woda z grzyb贸w.

Podlewamy kurki wrzc wod lub wywarem, dodajemy makaron, szczypt soli i gotujemy do jego mikkoci.

Zabielamy zup mietank. Na talerzach doprawiamy zup kurkow z makaronem wie偶o mielonym pieprzem i opr贸szamy listkami tymianku.

|===

[.text-center]
== Zdjcia
