= Zupa rosół +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 1 h
* 4 porcje
* https://www.kwestiasmaku.com/kuchnia_polska/rosol/przepis.html[link do źródła przepisu]

== Składniki
* 1 kurczak o wadze około 2 kg 
* 3 litry wody
* 2 włoszczyzny:
* przyprawy: 1 łyżka soli morskiej, 3 ziarenka ziela angielskiego, 1 liść laurowy, 4 całe ziarenka pieprzu

|
== Przygotowanie

Jeśli mamy całego kurczaka należy go pokroić na części - odciąć szyję, skrzydełka, uda. Korpus pozostawić razem z piersiami.

Wszystkie części opłukać, następnie włożyć do dużego garnka i zalać zimną wodą. Posolić i zagotować na średnim ogniu.

Po zagotowaniu zmniejszyć ogień i zszumować wywar. Zmniejszyć ogień i gotować na małym ogniu (rosół ma tylko "mrugać") pod lekko uchyloną pokrywą przez około 1 i 1/2 godziny.

W międzyczasie przygotować warzywa: marchewkę, pietruszkę i selera obrać (lub dla większego aromatu - tylko dokładnie umyć). Cebulę, pora i natkę opłukać (cebuli nie obierać, jej łuski nadadzą zupie ładnego koloru).

Warzywa włożyć do rosołu i zagotować. Dodać przyprawy: ziele angielskie, liść laurowy i czarny pieprz. Zmniejszyć ogień i gotować na małym ogniu przez około 1 godzinę lub do 1 i 1/2 godziny.

Rosół podawać gorący, z ugotowanym makaronem, posiekaną natką, pokrojoną na cienkie plasterki marchewką z rosołu oraz kawałkami mięsa z kurczaka.

|===

[.text-center]
== Zdjęcia

