= Zupa z cukinii

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 25 minut
* czas gotowania: 20 minut
* liczba porcji: 1 litr zupy
* https://aniagotuje.pl/przepis/zupa-z-cukinii[link do źródła przepisu]

== Składniki

Składniki na zupę z cukinii:
* 500 ml bulionu warzywnego lub drobiowego
* 2 cukinie - 800 g
* mała cebula cukrowa
* 2 łyżki masła
* 4 ząbki czosnku
* 5 łyżek śmietanki 30 %
* przyprawy: po pół płaskiej łyżeczki soli i pieprzu, łyżeczka ziół prowansalskich
* zioła: garść siekanego szczypiorku, oraz natki pietruszki

Składniki na grzanki do zupy:
* 2 kromki jasnego pieczywa pszennego
* 4 łyżki delikatnej oliwy
* łyżeczka ziół prowansalskich

|
== Przygotowanie

Do zupy z cukinii odlewam przygotowuję 500 ml bulionu.

Cukinie myję i odcinam same końce. Obierz cebulę oraz ząbki czosnku.

Na patelni roztop dwie łyżki masła. Dodaj siekaną cebulę oraz całe ząbki czosnku. Cebulę z czosnkiem podsmażaj na małej mocy palnika przez około 3 minuty. 

Na patelnię dodaj też cukinie pokrojone w kostkę. Warzywa nie muszą być równo pokrojone. Zupa z cukinii będzie blendowana na krem. Warzywa podsmażaj razem około 10 minut, już na średniej mocy palnika. Pod koniec dodaj po pół płaskiej łyżeczki soli i  pieprzu oraz łyżeczkę ziół prowansalskich.

Bulion wlej do garnuszka. Dodaj siekaną natkę pietruszki i zagotuj. 

Do bulionu dodaj całą zawartość patelni. Zupę z cukinii gotuj na małej mocy palnika przez niecałe 15 minut

Do zupy możesz dodać śmietankę od razu lub dopiero po zblendowaniu/zmiksowaniu zupy na krem. Zupa krem z cukinii powinna wyjść dość gęsta. 

Zupa krem z cukinii najlepiej smakuje podana ze świeżo uprażonymi grzankami. Dwie kromki pieczywa pokrój w kostkę. Nagrzej małą patelnię. Na nagrzaną patelnię wyłóż pokrojone na kawałki pieczywo. Grzanki podsmażaj tak na suchej patelni przez minutę. Co chwilę przewracaj je ostrożnie na drugą stronę. 

Dopiero na częściowo podpieczone grzanki wylej cienką strużką dwie łyżki oliwy. Znów chwilę podsmażaj grzanki. Wylej kolejne dwie łyżki oliwy. Na koniec grzanki posyp ziołami. Jeśli zioła dodasz za wcześnie, to niepotrzebnie się przypalą.

== Zdjęcia
|===
