= Zupa klopsowa +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 30 min
* 4 porcje
* https://www.doradcasmaku.pl/przepis-zupa-klopsowa-z-koperkiem-i-ziemniakami-310942[link do źródła przepisu]

== Składniki

* mięso mielone 0,5 kg (z łopatki)
* pieprz czarny mielony Prymat 1 szczypta
* kucharek przyprawa uniwersalna 0.5 łyżeczki
* jajko 1 sztuka
* kasza manna 1 płaska łyżeczka
* czosnek 2 ząbki
* ziemniaki 3 sztuki
* marchew 2 sztuki
* por 1 \ 3 sztuki
* seler 0,5 sztuki
* czosnek 3 ząbki
* koperek 1 łyżeczka
* śmietana kremowa 30% 1 szklanka
* ziele angielskie całe Prymat 3 ziarna
* majeranek 1 szczypta
* przyprawa do mięsa mielonego farszu i klopsów Prymat 0,5 opakowanie

|
== Przygotowanie

Do miski przekładamy mięso mielone , dodajemy jajko, przyprawy: kucharka, przyprawę do mięsa mielonego, pieprz, czosnek. Wszystkie składniki mieszamy. Na końcu dodajemy kasze manna.

Przygotowujemy warzywa: ziemniaki obieramy i kroimy w kostkę, pietruszkę i marchewkę obieramy i trzemy na tarce. Seler i por obieramy i myjemy.

Z doprawionego mięsa formujemy pulpeciki . W garnku zagotowujemy wodę i dodajemy do niej pulpety. Jednocześnie dodajemy pokrojone w kostkę ziemniaki. Gotujemy pulpety 20 minut.

Dodajemy resztę warzyw : potartą marchewkę i pietruszkę oraz por w całości. Zupę gotujemy jeszcze przez 15 minut.

Na samym końcu dodajemy przyprawy : sól, pieprz, ziele angielskie, majeranek oraz czosnek. Dodajemy także posiekany koperek oraz szklankę śmietany kremówki. Zagotowujemy zupę i podajemy gorącą.

Zupkę klopsową serwujemy gorącą, przybraną listkiem świeżej mięty.

|===

[.text-center]
== Zdjęcia
