= Zupa tajska

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczegóły
* czas przygotowania: 35 min
* 4 porcje
* https://poprostupycha.com.pl/przepis/zupa-tajska[link do źródła przepisu]

== Składniki
* 2 płaskie łyżki tajskiej pasty curry (np. żółta lub czerwona)
* 3 cm korzeń imbiru
* 1 ząbek czosnku
* 600 g fileta piersi z kurczaka
* 1 papryka czerwona
* 1 papryka żółta
* 200 g pieczarek
* 2 l bulionu warzywnego
* opcjonalnie 1/2 papryczki chili lub szczypta papryki ostrej
* 250 ml mleka kokosowego
* 2 łyżeczki sosu rybnego
* opcjonalnie szczypta trawy cytrynowej lub kilka liści kaffiru
* szczypta soli i pieprzu
* świeża kolendra
* 1 limonka
* 50 g cienkiego makaronu ryżowego (waga przed namoczeniem)

|
== Przygotowanie

Filet z piersi kurczaka (około 500-600 g) kroimy w małą kostkę.

Pieczarki (200 g) oraz papryki (ja użyłam jednej czerwonej i żółtej) kroimy w kostkę.

Do garnka z nieprzywierającą powierzchnią nalewamy odrobinę oleju i smażymy w nim pastę curry (2 płaskie łyżki), starty na drobnych oczkach świeży imbir (około 3 cm), trawę cytrynową lub liście kaffiru (kilka sztuk) i dodajemy pokrojonego kurczaka. Całość smażymy na średnim lub większym ogniu przez 2-3 minuty ciągle mieszając.

Po tym czasie dodajemy pokrojone papryki (u mnie czerwona i żółta), a także pieczarki i ponownie smażymy przez 2-3 minutki.

Wlewamy bulion (2 litry, ja użyłam bulionu warzywnego) i gotujemy przez około 20 minut.
Wlewamy sos rybny (2 łyżeczki), mleko kokosowe (200-250 ml) i lekko posiekaną świeżą kolendrę (2 łyżki). Gotujemy jeszcze przez 2-3 minuty i doprawiamy do smaku (np. 1/2 łyżeczki soli i szczypta pieprzu). Jeżeli zupa będzie mało pikantna czy wyrazista, wtedy dodaj nieco więcej pasty curry czy szczyptę papryki ostrej lub drobno posiekaną papryczkę chili. Dodawaj jednak stopniowo, żeby nie przesadzić z ostrością.

Makaron ryżowy lub sojowy zalewamy wodą według wskazań producenta. Podajemy z ugotowaną i nałożoną do miseczek zupą. Wierzch dekorujemy listkami świeżej kolendry. Często podaję także z plasterkiem czy ćwiartką limonki i wyciskam odrobinę soku do każdej miseczki. Smacznego!

|===

[.text-center]
== Zdjęcia
