= Zupa klopsowa  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: 30 min
* 4 porcje
* https://www.doradcasmaku.pl/przepis-zupa-klopsowa-z-koperkiem-i-ziemniakami-310942[link do 藕r贸da przepisu]

== Skadniki

* miso mielone 0,5 kg (z opatki)
* pieprz czarny mielony Prymat 1 szczypta
* kucharek przyprawa uniwersalna 0.5 y偶eczki
* jajko 1 sztuka
* kasza manna 1 paska y偶eczka
* czosnek 2 zbki
* ziemniaki 3 sztuki
* marchew 2 sztuki
* por 1 \ 3 sztuki
* seler 0,5 sztuki
* czosnek 3 zbki
* koperek 1 y偶eczka
* mietana kremowa 30% 1 szklanka
* ziele angielskie cae Prymat 3 ziarna
* majeranek 1 szczypta
* przyprawa do misa mielonego farszu i klops贸w Prymat 0,5 opakowanie

|
== Przygotowanie

Do miski przekadamy miso mielone , dodajemy jajko, przyprawy: kucharka, przypraw do misa mielonego, pieprz, czosnek. Wszystkie skadniki mieszamy. Na kocu dodajemy kasze manna.

Przygotowujemy warzywa: ziemniaki obieramy i kroimy w kostk, pietruszk i marchewk obieramy i trzemy na tarce. Seler i por obieramy i myjemy.

Z doprawionego misa formujemy pulpeciki . W garnku zagotowujemy wod i dodajemy do niej pulpety. Jednoczenie dodajemy pokrojone w kostk ziemniaki. Gotujemy pulpety 20 minut.

Dodajemy reszt warzyw : potart marchewk i pietruszk oraz por w caoci. Zup gotujemy jeszcze przez 15 minut.

Na samym kocu dodajemy przyprawy : s贸l, pieprz, ziele angielskie, majeranek oraz czosnek. Dodajemy tak偶e posiekany koperek oraz szklank mietany krem贸wki. Zagotowujemy zup i podajemy gorc.

Zupk klopsow serwujemy gorc, przybran listkiem wie偶ej mity.

|===

[.text-center]
== Zdjcia
