= Zupa krem z szparag贸w  +++ <label class="switch"><input data-status="off" type="checkbox"><span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: 35 min
* 2 - 4 porcje
* https://www.kwestiasmaku.com/zielony_srodek/szparagi/zupa_krem_z_bialych_szparagow/przepis.html[link do 藕r贸da przepisu]

== Skadniki
* 2 pczki biaych szparag贸w
* 1 du偶a cebula
* 4 y偶ki masa
* 2 ziemniaki
* 1/2 y偶eczki tartej gaki muszkatoowej
* 1,25 litra bulionu jarzynowego lub drobiowego
* drobno zmielony pieprz
* 100 ml mietanki krem贸wki 30%

|
== Przygotowanie
Szparagi opuka, odama twarde i grube koc贸wki (ok. 3 cm), ody偶ki obra, pokroi na 2 cm kawaki. Twarde koc贸wki mo偶na wykorzysta do ugotowania bulionu jarzynowego, s ykowate i nie nadaj si na zmiksowanie w zupie.

W garnku roztopi 2 y偶ki masa i zeszkli pokrojon w kosteczk cebul. Nastpnie doda obrane i pokrojone w drobn kosteczk ziemniaki i mieszajc co chwil sma偶y przez ok. 5 minut.

Doda szparagi (opr贸cz g贸wek) oraz 2 y偶ki masa i sma偶y co chwil mieszajc przez 1 - 2 minuty. Doprawi sol, gak muszkatoow i wymiesza.

Wla gorcy bulion i zagotowa. Gotowa przez ok. 5 minut, nastpnie doda g贸wki szparag贸w i gotowa jeszcze 2 minuty. Zmiksowa w stojcym blenderze z dodatkiem mietanki krem贸wki na idealnie gadki krem (okoo 1 minuta miksowania), pozostawiajc kilka g贸wek szparag贸w do dekoracji.

Zup mo偶na dodatkowo przela przez sito i przetrze y偶k zgromadzony na sicie mi偶sz, w ten spos贸b pozbdziemy si resztek ykowatych czstek szparag贸w. Do zupy doda p贸 y偶eczki drobno zmielonego pieprzu i podgrza przed podaniem na maym ogniu. Podawa z chipsami z bekonu i tart gak muszkatoow oraz opcjonalnie z rukwi wodn lub rukol.

|===

[.text-center]
== Zdjcia
