= Zuppa di pesce  +++ <label class="switch">  <input data-status="off" type="checkbox" >  <span class="slider round"></span></label>+++ 

[cols=".<a,.<a"]
[frame=none]
[grid=none]
|===
|
== Szczeg贸y
* czas przygotowania: 35 min
* 2 porcje
* https://www.kwestiasmaku.com/przepis/zuppa-di-pesce[link do 藕r贸da przepisu]

== Skadniki
* 2 y偶ki oliwy extra vergine
* 1 zbek czosnku
* p贸 pczka natki pietruszki
* 1/2 papryczki chili
* 2 pomidory + 1 y偶ka koncentratu pomidorowego
* 100 ml biaego wytrawnego wina
* 350 ml wrzcej wody
* 300 filet贸w ryby morskiej (np. dorsz, halibut, sola, 偶abnica)
* 200 g wie偶ych ma偶y
* 100 g krewetek + opcjonalnie 2 krewetki nieobrane, z gowami
* bagietka

|
== Przygotowanie
Do szerokiego wikszego garnka wla oliw, doda obrany i pokrojony na cienkie plasterki czosnek, posiekan w kosteczk papryczk chili i sma偶y na maym ogniu przez okoo 3 minuty co chwil mieszajc.

Pomidory sparzy, obra ze sk贸rki i pokroi w kosteczk. Doda do garnka i na wikszym ogniu gotowa przez ok. 5 minut co chwil mieszajc.

Doda koncentrat, poow posiekanej natki pietruszki, wla wino i gotowa przez kolejne 5 minut. Wla wrztek, doprawi sol, wie偶o zmielonym pieprzem i gotowa na wikszym ogniu przez ok. 5 minut a偶 sos odparuje i zgstnieje.

Filety ryby bez sk贸ry i oci pokroi na kilka mniejszych kawak贸w. Ma偶e opuka pod bie偶c zimn wod i oczyci. Krewetki obra z pancerzy, naci grzbiet i usun ciemne jelito. Jeli mamy 2 krewetki z gowami, pozostawiamy je w caoci.

Do garnka z sosem doda ma偶e, krewetki oraz filety ryby. Gotowa przez ok. 3 minuty na rednim ogniu, w poowie delikatnie przemiesza skadniki.

Wszystkie nieotwarte ma偶e wyrzuci. Doda reszt natki pietruszki, jeszcze raz doprawi w razie potrzeby. Przygotowa grzanki z bagietki.

Zup nao偶y do talerzy, doda grzanki. Obok ka偶dej porcji postawi talerz na muszle po ma偶ach oraz miseczk z zimn wod i kawakiem cytryny (do umycia palc贸w po posiku).

|===

[.text-center]
== Zdjcia
