name: Deploy static content to Pages

on:
  workflow_run:
    workflows: ["Build asciidoc"] # Musi idealnie pasować do 'name' z pierwszego pliku
    types:
      - completed
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: self-hosted
    # Uruchom tylko wtedy, gdy poprzedni workflow zakończył się sukcesem
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      # Krok 1: Pobranie artefaktu z konkretnego, zakończonego właśnie workflow
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: page
          path: ./public
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }} # To wskazuje GitHubowi właściwą paczkę

      # Krok 2: Konfiguracja środowiska GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v6

      # Krok 3: Przygotowanie plików z folderu ./public do wysłania
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./public

      # Krok 4: Wdrożenie na serwery GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
