name: MegaLinter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  issues: write # needed for issue creation when errors are found
  pull-requests: write # needed for PR comments

jobs:
  megalinter:
    name: MegaLinter
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        # zizmor-ignore-next-line: unpinned-uses
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          lfs: false
          clean: true
          persist-credentials: false

      # Ręcznie instalujemy LFS z flagą --force, która zmiażdży blokujący plik hooka
      - name: Setup and Force Git LFS
        run: |
          git lfs install --local --force
          git lfs update --force
          git lfs pull

      # MegaLinter (Wersja v9 ze zoptymalizowanymi zmiennymi)
      - name: Run MegaLinter
        uses: oxsecurity/megalinter/flavors/documentation@v9.5.0
        id: ml
        env:
          # Pełne skanowanie tylko na push do main, na PR tylko zmienione pliki
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

          # Linter nie wywali całego pipeline'u w przypadku błędów formatowania
          DISABLE_ERRORS: true

          # Zabezpieczenie przed modyfikacją hooków przez wewnętrzne narzędzia MegaLintera
          ADD_GIT_MUZZLE: true

          # Twoje niestandardowe argumenty dla linterów
          REPOSITORY_CHECKOV_ARGUMENTS: "--skip-check CKV2_GHA_1"
          SPELL_LYCHEE_ARGUMENTS: "--exclude drive.google.com"

          # Token potrzebny do wystawiania statusów w GitHub Actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fix file permissions for self-hosted runner
        if: always()
        run: sudo chown -R "$USER":"$USER" "${{ github.workspace }}"
